/*  ***************************************************************************
    *    $Date:   14 Aug 2001 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for Sales Order outbound in Application Schema  
    * Program Name:         wm_from_order_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for Sales Order Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     11-NOV-02	Panchali Samanta         Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_order_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."

/*----------------------------------------------------------------------*/
--      Create View WM_ORDER_HEADERS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ORDER_HEADERS_VW AS
SELECT
WMTC.WEB_TRANSACTION_ID,  
WMTC.TRANSACTION_TYPE DOCUMENT_TYPE,  
DECODE((WMTC.TRANSACTION_STATUS),0,'UPDATE',1,'INSERT',2, 'DELETE') DOCUMENT_STATUS,  
OEH.HEADER_ID,
OE_QUERY.Get_entry_status_name(OEH.OPEN_FLAG, OEH.CANCELLED_FLAG, OEH.S1) ENTRY_STATUS,
OT.NAME ORDER_TYPE,
ORG.NAME  ORGANIZATION_NAME,
OEH.ORDER_NUMBER,
OEH.DATE_ORDERED, 
OECAT.MEANING ORDER_CATEGORY,
SRC.NAME  ORDER_SOURCE,
OEH.ORIGINAL_SYSTEM_REFERENCE, 
CUST_ACCT.CUSTOMER_NAME  CUSTOMER_NAME,
CUST_ACCT.CUSTOMER_NUMBER CUSTOMER_NUMBER, 
PL.NAME PRICE_LIST_NAME,
OEH.CONVERSION_RATE, 
OEH.CONVERSION_DATE, 
OEH.CONVERSION_TYPE_CODE, 
OEH.CURRENCY_CODE, 
RAS.NAME  SALESREP_NAME,
RAS.SALESREP_NUMBER SALESREP_NUMBER,
OEH.SALES_CHANNEL_CODE,
OEH.TAX_EXEMPT_FLAG, 
OEH.TAX_EXEMPT_NUM, 
OEH.TAX_EXEMPT_REASON_CODE, 
OAB.NAME AGREEMENT_NAME,
INVRULE.NAME INVOICING_RULE,
ACCRULE.NAME ACCOUNTING_RULE, 
OEH.CONTEXT  CONTEXT,
TERM.NAME TERMS_NAME,
OEH.SHIPMENT_PRIORITY_CODE,
OEH.SHIP_METHOD_CODE, 
OEH.FREIGHT_TERMS_CODE,
OEH.FOB_CODE,  
OEH.SHIPPING_INSTRUCTIONS, 
OEH.PACKING_INSTRUCTIONS,
OEH.PURCHASE_ORDER_NUM   PURCHASE_ORDER_NUM,
OEH.PAYMENT_TYPE_CODE, 
OEH.PAYMENT_AMOUNT,
OEH.CHECK_NUMBER, 
OEH.CREDIT_CARD_CODE, 
OEH.CREDIT_CARD_HOLDER_NAME, 
OEH.CREDIT_CARD_NUMBER, 
OEH.CREDIT_CARD_EXPIRATION_DATE, 
OEH.CREDIT_CARD_APPROVAL_CODE,
NULL DATE_SHIPPED,
SHIP_TO_ADDR.ADDRESS1 SHIP_TO_ADDRESS1,
SHIP_TO_ADDR.ADDRESS2 SHIP_TO_ADDRESS2,
SHIP_TO_ADDR.ADDRESS3 SHIP_TO_ADDRESS3,
SHIP_TO_ADDR.ADDRESS4 SHIP_TO_ADDRESS4,
SHIP_TO_ADDR.CITY  SHIP_TO_CITY,
SHIP_TO_ADDR.COUNTY SHIP_TO_COUNTY,
SHIP_TO_ADDR.STATE SHIP_TO_STATE,
SHIP_TO_ADDR.POSTAL_CODE SHIP_TO_POSTAL_CODE,
SHIP_TO_ADDR.COUNTRY SHIP_TO_COUNTRY,
SHIP_TO_CUST.CUSTOMER_NAME SHIP_TO_CUSTOMER,
BILL_TO_ADDR.ADDRESS1 INVOICE_ADDRESS1, 
BILL_TO_ADDR.ADDRESS2 INVOICE_ADDRESS2, 
BILL_TO_ADDR.ADDRESS3 INVOICE_ADDRESS3,
BILL_TO_ADDR.ADDRESS4 INVOICE_ADDRESS4,
BILL_TO_ADDR.CITY  INVOICE_CITY,
BILL_TO_ADDR.COUNTY INVOICE_COUNTY,
BILL_TO_ADDR.STATE INVOICE_STATE,
BILL_TO_ADDR.POSTAL_CODE INVOICE_POSTAL_CODE,
BILL_TO_ADDR.COUNTRY INVOICE_COUNTRY,
BILL_TO_CUST.CUSTOMER_NAME INVOICE_CUSTOMER,
SHIPCONT.FIRST_NAME SHIP_TO_CONTACT_FIRST_NAME,
SHIPCONT.LAST_NAME SHIP_TO_CONTACT_LAST_NAME,
BILLCONT.FIRST_NAME INVOICE_TO_CONTACT_FIRST_NAME,
BILLCONT.LAST_NAME INVOICE_TO_CONTACT_LAST_NAME,
ORDERCONT.FIRST_NAME ORDERED_BY_CONTACT_FIRST_NAME,
ORDERCONT.LAST_NAME ORDERED_BY_CONTACT_LAST_NAME,
NULL OPERATION_CODE,
NULL APPLY_STANDARD_NOTES,
NULL ENTERED_STATE_NAME,
NULL ENTERED_STATE_DATE,
OEH.DATE_REQUESTED_CURRENT,
NULL SCHEDULE_STATUS_CODE,
NULL COMPLETE_FLAG
FROM 
WM_TRACK_CHANGES_VW WMTC,
SO_HEADERS_ALL OEH,
SO_ORDER_TYPES_ALL OT,
HR_ALL_ORGANIZATION_UNITS ORG,
SO_ORDER_SOURCES SRC,
SO_PRICE_LISTS PL, 
RA_SALESREPS_ALL RAS,
SO_AGREEMENTS  OAB,
RA_RULES INVRULE, 
RA_RULES ACCRULE, 
RA_TERMS TERM,
RA_CUSTOMERS CUST_ACCT,
RA_SITE_USES_ALL SHIP_TO_ORG,
RA_ADDRESSES_ALL SHIP_TO_ADDR, 
RA_SITE_USES_ALL BILLORG, 
RA_ADDRESSES_ALL BILL_TO_ADDR,
RA_CONTACTS SHIPCONT, 
RA_CONTACTS BILLCONT,  
RA_CONTACTS ORDERCONT,
RA_CUSTOMERS SHIP_TO_CUST,
RA_CUSTOMERS BILL_TO_CUST,
SO_LOOKUPS  OECAT
WHERE 
OEH.ORDER_TYPE_ID = OT.ORDER_TYPE_ID AND 
ORG.ORGANIZATION_ID(+) = OEH.ORG_ID AND
TO_NUMBER( OEH.ORIGINAL_SYSTEM_SOURCE_CODE) = SRC.ORDER_SOURCE_ID(+) AND
OEH.PRICE_LIST_ID = PL.PRICE_LIST_ID(+) AND 
RAS.SALESREP_ID(+) = OEH.SALESREP_ID AND
RAS.ORG_ID(+) = OEH.SALESREP_ID AND
OAB.AGREEMENT_ID(+) = OEH.AGREEMENT_ID AND
OEH.INVOICING_RULE_ID = INVRULE.RULE_ID(+) AND
OEH.ACCOUNTING_RULE_ID = ACCRULE.RULE_ID(+) AND 
OEH.TERMS_ID = TERM.TERM_ID(+) AND 
OEH.CUSTOMER_ID = CUST_ACCT.CUSTOMER_ID(+) AND
OEH.SHIP_TO_SITE_USE_ID = SHIP_TO_ORG.SITE_USE_ID(+) AND 
SHIP_TO_ORG.ADDRESS_ID = SHIP_TO_ADDR.ADDRESS_ID(+) AND 
OEH.INVOICE_TO_SITE_USE_ID = BILLORG.SITE_USE_ID(+) AND
BILLORG.ADDRESS_ID = BILL_TO_ADDR.ADDRESS_ID(+) AND
OEH.ORDERED_BY_CONTACT_ID = ORDERCONT.CONTACT_ID(+) AND
OEH.SHIP_TO_CONTACT_ID = SHIPCONT.CONTACT_ID(+) AND 
OEH.INVOICE_TO_CONTACT_ID = BILLCONT.CONTACT_ID(+) AND
SHIP_TO_ADDR.CUSTOMER_ID = SHIP_TO_CUST.CUSTOMER_ID(+) AND
BILL_TO_ADDR.CUSTOMER_ID = BILL_TO_CUST.CUSTOMER_ID(+) AND
OECAT.LOOKUP_CODE(+) = OEH.ORDER_CATEGORY AND
OECAT.LOOKUP_TYPE(+) = 'ORDER_CATEGORY' AND
OEH.S1 = 1 AND
OEH.HEADER_ID = WMTC.TRANSACTION_ID AND  
TRANSACTION_STATUS <= 2 AND  
WMTC.TRANSACTION_TYPE = 'SALESORDER'  
/
  
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_ORDER_HEADER_QRY_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_ORDER_HEADER_QRY_VW AS
SELECT
NULL  WEB_TRANSACTION_ID,
'SALESORDER' DOCUMENT_TYPE,
'QUERY' DOCUMENT_STATUS,
OEH.HEADER_ID,
OE_QUERY.Get_entry_status_name(OEH.OPEN_FLAG, OEH.CANCELLED_FLAG, OEH.S1) ENTRY_STATUS,
OT.NAME ORDER_TYPE,
ORG.NAME  ORGANIZATION_NAME,
OEH.ORDER_NUMBER,
OEH.DATE_ORDERED, 
OECAT.MEANING ORDER_CATEGORY,
SRC.NAME  ORDER_SOURCE,
OEH.ORIGINAL_SYSTEM_REFERENCE, 
CUST_ACCT.CUSTOMER_NAME  CUSTOMER_NAME,
CUST_ACCT.CUSTOMER_NUMBER CUSTOMER_NUMBER, 
PL.NAME PRICE_LIST_NAME,
OEH.CONVERSION_RATE, 
OEH.CONVERSION_DATE, 
OEH.CONVERSION_TYPE_CODE, 
OEH.CURRENCY_CODE, 
RAS.NAME  SALESREP_NAME,
RAS.SALESREP_NUMBER SALESREP_NUMBER,
OEH.SALES_CHANNEL_CODE,
OEH.TAX_EXEMPT_FLAG, 
OEH.TAX_EXEMPT_NUM, 
OEH.TAX_EXEMPT_REASON_CODE, 
OAB.NAME AGREEMENT_NAME,
INVRULE.NAME INVOICING_RULE,
ACCRULE.NAME ACCOUNTING_RULE, 
OEH.CONTEXT  CONTEXT,
TERM.NAME TERMS_NAME,
OEH.SHIPMENT_PRIORITY_CODE,
OEH.SHIP_METHOD_CODE, 
OEH.FREIGHT_TERMS_CODE,
OEH.FOB_CODE,  
OEH.SHIPPING_INSTRUCTIONS, 
OEH.PACKING_INSTRUCTIONS,
OEH.PURCHASE_ORDER_NUM   PURCHASE_ORDER_NUM,
OEH.PAYMENT_TYPE_CODE, 
OEH.PAYMENT_AMOUNT,
OEH.CHECK_NUMBER, 
OEH.CREDIT_CARD_CODE, 
OEH.CREDIT_CARD_HOLDER_NAME, 
OEH.CREDIT_CARD_NUMBER, 
OEH.CREDIT_CARD_EXPIRATION_DATE, 
OEH.CREDIT_CARD_APPROVAL_CODE,
NULL DATE_SHIPPED,
SHIP_TO_ADDR.ADDRESS1 SHIP_TO_ADDRESS1,
SHIP_TO_ADDR.ADDRESS2 SHIP_TO_ADDRESS2,
SHIP_TO_ADDR.ADDRESS3 SHIP_TO_ADDRESS3,
SHIP_TO_ADDR.ADDRESS4 SHIP_TO_ADDRESS4,
SHIP_TO_ADDR.CITY  SHIP_TO_CITY,
SHIP_TO_ADDR.COUNTY SHIP_TO_COUNTY,
SHIP_TO_ADDR.STATE SHIP_TO_STATE,
SHIP_TO_ADDR.POSTAL_CODE SHIP_TO_POSTAL_CODE,
SHIP_TO_ADDR.COUNTRY SHIP_TO_COUNTRY,
SHIP_TO_CUST.CUSTOMER_NAME SHIP_TO_CUSTOMER,
BILL_TO_ADDR.ADDRESS1 INVOICE_ADDRESS1, 
BILL_TO_ADDR.ADDRESS2 INVOICE_ADDRESS2, 
BILL_TO_ADDR.ADDRESS3 INVOICE_ADDRESS3,
BILL_TO_ADDR.ADDRESS4 INVOICE_ADDRESS4,
BILL_TO_ADDR.CITY  INVOICE_CITY,
BILL_TO_ADDR.COUNTY INVOICE_COUNTY,
BILL_TO_ADDR.STATE INVOICE_STATE,
BILL_TO_ADDR.POSTAL_CODE INVOICE_POSTAL_CODE,
BILL_TO_ADDR.COUNTRY INVOICE_COUNTRY,
BILL_TO_CUST.CUSTOMER_NAME INVOICE_CUSTOMER,
SHIPCONT.FIRST_NAME SHIP_TO_CONTACT_FIRST_NAME,
SHIPCONT.LAST_NAME SHIP_TO_CONTACT_LAST_NAME,
BILLCONT.FIRST_NAME INVOICE_TO_CONTACT_FIRST_NAME,
BILLCONT.LAST_NAME INVOICE_TO_CONTACT_LAST_NAME,
ORDERCONT.FIRST_NAME ORDERED_BY_CONTACT_FIRST_NAME,
ORDERCONT.LAST_NAME ORDERED_BY_CONTACT_LAST_NAME,
NULL OPERATION_CODE,
NULL APPLY_STANDARD_NOTES,
NULL ENTERED_STATE_NAME,
NULL ENTERED_STATE_DATE,
OEH.DATE_REQUESTED_CURRENT,
NULL SCHEDULE_STATUS_CODE,
NULL COMPLETE_FLAG
FROM 
SO_HEADERS_ALL OEH,
SO_ORDER_TYPES_ALL OT,
HR_ALL_ORGANIZATION_UNITS ORG,
SO_ORDER_SOURCES SRC,
SO_PRICE_LISTS PL, 
RA_SALESREPS_ALL RAS,
SO_AGREEMENTS  OAB,
RA_RULES INVRULE, 
RA_RULES ACCRULE, 
RA_TERMS TERM,
RA_CUSTOMERS CUST_ACCT,
RA_SITE_USES_ALL SHIP_TO_ORG,
RA_ADDRESSES_ALL SHIP_TO_ADDR, 
RA_SITE_USES_ALL BILLORG, 
RA_ADDRESSES_ALL BILL_TO_ADDR,
RA_CONTACTS SHIPCONT, 
RA_CONTACTS BILLCONT,  
RA_CONTACTS ORDERCONT,
RA_CUSTOMERS SHIP_TO_CUST,
RA_CUSTOMERS BILL_TO_CUST,
SO_LOOKUPS  OECAT
WHERE 
OEH.ORDER_TYPE_ID = OT.ORDER_TYPE_ID AND 
ORG.ORGANIZATION_ID(+) = OEH.ORG_ID AND
TO_NUMBER( OEH.ORIGINAL_SYSTEM_SOURCE_CODE) = SRC.ORDER_SOURCE_ID(+) AND
OEH.PRICE_LIST_ID = PL.PRICE_LIST_ID(+) AND 
RAS.SALESREP_ID(+) = OEH.SALESREP_ID AND
RAS.ORG_ID(+) = OEH.SALESREP_ID AND
OAB.AGREEMENT_ID(+) = OEH.AGREEMENT_ID AND
OEH.INVOICING_RULE_ID = INVRULE.RULE_ID(+) AND
OEH.ACCOUNTING_RULE_ID = ACCRULE.RULE_ID(+) AND 
OEH.TERMS_ID = TERM.TERM_ID(+) AND 
OEH.CUSTOMER_ID = CUST_ACCT.CUSTOMER_ID(+) AND
OEH.SHIP_TO_SITE_USE_ID = SHIP_TO_ORG.SITE_USE_ID(+) AND 
SHIP_TO_ORG.ADDRESS_ID = SHIP_TO_ADDR.ADDRESS_ID(+) AND 
OEH.INVOICE_TO_SITE_USE_ID = BILLORG.SITE_USE_ID(+) AND
BILLORG.ADDRESS_ID = BILL_TO_ADDR.ADDRESS_ID(+) AND
OEH.ORDERED_BY_CONTACT_ID = ORDERCONT.CONTACT_ID(+) AND
OEH.SHIP_TO_CONTACT_ID = SHIPCONT.CONTACT_ID(+) AND 
OEH.INVOICE_TO_CONTACT_ID = BILLCONT.CONTACT_ID(+) AND
SHIP_TO_ADDR.CUSTOMER_ID = SHIP_TO_CUST.CUSTOMER_ID(+) AND
BILL_TO_ADDR.CUSTOMER_ID = BILL_TO_CUST.CUSTOMER_ID(+) AND
OECAT.LOOKUP_CODE(+) = OEH.ORDER_CATEGORY AND
OECAT.LOOKUP_TYPE(+) = 'ORDER_CATEGORY' AND
OEH.S1 = 1 
/
  
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_ORDER_LINES_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_ORDER_LINES_VW 
AS
SELECT DISTINCT
  LIN.HEADER_ID ,
  LIN.LINE_ID ,
  LIN.ORIGINAL_SYSTEM_LINE_REFERENCE ,
  H.ORIGINAL_SYSTEM_REFERENCE ,
  SRC.NAME  ORDER_SOURCE,
  LIN.LINE_NUMBER ,
  LIN.LINE_TYPE_CODE LINE_TYPE,
  TRX.TRX_NUMBER COMMITMENT ,
  ACCRULE.NAME ACCOUNTING_RULE, 
  INVRULE.NAME INVOICING_RULE,
  SHIP_TO_CUST.CUSTOMER_NAME SHIP_TO_CUSTOMER,
  RAD.ADDRESS1 SHIP_ADDRESS1,
  RAD.ADDRESS2 SHIP_ADDRESS2,
  RAD.ADDRESS3 SHIP_ADDRESS3,
  RAD.ADDRESS4 SHIP_ADDRESS4,
  RAD.CITY  SHIP_CITY,
  RAD.COUNTY SHIP_COUNTY,
  RAD.STATE SHIP_STATE,
  RAD.POSTAL_CODE SHIP_POSTAL_CODE,
  RAD.COUNTRY SHIP_COUNTRY,
  CON.FIRST_NAME SHIP_TO_CONTACT_FIRST_NAME,
  CON.LAST_NAME SHIP_TO_CONTACT_LAST_NAME,
  LIN.TAX_CODE ,
  LIN3.ORIGINAL_SYSTEM_LINE_REFERENCE  LINK_TO_LINE_REF,
  LIN4.ORIGINAL_SYSTEM_LINE_REFERENCE  PARENT_LINE_REF,
  LIN.SHIP_SET_NUMBER ,
  LIN.SHIPMENT_PRIORITY_CODE ,
  LIN.SHIP_METHOD_CODE ,
  OOD.ORGANIZATION_CODE WAREHOUSE_CODE ,
  LIN.UNIT_CODE ,
  LIN.ORDERED_QUANTITY ,
  LIN.LIST_PRICE ,
  LIN.SELLING_PRICE ,
  LIN.DATE_REQUESTED_CURRENT ,
  MTL.CONCATENATED_SEGMENTS ITEM,
  LIN.SHIPPED_QUANTITY ,
  LIN.SCHEDULE_DATE   SCHEDULED_SHIPMENT_DATE,
  LIN.PRICING_CONTEXT ,
  LIN.PRICING_METHOD_CODE ,
  LIN.ITEM_TYPE_CODE ,
  LIN.OPTION_FLAG ,
  OECAT.MEANING ORDER_CATEGORY,
  LIN.CONTEXT ,
  NULL CALCULATE_PRICE,
  NULL OPERATION_CODE
FROM 
  MTL_SYSTEM_ITEMS_KFV MTL ,
  MTL_PARAMETERS OOD ,
  SO_LINES_ALL LIN4,
  SO_LINES_ALL LIN3,
  RA_CONTACTS CON ,
  RA_SITE_USES_ALL RSU ,
  RA_ADDRESSES_ALL RAD ,
  RA_CUSTOMERS SHIP_TO_CUST,
  RA_RULES ACCRULE, 
  RA_RULES INVRULE, 
  RA_CUSTOMER_TRX_ALL TRX ,
  SO_LOOKUPS  OECAT,
  SO_LINES_ALL LIN ,
  SO_HEADERS_ALL H,
  SO_ORDER_SOURCES SRC
WHERE 
  LIN.HEADER_ID = H.HEADER_ID AND
  LIN.COMMITMENT_ID = TRX.CUSTOMER_TRX_ID (+) AND
  LIN.ACCOUNTING_RULE_ID = ACCRULE.RULE_ID (+) AND 
  LIN.INVOICING_RULE_ID = INVRULE.RULE_ID (+) AND 
  LIN.SHIP_TO_SITE_USE_ID = RSU.SITE_USE_ID (+) AND
  RAD.ADDRESS_ID (+) = RSU.ADDRESS_ID AND
  RAD.CUSTOMER_ID = SHIP_TO_CUST.CUSTOMER_ID(+) AND
  LIN.SHIP_TO_CONTACT_ID = CON.CONTACT_ID (+) AND
  LIN.LINK_TO_LINE_ID = LIN3.LINE_ID(+) AND
  LIN.PARENT_LINE_ID = LIN4.LINE_ID(+) AND
  LIN.WAREHOUSE_ID = OOD.ORGANIZATION_ID (+) AND
  LIN.INVENTORY_ITEM_ID = MTL.INVENTORY_ITEM_ID AND
  TO_NUMBER( H.ORIGINAL_SYSTEM_SOURCE_CODE) = SRC.ORDER_SOURCE_ID(+) AND  
  OECAT.LOOKUP_CODE(+) = H.ORDER_CATEGORY AND
  OECAT.LOOKUP_TYPE(+) = 'ORDER_CATEGORY'
/
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_LINES_DETAIL_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_LINES_DETAIL_VW 
AS
SELECT 
  D.LINE_ID ,
  H.ORIGINAL_SYSTEM_REFERENCE,
  L.ORIGINAL_SYSTEM_LINE_REFERENCE,
  SRC.NAME  ORDER_SOURCE,
  D.QUANTITY ,
  D.SCHEDULE_DATE ,
  D.LOT_NUMBER ,
  D.SUBINVENTORY ,  
  D.CUSTOMER_REQUESTED_LOT_FLAG ,
  D.CONTEXT ,  
  D.REVISION ,
  MTLP.ORGANIZATION_CODE WAREHOUSE 
FROM 
  SO_LINE_DETAILS D,
  SO_LINES_ALL L,
  SO_HEADERS_ALL H,
  SO_ORDER_SOURCES SRC,
  MTL_PARAMETERS MTLP
WHERE 
  D.LINE_ID = L.LINE_ID AND
  L.HEADER_ID = H.HEADER_ID AND
  TO_NUMBER( H.ORIGINAL_SYSTEM_SOURCE_CODE) = SRC.ORDER_SOURCE_ID(+) AND
  D.WAREHOUSE_ID = MTLP.ORGANIZATION_ID (+) 
/
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_LINE_SALES_CREDITS_VW
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_LINE_SALES_CREDITS_VW
AS
SELECT 
C.HEADER_ID,
C.LINE_ID,
H.ORIGINAL_SYSTEM_REFERENCE,
L.ORIGINAL_SYSTEM_LINE_REFERENCE,
SRC.NAME ORDER_SOURCE,
SALES.NAME  SALESREP_NAME,
CREDIT_TYPES.NAME SALES_CREDIT_TYPE,
C.PERCENT,
C.CONTEXT,
NULL OPERATION_CODE
FROM 
SO_SALES_CREDITS C,
SO_HEADERS_ALL H,
SO_LINES_ALL L,
SO_ORDER_SOURCES SRC,
RA_SALESREPS_ALL SALES,
SO_SALES_CREDIT_TYPES  CREDIT_TYPES
WHERE
C.HEADER_ID = H.HEADER_ID AND
L.HEADER_ID = H.HEADER_ID AND
C.LINE_ID = L.LINE_ID AND
SRC.ORDER_SOURCE_ID (+) = TO_NUMBER( H.ORIGINAL_SYSTEM_SOURCE_CODE)  AND
SALES.SALESREP_ID = C.SALESREP_ID AND
SALES.ORG_ID (+) = H.ORG_ID AND
CREDIT_TYPES.SALES_CREDIT_TYPE_ID (+) = C.SALES_CREDIT_TYPE_ID
/
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_HEADER_SALES_CREDIT_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_HEADER_SALES_CREDIT_VW
AS
SELECT 
C.HEADER_ID,
H.ORIGINAL_SYSTEM_REFERENCE,
SRC.NAME ORDER_SOURCE,
SALES.NAME  SALESREP_NAME,
CREDIT_TYPES.NAME SALES_CREDIT_TYPE,
C.PERCENT,
C.CONTEXT,
NULL OPERATION_CODE
FROM 
SO_SALES_CREDITS C,
SO_HEADERS_ALL H,
SO_ORDER_SOURCES SRC,
RA_SALESREPS_ALL SALES,
SO_SALES_CREDIT_TYPES  CREDIT_TYPES
WHERE
C.HEADER_ID = H.HEADER_ID AND
SRC.ORDER_SOURCE_ID (+) = TO_NUMBER( H.ORIGINAL_SYSTEM_SOURCE_CODE)  AND
SALES.SALESREP_ID = C.SALESREP_ID AND
SALES.ORG_ID (+) = H.ORG_ID AND
CREDIT_TYPES.SALES_CREDIT_TYPE_ID (+) = C.SALES_CREDIT_TYPE_ID AND
C.LINE_ID IS NULL
/
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_LINE_PRICE_ADJ_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_LINE_PRICE_ADJ_VW 
AS
SELECT  
ADJ.HEADER_ID,
ADJ.LINE_ID,
H.ORIGINAL_SYSTEM_REFERENCE,
L.ORIGINAL_SYSTEM_LINE_REFERENCE,
SRC.NAME ORDER_SOURCE,
DISCOUNT.NAME DISCOUNT_NAME , 
ADJ.PERCENT,
ADJ.CONTEXT,  
NULL PRICING_CONTEXT,
NULL OPERATION_CODE
FROM 
SO_PRICE_ADJUSTMENTS ADJ , 
SO_HEADERS_ALL H,
SO_LINES_ALL L,
SO_ORDER_SOURCES SRC,
SO_DISCOUNTS DISCOUNT
WHERE 
ADJ.HEADER_ID = H.HEADER_ID AND
L.HEADER_ID = H.HEADER_ID AND
ADJ.LINE_ID = L.LINE_ID AND
SRC.ORDER_SOURCE_ID (+) = TO_NUMBER( H.ORIGINAL_SYSTEM_SOURCE_CODE)  AND
ADJ.DISCOUNT_ID = DISCOUNT.DISCOUNT_ID 
/
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_HRD_PRICE_ADJ_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_HRD_PRICE_ADJ_VW 
AS
SELECT  
ADJ.HEADER_ID,
H.ORIGINAL_SYSTEM_REFERENCE,
SRC.NAME ORDER_SOURCE,
DISCOUNT.NAME DISCOUNT_NAME , 
ADJ.PERCENT,
ADJ.CONTEXT,  
NULL PRICING_CONTEXT,
NULL OPERATION_CODE
FROM 
SO_PRICE_ADJUSTMENTS ADJ , 
SO_HEADERS_ALL H,
SO_ORDER_SOURCES SRC,
SO_DISCOUNTS DISCOUNT
WHERE 
ADJ.HEADER_ID = H.HEADER_ID AND
SRC.ORDER_SOURCE_ID (+) = TO_NUMBER( H.ORIGINAL_SYSTEM_SOURCE_CODE)  AND
ADJ.DISCOUNT_ID = DISCOUNT.DISCOUNT_ID AND
ADJ.LINE_ID IS NULL
/
SHOW ERRORS
