<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteBook</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaW5wdXRDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmluZyBy
ZXNvdXJjZUlEID0gSURhdGFVdGlsLmdldFN0cmluZyhpbnB1dEN1cnNvciwgIiRyZXNvdXJjZUlE
Iik7DQpTdHJpbmcgcGF0aCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaW5wdXRDdXJzb3IsICIkcGF0
aCIpOw0KaW5wdXRDdXJzb3IuZGVzdHJveSgpOw0KCQkNCnN5bmNocm9uaXplZChsaWJyYXJ5KSB7
DQoNCglTdHJpbmcgcmVzdWx0ID0gIiI7DQoJDQoJaWYgKHBhdGggIT0gbnVsbCkgew0KDQoJCXJl
c3VsdCA9IGVycm9yTWVzc2FnZSgiVGhlIFBhdGggbXVzdCBub3QgYmUgc3BlY2lmaWVkIGR1cmlu
ZyBERUxFVEUgcmVxdWVzdHMhIik7DQoNCgl9IGVsc2UgaWYgKHJlc291cmNlSUQgPT0gbnVsbCkg
ew0KCQkNCgkJcmVzdWx0ID0gZXJyb3JNZXNzYWdlKCJUaGUgcmVzb3VyY2VJRCBtdXN0IGJlIHNw
ZWNpZmllZCBkdXJpbmcgREVMRVRFIHJlcXVlc3RzISIpOw0KCQkNCgl9IGVsc2UgLyogKHJlc291
cmNlSUQgIT0gbnVsbCkgKi8gew0KCQkNCgkJLy8gZGVsZXRlIGEgc3BlY2lmaWMgYm9vaw0KCQkN
CgkJaWYgKGxpYnJhcnkuY29udGFpbnNLZXkocmVzb3VyY2VJRCkpIHsNCgkJCWxpYnJhcnkucmVt
b3ZlKHJlc291cmNlSUQpOw0KCQkJcmVzdWx0ID0gc3VjY2Vzc01lc3NhZ2UoIlRoZSBib29rIHdp
dGggdGhlIGlkICciICsgcmVzb3VyY2VJRCArICInIHdhcyBkZWxldGVkIGZyb20gdGhlIGxpYnJh
cnkhIik7DQoJCQkNCgkJfSBlbHNlIHsNCgkJCXJlc3VsdCA9IGVycm9yTWVzc2FnZSgiVGhlIGJv
b2sgd2l0aCB0aGUgaWQgJyIgKyByZXNvdXJjZUlEICsgIicgaXMgbm90IGluIHRoZSBsaWJyYXJ5
ISIpOw0KCQl9CQkJCQ0KCX0NCg0KCS8vIGNhbGwgc2V0IHJlc3BvbnNlIHRvIHJldHVybiBvdXIg
cmVzdWx0DQoNCglzZXRSZXNwb25zZShyZXNvdXJjZUlELCBwYXRoLCByZXN1bHQpOw0KfQ==</value>
</Values>
