/*  ***************************************************************************
        $Date:   09 Apr 2009 10:56:36  $
        $Revision:   1.0  $
        $Author:   
    *   Copyright (c) 2009, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create custom views common for the transactions of all packages
    * Program Name:         ra_customers_all_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 6.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:         Create custom views common for the transactions of all packages.      
    *
    *           
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    * 
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     09-APR-09	Telagareddy Sriram Mohan   Created
    ***************************************************************************
*/
set feedback  on
set verify            off
set newpage   0
set pause             off
set termout   on

prompt Program : ra_contacts_vw.sql
  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating View WM_RA_CUSTOMERS_VW"


CREATE OR REPLACE VIEW APPS.WM_RA_CUSTOMERS_VW (
CUSTOMER_ID,
PARTY_ID,
PARTY_NUMBER,
PARTY_TYPE,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
CREATION_DATE,
CREATED_BY,
CUSTOMER_NAME,
CUSTOMER_NUMBER,
ORIG_SYSTEM_REFERENCE,
STATUS,
LAST_UPDATE_LOGIN,
CUSTOMER_TYPE,
CUSTOMER_PROSPECT_CODE,
CUSTOMER_CLASS_CODE,
PRIMARY_SALESREP_ID,
SALES_CHANNEL_CODE,
SIC_CODE,
ORDER_TYPE_ID,
PRICE_LIST_ID,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
ANALYSIS_FY,
CUSTOMER_CATEGORY_CODE,
CUSTOMER_GROUP_CODE,
CUSTOMER_KEY,
CUSTOMER_SUBGROUP_CODE,
FISCAL_YEAREND_MONTH,
NET_WORTH,
NUM_OF_EMPLOYEES,
POTENTIAL_REVENUE_CURR_FY,
POTENTIAL_REVENUE_NEXT_FY,
RANK,
REFERENCE_USE_FLAG,
TAX_CODE,
TAX_REFERENCE,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
THIRD_PARTY_FLAG,
ACCESS_TEMPLATE_ENTITY_CODE,
PRIMARY_SPECIALIST_ID,
SECONDARY_SPECIALIST_ID,
COMPETITOR_FLAG,
DUNNING_SITE_USE_ID,
STATEMENT_SITE_USE_ID,
ORIG_SYSTEM,
YEAR_ESTABLISHED,
COTERMINATE_DAY_MONTH,
FOB_POINT,
FREIGHT_TERM,
GSA_INDICATOR,
SHIP_PARTIAL,
SHIP_VIA,
WAREHOUSE_ID,
PAYMENT_TERM_ID,
TAX_EXEMPT,
TAX_EXEMPT_NUM,
TAX_EXEMPT_REASON_CODE,
JGZZ_FISCAL_CODE,
DO_NOT_MAIL_FLAG,
MISSION_STATEMENT,
CUSTOMER_NAME_PHONETIC,
TAX_HEADER_LEVEL_FLAG,
TAX_ROUNDING_RULE,
WH_UPDATE_DATE,
GLOBAL_ATTRIBUTE1,
GLOBAL_ATTRIBUTE2,
GLOBAL_ATTRIBUTE3,
GLOBAL_ATTRIBUTE4,
GLOBAL_ATTRIBUTE5,
GLOBAL_ATTRIBUTE6,
GLOBAL_ATTRIBUTE7,
GLOBAL_ATTRIBUTE8,
GLOBAL_ATTRIBUTE9,
GppLOBAL_ATTRIBUTE10,
GLOBAL_ATTRIBUTE11,
GLOBAL_ATTRIBUTE12,
GLOBAL_ATTRIBUTE13,
GLOBAL_ATTRIBUTE14,
GLOBAL_ATTRIBUTE15,
GLOBAL_ATTRIBUTE16,
GLOBAL_ATTRIBUTE17,
GLOBAL_ATTRIBUTE18,
GLOBAL_ATTRIBUTE19,
GLOBAL_ATTRIBUTE20,
GLOBAL_ATTRIBUTE_CATEGORY,
URL,
LANGUAGE,
TRANSLATED_CUSTOMER_NAME,
PERSON_PRE_NAME_ADJUNCT,
PERSON_FIRST_NAME,
PERSON_MIDDLE_NAME,
PERSON_LAST_NAME,
PERSON_SUFFIX,
PERSON_FIRST_NAME_PHONETIC,
PERSON_LAST_NAME_PHONETIC,
SHIP_SETS_INCLUDE_LINES_FLAG,
ARRIVALSETS_INCLUDE_LINES_FLAG,
SCHED_DATE_PUSH_FLAG,
OVER_SHIPMENT_TOLERANCE,
UNDER_SHIPMENT_TOLERANCE,
OVER_RETURN_TOLERANCE,
UNDER_RETURN_TOLERANCE,
ITEM_CROSS_REF_PREF,
DATE_TYPE_PREFERENCE,
DATES_NEGATIVE_TOLERANCE,
DATES_POSITIVE_TOLERANCE,
INVOICE_QUANTITY_RULE,
ATTRIBUTE16,
ATTRIBUTE17,
ATTRIBUTE18,
ATTRIBUTE19,
ATTRIBUTE20,
DUNS_NUMBER,
DUNS_NUMBER_C,
PARTY_LAST_UPDATE_DATE,
SIC_CODE_TYPE)
AS 
SELECT 
CUST_ACCT.CUST_ACCOUNT_ID,
PARTY.PARTY_ID,
PARTY.PARTY_NUMBER,
PARTY.PARTY_TYPE,
 CUST_ACCT.LAST_UPDATE_DATE ,
 CUST_ACCT.LAST_UPDATED_BY ,
 CUST_ACCT.CREATION_DATE ,
 CUST_ACCT.CREATED_BY ,
 SUBSTRB(PARTY.PARTY_NAME, 1, 50)/*customer_name*/,
 CUST_ACCT.ACCOUNT_NUMBER /*customer_number*/,
 CUST_ACCT.ORIG_SYSTEM_REFERENCE ,
 CUST_ACCT.STATUS ,
 CUST_ACCT.LAST_UPDATE_LOGIN ,
CUST_ACCT.CUSTOMER_TYPE ,
 'CUSTOMER' ,
 CUST_ACCT.CUSTOMER_CLASS_CODE ,
 CUST_ACCT.PRIMARY_SALESREP_ID ,
 CUST_ACCT.SALES_CHANNEL_CODE ,
 DECODE(PARTY.PARTY_TYPE, 'OGANIZATION', PARTY.SIC_CODE , NULL),
 CUST_ACCT.ORDER_TYPE_ID ,
 CUST_ACCT.PRICE_LIST_ID ,
 CUST_ACCT.ATTRIBUTE_CATEGORY ,
 CUST_ACCT.ATTRIBUTE1 ,
 CUST_ACCT.ATTRIBUTE2 ,
 CUST_ACCT.ATTRIBUTE3 ,
 CUST_ACCT.ATTRIBUTE4 ,
 CUST_ACCT.ATTRIBUTE5 ,
 CUST_ACCT.ATTRIBUTE6 ,
 CUST_ACCT.ATTRIBUTE7 ,
 CUST_ACCT.ATTRIBUTE8 ,
 CUST_ACCT.ATTRIBUTE9 ,
 CUST_ACCT.ATTRIBUTE10 ,
 CUST_ACCT.REQUEST_ID ,
 CUST_ACCT.PROGRAM_APPLICATION_ID ,
 CUST_ACCT.PROGRAM_ID ,
 CUST_ACCT.PROGRAM_UPDATE_DATE ,
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.ANALYSIS_FY, NULL),
 PARTY.CATEGORY_CODE ,
 NULL /*CUSTMER_GROUP_CODE*/,
 PARTY.CUSTOMER_KEY ,
 NULL /*CUSTOMER_SUBGROUP_CODE*/ ,
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.FISCAL_YEAREND_MONTH , NULL),
 TO_NUMBER(NULL) /*NET_WORTH*/ ,
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.EMPLOYEES_TOTAL, TO_NUMBER(NULL)),
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.CURR_FY_POTENTIAL_REVENUE, TO_NUMBER(NULL)),
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.NEXT_FY_POTENTIAL_REVENUE, TO_NUMBER(NULL)),
 NULL /*RANK*/ ,
 PARTY.REFERENCE_USE_FLAG ,
CUST_ACCT.TAX_CODE ,
 PARTY.TAX_REFERENCE ,
 CUST_ACCT.ATTRIBUTE11 ,
 CUST_ACCT.ATTRIBUTE12 ,
 CUST_ACCT.ATTRIBUTE13 ,
 CUST_ACCT.ATTRIBUTE14 ,
 CUST_ACCT.ATTRIBUTE15,
 PARTY.THIRD_PARTY_FLAG ,
 NULL /*ACCESS_TEMPLATE_ENTITY_CODE*/ ,
 CUST_ACCT.PRIMARY_SPECIALIST_ID ,
 CUST_ACCT.SECONDARY_SPECIALIST_ID ,
 PARTY.COMPETITOR_FLAG ,
TO_NUMBER(NULL) /*DUNNING_SITE_USE_ID*/ ,
 TO_NUMBER(NULL) /*STATEMENT_SITE_USE_ID */,
 NULL /*ORIG_SYSTEM*/ ,
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.YEAR_ESTABLISHED , TO_NUMBER(NULL)),
 CUST_ACCT.COTERMINATE_DAY_MONTH ,
 CUST_ACCT.FOB_POINT ,
 CUST_ACCT.FREIGHT_TERM ,
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.GSA_INDICATOR_FLAG , 'N'),
 CUST_ACCT.SHIP_PARTIAL ,
 CUST_ACCT.SHIP_VIA ,
 CUST_ACCT.WAREHOUSE_ID ,
 CUST_ACCT.PAYMENT_TERM_ID ,
 NULL /*TAX_EXEMPT*/ ,
 NULL /*TAX_EXEMPT_NUM*/ ,
 NULL /*TAX_EXEMPT_REASON_CODE*/ ,
 PARTY.JGZZ_FISCAL_CODE ,
 PARTY.DO_NOT_MAIL_FLAG ,
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.MISSION_STATEMENT , NULL),
 DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.ORGANIZATION_NAME_PHONETIC , NULL),
 CUST_ACCT.TAX_HEADER_LEVEL_FLAG ,
 CUST_ACCT.TAX_ROUNDING_RULE ,
 CUST_ACCT.WH_UPDATE_DATE ,
 CUST_ACCT.GLOBAL_ATTRIBUTE1,
 CUST_ACCT.GLOBAL_ATTRIBUTE2 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE3 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE4 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE5 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE6 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE7 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE8 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE9 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE10 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE11 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE12 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE13 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE14 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE15 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE16 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE17 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE18 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE19 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE20 ,
 CUST_ACCT.GLOBAL_ATTRIBUTE_CATEGORY ,
 PARTY.URL,
NULL, 				--PARTY.LANGUAGE,
NULL,
PARTY.PERSON_PRE_NAME_ADJUNCT,
PARTY.PERSON_FIRST_NAME,
PARTY.PERSON_MIDDLE_NAME,
PARTY.PERSON_LAST_NAME,
PARTY.PERSON_NAME_SUFFIX,
PARTY.PERSON_FIRST_NAME_PHONETIC,
PARTY.PERSON_LAST_NAME_PHONETIC,
CUST_ACCT.SHIP_SETS_INCLUDE_LINES_FLAG,
CUST_ACCT.ARRIVALSETS_INCLUDE_LINES_FLAG,
CUST_ACCT.SCHED_DATE_PUSH_FLAG,
CUST_ACCT.OVER_SHIPMENT_TOLERANCE,
CUST_ACCT.UNDER_SHIPMENT_TOLERANCE,
CUST_ACCT.OVER_RETURN_TOLERANCE,
CUST_ACCT.UNDER_RETURN_TOLERANCE,
CUST_ACCT.ITEM_CROSS_REF_PREF,
CUST_ACCT.DATE_TYPE_PREFERENCE,
CUST_ACCT.DATES_NEGATIVE_TOLERANCE,
CUST_ACCT.DATES_POSITIVE_TOLERANCE,
CUST_ACCT.INVOICE_QUANTITY_RULE,
CUST_ACCT.ATTRIBUTE16,
CUST_ACCT.ATTRIBUTE17,
CUST_ACCT.ATTRIBUTE18,
CUST_ACCT.ATTRIBUTE19,
CUST_ACCT.ATTRIBUTE20,
PARTY.DUNS_NUMBER,
PARTY.DUNS_NUMBER_C,
PARTY.LAST_UPDATE_DATE,
PARTY.SIC_CODE_TYPE
 FROM APPS.HZ_PARTIES PARTY,
 APPS.HZ_CUST_ACCOUNTS CUST_ACCT WHERE CUST_ACCT.PARTY_ID=PARTY.PARTY_ID
/
