/*  ***************************************************************************
        $Date:   09 Apr 2009 10:56:36  $
        $Revision:   1.0  $
        $Author:   
    *   Copyright (c) 2009, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create custom views common for the transactions of all packages
    * Program Name:         ra_contacts_all_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 6.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:         Create custom views common for the transactions of all packages.      
    *
    *           
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    * 
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     09-APR-09	Telagareddy Sriram Mohan   Created
    ***************************************************************************
*/
set feedback  on
set verify            off
set newpage   0
set pause             off
set termout   on

prompt Program : ra_contacts_vw.sql
  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating View WM_RA_CONTACTS_VW"

CREATE OR REPLACE VIEW APPS.WM_RA_CONTACTS_VW
(CONTACT_ID,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
CREATION_DATE,
CREATED_BY,
CUSTOMER_ID,
STATUS,
ORIG_SYSTEM_REFERENCE,
LAST_NAME,
LAST_UPDATE_LOGIN,
TITLE,
FIRST_NAME,
JOB_TITLE,
MAIL_STOP,
ADDRESS_ID,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
CONTACT_KEY,
CONTACT_PERSONAL_INFORMATION,
DECISION_MAKER_FLAG,
JOB_TITLE_CODE,
MANAGED_BY,
NATIVE_LANGUAGE,
REFERENCE_USE_FLAG,
CONTACT_NUMBER,
ATTRIBUTE11,
ATTRIBUTE25,
OTHER_LANGUAGE_1,
OTHER_LANGUAGE_2,
RANK,
PRIMARY_ROLE,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
ATTRIBUTE16,
ATTRIBUTE17,
ATTRIBUTE18,
ATTRIBUTE19,
ATTRIBUTE20,
ATTRIBUTE21,
ATTRIBUTE22,
ATTRIBUTE23,
ATTRIBUTE24,
DO_NOT_MAIL_FLAG,
SUFFIX,
EMAIL_ADDRESS,
MAILING_ADDRESS_ID,
MATCH_GROUP_ID,
SEX_CODE,
SALUTATION,
DEPARTMENT_CODE,
DEPARTMENT,
LAST_NAME_ALT,
FIRST_NAME_ALT,
CONTACT_PARTY_ID,
ORG_CONTACT_ID,
PARTY_LAST_UPDATE_DATE,
REL_LAST_UPDATE_DATE,
ORG_CONT_LAST_UPDATE_DATE,
PARTY_RELATIONSHIP_ID
) AS 
 SELECT 
ACCT_ROLE.CUST_ACCOUNT_ROLE_ID,
ACCT_ROLE.LAST_UPDATE_DATE,
ACCT_ROLE.LAST_UPDATED_BY,
ACCT_ROLE.CREATION_DATE,
ACCT_ROLE.CREATED_BY,
ACCT_ROLE.CUST_ACCOUNT_ID,
ACCT_ROLE.STATUS,
ACCT_ROLE.ORIG_SYSTEM_REFERENCE,
substrb( PARTY.PERSON_LAST_NAME,1,50) LAST_NAME,
ORG_CONT.LAST_UPDATE_LOGIN,
PARTY.PERSON_PRE_NAME_ADJUNCT,
substrb(PARTY.PERSON_FIRST_NAME,1,40) FIRST_NAME,
ORG_CONT.JOB_TITLE,
ORG_CONT.MAIL_STOP,
ACCT_ROLE.CUST_ACCT_SITE_ID /* ADDRESS_ID */,
ACCT_ROLE.ATTRIBUTE_CATEGORY,
ACCT_ROLE.ATTRIBUTE1,
ACCT_ROLE.ATTRIBUTE2,
ACCT_ROLE.ATTRIBUTE3,
ACCT_ROLE.ATTRIBUTE4,
ACCT_ROLE.ATTRIBUTE5,
ACCT_ROLE.ATTRIBUTE6,
ACCT_ROLE.ATTRIBUTE7,
ACCT_ROLE.ATTRIBUTE8,
ACCT_ROLE.ATTRIBUTE9,
ACCT_ROLE.ATTRIBUTE10,
ACCT_ROLE.REQUEST_ID,
ACCT_ROLE.PROGRAM_APPLICATION_ID,
ACCT_ROLE.PROGRAM_ID,
ACCT_ROLE.PROGRAM_UPDATE_DATE,
PARTY.CUSTOMER_KEY,
null /*CONTACT_PERSONAL_INFORMATION*/,
ORG_CONT.DECISION_MAKER_FLAG,
ORG_CONT.JOB_TITLE_CODE,
ORG_CONT.MANAGED_BY,
PARTY.LANGUAGE_NAME NATIVE_LANGUAGE,
ORG_CONT.REFERENCE_USE_FLAG,
ORG_CONT.CONTACT_NUMBER,
ACCT_ROLE.ATTRIBUTE11,
ACCT_ROLE.ATTRIBUTE25,
null /*OTHER_LANGUAGE_1*/,
null /*OTHER_LANGUAGE_2*/,
ORG_CONT.RANK,
ACCT_ROLE.PRIMARY_FLAG,
ACCT_ROLE.ATTRIBUTE12,
ACCT_ROLE.ATTRIBUTE13,
ACCT_ROLE.ATTRIBUTE14,
ACCT_ROLE.ATTRIBUTE15,
ACCT_ROLE.ATTRIBUTE16,
ACCT_ROLE.ATTRIBUTE17,
ACCT_ROLE.ATTRIBUTE18,
ACCT_ROLE.ATTRIBUTE19,
ACCT_ROLE.ATTRIBUTE20,
ACCT_ROLE.ATTRIBUTE21,
ACCT_ROLE.ATTRIBUTE22,
ACCT_ROLE.ATTRIBUTE23,
ACCT_ROLE.ATTRIBUTE24,
PARTY.DO_NOT_MAIL_FLAG,
PARTY.PERSON_NAME_SUFFIX SUFFIX,
REL_PARTY.EMAIL_ADDRESS,
ORG_CONT.MAILING_ADDRESS_ID,
ORG_CONT.MATCH_GROUP_ID,
null /*SEX_CODE*/,
null /*SALUTATION*/,
ORG_CONT.DEPARTMENT_CODE,
ORG_CONT.DEPARTMENT,
NULL /*LAST_NAME_ALT*/,
NULL /*FIRST_NAME_ALT*/,
NULL /*CONTACT_PARTY_ID*/,
ORG_CONT.ORG_CONTACT_ID,
PARTY.LAST_UPDATE_DATE,
REL_PARTY.LAST_UPDATE_DATE,
ORG_CONT.LAST_UPDATE_DATE,
ORG_CONT.PARTY_RELATIONSHIP_ID
FROM 
HZ_CUST_ACCOUNT_ROLES ACCT_ROLE,
HZ_PARTIES PARTY,
HZ_RELATIONSHIPS REL,
HZ_ORG_CONTACTS ORG_CONT,
HZ_PARTIES REL_PARTY,
HZ_CUST_ACCOUNTS ACCT WHERE ACCT_ROLE.PARTY_ID = REL.PARTY_ID AND ACCT_ROLE.ROLE_TYPE = 'CONTACT' AND ORG_CONT.PARTY_RELATIONSHIP_ID = REL.RELATIONSHIP_ID AND REL.SUBJECT_TABLE_NAME = 'HZ_PARTIES' AND REL.OBJECT_TABLE_NAME = 'HZ_PARTIES' AND REL.SUBJECT_ID = PARTY.PARTY_ID AND REL.PARTY_ID = REL_PARTY.PARTY_ID AND REL.OBJECT_ID = ACCT.PARTY_ID AND ACCT.CUST_ACCOUNT_ID = ACCT_ROLE.CUST_ACCOUNT_ID
/
