/*  ***************************************************************************
    *    $Date:   14 Nov 2002 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   TCS  $
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for AP Invoice outbound in Application Schema  
    * Program Name:         wm_from_apinvoice_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for AP Invoice Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     14-NOV-02	   Rajib Naha   	   Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_apinvoice_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."


/*----------------------------------------------------------------------*/
--      Create View WM_AP_INVOICES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AP_INVOICES_VW 
(
	WEB_TRANSACTION_ID, 
	DOCUMENT_TYPE,
	DOCUMENT_STATUS,
	INVOICE_ID,
	INVOICE_NUM ,
	INVOICE_TYPE,
	INVOICE_DATE ,
	PO_NUMBER ,
	VENDOR_NUMBER ,
	VENDOR_NAME ,
	VENDOR_SITE_ADDRESS_LINE1,
	VENDOR_SITE_ADDRESS_LINE2,
	VENDOR_SITE_ADDRESS_LINE3,
	VENDOR_TOWN_OR_CITY,
	VENDOR_COUNTY,
	VENDOR_STATE,
	VENDOR_POSTAL_CODE,
	VENDOR_COUNTRY,
	INVOICE_AMOUNT ,
	INVOICE_CURRENCY_CODE ,
	EXCHANGE_RATE ,
      	EXCHANGE_RATE_TYPE ,
      	TERMS_NAME ,
      	EXCHANGE_RATE_DATE ,
      	DESCRIPTION ,
	AWT_GROUP_NAME ,
	SOURCE ,
	PAYMENT_CROSS_RATE ,
	PAYMENT_CURRENCY_CODE ,
	DOC_CATEGORY_CODE ,
	VOUCHER_NUM ,
	PAYMENT_METHOD_LOOKUP_CODE ,
	PAY_GROUP_LOOKUP_CODE ,
	GOODS_RECEIVED_DATE ,
	INVOICE_RECEIVED_DATE ,
	SET_OF_BOOKS_NAME,
	LIABILITY_ACCOUNT,
	USSGL_TRANSACTION_CODE ,
	EXCLUSIVE_PAYMENT ,
	ORGANIZATION_NAME,
	AMOUNT_APPLICABLE_TO_DISCOUNT
) AS
SELECT
	WMTC.WEB_TRANSACTION_ID WEB_TRANSACTION_ID, 
	WMTC.TRANSACTION_TYPE  DOCUMENT_TYPE,
	DECODE(WMTC.TRANSACTION_STATUS,0,'UPDATE',1,'INSERT',2,'DELETE')  DOCUMENT_STATUS,
	AI.INVOICE_ID INVOICE_ID,
	AI.INVOICE_NUM INVOICE_NUM ,
	AI.INVOICE_TYPE_LOOKUP_CODE INVOICE_TYPE_LOOKUP_CODE ,
	AI.INVOICE_DATE INVOICE_DATE ,
	AP_INVOICES_PKG.GET_PO_NUMBER( AI.INVOICE_ID) PO_NUMBER ,
	PV.SEGMENT1 VENDOR_NUMBER ,
	PV.VENDOR_NAME VENDOR_NAME ,
	PVS.ADDRESS_LINE1 ADDRESS_LINE1,
	PVS.ADDRESS_LINE2 ADDRESS_LINE2,
	PVS.ADDRESS_LINE3 ADDRESS_LINE3,
	PVS.CITY  CITY,
	PVS.COUNTY COUNTY,
	PVS.STATE STATE,
	PVS.ZIP ZIP,
	PVS.COUNTRY COUNTRY,
	AI.INVOICE_AMOUNT INVOICE_AMOUNT ,
	AI.INVOICE_CURRENCY_CODE INVOICE_CURRENCY_CODE ,
      	AI.EXCHANGE_RATE EXCHANGE_RATE ,
      	AI.EXCHANGE_RATE_TYPE EXCHANGE_RATE_TYPE ,
      	AT.NAME TERMS_NAME ,
      	AI.EXCHANGE_DATE EXCHANGE_DATE ,
      	AI.DESCRIPTION DESCRIPTION ,
	AWT.NAME AWT_GROUP_NAME ,
	AI.SOURCE SOURCE ,
	AI.PAYMENT_CROSS_RATE PAYMENT_CROSS_RATE ,
	AI.PAYMENT_CURRENCY_CODE PAYMENT_CURRENCY_CODE ,
	AI.DOC_CATEGORY_CODE DOC_CATEGORY_CODE ,
	AI.VOUCHER_NUM VOUCHER_NUM ,
	AI.PAYMENT_METHOD_LOOKUP_CODE PAYMENT_METHOD_LOOKUP_CODE ,
	AI.PAY_GROUP_LOOKUP_CODE PAY_GROUP_LOOKUP_CODE ,
	AI.GOODS_RECEIVED_DATE GOODS_RECEIVED_DATE ,
	AI.INVOICE_RECEIVED_DATE INVOICE_RECEIVED_DATE ,
	GSOB.NAME SET_OF_BOOKS_NAME,
	GLCL.CONCATENATED_SEGMENTS LIABILITY_ACCOUNT,	  
	AI.USSGL_TRANSACTION_CODE USSGL_TRANSACTION_CODE ,
	AI.EXCLUSIVE_PAYMENT_FLAG EXCLUSIVE_PAYMENT_FLAG ,
	HAOTL.NAME ORG_NAME,
	AI.AMOUNT_APPLICABLE_TO_DISCOUNT AMOUNT_APPLICABLE_TO_DISCOUNT 
FROM 
      	AP_INVOICES_ALL AI,
      	AP_TERMS AT,
      	PO_VENDORS PV,
      	PO_VENDOR_SITES_ALL PVS,
      	AP_LOOKUP_CODES ALC1,
      	AP_LOOKUP_CODES ALC2,
	AP_AWT_GROUPS AWT,
	HR_ALL_ORGANIZATION_UNITS HAOTL,	  
	GL_CODE_COMBINATIONS_KFV GLCL,
	GL_SETS_OF_BOOKS GSOB,	  
	WM_TRACK_CHANGES_VW WMTC	  
WHERE
      	AI.TERMS_ID = AT.TERM_ID (+) AND
      	ALC1.LOOKUP_TYPE (+) = 'INVOICE TYPE' AND
      	ALC1.LOOKUP_CODE (+) = AI.INVOICE_TYPE_LOOKUP_CODE AND
      	ALC2.LOOKUP_TYPE (+) = 'PAYMENT METHOD' AND
      	ALC2.LOOKUP_CODE (+) = AI.PAYMENT_METHOD_LOOKUP_CODE AND
      	AI.VENDOR_ID = PV.VENDOR_ID (+) AND
      	AI.VENDOR_SITE_ID = PVS.VENDOR_SITE_ID (+) AND
	AI.AWT_GROUP_ID = AWT.GROUP_ID (+) AND
	AI.ACCTS_PAY_CODE_COMBINATION_ID = GLCL.CODE_COMBINATION_ID (+) AND
	AI.ORG_ID = HAOTL.ORGANIZATION_ID (+) AND	 
	AI.ORG_ID = PVS.ORG_ID (+) AND
	AI.SET_OF_BOOKS_ID =	GSOB.SET_OF_BOOKS_ID (+) AND
      	AI.INVOICE_ID = WMTC.TRANSACTION_ID AND
      	TRANSACTION_STATUS <= 2 AND
      	WMTC.TRANSACTION_TYPE = 'APINVOICE' AND
	AI.INVOICE_ID IN 
	(SELECT INVOICE_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL
	 WHERE MATCH_STATUS_FLAG = 'A')
  
/

/*----------------------------------------------------------------------*/
--      Create View WM_AP_INVOICES_LINES_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AP_INVOICES_LINES_VW
(
      	INVOICE_ID,
	LINE_NUMBER ,	  
      	LINE_TYPE ,
	STATUS,
      	AMOUNT ,
      	ACCOUNTING_DATE ,
      	DESCRIPTION , 
	AMOUNT_INCLUDES_TAX_FLAG,
      	PO_NUMBER ,
      	PO_LINE_NUMBER ,
      	PO_SHIPMENT_NUM,
      	PO_DISTRIBUTION_NUM ,
      	PO_UNIT_OF_MEASURE ,
      	ITEM_DESCRIPTION, 
	QUANTITY_INVOICED ,
      	SHIP_TO_LOC_ADDRESS_LINE_1 ,
      	SHIP_TO_LOC_ADDRESS_LINE_2 ,
      	SHIP_TO_LOC_ADDRESS_LINE_3 ,
      	SHIP_TO_LOC_TOWN_OR_CITY,
      	SHIP_TO_LOC_COUNTY,
      	SHIP_TO_LOC_STATE,
      	SHIP_TO_LOC_POSTAL_CODE,
      	SHIP_TO_LOC_COUNTRY,
      	UNIT_PRICE ,
	SET_OF_BOOKS_NAME,
      	DIST_CODE_CONCATENATED,
      	AWT_GROUP_NAME ,
	RELEASE_NUM,
      	PROJECT_NAME ,
      	TASK ,
      	EXPENDITURE_TYPE ,
      	EXPENDITURE_ITEM_DATE ,
      	EXPENDITURE_ORGANIZATION_NAME ,
	PROJECT_ACCOUNTING_CONTEXT,
	PA_ADDITION_FLAG,
	PA_QUANTITY, 
      	USSGL_TRANSACTION_CODE ,
      	STAT_AMOUNT ,
      	TYPE_1099 ,
      	INCOME_TAX_REGION_NAME ,
      	ORGANIZATION_NAME,
	PA_REFERENCE1,
	PA_REFERENCE2,
	ASSET_TRACKING_FLAG,
	PRICE_CORRECTION_FLAG
) AS
SELECT	DISTINCT
      	AID.INVOICE_ID,
	AID.DISTRIBUTION_LINE_NUMBER LINE_NUMBER ,	  
      	AID.LINE_TYPE_LOOKUP_CODE LINE_TYPE ,
	DECODE(AID.MATCH_STATUS_FLAG , NULL,'NEVER APPROVED', 'N', 'NEVER APPROVED', 'T', 'NEEDS REAPPROVAL', 'A', 'APPROVED', 'S', 'NEVER APPROVED') STATUS,
      	AID.AMOUNT AMOUNT ,
      	AID.ACCOUNTING_DATE ACCOUNTING_DATE ,
      	AID.DESCRIPTION DESCRIPTION , 
	AID.AMOUNT_INCLUDES_TAX_FLAG AMOUNT_INCLUDES_TAX_FLAG,
      	PH.SEGMENT1 PO_NUMBER ,
      	PL.LINE_NUM PO_LINE_NUMBER ,
      	PLL.SHIPMENT_NUM SHIPMENT_NUM,
      	PD.DISTRIBUTION_NUM DISTRIBUTION_NUM ,
      	PL.UNIT_MEAS_LOOKUP_CODE UNIT_MEAS_LOOKUP_CODE ,
      	MSI.DESCRIPTION ITEM_DESCRIPTION, 
	AID.QUANTITY_INVOICED QUANTITY_INVOICED ,
      	HRL.ADDRESS_LINE_1 SHIP_TO_LOC_ADDRESS_LINE_1 ,
      	HRL.ADDRESS_LINE_2 SHIP_TO_LOC_ADDRESS_LINE_2 ,
      	HRL.ADDRESS_LINE_3 SHIP_TO_LOC_ADDRESS_LINE_3 ,
      	HRL.TOWN_OR_CITY SHIP_TO_LOC_TOWN_OR_CITY,
      	HRL.REGION_1 SHIP_TO_LOC_COUNTY,
      	HRL.REGION_2 SHIP_TO_LOC_STATE,
      	HRL.POSTAL_CODE SHIP_TO_LOC_POSTAL_CODE,
      	HRL.COUNTRY SHIP_TO_LOC_COUNTRY,
      	AID.UNIT_PRICE UNIT_PRICE ,
	GSOB.NAME SET_OF_BOOKS_NAME,
      	GLCD.CONCATENATED_SEGMENTS DIST_CODE_CONCATENATED,
      	AWT.NAME AWT_GROUP_NAME ,
	PH.REVISION_NUM RELEASE_NUM,
      	PAP.SEGMENT1 PROJECT ,
      	PAT.TASK_NAME TASK ,
      	AID.EXPENDITURE_TYPE EXPENDITURE_TYPE ,
      	AID.EXPENDITURE_ITEM_DATE EXPENDITURE_ITEM_DATE ,
      	HAOTL.NAME EXPENDITURE_ORGANIZATION_NAME ,
	AID.PROJECT_ACCOUNTING_CONTEXT PROJECT_ACCOUNTING_CONTEXT,
	AID.PA_ADDITION_FLAG PA_ADDITION_FLAG,
	AID.PA_QUANTITY PA_QUANTITY, 
      	AID.USSGL_TRANSACTION_CODE USSGL_TRANSACTION_CODE ,
      	AID.STAT_AMOUNT STAT_AMOUNT ,
      	AID.TYPE_1099 TYPE_1099 ,
      	AITR.REGION_LONG_NAME INCOME_TAX_REGION_NAME ,
      	HAOTL.NAME ORG_NAME,
	AID.REFERENCE_1 PA_REFERENCE1,
	AID.REFERENCE_2 PA_REFERENCE2,
	AID.ASSETS_TRACKING_FLAG ASSET_TRACKING_FLAG,
	AID.PRICE_ADJUSTMENT_FLAG PRICE_CORRECTION_FLAG
FROM
      	AP_INVOICE_DISTRIBUTIONS_ALL AID,
      	AP_AWT_GROUPS AWT,
      	AP_INCOME_TAX_REGIONS AITR,
      	AP_LOOKUP_CODES ALC1,
      	AP_LOOKUP_CODES ALC2,
      	AP_LOOKUP_CODES ALC3,
      	AP_LOOKUP_CODES ALC4,
      	HR_ALL_ORGANIZATION_UNITS HAOTL,
	GL_CODE_COMBINATIONS_KFV GLCD,
	HR_LOCATIONS HRL,
	MTL_SYSTEM_ITEMS MSI,
      	PA_PROJECTS_ALL PAP,
      	PA_TASKS PAT,
      	PO_HEADERS_ALL PH,
      	PO_LINES_ALL PL,
      	PO_LINE_LOCATIONS_ALL PLL, 
	PO_DISTRIBUTIONS_ALL PD,
	GL_SETS_OF_BOOKS GSOB
WHERE
      	AID.INCOME_TAX_REGION = AITR.REGION_SHORT_NAME (+) AND
      	ALC1.LOOKUP_TYPE (+) = 'INVOICE DISTRIBUTION TYPE' AND
      	ALC1.LOOKUP_CODE (+) = AID.LINE_TYPE_LOOKUP_CODE AND
        ALC2.LOOKUP_TYPE (+) = 'NLS TRANSLATION' AND
        ALC2.LOOKUP_CODE (+) = DECODE(AID.MATCH_STATUS_FLAG , NULL,'NEVER APPROVED', 'N', 'NEVER APPROVED', 'T', 'NEEDS REAPPROVAL', 'A', 'APPROVED', 'S', 'NEVER APPROVED') AND
        ALC3.LOOKUP_TYPE (+) = 'AWT FLAG' AND
        ALC3.LOOKUP_CODE (+) = AID.AWT_FLAG AND
        ALC4.LOOKUP_TYPE (+) = 'POSTING STATUS' AND
        ALC4.LOOKUP_CODE (+) = AP_INVOICE_DISTRIBUTIONS_PKG .GET_POSTED_STATUS( AID.ACCRUAL_POSTED_FLAG, AID.CASH_POSTED_FLAG, AID.POSTED_FLAG) AND
      	AID.PROJECT_ID = PAP.PROJECT_ID (+) AND
      	AID.TASK_ID = PAT.TASK_ID (+) AND
      	AID.EXPENDITURE_ORGANIZATION_ID = HAOTL.ORGANIZATION_ID (+) AND
      	AID.PO_DISTRIBUTION_ID = PD.PO_DISTRIBUTION_ID (+) AND
      	PD.PO_HEADER_ID = PH.PO_HEADER_ID (+) AND
      	PD.LINE_LOCATION_ID = PLL.LINE_LOCATION_ID (+) AND
      	PLL.PO_LINE_ID = PL.PO_LINE_ID (+) AND
      	AID.AWT_GROUP_ID = AWT.GROUP_ID (+) AND
      	-- TCS ADDITION STARTS
	AID.SET_OF_BOOKS_ID =	GSOB.SET_OF_BOOKS_ID (+) AND
	PL.ITEM_ID  = MSI.INVENTORY_ITEM_ID (+) AND
	AID.ORG_ID = 	HAOTL.ORGANIZATION_ID (+) AND
	AID.DIST_CODE_COMBINATION_ID = GLCD.CODE_COMBINATION_ID (+) AND
	PLL.SHIP_TO_LOCATION_ID = HRL.LOCATION_ID (+) 
/
 
/*----------------------------------------------------------------------*/
--      Create View WM_AP_INVOICES_QRY_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AP_INVOICES_QRY_VW 
(
	WEB_TRANSACTION_ID, 
	DOCUMENT_TYPE,
	DOCUMENT_STATUS,
	INVOICE_ID,
	INVOICE_NUM ,
	INVOICE_TYPE,
	INVOICE_DATE ,
	PO_NUMBER ,
	VENDOR_NUMBER ,
	VENDOR_NAME ,
	VENDOR_SITE_ADDRESS_LINE1,
	VENDOR_SITE_ADDRESS_LINE2,
	VENDOR_SITE_ADDRESS_LINE3,
	VENDOR_TOWN_OR_CITY,
	VENDOR_COUNTY,
	VENDOR_STATE,
	VENDOR_POSTAL_CODE,
	VENDOR_COUNTRY,
	INVOICE_AMOUNT ,
	INVOICE_CURRENCY_CODE ,
	EXCHANGE_RATE ,
      	EXCHANGE_RATE_TYPE ,
      	TERMS_NAME ,
      	EXCHANGE_RATE_DATE ,
      	DESCRIPTION ,
	AWT_GROUP_NAME ,
	SOURCE ,
	PAYMENT_CROSS_RATE ,
	PAYMENT_CURRENCY_CODE ,
	DOC_CATEGORY_CODE ,
	VOUCHER_NUM ,
	PAYMENT_METHOD_LOOKUP_CODE ,
	PAY_GROUP_LOOKUP_CODE ,
	GOODS_RECEIVED_DATE ,
	INVOICE_RECEIVED_DATE ,
	SET_OF_BOOKS_NAME ,
	LIABILITY_ACCOUNT,
	USSGL_TRANSACTION_CODE ,
	EXCLUSIVE_PAYMENT ,
	ORGANIZATION_NAME,
	AMOUNT_APPLICABLE_TO_DISCOUNT 
) AS
SELECT
	NULL WEB_TRANSACTION_ID, 
	'APINVOICE' DOCUMENT_TYPE,
	'QUERY' DOCUMENT_STATUS,
	AI.INVOICE_ID,
	AI.INVOICE_NUM INVOICE_NUM ,
	AI.INVOICE_TYPE_LOOKUP_CODE INVOICE_TYPE_LOOKUP_CODE ,
	AI.INVOICE_DATE INVOICE_DATE ,
	AP_INVOICES_PKG.GET_PO_NUMBER( AI.INVOICE_ID) PO_NUMBER ,
	PV.SEGMENT1 VENDOR_NUMBER ,
	PV.VENDOR_NAME VENDOR_NAME ,
	PVS.ADDRESS_LINE1 ADDRESS_LINE1,
	PVS.ADDRESS_LINE2 ADDRESS_LINE2,
	PVS.ADDRESS_LINE3 ADDRESS_LINE3,
	PVS.CITY  CITY,
	PVS.COUNTY COUNTY,
	PVS.STATE STATE,
	PVS.ZIP ZIP,
	PVS.COUNTRY COUNTRY,
	AI.INVOICE_AMOUNT INVOICE_AMOUNT ,
	AI.INVOICE_CURRENCY_CODE INVOICE_CURRENCY_CODE ,
      	AI.EXCHANGE_RATE EXCHANGE_RATE ,
      	AI.EXCHANGE_RATE_TYPE EXCHANGE_RATE_TYPE ,
      	AT.NAME TERMS_NAME ,
      	AI.EXCHANGE_DATE EXCHANGE_DATE ,
      	AI.DESCRIPTION DESCRIPTION ,
	AWT.NAME AWT_GROUP_NAME ,
	AI.SOURCE SOURCE ,
	AI.PAYMENT_CROSS_RATE PAYMENT_CROSS_RATE ,
	AI.PAYMENT_CURRENCY_CODE PAYMENT_CURRENCY_CODE ,
	AI.DOC_CATEGORY_CODE DOC_CATEGORY_CODE ,
	AI.VOUCHER_NUM VOUCHER_NUM ,
	AI.PAYMENT_METHOD_LOOKUP_CODE PAYMENT_METHOD_LOOKUP_CODE ,
	AI.PAY_GROUP_LOOKUP_CODE PAY_GROUP_LOOKUP_CODE ,
	AI.GOODS_RECEIVED_DATE GOODS_RECEIVED_DATE ,
	AI.INVOICE_RECEIVED_DATE INVOICE_RECEIVED_DATE ,
	GSOB.NAME SET_OF_BOOKS_NAME,
	GLCL.CONCATENATED_SEGMENTS LIABILITY_ACCOUNT,	  
	AI.USSGL_TRANSACTION_CODE USSGL_TRANSACTION_CODE ,
	AI.EXCLUSIVE_PAYMENT_FLAG EXCLUSIVE_PAYMENT_FLAG ,
	HAOTL.NAME ORG_NAME,
	AI.AMOUNT_APPLICABLE_TO_DISCOUNT AMOUNT_APPLICABLE_TO_DISCOUNT 
FROM 
      	AP_INVOICES_ALL AI,
      	AP_TERMS AT,
      	PO_VENDORS PV,
      	PO_VENDOR_SITES_ALL PVS,
      	AP_LOOKUP_CODES ALC1,
      	AP_LOOKUP_CODES ALC2,
	AP_AWT_GROUPS AWT,
	HR_ALL_ORGANIZATION_UNITS HAOTL,	  
	GL_SETS_OF_BOOKS GSOB,	  
	GL_CODE_COMBINATIONS_KFV GLCL
WHERE
      	AI.TERMS_ID = AT.TERM_ID (+) AND
      	ALC1.LOOKUP_TYPE (+) = 'INVOICE TYPE' AND
      	ALC1.LOOKUP_CODE (+) = AI.INVOICE_TYPE_LOOKUP_CODE AND
      	ALC2.LOOKUP_TYPE (+) = 'PAYMENT METHOD' AND
      	ALC2.LOOKUP_CODE (+) = AI.PAYMENT_METHOD_LOOKUP_CODE AND
      	AI.VENDOR_ID = PV.VENDOR_ID (+) AND
      	AI.VENDOR_SITE_ID = PVS.VENDOR_SITE_ID (+) AND
	AI.AWT_GROUP_ID = AWT.GROUP_ID (+) AND
	AI.ACCTS_PAY_CODE_COMBINATION_ID = GLCL.CODE_COMBINATION_ID (+) AND
	AI.ORG_ID = HAOTL.ORGANIZATION_ID (+) AND	 
	AI.ORG_ID = PVS.ORG_ID (+) AND
	AI.SET_OF_BOOKS_ID = GSOB.SET_OF_BOOKS_ID (+)
/	

SHOW ERRORS


