/*  ***************************************************************************
    *    $Date:   15 Nov 2002 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   TCS  $
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for AR Transactions outbound in Application Schema  
    * Program Name:         wm_from_artrans_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for AR Transactions Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     15-NOV-02	 Gautam Naha  Created
    ***************************************************************************
*/

  SET feedback  ON
  SET verify            OFF
  SET newpage   0
  SET pause             OFF
  SET termout   ON

 prompt Program : wm_from_artrans_vw.SQL

  
CONNECT &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUSTOMER_TRX_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW wm_ra_customer_trx_vw ( 
web_transaction_id,document_type, document_status,
customer_trx_id,   trx_number, trx_date, previous_customer_trx_id, previous_customer_trx_number,   
related_customer_trx_number, initial_customer_trx_id, initial_customer_trx_number, 
related_batch_source_id,   related_batch_source_name, related_customer_trx_id, 
cust_trx_type_id, batch_source_id,   batch_source_name, term_id, primary_salesrep_id, 
primary_salesrep_number,   agreement_id, credit_method_for_rules, credit_method_for_installments, 
receipt_method_id,   receipt_method_name, invoicing_rule_id, invoicing_rule_name, ship_via,   
fob_point, customer_bank_account_id, customer_bank_account_name, invoice_currency_code,   
set_of_books_id, set_of_books_name, printing_option, purchase_order,   purchase_order_revision, 
purchase_order_date, comments, internal_notes,   territory_id, territory, orig_system_batch_name, 
ship_date_actual,   waybill_number, doc_sequence_id, document_number, paying_customer_id,   
paying_customer_number, paying_site_use_id, paying_site_use_number, trx_type_name,   term_name, 
agreement_name, gl_date, conversion_type,   orig_system_bill_customer_ref, orig_system_bill_address_ref,orig_system_ship_address_ref,
orig_system_sold_customer_ref,orig_system_bill_contact_ref,orig_system_ship_contact_ref,orig_system_ship_customer_ref,
conversion_rate, conversion_date,    cons_billing_num, 
header_attribute_category, header_attribute1, 
header_attribute2, header_attribute3,   header_attribute4, 
header_attribute5, header_attribute6, header_attribute7,   
header_attribute8, header_attribute9, header_attribute10, 
header_attribute11,   header_attribute12, header_attribute13, header_attribute14,
header_attribute15, attribute_category,  attribute1, attribute2, attribute3, attribute4,   attribute5, attribute6, attribute7, 
attribute8,   attribute9, attribute10, attribute11, attribute12,   attribute13, attribute14, attribute15, 
reset_trx_date_flag,reason_code,default_ussgl_transaction_code,default_ussgl_trx_code_context,organization_name  ) 
  AS SELECT 
  wmtc.web_transaction_id,  
  wmtc.transaction_type document_type,  
  DECODE((wmtc.transaction_status),0,'UPDATE',1,'INSERT',2, 'DELETE') document_status, 	
  ct.customer_trx_id ,
  ct.trx_number ,
  ct.trx_date ,
  ct.previous_customer_trx_id ,
  ctprev.trx_number previous_customer_trx_number,
  ct_rel.trx_number related_customer_trx_number,
  ct.initial_customer_trx_id ,
  ctini.trx_number initial_customer_trx_number,
  ct.related_batch_source_id ,
  bs.name related_batch_source_name,
  ct.related_customer_trx_id ,
  ct.cust_trx_type_id ,
  ct.batch_source_id,
  bs.name batch_source_name,
  ct.term_id ,
  ct.primary_salesrep_id ,
  rsep.salesrep_number,
  ct.agreement_id ,
  ct.credit_method_for_rules ,
  ct.credit_method_for_installments ,
  ct.receipt_method_id ,
  arm.name,
  ct.invoicing_rule_id ,
  rr.name,  /* invoicing rule name */    
  ct.ship_via ,
  ct.fob_point ,
  ct.customer_bank_account_id ,
  apba.bank_account_name ,
  ct.invoice_currency_code ,
  ct.set_of_books_id ,
  glsb.name set_of_books_name,
  ct.printing_option,
  ct.purchase_order ,
  ct.purchase_order_revision ,
  ct.purchase_order_date ,
  ct.comments ,
  ct.internal_notes ,
  ct.territory_id ,
  ter.name territory,
  ct.orig_system_batch_name ,
  ct.ship_date_actual ,
  ct.waybill_number ,
  ct.doc_sequence_id ,
  ct.doc_sequence_value ,
  ct.paying_customer_id ,
  NULL paying_customer_number,
  ct.paying_site_use_id ,
  NULL paying_site_use_number,
  ctt.name ,
  rat.name ,  /* term_name */    
  soa.name ,  /*  agreement_name */    
  gd.gl_date,  /* gd.gl_date*/    
  ct.exchange_rate_type,
  rac_bill.orig_system_reference orig_system_bill_customer_ref,
  custacct.orig_system_reference orig_system_bill_address_ref,
  su_ship.orig_system_reference orig_system_ship_address_ref ,
  rac_sold.orig_system_reference orig_system_sold_customer_ref, 
  raco_bill.orig_system_reference orig_system_bill_contact_ref ,
  raco_ship.orig_system_reference orig_system_ship_contact_ref, 
  rac_ship.orig_system_reference orig_system_ship_customer_ref ,
  ct.exchange_rate,
  ct.exchange_date,
  --ct.payment_server_order_num,
  --ct.approval_code ,
  NULL cons_billing_number,
  --ct.address_verification_code,
  ct.interface_header_context,
  ct.interface_header_attribute1,
  ct.interface_header_attribute2,
  ct.interface_header_attribute3,
  ct.interface_header_attribute4,
  ct.interface_header_attribute5,
  ct.interface_header_attribute6,
  ct.interface_header_attribute7,
  ct.interface_header_attribute8,
  ct.interface_header_attribute9,
  ct.interface_header_attribute10,
  ct.interface_header_attribute11,
  ct.interface_header_attribute12,
  ct.interface_header_attribute13,
  ct.interface_header_attribute14,
  ct.interface_header_attribute15,
  ct.attribute_category,
  ct.attribute1,
  ct.attribute2,
  ct.attribute3,
  ct.attribute4,
  ct.attribute5,
  ct.attribute6,
  ct.attribute7,
  ct.attribute8,
  ct.attribute9,
  ct.attribute10,
  ct.attribute11,
  ct.attribute12,
  ct.attribute13,
  ct.attribute14,
  ct.attribute15,
  NULL reset_trx_date_flag,
  ct.reason_code ,
  ct.default_ussgl_transaction_code,
  ct.default_ussgl_trx_code_context,
  org.name  
FROM 
  ra_cust_trx_line_gl_dist_all gd,
  ra_customer_trx_all ct,
  ra_customers rac_bill,
  ra_customers rac_ship,
  ra_customers rac_sold,
  ra_customers rac_paying,
  RA_SITE_USES_ALL su_bill,
  RA_SITE_USES_ALL su_ship,
  RA_SITE_USES_ALL su_paying,
  fnd_territories_vl ft_bill,
  fnd_territories_vl ft_ship,
  fnd_territories_vl ft_remit,
  ra_addresses_all raa_bill,
  ra_addresses_all raa_ship,
  ra_addresses_all raa_remit,
  ra_contacts raco_ship,
  ra_contacts raco_bill,
  ap_bank_accounts_all apba,
  ap_bank_branches apb,
  ar_receipt_methods arm,
  ar_receipt_classes arc,
  ra_batch_sources_all bs,
  ra_batches_all rab,
  ra_cust_trx_types_all ctt,  /* ra_salesreps ras  */    
  ra_terms rat,
  so_agreements soa,
  org_freight orf,
  gl_daily_conversion_types gdct,
  ra_customer_trx_all ct_rel,
  ar_lookups al_fob ,
  ar_lookups al_tax,
  -- change begins    
  ra_salesreps_all rsep ,
  ra_rules rr,
  gl_sets_of_books glsb,
  ra_customer_trx_all ctprev,
  ra_customer_trx_all ctini,
  ra_territories ter,
  ra_addresses_all custacct,
  hr_organization_units org,
  wm_track_changes_vw wmtc
WHERE 
  ct.customer_trx_id = gd.customer_trx_id AND
  'REC' = gd.account_class AND
  'Y' = gd.latest_rec_flag AND
  ct.related_customer_trx_id = ct_rel.customer_trx_id(+) AND
  ct.bill_to_customer_id = rac_bill.customer_id AND
  ct.ship_to_customer_id = rac_ship.customer_id(+) AND
  ct.sold_to_customer_id = rac_sold.customer_id(+) AND
  ct.paying_customer_id = rac_paying.customer_id(+) AND
  ct.bill_to_site_use_id = su_bill.site_use_id AND
  ct.ship_to_site_use_id = su_ship.site_use_id(+) AND
  ct.paying_site_use_id = su_paying.site_use_id(+)AND
  --su_bill.address_id = raa_bill.address_id and
  --su_ship.address_id = raa_ship.address_id(+) and
  su_bill.address_id =  raa_bill.address_id AND
  su_ship.address_id = raa_ship.address_id(+) AND
  ct.bill_to_contact_id = raco_bill.contact_id(+) AND
  ct.ship_to_contact_id = raco_ship.contact_id(+) AND
  ct.remit_to_address_id = raa_remit.address_id(+) AND
  raa_bill.country =  ft_bill.territory_code(+) AND
  raa_ship.country = ft_ship.territory_code(+) AND
  raa_remit.country = ft_remit.territory_code(+) AND
  ct.customer_bank_account_id = apba.bank_account_id(+) AND
  apba.bank_branch_id = apb.bank_branch_id(+) AND
  ct.receipt_method_id = arm.receipt_method_id(+) AND
  arm.receipt_class_id = arc.receipt_class_id(+) AND
  ct.batch_source_id = bs.batch_source_id AND
  ct.batch_id =  rab.batch_id(+) AND
  ct.cust_trx_type_id = ctt.cust_trx_type_id AND
  ctt.TYPE <> 'BR'AND
  ct.term_id = rat.term_id(+) AND
  ct.agreement_id = soa.agreement_id(+) AND
  ct.exchange_rate_type = gdct.conversion_type(+) AND
  'FOB' = al_fob.lookup_type(+) AND
  ct.fob_point = al_fob.lookup_code(+) AND
  ct.ship_via = orf.freight_code(+) AND
  ct.org_id = orf.organization_id(+) AND
  'TAX_CONTROL_FLAG' = al_tax.lookup_type(+) AND
  ct.default_tax_exempt_flag = al_tax.lookup_code(+) AND
  --change begins    
  ctprev.customer_trx_id (+) = ct.previous_customer_trx_id AND
  ctini.customer_trx_id (+) = ct.initial_customer_trx_id  AND
  ter.territory_id (+) = ct.territory_id  AND
  gd.org_id (+) = ct.org_id AND
  su_bill.org_id (+) = ct.org_id AND
  su_ship.org_id (+) = ct.org_id AND
  su_paying.org_id (+) = ct.org_id AND
  raa_bill.org_id (+) = ct.org_id AND
  raa_remit.org_id (+) = ct.org_id AND
  apba.org_id (+) = ct.org_id AND
  bs.org_id (+) = ct.org_id AND
  rab.org_id (+) = ct.org_id AND
  ctt.org_id  (+) = ct.org_id AND
  rsep.salesrep_id (+) = ct.primary_salesrep_id  AND
  ct.invoicing_rule_id  = rr.rule_id (+) AND
  ct.customer_bank_account_id  = apba.bank_account_id (+) AND
  glsb.set_of_books_id (+) = ct.set_of_books_id AND
  rsep.org_id (+) = ct.org_id AND
  custacct.address_id (+) = su_bill.address_id AND
  ct.org_id = org.organization_id (+) AND 
  ct.customer_trx_id = wmtc.transaction_id AND  
  wmtc.transaction_status <= 2 AND  
  wmtc.transaction_type = 'ARTRANSACTION' AND
  ct.complete_flag = 'Y'
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_LINE_GL_DIST_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_LINE_GL_DIST_VW ( CUST_TRX_LINE_GL_DIST_ID, 
CUSTOMER_TRX_ID, CUSTOMER_TRX_LINE_ID, CUST_TRX_LINE_SALESREP_ID, ACCT_DISTRIBUTION_PERCENT, 
AMOUNT, ACCTD_AMOUNT, GL_DATE, ORIGINAL_GL_DATE, 
GL_POSTED_DATE, ACCOUNT_CLASS, ACCOUNT_SET_FLAG, LATEST_REC_FLAG, 
CODE_COMBINATION_ID, ACCOUNT_NUMBER, 
--COLLECTED_TAX_CCID, 
--INTERIM_TAX_ACCOUNT_NUMBER, 
COMMENTS, SET_OF_BOOKS_ID, LAST_UPDATE_DATE, LAST_UPDATED_BY, 
CREATION_DATE, CREATED_BY, LAST_UPDATE_LOGIN, REQUEST_ID, 
PROGRAM_APPLICATION_ID, PROGRAM_ID, PROGRAM_UPDATE_DATE, POST_REQUEST_ID, 
POSTING_CONTROL_ID, RA_POST_LOOP_NUMBER, USSGL_TRANSACTION_CODE, USSGL_TRANSACTION_CODE_CONTEXT, 
ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, 
ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, 
ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, 
ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, 
CTL_LINE_AMOUNT, RR_ACCOUNTING_RULE, CTL_LINE_NUMBER, CTL_OTHER_LINE_NUMBER, 
AL_CLASS_MEANING, AL_LINE_TYPE_MEANING, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, 
INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, 
INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, 
INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, 
INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15 ) AS SELECT  
LGD.CUST_TRX_LINE_GL_DIST_ID ,  
LGD.CUSTOMER_TRX_ID ,  
LGD.CUSTOMER_TRX_LINE_ID ,  
LGD.CUST_TRX_LINE_SALESREP_ID ,  
LGD.PERCENT ,  
LGD.AMOUNT ,  
LGD.ACCTD_AMOUNT ,  
LGD.GL_DATE ,  
LGD.ORIGINAL_GL_DATE ,  
LGD.GL_POSTED_DATE ,  
LGD.ACCOUNT_CLASS ,  
LGD.ACCOUNT_SET_FLAG ,  
LGD.LATEST_REC_FLAG ,  
LGD.CODE_COMBINATION_ID ,  
LGD.CONCATENATED_SEGMENTS ,  
--LGD.COLLECTED_TAX_CCID ,  
--LGD.COLLECTED_TAX_CONCAT_SEG ,  
LGD.COMMENTS ,  
LGD.SET_OF_BOOKS_ID ,  
LGD.LAST_UPDATE_DATE ,  
LGD.LAST_UPDATED_BY ,  
LGD.CREATION_DATE ,  
LGD.CREATED_BY ,  
LGD.LAST_UPDATE_LOGIN ,  
LGD.REQUEST_ID ,  
LGD.PROGRAM_APPLICATION_ID ,  
LGD.PROGRAM_ID ,  
LGD.PROGRAM_UPDATE_DATE ,  
LGD.POST_REQUEST_ID ,  
LGD.POSTING_CONTROL_ID ,  
LGD.RA_POST_LOOP_NUMBER ,  
LGD.USSGL_TRANSACTION_CODE ,  
LGD.USSGL_TRANSACTION_CODE_CONTEXT ,  
LGD.ATTRIBUTE_CATEGORY ,  
LGD.ATTRIBUTE1 ,  
LGD.ATTRIBUTE2 ,  
LGD.ATTRIBUTE3 ,  
LGD.ATTRIBUTE4 ,  
LGD.ATTRIBUTE5 ,  
LGD.ATTRIBUTE6 ,  
LGD.ATTRIBUTE7 ,  
LGD.ATTRIBUTE8 ,  
LGD.ATTRIBUTE9 ,  
LGD.ATTRIBUTE10 ,  
LGD.ATTRIBUTE11 ,  
LGD.ATTRIBUTE12 ,  
LGD.ATTRIBUTE13 ,  
LGD.ATTRIBUTE14 ,  
LGD.ATTRIBUTE15 ,  
CTL.EXTENDED_AMOUNT ,  
RR.NAME ,  
DECODE(CTL.LINK_TO_CUST_TRX_LINE_ID,  
NULL,  
CTL.LINE_NUMBER,  
CTL_LINE.LINE_NUMBER) ,  
DECODE(CTL.LINK_TO_CUST_TRX_LINE_ID,  
NULL,  
'',  
CTL.LINE_NUMBER) ,  
AL_CLASS.MEANING ,  
AL_TYPE.MEANING,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1 ,  
CTL.INTERFACE_LINE_ATTRIBUTE2 ,  
CTL.INTERFACE_LINE_ATTRIBUTE3 ,  
CTL.INTERFACE_LINE_ATTRIBUTE4 ,  
CTL.INTERFACE_LINE_ATTRIBUTE5 ,  
CTL.INTERFACE_LINE_ATTRIBUTE6 ,  
CTL.INTERFACE_LINE_ATTRIBUTE7 ,  
CTL.INTERFACE_LINE_ATTRIBUTE8 ,  
CTL.INTERFACE_LINE_ATTRIBUTE9 ,  
CTL.INTERFACE_LINE_ATTRIBUTE10 ,  
CTL.INTERFACE_LINE_ATTRIBUTE11 ,  
CTL.INTERFACE_LINE_ATTRIBUTE12 ,  
CTL.INTERFACE_LINE_ATTRIBUTE13 ,  
CTL.INTERFACE_LINE_ATTRIBUTE14 ,  
CTL.INTERFACE_LINE_ATTRIBUTE15  
FROM  
RA_CUST_TRX_LINE_GL_DIST_ALL LGD,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINE,  
AR_LOOKUPS AL_CLASS,  
AR_LOOKUPS AL_TYPE,  
RA_RULES RR  
WHERE  
LGD.CUSTOMER_TRX_LINE_ID = CTL.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.LINK_TO_CUST_TRX_LINE_ID = CTL_LINE.CUSTOMER_TRX_LINE_ID(+) AND  
AL_CLASS.LOOKUP_TYPE = 'AUTOGL_TYPE' AND  
AL_CLASS.LOOKUP_CODE = LGD.ACCOUNT_CLASS AND  
AL_TYPE.LOOKUP_TYPE(+) = 'STD_LINE_TYPE' AND  
AL_TYPE.LOOKUP_CODE(+) = CTL.LINE_TYPE AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+)
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_FREIGHT_VW
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_RA_CUST_TRX_FREIGHT_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, PREVIOUS_CUST_TRX_LINE_NUM, LINE_NUMBER, 
LINE_TYPE, DESCRIPTION, QUANTITY_ORDERED, QUANTITY_CREDITED, 
QUANTITY, UNIT_STANDARD_PRICE, UNIT_SELLING_PRICE, REVENUE_AMOUNT, 
AMOUNT, 
--AMOUNT_INCLUDES_TAX_FLAG, 
UOM_CODE, REASON_CODE, 
REASON_CODE_MEANING, ACCOUNTING_RULE_ID, ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, 
RULE_START_DATE, LAST_PERIOD_TO_CREDIT, INVENTORY_ITEM_ID, INVENTORY_ITEM, 
MEMO_LINE_ID, MEMO_LINE_NAME, TAX_PRECEDENCE, TAX_RATE, 
TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, 
SALES_TAX_ID, SALES_TAX_CODE, LOCATION_SEGMENT_ID, VAT_TAX_ID, 
SALES_ORDER_SOURCE, SALES_ORDER, SALES_ORDER_REVISION, SALES_ORDER_LINE, 
SALES_ORDER_DATE, MOVEMENT_ID, DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, 
ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, 
ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, 
ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, 
ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, 
INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, 
INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, 
INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, 
INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, 
REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, 
REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, 
REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, 
REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, 
UOM_NAME, 
--WAREHOUSE_ID, 
WAREHOUSE_NAME, ORGANIZATION_NAME, 
--TRANSLATED_DESCRIPTION, 
TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, 
SALES_TAX_FROM_POSTAL_CODE, TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
--NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
CTL.MEMO_LINE_ID ,  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
--CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
--CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL T,  
AR_MEMO_LINES_ALL B,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.ORG_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   (+)AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL.LINE_TYPE = 'FREIGHT' AND  
CTL.LINK_TO_CUST_TRX_LINE_ID IS NULL
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_NOTES_VW 
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_AR_NOTES_VW ( NOTE_ID, 
CUSTOMER_TRX_ID, NOTE_DATE, SOURCE, AL_NOTE_TYPE_MEANING, 
MEMO, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, 
CREATION_DATE, CREATED_BY ) AS SELECT  
N.NOTE_ID ,  
N.CUSTOMER_TRX_ID ,  
N.CREATION_DATE ,  
N.NOTE_TYPE ,  
L.MEANING ,  
N.TEXT ,  
N.LAST_UPDATED_BY ,  
N.LAST_UPDATE_DATE ,  
N.LAST_UPDATE_LOGIN ,  
N.CREATION_DATE ,  
N.CREATED_BY  
FROM  
AR_NOTES N,  
AR_LOOKUPS L  
WHERE  
L.LOOKUP_TYPE = 'NOTE_TYPE' AND  
N.NOTE_TYPE = L.LOOKUP_CODE
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_CHARGES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_CHARGES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, PREVIOUS_CUST_TRX_LINE_NUM, LINE_NUMBER, 
LINE_TYPE, DESCRIPTION, QUANTITY_ORDERED, QUANTITY_CREDITED, 
QUANTITY, UNIT_STANDARD_PRICE, UNIT_SELLING_PRICE, REVENUE_AMOUNT, 
AMOUNT, 
--AMOUNT_INCLUDES_TAX_FLAG, 
UOM_CODE, REASON_CODE, 
REASON_CODE_MEANING, ACCOUNTING_RULE_ID, ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, 
RULE_START_DATE, LAST_PERIOD_TO_CREDIT, INVENTORY_ITEM_ID, INVENTORY_ITEM, 
MEMO_LINE_ID, MEMO_LINE_NAME, TAX_PRECEDENCE, TAX_RATE, 
TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, 
SALES_TAX_ID, SALES_TAX_CODE, LOCATION_SEGMENT_ID, VAT_TAX_ID, 
SALES_ORDER_SOURCE, SALES_ORDER, SALES_ORDER_REVISION, SALES_ORDER_LINE, 
SALES_ORDER_DATE, MOVEMENT_ID, DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, 
ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, 
ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, 
ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, 
ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, 
INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, 
INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, 
INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, 
INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, 
REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, 
REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, 
REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, 
REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, 
UOM_NAME, 
--WAREHOUSE_ID, 
WAREHOUSE_NAME, ORGANIZATION_NAME, 
--TRANSLATED_DESCRIPTION, 
TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, 
SALES_TAX_FROM_POSTAL_CODE, TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
--NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
CTL.MEMO_LINE_ID ,  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
--CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
--CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL T,  
AR_MEMO_LINES_ALL B,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.ORG_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   (+)AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL.LINE_TYPE = 'CHARGES' AND  
CTL.LINK_TO_CUST_TRX_LINE_ID IS NULL
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUSTOMER_TRX_LINES_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUSTOMER_TRX_LINES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINK_TO_CUST_TRX_LINE, PREVIOUS_CUST_TRX_LINE_NUM, 
INITIAL_CUSTOMER_TRX_LINE_NUM, LINE_NUMBER, LINE_TYPE, DESCRIPTION, 
QUANTITY_ORDERED, QUANTITY_CREDITED, QUANTITY_INVOICED, UNIT_STANDARD_PRICE, 
UNIT_SELLING_PRICE, REVENUE_AMOUNT, EXTENDED_AMOUNT, 
--AMOUNT_INCLUDES_TAX_FLAG, 
UOM_CODE, REASON_CODE, REASON_CODE_MEANING, ACCOUNTING_RULE_ID, 
ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, RULE_START_DATE, LAST_PERIOD_TO_CREDIT, 
INVENTORY_ITEM_ID, INVENTORY_ITEM, MEMO_LINE_ID, MEMO_LINE_NAME, 
TAX_PRECEDENCE, TAX_RATE, TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, 
TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, SALES_TAX_ID, SALES_TAX_CODE, 
LOCATION_SEGMENT_ID, VAT_TAX_ID, SALES_ORDER_SOURCE, SALES_ORDER, 
SALES_ORDER_REVISION, SALES_ORDER_LINE, SALES_ORDER_DATE, MOVEMENT_ID, 
DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, ATTRIBUTE_CATEGORY, ATTRIBUTE1, 
ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, 
ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, 
ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, 
ATTRIBUTE14, ATTRIBUTE15, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, 
INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, 
INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, 
INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, 
INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, 
REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, 
REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, 
REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, 
REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, UOM_NAME, 
--WAREHOUSE_ID, 
WAREHOUSE_NAME, ORGANIZATION_NAME, VAT_TAX_CODE, 
--TRANSLATED_DESCRIPTION, 
TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, SALES_TAX_FROM_POSTAL_CODE, 
TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE, LINK_TO_LINE_CONTEXT, LINK_TO_LINE_ATTRIBUTE1, 
LINK_TO_LINE_ATTRIBUTE2, LINK_TO_LINE_ATTRIBUTE3, LINK_TO_LINE_ATTRIBUTE4, LINK_TO_LINE_ATTRIBUTE5, 
LINK_TO_LINE_ATTRIBUTE6, LINK_TO_LINE_ATTRIBUTE7, LINK_TO_LINE_ATTRIBUTE8, LINK_TO_LINE_ATTRIBUTE9, 
LINK_TO_LINE_ATTRIBUTE10, LINK_TO_LINE_ATTRIBUTE11, LINK_TO_LINE_ATTRIBUTE12, LINK_TO_LINE_ATTRIBUTE13, 
LINK_TO_LINE_ATTRIBUTE14, LINK_TO_LINE_ATTRIBUTE15 ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_LINK.LINE_NUMBER LINK_TO_CUST_TRX_LINE,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
NULL,  
--CTL_INI.LINE_NUMBER INITIAL_CUSTOMER_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
--NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
/*SEGMENT 1 IN TABLE MTL_SYSTEM_ITEMS */    CTL.MEMO_LINE_ID ,  
/* + MEMO_LINE_NAME*/  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
/* MTL_MOVEMENT_STATISTICS*/    CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
--CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
VAT.TAX_CODE ,  
--CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE,  
CTL_LINK.INTERFACE_LINE_CONTEXT ,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE1,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE2,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE3,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE4,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE5,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE6,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE7,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE8,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE9,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE10,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE11,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE12,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE13,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE14,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE15  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
--MTL_UNITS_OF_MEASURE UOM_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL T,  
AR_MEMO_LINES_ALL B,  
AR_VAT_TAX_ALL VAT,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
--- CHANGE BEGINS  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINK,  
--RA_CUSTOMER_TRX_LINES_ALL CTL_INI,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG,  
MTL_UNITS_OF_MEASURE UOM_LINK  
--MTL_UNITS_OF_MEASURE UOM_INI  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') /* 19-APR-2000 J RAUTIAINEN BR IMPLEMENTATION */ AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
--CTL_PREV.UOM_CODE = UOM_PREV.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.VAT_TAX_ID = VAT.VAT_TAX_ID(+) AND  
CTL.ORG_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
--- CHANGE BEGINS  
CTL_LINK.CUSTOMER_TRX_LINE_ID (+) = CTL.LINK_TO_CUST_TRX_LINE_ID AND  
--CTL_INI.CUSTOMER_TRX_LINE_ID (+) = CTL.INITIAL_CUSTOMER_TRX_LINE_ID  AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CT.ORG_ID = VAT.ORG_ID  AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL_LINK.UOM_CODE = UOM_LINK.UOM_CODE(+) AND  
--CTL_INI.UOM_CODE = UOM_INI.UOM_CODE(+) AND  
CTL.LINE_TYPE = 'LINE'
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_FREIGHTLINES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_FREIGHTLINES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINK_TO_CUST_TRX_LINE, PREVIOUS_CUST_TRX_LINE_NUM, 
LINE_NUMBER, LINE_TYPE, DESCRIPTION, QUANTITY_ORDERED, 
QUANTITY_CREDITED, QUANTITY_INVOICED, UNIT_STANDARD_PRICE, UNIT_SELLING_PRICE, 
REVENUE_AMOUNT, AMOUNT, 
--AMOUNT_INCLUDES_TAX_FLAG, 
UOM_CODE, 
REASON_CODE, REASON_CODE_MEANING, ACCOUNTING_RULE_ID, ACCOUNTING_RULE_DURATION, 
ACCOUNTING_RULE_NAME, RULE_START_DATE, LAST_PERIOD_TO_CREDIT, INVENTORY_ITEM_ID, 
INVENTORY_ITEM, MEMO_LINE_ID, MEMO_LINE_NAME, TAX_PRECEDENCE, 
TAX_RATE, TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, TAX_EXEMPT_REASON_CODE, 
TAX_EXEMPT_REASON_CODE_MEANING, SALES_TAX_ID, SALES_TAX_CODE, LOCATION_SEGMENT_ID, 
VAT_TAX_ID, SALES_ORDER_SOURCE, SALES_ORDER, SALES_ORDER_REVISION, 
SALES_ORDER_LINE, SALES_ORDER_DATE, MOVEMENT_ID, DEFAULT_USSGL_TRANSACTION_CODE, 
DEFAULT_USSGL_TRX_CODE_CONTEXT, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, 
ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, 
ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, 
ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, 
ATTRIBUTE15, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, 
INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, 
INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, 
INTERFACE_LINE_ATTRIBUTE15, REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, REFERENCE_LINE_ATTRIBUTE2, 
REFERENCE_LINE_ATTRIBUTE3, REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, REFERENCE_LINE_ATTRIBUTE6, 
REFERENCE_LINE_ATTRIBUTE7, REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, REFERENCE_LINE_ATTRIBUTE10, 
REFERENCE_LINE_ATTRIBUTE11, REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, REFERENCE_LINE_ATTRIBUTE14, 
REFERENCE_LINE_ATTRIBUTE15, UOM_NAME, 
--WAREHOUSE_ID, 
WAREHOUSE_NAME, 
ORGANIZATION_NAME, 
--TRANSLATED_DESCRIPTION, 
TAX_ITEM_EXCEPTION, TAX_EXEMPTION, 
SALES_TAX_TO_POSTAL_CODE, SALES_TAX_FROM_POSTAL_CODE, TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE, 
LINK_TO_LINE_CONTEXT, LINK_TO_LINE_ATTRIBUTE1, LINK_TO_LINE_ATTRIBUTE2, LINK_TO_LINE_ATTRIBUTE3, 
LINK_TO_LINE_ATTRIBUTE4, LINK_TO_LINE_ATTRIBUTE5, LINK_TO_LINE_ATTRIBUTE6, LINK_TO_LINE_ATTRIBUTE7, 
LINK_TO_LINE_ATTRIBUTE8, LINK_TO_LINE_ATTRIBUTE9, LINK_TO_LINE_ATTRIBUTE10, LINK_TO_LINE_ATTRIBUTE11, 
LINK_TO_LINE_ATTRIBUTE12, LINK_TO_LINE_ATTRIBUTE13, LINK_TO_LINE_ATTRIBUTE14, LINK_TO_LINE_ATTRIBUTE15
 ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_LINK.LINE_NUMBER LINK_TO_CUST_TRX_LINE,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
--NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
CTL.MEMO_LINE_ID ,  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
--CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
--CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE,  
CTL_LINK.INTERFACE_LINE_CONTEXT ,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE1,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE2,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE3,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE4,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE5,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE6,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE7,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE8,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE9,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE10,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE11,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE12,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE13,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE14,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE15  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL T,  
AR_MEMO_LINES_ALL B,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINK,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG,  
MTL_UNITS_OF_MEASURE UOM_LINK  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.ORG_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
CTL_LINK.CUSTOMER_TRX_LINE_ID (+) = CTL.LINK_TO_CUST_TRX_LINE_ID AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   (+)AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL_LINK.UOM_CODE = UOM_LINK.UOM_CODE(+) AND  
CTL.LINE_TYPE = 'FREIGHT'
/
 

/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_TAXLINES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_TAXLINES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINK_TO_CUST_TRX_LINE, PREVIOUS_CUST_TRX_LINE_NUM, 
INITIAL_CUSTOMER_TRX_LINE_NUM, LINE_NUMBER, LINE_TYPE, DESCRIPTION, 
QUANTITY_ORDERED, QUANTITY_CREDITED, QUANTITY_INVOICED, UNIT_STANDARD_PRICE, 
UNIT_SELLING_PRICE, REVENUE_AMOUNT, AMOUNT, 
--AMOUNT_INCLUDES_TAX_FLAG, 
UOM_CODE, REASON_CODE, REASON_CODE_MEANING, ACCOUNTING_RULE_ID, 
ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, RULE_START_DATE, LAST_PERIOD_TO_CREDIT, 
INVENTORY_ITEM_ID, INVENTORY_ITEM, MEMO_LINE_ID, MEMO_LINE_NAME, 
TAX_PRECEDENCE, TAX_RATE, TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, 
TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, SALES_TAX_ID, SALES_TAX_CODE, 
LOCATION_SEGMENT_ID, VAT_TAX_ID, SALES_ORDER_SOURCE, SALES_ORDER, 
SALES_ORDER_REVISION, SALES_ORDER_LINE, SALES_ORDER_DATE, MOVEMENT_ID, 
DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, ATTRIBUTE_CATEGORY, ATTRIBUTE1, 
ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, 
ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, 
ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, 
ATTRIBUTE14, ATTRIBUTE15, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, 
INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, 
INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, 
INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, 
INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, 
REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, 
REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, 
REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, 
REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, UOM_NAME, 
--WAREHOUSE_ID, 
WAREHOUSE_NAME, ORGANIZATION_NAME, VAT_TAX_CODE, 
--TRANSLATED_DESCRIPTION, 
TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, SALES_TAX_FROM_POSTAL_CODE, 
TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE, LINK_TO_LINE_CONTEXT, LINK_TO_LINE_ATTRIBUTE1, 
LINK_TO_LINE_ATTRIBUTE2, LINK_TO_LINE_ATTRIBUTE3, LINK_TO_LINE_ATTRIBUTE4, LINK_TO_LINE_ATTRIBUTE5, 
LINK_TO_LINE_ATTRIBUTE6, LINK_TO_LINE_ATTRIBUTE7, LINK_TO_LINE_ATTRIBUTE8, LINK_TO_LINE_ATTRIBUTE9, 
LINK_TO_LINE_ATTRIBUTE10, LINK_TO_LINE_ATTRIBUTE11, LINK_TO_LINE_ATTRIBUTE12, LINK_TO_LINE_ATTRIBUTE13, 
LINK_TO_LINE_ATTRIBUTE14, LINK_TO_LINE_ATTRIBUTE15 ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_LINK.LINE_NUMBER LINK_TO_CUST_TRX_LINE,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
NULL,  
--CTL_INI.LINE_NUMBER INITIAL_CUSTOMER_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
--NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
/*SEGMENT 1 IN TABLE MTL_SYSTEM_ITEMS */    CTL.MEMO_LINE_ID ,  
/* + MEMO_LINE_NAME*/  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
/* MTL_MOVEMENT_STATISTICS*/    CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
--CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
VAT.TAX_CODE ,  
--CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE,  
CTL_LINK.INTERFACE_LINE_CONTEXT ,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE1,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE2,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE3,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE4,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE5,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE6,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE7,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE8,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE9,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE10,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE11,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE12,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE13,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE14,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE15  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
--MTL_UNITS_OF_MEASURE UOM_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL T,  
AR_MEMO_LINES_ALL B,  
AR_VAT_TAX_ALL VAT,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
--- CHANGE BEGINS  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINK,  
--RA_CUSTOMER_TRX_LINES_ALL CTL_INI,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG,  
MTL_UNITS_OF_MEASURE UOM_LINK  
--MTL_UNITS_OF_MEASURE UOM_INI  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') /* 19-APR-2000 J RAUTIAINEN BR IMPLEMENTATION */ AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
--CTL_PREV.UOM_CODE = UOM_PREV.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.VAT_TAX_ID = VAT.VAT_TAX_ID(+) AND  
CTL.ORG_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
--- CHANGE BEGINS  
CTL_LINK.CUSTOMER_TRX_LINE_ID (+) = CTL.LINK_TO_CUST_TRX_LINE_ID AND  
--CTL_INI.CUSTOMER_TRX_LINE_ID (+) = CTL.INITIAL_CUSTOMER_TRX_LINE_ID  AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CT.ORG_ID = VAT.ORG_ID  AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL_LINK.UOM_CODE = UOM_LINK.UOM_CODE(+) AND  
--CTL_INI.UOM_CODE = UOM_INI.UOM_CODE(+) AND  
CTL.LINE_TYPE = 'TAX'
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_SALESREPS_LINES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_SALESREPS_LINES_VW ( CUSTOMER_TRX_ID, 
CUST_TRX_LINE_SALESREP_ID, SALESREP_NUMBER, CUSTOMER_TRX_LINE_ID, REVENUE_PERCENT_SPLIT, 
REVENUE_AMOUNT_SPLIT, NON_REVENUE_PERCENT_SPLIT, NON_REVENUE_AMOUNT_SPLIT, SALESREP_NAME, 
SALES_CREDIT_TYPE_NAME, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, 
INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, 
INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, 
INTERFACE_LINE_ATTRIBUTE15, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, 
ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, 
ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, 
ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, 
ATTRIBUTE15 ) AS SELECT  
TRX_LINE.CUSTOMER_TRX_ID,  
SCREDITS.CUST_TRX_LINE_SALESREP_ID,  
SALESREP.SALESREP_NUMBER ,  
SCREDITS.CUSTOMER_TRX_LINE_ID ,  
SCREDITS.REVENUE_PERCENT_SPLIT ,  
SCREDITS.REVENUE_AMOUNT_SPLIT ,  
SCREDITS.NON_REVENUE_PERCENT_SPLIT ,  
SCREDITS.NON_REVENUE_AMOUNT_SPLIT ,  
SALESREP.NAME,  
SCT.NAME SALES_CREDIT_TYPE_NAME,  
NULL INTERFACE_LINE_CONTEXT,  
NULL INTERFACE_LINE_ATTRIBUTE1,  
NULL INTERFACE_LINE_ATTRIBUTE2,  
NULL INTERFACE_LINE_ATTRIBUTE3,  
NULL INTERFACE_LINE_ATTRIBUTE4,  
NULL INTERFACE_LINE_ATTRIBUTE5,  
NULL INTERFACE_LINE_ATTRIBUTE6,  
NULL INTERFACE_LINE_ATTRIBUTE7,  
NULL INTERFACE_LINE_ATTRIBUTE8,  
NULL INTERFACE_LINE_ATTRIBUTE9,  
NULL INTERFACE_LINE_ATTRIBUTE10,  
NULL INTERFACE_LINE_ATTRIBUTE11,  
NULL INTERFACE_LINE_ATTRIBUTE12,  
NULL INTERFACE_LINE_ATTRIBUTE13,  
NULL INTERFACE_LINE_ATTRIBUTE14,  
NULL INTERFACE_LINE_ATTRIBUTE15,  
SCREDITS.ATTRIBUTE_CATEGORY ,  
SCREDITS.ATTRIBUTE1 ,  
SCREDITS.ATTRIBUTE2 ,  
SCREDITS.ATTRIBUTE3 ,  
SCREDITS.ATTRIBUTE4 ,  
SCREDITS.ATTRIBUTE5 ,  
SCREDITS.ATTRIBUTE6 ,  
SCREDITS.ATTRIBUTE7 ,  
SCREDITS.ATTRIBUTE8 ,  
SCREDITS.ATTRIBUTE9 ,  
SCREDITS.ATTRIBUTE10 ,  
SCREDITS.ATTRIBUTE11 ,  
SCREDITS.ATTRIBUTE12 ,  
SCREDITS.ATTRIBUTE13 ,  
SCREDITS.ATTRIBUTE14 ,  
SCREDITS.ATTRIBUTE15  
FROM  
RA_SALESREPS_ALL SALESREP ,  
--JTF_RS_RESOURCE_EXTNS_VL RES,  
RA_SALESREPS_ALL PREV_SREP ,  
RA_CUST_TRX_LINE_SALESREPS_ALL  PREV_SCREDIT,  
RA_CUSTOMER_TRX_LINES_ALL TRX_LINE,  
RA_CUST_TRX_LINE_SALESREPS_ALL SCREDITS  ,  
SO_SALES_CREDIT_TYPES SCT  
WHERE  
SCREDITS.SALESREP_ID  = SALESREP.SALESREP_ID  AND  
SCREDITS.CUSTOMER_TRX_LINE_ID = TRX_LINE.CUSTOMER_TRX_LINE_ID (+) AND  
SCREDITS.PREV_CUST_TRX_LINE_SALESREP_ID = PREV_SCREDIT.CUST_TRX_LINE_SALESREP_ID(+) AND  
PREV_SCREDIT.SALESREP_ID = PREV_SREP.SALESREP_ID(+) AND  
TRX_LINE.ORG_ID (+) = SCREDITS.ORG_ID AND  
--SALESREP.RESOURCE_ID = RES.RESOURCE_ID AND  
--RES.CATEGORY IN ('EMPLOYEE','OTHER','PARTY','PARTNER','SUPPLIER_CONTACT') AND  
SALESREP.ORG_ID (+) = SCREDITS.ORG_ID AND  
SALESREP.SALES_CREDIT_TYPE_ID = SCT.SALES_CREDIT_TYPE_ID
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_SALESREPS_DEFAULT_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_SALESREPS_DEFAULT_VW ( CUSTOMER_TRX_ID, 
CUST_TRX_LINE_SALESREP_ID, SALESREP_NUMBER, CUSTOMER_TRX_LINE_ID, REVENUE_PERCENT_SPLIT, 
REVENUE_AMOUNT_SPLIT, NON_REVENUE_PERCENT_SPLIT, NON_REVENUE_AMOUNT_SPLIT, SALESREP_NAME, 
SALES_CREDIT_TYPE_NAME, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, 
INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, 
INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, 
INTERFACE_LINE_ATTRIBUTE15, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, 
ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, 
ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, 
ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, 
ATTRIBUTE15 ) AS SELECT  
SCREDITS.CUSTOMER_TRX_ID,  
SCREDITS.CUST_TRX_LINE_SALESREP_ID,  
SALESREP.SALESREP_NUMBER ,  
SCREDITS.CUSTOMER_TRX_LINE_ID ,  
SCREDITS.REVENUE_PERCENT_SPLIT ,  
SCREDITS.REVENUE_AMOUNT_SPLIT ,  
SCREDITS.NON_REVENUE_PERCENT_SPLIT ,  
SCREDITS.NON_REVENUE_AMOUNT_SPLIT ,  
SALESREP.NAME,  
SCT.NAME SALES_CREDIT_TYPE_NAME,  
NULL INTERFACE_LINE_CONTEXT,  
NULL INTERFACE_LINE_ATTRIBUTE1,  
NULL INTERFACE_LINE_ATTRIBUTE2,  
NULL INTERFACE_LINE_ATTRIBUTE3,  
NULL INTERFACE_LINE_ATTRIBUTE4,  
NULL INTERFACE_LINE_ATTRIBUTE5,  
NULL INTERFACE_LINE_ATTRIBUTE6,  
NULL INTERFACE_LINE_ATTRIBUTE7,  
NULL INTERFACE_LINE_ATTRIBUTE8,  
NULL INTERFACE_LINE_ATTRIBUTE9,  
NULL INTERFACE_LINE_ATTRIBUTE10,  
NULL INTERFACE_LINE_ATTRIBUTE11,  
NULL INTERFACE_LINE_ATTRIBUTE12,  
NULL INTERFACE_LINE_ATTRIBUTE13,  
NULL INTERFACE_LINE_ATTRIBUTE14,  
NULL INTERFACE_LINE_ATTRIBUTE15,  
SCREDITS.ATTRIBUTE_CATEGORY ,  
SCREDITS.ATTRIBUTE1 ,  
SCREDITS.ATTRIBUTE2 ,  
SCREDITS.ATTRIBUTE3 ,  
SCREDITS.ATTRIBUTE4 ,  
SCREDITS.ATTRIBUTE5 ,  
SCREDITS.ATTRIBUTE6 ,  
SCREDITS.ATTRIBUTE7 ,  
SCREDITS.ATTRIBUTE8 ,  
SCREDITS.ATTRIBUTE9 ,  
SCREDITS.ATTRIBUTE10 ,  
SCREDITS.ATTRIBUTE11 ,  
SCREDITS.ATTRIBUTE12 ,  
SCREDITS.ATTRIBUTE13 ,  
SCREDITS.ATTRIBUTE14 ,  
SCREDITS.ATTRIBUTE15  
FROM  
RA_SALESREPS_ALL SALESREP ,  
--JTF_RS_RESOURCE_EXTNS_VL RES,  
RA_SALESREPS_ALL PREV_SREP ,  
RA_CUST_TRX_LINE_SALESREPS_ALL  PREV_SCREDIT,  
RA_CUST_TRX_LINE_SALESREPS_ALL SCREDITS  ,  
SO_SALES_CREDIT_TYPES SCT  
WHERE  
SCREDITS.SALESREP_ID  = SALESREP.SALESREP_ID  AND  
SCREDITS.PREV_CUST_TRX_LINE_SALESREP_ID = PREV_SCREDIT.CUST_TRX_LINE_SALESREP_ID(+) AND  
PREV_SCREDIT.SALESREP_ID = PREV_SREP.SALESREP_ID(+) AND  
--SALESREP.RESOURCE_ID = RES.RESOURCE_ID AND  
--RES.CATEGORY IN ('EMPLOYEE','OTHER','PARTY','PARTNER','SUPPLIER_CONTACT') AND  
SALESREP.ORG_ID (+) = SCREDITS.ORG_ID AND  
SALESREP.SALES_CREDIT_TYPE_ID = SCT.SALES_CREDIT_TYPE_ID AND  
SCREDITS.CUSTOMER_TRX_LINE_ID IS NULL
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUSTOMER_TRX_QRY_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUSTOMER_TRX_QRY_VW ( WEB_TRANSACTION_ID, 
DOCUMENT_TYPE, DOCUMENT_STATUS, CUSTOMER_TRX_ID, TRX_NUMBER, 
TRX_DATE, PREVIOUS_CUSTOMER_TRX_ID, PREVIOUS_CUSTOMER_TRX_NUMBER, RELATED_CUSTOMER_TRX_NUMBER, 
INITIAL_CUSTOMER_TRX_ID, INITIAL_CUSTOMER_TRX_NUMBER, RELATED_BATCH_SOURCE_ID, RELATED_BATCH_SOURCE_NAME, 
RELATED_CUSTOMER_TRX_ID, CUST_TRX_TYPE_ID, BATCH_SOURCE_ID, BATCH_SOURCE_NAME, 
TERM_ID, PRIMARY_SALESREP_ID, PRIMARY_SALESREP_NUMBER, AGREEMENT_ID, 
CREDIT_METHOD_FOR_RULES, CREDIT_METHOD_FOR_INSTALLMENTS, RECEIPT_METHOD_ID, RECEIPT_METHOD_NAME, 
INVOICING_RULE_ID, INVOICING_RULE_NAME, SHIP_VIA, FOB_POINT, 
CUSTOMER_BANK_ACCOUNT_ID, CUSTOMER_BANK_ACCOUNT_NAME, INVOICE_CURRENCY_CODE, SET_OF_BOOKS_ID, 
SET_OF_BOOKS_NAME, PRINTING_OPTION, PURCHASE_ORDER, PURCHASE_ORDER_REVISION, 
PURCHASE_ORDER_DATE, COMMENTS, INTERNAL_NOTES, TERRITORY_ID, 
TERRITORY, ORIG_SYSTEM_BATCH_NAME, SHIP_DATE_ACTUAL, WAYBILL_NUMBER, 
DOC_SEQUENCE_ID, DOCUMENT_NUMBER, PAYING_CUSTOMER_ID, PAYING_CUSTOMER_NUMBER, 
PAYING_SITE_USE_ID, PAYING_SITE_USE_NUMBER, TRX_TYPE_NAME, TERM_NAME, 
AGREEMENT_NAME, GL_DATE, CONVERSION_TYPE, ORIG_SYSTEM_BILL_CUSTOMER_REF, 
ORIG_SYSTEM_SHIP_ADDRESS_REF,ORIG_SYSTEM_SOLD_CUSTOMER_REF,ORIG_SYSTEM_BILL_CONTACT_REF,
ORIG_SYSTEM_SHIP_CONTACT_REF,ORIG_SYSTEM_SHIP_CUSTOMER_REF,
BILL_TO_CUSTOMER_NAME, BILL_TO_CUSTOMER_NUMBER, SHIP_TO_CUSTOMER_NAME, SHIP_TO_CUSTOMER_NUMBER, 
ORIG_SYSTEM_BILL_ADDRESS_REF, CONVERSION_RATE, CONVERSION_DATE, CONS_BILLING_NUM, 
HEADER_ATTRIBUTE_CATEGORY, HEADER_ATTRIBUTE1, HEADER_ATTRIBUTE2, HEADER_ATTRIBUTE3, 
HEADER_ATTRIBUTE4, HEADER_ATTRIBUTE5, HEADER_ATTRIBUTE6, HEADER_ATTRIBUTE7, 
HEADER_ATTRIBUTE8, HEADER_ATTRIBUTE9, HEADER_ATTRIBUTE10, HEADER_ATTRIBUTE11, 
HEADER_ATTRIBUTE12, HEADER_ATTRIBUTE13, HEADER_ATTRIBUTE14, HEADER_ATTRIBUTE15, ATTRIBUTE_CATEGORY,
ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, 
ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, 
ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, 
ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, RESET_TRX_DATE_FLAG,
REASON_CODE,DEFAULT_USSGL_TRANSACTION_CODE,DEFAULT_USSGL_TRX_CODE_CONTEXT ,
ORGANIZATION_NAME ) AS SELECT
  NULL web_transaction_id,
  'ar transaction' document_type,
  'query' document_status,
  ct.customer_trx_id ,
  ct.trx_number ,
  ct.trx_date ,
  ct.previous_customer_trx_id ,
  ctprev.trx_number previous_customer_trx_number,
  ct_rel.trx_number related_customer_trx_number,
  ct.initial_customer_trx_id ,
  ctini.trx_number initial_customer_trx_number,
  ct.related_batch_source_id ,
  bs.name related_batch_source_name,
  ct.related_customer_trx_id ,
  ct.cust_trx_type_id ,
  ct.batch_source_id,
  bs.name batch_source_name,
  ct.term_id ,
  ct.primary_salesrep_id ,
  rsep.salesrep_number,
  ct.agreement_id ,
  ct.credit_method_for_rules ,
  ct.credit_method_for_installments ,
  ct.receipt_method_id ,
  arm.name,
  ct.invoicing_rule_id ,
  rr.name,  /* invoicing rule name */
  ct.ship_via ,
  ct.fob_point ,
  ct.customer_bank_account_id ,
  apba.bank_account_name ,
  ct.invoice_currency_code ,
  ct.set_of_books_id ,
  glsb.name set_of_books_name,
  ct.printing_option,
  ct.purchase_order ,
  ct.purchase_order_revision ,
  ct.purchase_order_date ,
  ct.comments ,
  ct.internal_notes ,
  ct.territory_id ,
  ter.name territory,
  ct.orig_system_batch_name ,
  ct.ship_date_actual ,
  ct.waybill_number ,
  ct.doc_sequence_id ,
  ct.doc_sequence_value ,
  ct.paying_customer_id ,
  NULL paying_customer_number,
  ct.paying_site_use_id ,
  NULL paying_site_use_number,
  ctt.name ,
  rat.name ,  /* term_name */
  soa.name ,  /*  agreement_name */
  gd.gl_date,  /* gd.gl_date*/
  ct.exchange_rate_type,
  rac_bill.orig_system_reference orig_system_bill_customer_ref,
  su_ship.orig_system_reference orig_system_ship_address_ref ,
  rac_sold.orig_system_reference orig_system_sold_customer_ref, 
  raco_bill.orig_system_reference orig_system_bill_contact_ref ,
  raco_ship.orig_system_reference orig_system_ship_contact_ref, 
  rac_ship.orig_system_reference orig_system_ship_customer_ref ,
  rac_bill.customer_name bill_to_customer_name,
  rac_bill.customer_number bill_to_customer_number,
  rac_ship.customer_name ship_to_customer_name,
  rac_ship.customer_number ship_to_customer_number,
  custacct.orig_system_reference orig_system_bill_address_ref,
  ct.exchange_rate,
  ct.exchange_date,
--  ct.payment_server_order_num,
--  ct.approval_code ,
  NULL cons_billing_number,
--  ct.address_verification_code,
  ct.interface_header_context,
  ct.interface_header_attribute1,
  ct.interface_header_attribute2,
  ct.interface_header_attribute3,
  ct.interface_header_attribute4,
  ct.interface_header_attribute5,
  ct.interface_header_attribute6,
  ct.interface_header_attribute7,
  ct.interface_header_attribute8,
  ct.interface_header_attribute9,
  ct.interface_header_attribute10,
  ct.interface_header_attribute11,
  ct.interface_header_attribute12,
  ct.interface_header_attribute13,
  ct.interface_header_attribute14,
  ct.interface_header_attribute15,
  ct.attribute_category,
  ct.attribute1,
  ct.attribute2,
  ct.attribute3,
  ct.attribute4,
  ct.attribute5,
  ct.attribute6,
  ct.attribute7,
  ct.attribute8,
  ct.attribute9,
  ct.attribute10,
  ct.attribute11,
  ct.attribute12,
  ct.attribute13,
  ct.attribute14,
  ct.attribute15,
  NULL reset_trx_date_flag,
  ct.reason_code ,
  ct.default_ussgl_transaction_code,
  ct.default_ussgl_trx_code_context,
  org.name
FROM
  ra_cust_trx_line_gl_dist_all gd,
  ra_customer_trx_all ct,
  ra_customers rac_bill,
  ra_customers rac_ship,
  ra_customers rac_sold,
  ra_customers rac_paying,
  ra_site_uses_all su_bill,
  ra_site_uses_all su_ship,
  ra_site_uses_all su_paying,
  fnd_territories_vl ft_bill,
  fnd_territories_vl ft_ship,
  fnd_territories_vl ft_remit,
  ra_addresses_all raa_bill,
  ra_addresses_all raa_ship,
  ra_addresses_all raa_remit,
  ra_contacts raco_ship,
  ra_contacts raco_bill,
  ap_bank_accounts_all apba,
  ap_bank_branches apb,
  ar_receipt_methods arm,
  ar_receipt_classes arc,
  ra_batch_sources_all bs,
  ra_batches_all rab,
  ra_cust_trx_types_all ctt,  /* ra_salesreps ras  */
  ra_terms rat,
  so_agreements soa,
  org_freight orf,
  gl_daily_conversion_types gdct,
  ra_customer_trx_all ct_rel,
  ar_lookups al_fob ,
  ar_lookups al_tax,
  -- change begins
  ra_salesreps rsep ,
  ra_rules rr,
  gl_sets_of_books glsb,
  ra_customer_trx_all ctprev,
  ra_customer_trx_all ctini,
  ra_territories ter,
  ra_addresses_all custacct,
  hr_organization_units org
  WHERE
  ct.customer_trx_id = gd.customer_trx_id AND
  'REC' = gd.account_class AND
  'Y' = gd.latest_rec_flag AND
  ct.related_customer_trx_id = ct_rel.customer_trx_id(+) AND
  ct.bill_to_customer_id = rac_bill.customer_id AND
  ct.ship_to_customer_id = rac_ship.customer_id(+) AND
  ct.sold_to_customer_id = rac_sold.customer_id(+) AND
  ct.paying_customer_id = rac_paying.customer_id(+) AND
  ct.bill_to_site_use_id = su_bill.site_use_id AND
  ct.ship_to_site_use_id = su_ship.site_use_id(+) AND
  ct.paying_site_use_id = su_paying.site_use_id(+)AND
  --su_bill.address_id = raa_bill.address_id and
  --su_ship.address_id = raa_ship.address_id(+) and
  su_bill.address_id =  raa_bill.address_id AND
  su_ship.address_id = raa_ship.address_id(+) AND
  ct.bill_to_contact_id = raco_bill.contact_id(+) AND
  ct.ship_to_contact_id = raco_ship.contact_id(+) AND
  ct.remit_to_address_id = raa_remit.address_id(+) AND
  raa_bill.country =  ft_bill.territory_code(+) AND
  raa_ship.country = ft_ship.territory_code(+) AND
  raa_remit.country = ft_remit.territory_code(+) AND
  ct.customer_bank_account_id = apba.bank_account_id(+) AND
  apba.bank_branch_id = apb.bank_branch_id(+) AND
  ct.receipt_method_id = arm.receipt_method_id(+) AND
  arm.receipt_class_id = arc.receipt_class_id(+) AND
  ct.batch_source_id = bs.batch_source_id AND
  ct.batch_id =  rab.batch_id(+) AND
  ct.cust_trx_type_id = ctt.cust_trx_type_id AND
  ctt.TYPE <> 'BR'AND
  ct.term_id = rat.term_id(+) AND
  ct.agreement_id = soa.agreement_id(+) AND
  ct.exchange_rate_type = gdct.conversion_type(+) AND
  'FOB' = al_fob.lookup_type(+) AND
  ct.fob_point = al_fob.lookup_code(+) AND
  ct.ship_via = orf.freight_code(+) AND
  ct.org_id = orf.organization_id(+) AND
  'TAX_CONTROL_FLAG' = al_tax.lookup_type(+) AND
  ct.default_tax_exempt_flag = al_tax.lookup_code(+) AND
  --change begins
  ctprev.customer_trx_id (+) = ct.previous_customer_trx_id AND
  ctini.customer_trx_id (+) = ct.initial_customer_trx_id  AND
  ter.territory_id (+) = ct.territory_id  AND
  gd.org_id (+) = ct.org_id AND
  su_bill.org_id (+) = ct.org_id AND
  su_ship.org_id (+) = ct.org_id AND
  su_paying.org_id (+) = ct.org_id AND
  raa_bill.org_id (+) = ct.org_id AND
  raa_remit.org_id (+) = ct.org_id AND
  apba.org_id (+) = ct.org_id AND
  bs.org_id (+) = ct.org_id AND
  rab.org_id (+) = ct.org_id AND
  ctt.org_id  (+) = ct.org_id AND
  rsep.salesrep_id (+) = ct.primary_salesrep_id  AND
  ct.invoicing_rule_id  = rr.rule_id (+) AND
  ct.customer_bank_account_id  = apba.bank_account_id (+) AND
  glsb.set_of_books_id (+) = ct.set_of_books_id AND
  rsep.org_id (+) = ct.org_id AND
  custacct.address_id (+) = su_bill.address_id AND
  ct.org_id = org.organization_id (+)
/

SHOW ERRORS

