/*  ***************************************************************************
    *    $Date:   14 Aug 2001 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   TCS  $
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for Engineering BOM outbound in Application Schema  
    * Program Name:         wm_from_engbom_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for Engineering BOM Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     22-oct-02	 Indrani Das 		Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_engbom_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."


/*----------------------------------------------------------------------*/
--      Create View WM_ENG_BOM_BILL_OF_MTLS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ENG_BOM_BILL_OF_MTLS_VW
AS
SELECT
WMTC.WEB_TRANSACTION_ID WEB_TRANSACTION_ID,
WMTC.TRANSACTION_TYPE DOCUMENT_TYPE,
DECODE(WMTC.TRANSACTION_STATUS,0,'UPDATE',1,'INSERT',2,'DELETE') DOCUMENT_STATUS,
BOM.BILL_SEQUENCE_ID BILL_SEQUENCE_ID,
MSI.CONCATENATED_SEGMENTS ITEM_NUMBER,
HOU.NAME ORGANIZATION_NAME,
MSI1.CONCATENATED_SEGMENTS COMMON_ITEM_NUMBER,
HOU1.NAME COMMON_ORG_NAME,
BOM.ALTERNATE_BOM_DESIGNATOR ALTERNATE_BOM_DESIGNATOR,
BOM.SPECIFIC_ASSEMBLY_COMMENT SPECIFIC_ASSEMBLY_COMMENT,
BOM.PENDING_FROM_ECN PENDING_FROM_ECN,
BOM.ASSEMBLY_TYPE ASSEMBLY_TYPE,
NULL DEMAND_SOURCE_LINE,
NULL SET_ID,
NULL DEMAND_SOURCE_TYPE,
NULL DEMAND_SOURCE_HEADER_ID,
BOM.NEXT_EXPLODE_DATE NEXT_EXPLODE_DATE,
NULL TRANSACTION_TYPE,
MUM.UNIT_OF_MEASURE,
NULL REVISION 
FROM
FND_COMMON_LOOKUPS FCL , 
BOM_BILL_OF_MATERIALS BOM ,
HR_ALL_ORGANIZATION_UNITS HOU,
MTL_SYSTEM_ITEMS_B_KFV MSI,
HR_ALL_ORGANIZATION_UNITS HOU1,
MTL_SYSTEM_ITEMS_B_KFV MSI1,
MTL_UNITS_OF_MEASURE_TL MUM,
WM_TRACK_CHANGES_VW WMTC
WHERE
BOM.ASSEMBLY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
AND BOM.ORGANIZATION_ID = HOU.ORGANIZATION_ID
AND BOM.COMMON_ASSEMBLY_ITEM_ID = MSI1.INVENTORY_ITEM_ID(+)
AND BOM.COMMON_ORGANIZATION_ID = MSI1.ORGANIZATION_ID(+)
AND BOM.COMMON_ORGANIZATION_ID= HOU1.ORGANIZATION_ID(+)
AND BOM.ORGANIZATION_ID = HOU.ORGANIZATION_ID
AND MUM.UOM_CODE = MSI.PRIMARY_UOM_CODE
AND MUM.LANGUAGE = USERENV('LANG') 
AND MSI.ITEM_TYPE = FCL.LOOKUP_CODE(+) 
AND FCL.LOOKUP_TYPE(+) = 'ITEM_TYPE' 
AND FCL.APPLICATION_ID(+) = 401
AND BOM.ASSEMBLY_TYPE = 2
AND BOM.BILL_SEQUENCE_ID = WMTC.TRANSACTION_ID 
AND WMTC.TRANSACTION_STATUS <= 2 
AND WMTC.TRANSACTION_TYPE = 'ENGBOM'
UNION
SELECT WTC.WEB_TRANSACTION_ID,
WTC.TRANSACTION_TYPE,
'DELETE',
TO_NUMBER(WTC.TRANSACTION_ID),
MSI.CONCATENATED_SEGMENTS, 
HOU.NAME, 
NULL,
NULL,
SUBSTR(WT.COMMENTS,instr(WT.COMMENTS,'+',1,2)+1,length(WT.COMMENTS) - instr(WT.COMMENTS,'+',1,2)),
NULL,
NULL,
TO_NUMBER(NULL),
NULL,
NULL,
NULL,
NULL,
TO_DATE(NULL),
NULL,
NULL,
NULL
FROM WM_TRACKCHANGES WT, MTL_SYSTEM_ITEMS_B_KFV MSI, HR_ALL_ORGANIZATION_UNITS HOU, WM_TRACK_CHANGES_VW WTC
WHERE  substr(WT.COMMENTS,1,instr(WT.COMMENTS,'+',1,1)-1)=MSI.INVENTORY_ITEM_ID AND
MSI.ORGANIZATION_ID=HOU.ORGANIZATION_ID AND
substr(WT.COMMENTS,instr(WT.COMMENTS,'+',1,1)+1,instr(WT.COMMENTS,'+',1,2) - instr(WT.COMMENTS,'+',1,1)-1)=MSI.ORGANIZATION_ID
AND WTC.TRANSACTION_STATUS=2
AND WTC.TRANSACTION_ID=WT.TRANSACTION_ID
AND WTC.TRANSACTION_TYPE=WT.TRANSACTION_TYPE
AND WTC.TRANSACTION_TYPE='ENGBOM'
AND WT.TRANSACTION_STATUS=2
AND WT.TRANSACTION_STATUS=WTC.TRANSACTION_STATUS
ORDER BY
WEB_TRANSACTION_ID
/

/*----------------------------------------------------------------------*/
--      Create View WM_ENG_BOM_ITEM_REVISIONS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ENG_BOM_ITEM_REVISIONS_VW 
AS
SELECT 
BOM.BILL_SEQUENCE_ID BILL_SEQUENCE_ID,
MSI.CONCATENATED_SEGMENTS ITEM_NUMBER,
HOU.NAME ORGANIZATION_NAME,
MIR.REVISION REVISION, 
MIR.CHANGE_NOTICE CHANGE_NOTICE, 
MIR.ECN_INITIATION_DATE ECN_INITIATION_DATE,
MIR.IMPLEMENTATION_DATE IMPLEMENTATION_DATE, 
MIR.EFFECTIVITY_DATE EFFECTIVITY_DATE, 
MIR.REVISED_ITEM_SEQUENCE_ID REVISED_ITEM_SEQUENCE_ID, 
NULL TRANSACTION_TYPE
FROM 
MTL_ITEM_REVISIONS MIR,
HR_ALL_ORGANIZATION_UNITS HOU,
MTL_SYSTEM_ITEMS_B_KFV MSI,
BOM_BILL_OF_MATERIALS BOM
WHERE 
MIR.ORGANIZATION_ID = HOU.ORGANIZATION_ID
AND MIR.ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND MIR.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
AND BOM.ORGANIZATION_ID = MIR.ORGANIZATION_ID
AND BOM.ASSEMBLY_ITEM_ID = MIR.INVENTORY_ITEM_ID
/

/*----------------------------------------------------------------------*/
--      Create View WM_ENG_BOM_INVENTORY_COMPS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ENG_BOM_INVENTORY_COMPS_VW  
AS
SELECT
BIC.COMPONENT_SEQUENCE_ID COMPONENT_SEQUENCE_ID,  
BIC.BILL_SEQUENCE_ID BILL_SEQUENCE_ID,
MSI.CONCATENATED_SEGMENTS ASSEMBLY_ITEM_NUMBER,
BOM.ALTERNATE_BOM_DESIGNATOR ALTERNATE_BOM_DESIGNATOR,
HOU.NAME ORGANIZATION_NAME,
MSI1.CONCATENATED_SEGMENTS COMPONENT_ITEM_NUMBER,
BIC.OPERATION_SEQ_NUM OPERATION_SEQ_NUM, 
BIC.EFFECTIVITY_DATE EFFECTIVITY_DATE,
MIL.DESCRIPTION LOCATION_NAME,
NULL SUBSTITUTE_COMPONENT_NUMBER,
BIC.ITEM_NUM ITEM_NUM, 
BIC.COMPONENT_QUANTITY COMPONENT_QUANTITY, 
BIC.COMPONENT_YIELD_FACTOR COMPONENT_YIELD_FACTOR, 
BIC.COMPONENT_REMARKS COMPONENT_REMARKS,  
BIC.CHANGE_NOTICE CHANGE_NOTICE, 
BIC.IMPLEMENTATION_DATE IMPLEMENTATION_DATE, 
BIC.DISABLE_DATE DISABLE_DATE, 
BIC.PLANNING_FACTOR PLANNING_FACTOR, 
DECODE(BIC.QUANTITY_RELATED,1,'Yes',2,'No',NULL) QUANTITY_RELATED, 
ML3.MEANING SO_BASIS, 
DECODE(BIC.OPTIONAL,1,'Yes',2,'No',NULL) OPTIONAL, 
DECODE(BIC.MUTUALLY_EXCLUSIVE_OPTIONS,1,'Yes',2,'No',NULL) MUTUALLY_EXCLUSIVE_OPTIONS, 
DECODE(BIC.INCLUDE_IN_COST_ROLLUP,1,'Yes',2,'No',NULL) INCLUDE_IN_COST_ROLLUP, 
DECODE(BIC.CHECK_ATP,1,'Yes',2,'No',NULL) CHECK_ATP, 
DECODE(BIC.SHIPPING_ALLOWED,1,'Yes',2,'No',NULL) SHIPPING_ALLOWED, 
DECODE(BIC.REQUIRED_TO_SHIP,1,'Yes',2,'No',NULL) REQUIRED_TO_SHIP, 
DECODE(BIC.REQUIRED_FOR_REVENUE,1,'Yes',2,'No',NULL) REQUIRED_FOR_REVENUE, 
DECODE(BIC.INCLUDE_ON_SHIP_DOCS,1,'Yes',2,'No',NULL) INCLUDE_ON_SHIP_DOCS, 
BIC.LOW_QUANTITY LOW_QUANTITY, 
BIC.HIGH_QUANTITY HIGH_QUANTITY, 
ML1.MEANING ACD_TYPE, 
MSI2.CONCATENATED_SEGMENTS REVISED_ITEM_NUMBER,
MIR.REVISION REVISION,
BIC1.OPERATION_SEQ_NUM OLD_OPERATION_SEQ_NUM,
BIC1.EFFECTIVITY_DATE OLD_EFFECTIVITY_DATE,
ML.MEANING WIP_SUPPLY_TYPE, 
BIC.SUPPLY_SUBINVENTORY SUPPLY_SUBINVENTORY,  
NULL REFERENCE_DESIGNATOR, 
NULL NEW_OPERATION_SEQ_NUM,
NULL NEW_EFFECTIVITY_DATE,
ML2.MEANING BOM_ITEM_TYPE,
BIC.OPERATION_LEAD_TIME_PERCENT OPERATION_LEAD_TIME_PERCENT, 
BOM.ASSEMBLY_TYPE ASSEMBLY_TYPE,
DECODE(BOM.ASSEMBLY_TYPE,1,'BILL',2,'ECO',NULL) INTERFACE_ENTITY_TYPE,
MUM.UNIT_OF_MEASURE,
NULL TRANSACTION_TYPE
FROM 
FND_COMMON_LOOKUPS FCL , MFG_LOOKUPS ML,
BOM_BILL_OF_MATERIALS BOM /* NEEDED TO GET ORG_ID */ , 
HR_ALL_ORGANIZATION_UNITS HOU,
MTL_SYSTEM_ITEMS_B_KFV MSI,
MTL_SYSTEM_ITEMS_B_KFV MSI1,
MTL_SYSTEM_ITEMS_B_KFV MSI2,
MTL_ITEM_LOCATIONS MIL,
ENG_REVISED_ITEMS ERI,
MTL_ITEM_REVISIONS MIR,
BOM_INVENTORY_COMPONENTS BIC1,
MFG_LOOKUPS ML1 , 
MFG_LOOKUPS ML2 , 
MFG_LOOKUPS ML3 , 
MTL_UNITS_OF_MEASURE_TL MUM,
BOM_INVENTORY_COMPONENTS BIC
WHERE 
BIC.BILL_SEQUENCE_ID = BOM.BILL_SEQUENCE_ID 
AND BIC.OLD_COMPONENT_SEQUENCE_ID = BIC1.COMPONENT_SEQUENCE_ID(+)
AND BOM.ASSEMBLY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
AND BIC.COMPONENT_ITEM_ID = MSI1.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI1.ORGANIZATION_ID 
AND BOM.ORGANIZATION_ID = HOU.ORGANIZATION_ID
AND BIC.SUPPLY_LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+)
AND MUM.UOM_CODE = MSI1.PRIMARY_UOM_CODE
AND MUM.LANGUAGE = USERENV('LANG') 
AND ML.LOOKUP_CODE(+) = BIC.WIP_SUPPLY_TYPE 
AND ML.LOOKUP_TYPE(+) = 'WIP_SUPPLY' 
AND ML1.LOOKUP_CODE(+) = BIC.ACD_TYPE
AND ML1.LOOKUP_TYPE(+) = 'ECG_ACTION' 
AND ML2.LOOKUP_CODE(+) = BIC.BOM_ITEM_TYPE
AND ML2.LOOKUP_TYPE(+) = 'BOM_ITEM_TYPE' 
AND ML3.LOOKUP_CODE(+) = BIC.SO_BASIS
AND ML3.LOOKUP_TYPE(+) = 'BOM_SO_BASYS' 
AND BIC.BILL_SEQUENCE_ID = ERI.BILL_SEQUENCE_ID(+)
AND BIC.REVISED_ITEM_SEQUENCE_ID = ERI.REVISED_ITEM_SEQUENCE_ID(+)
AND MIR.ORGANIZATION_ID(+) = ERI.ORGANIZATION_ID
AND MIR.INVENTORY_ITEM_ID(+) = ERI.REVISED_ITEM_ID
AND MIR.REVISED_ITEM_SEQUENCE_ID(+) = ERI.REVISED_ITEM_SEQUENCE_ID
AND ERI.REVISED_ITEM_ID = MSI2.INVENTORY_ITEM_ID (+)
AND ERI.ORGANIZATION_ID = MSI2.ORGANIZATION_ID (+)
AND FCL.LOOKUP_TYPE(+) = 'ITEM_TYPE' AND FCL.LOOKUP_CODE(+) = MSI.ITEM_TYPE 
AND FCL.APPLICATION_ID(+) = 401 AND NVL(BIC.ECO_FOR_PRODUCTION,2) = 2
/

/*----------------------------------------------------------------------*/
--      Create View WM_ENG_BOM_SUBSTITUTE_COMPS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ENG_BOM_SUBSTITUTE_COMPS_VW 
AS
SELECT
BSC.COMPONENT_SEQUENCE_ID COMPONENT_SEQUENCE_ID,
BOM.BILL_SEQUENCE_ID BILL_SEQUENCE_ID,
MSI3.CONCATENATED_SEGMENTS SUBSTITUTE_COMP_NUMBER,
BSC.SUBSTITUTE_ITEM_QUANTITY SUBSTITUTE_ITEM_QUANTITY, 
ML.MEANING ACD_TYPE, 
BSC.CHANGE_NOTICE CHANGE_NOTICE, 
HOU.NAME ORGANIZATION_NAME,
MSI1.CONCATENATED_SEGMENTS ASSEMBLY_ITEM_NUMBER,
BOM.ALTERNATE_BOM_DESIGNATOR ALTERNATE_BOM_DESIGNATOR,
MSI2.CONCATENATED_SEGMENTS COMPONENT_ITEM_NUMBER,
BIC1.OPERATION_SEQ_NUM OPERATION_SEQ_NUM,
BIC1.EFFECTIVITY_DATE EFFECTIVITY_DATE,
NULL NEW_SUB_COMP_NUMBER,
DECODE(BOM.ASSEMBLY_TYPE,1,'BILL',2,'ECO',NULL) INTERFACE_ENTITY_TYPE,
MUM.UNIT_OF_MEASURE,
NULL TRANSACTION_TYPE
FROM 
BOM_SUBSTITUTE_COMPONENTS BSC , 
BOM_BILL_OF_MATERIALS BOM , 
BOM_INVENTORY_COMPONENTS BIC1 , /* CURRENT COMPONENT RECORD */ 
BOM_INVENTORY_COMPONENTS BIC2 , /* COMPONENT BEING REFERENCED */ 
HR_ALL_ORGANIZATION_UNITS HOU,
MTL_SYSTEM_ITEMS_B_KFV MSI1, 
MTL_SYSTEM_ITEMS_B_KFV MSI2, 
MFG_LOOKUPS ML , 
MTL_UNITS_OF_MEASURE_TL MUM,
MTL_SYSTEM_ITEMS_B_KFV MSI3 
WHERE 
BSC.COMPONENT_SEQUENCE_ID = BIC1.COMPONENT_SEQUENCE_ID 
AND BIC1.BILL_SEQUENCE_ID = BOM.BILL_SEQUENCE_ID 
AND BSC.SUBSTITUTE_COMPONENT_ID = MSI3.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI3.ORGANIZATION_ID 
AND BOM.ASSEMBLY_ITEM_ID = MSI1.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI1.ORGANIZATION_ID 
AND BIC1.COMPONENT_ITEM_ID = MSI2.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI2.ORGANIZATION_ID 
AND HOU.ORGANIZATION_ID = BOM.ORGANIZATION_ID
AND MUM.UOM_CODE = MSI3.PRIMARY_UOM_CODE
AND MUM.LANGUAGE = USERENV('LANG') 
AND ML.LOOKUP_CODE(+) = BSC.ACD_TYPE
AND ML.LOOKUP_TYPE(+) = 'ECG_ACTION' 
AND NVL(BSC.ACD_TYPE, 1) <> 3 
AND BIC2.BILL_SEQUENCE_ID = BIC1.BILL_SEQUENCE_ID 
AND DECODE(BIC2.IMPLEMENTATION_DATE, NULL, BIC2.OLD_COMPONENT_SEQUENCE_ID , BIC2.COMPONENT_SEQUENCE_ID) 
    = DECODE(BIC1.IMPLEMENTATION_DATE , NULL , BIC1.OLD_COMPONENT_SEQUENCE_ID , BIC1.COMPONENT_SEQUENCE_ID) 
AND BIC1.EFFECTIVITY_DATE = (SELECT MAX(BIC3.EFFECTIVITY_DATE) 
                          FROM BOM_SUBSTITUTE_COMPONENTS BSC2 , BOM_INVENTORY_COMPONENTS BIC3 
                          WHERE BIC3.COMPONENT_SEQUENCE_ID = BSC2.COMPONENT_SEQUENCE_ID 
                          AND DECODE(BIC3.IMPLEMENTATION_DATE, NULL, BIC3.OLD_COMPONENT_SEQUENCE_ID , BIC3.COMPONENT_SEQUENCE_ID) 
                              = DECODE(BIC1.IMPLEMENTATION_DATE , NULL , BIC1.OLD_COMPONENT_SEQUENCE_ID , BIC1.COMPONENT_SEQUENCE_ID) 
                          AND BIC3.BILL_SEQUENCE_ID = BIC2.BILL_SEQUENCE_ID 
                          AND BSC2.SUBSTITUTE_COMPONENT_ID = BSC.SUBSTITUTE_COMPONENT_ID 
                          AND BIC3.EFFECTIVITY_DATE <= BIC2.EFFECTIVITY_DATE)
/

/*----------------------------------------------------------------------*/
--      Create View WM_ENG_BOM_REFERENCE_DESGS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ENG_BOM_REFERENCE_DESGS_VW 
AS
SELECT 
BRD1.COMPONENT_SEQUENCE_ID COMPONENT_SEQUENCE_ID, 
BOM.BILL_SEQUENCE_ID BILL_SEQUENCE_ID,
BRD1.COMPONENT_REFERENCE_DESIGNATOR COMPONENT_REFERENCE_DESIGNATOR, 
HOU.NAME ORGANIZATION_NAME,
MSI1.CONCATENATED_SEGMENTS ASSEMBLY_ITEM_NUMBER,
BOM.ALTERNATE_BOM_DESIGNATOR ALTERNATE_BOM_DESIGNATOR,
MSI2.CONCATENATED_SEGMENTS COMPONENT_ITEM_NUMBER,
BIC1.OPERATION_SEQ_NUM OPERATION_SEQ_NUM,
BIC1.EFFECTIVITY_DATE EFFECTIVITY_DATE,
BRD1.REF_DESIGNATOR_COMMENT REF_DESIGNATOR_COMMENT, 
BRD1.CHANGE_NOTICE CHANGE_NOTICE, 
ML.MEANING ACD_TYPE , 
NULL NEW_DESIGNATOR,
DECODE(BOM.ASSEMBLY_TYPE,1,'BILL',2,'ECO',NULL) INTERFACE_ENTITY_TYPE,
NULL TRANSACTION_TYPE
FROM 
BOM_BILL_OF_MATERIALS BOM , 
BOM_REFERENCE_DESIGNATORS BRD1 , 
BOM_INVENTORY_COMPONENTS BIC1 , 
BOM_INVENTORY_COMPONENTS BIC2 ,
HR_ALL_ORGANIZATION_UNITS HOU,
MFG_LOOKUPS ML , 
MTL_SYSTEM_ITEMS_B_KFV MSI1, 
MTL_SYSTEM_ITEMS_B_KFV MSI2 
WHERE 
BRD1.COMPONENT_SEQUENCE_ID = BIC1.COMPONENT_SEQUENCE_ID 
AND BIC1.BILL_SEQUENCE_ID = BOM.BILL_SEQUENCE_ID 
AND BOM.ASSEMBLY_ITEM_ID = MSI1.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI1.ORGANIZATION_ID 
AND BIC1.COMPONENT_ITEM_ID = MSI2.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI2.ORGANIZATION_ID 
AND HOU.ORGANIZATION_ID = BOM.ORGANIZATION_ID
AND ML.LOOKUP_CODE(+) = BRD1.ACD_TYPE
AND ML.LOOKUP_TYPE(+) = 'ECG_ACTION' 
AND NVL(BRD1.ACD_TYPE, 1) <> 3 
AND BIC2.BILL_SEQUENCE_ID = BIC1.BILL_SEQUENCE_ID 
AND DECODE(BIC2.IMPLEMENTATION_DATE, NULL, BIC2.OLD_COMPONENT_SEQUENCE_ID , BIC2.COMPONENT_SEQUENCE_ID) 
    = DECODE(BIC1.IMPLEMENTATION_DATE , NULL , BIC1.OLD_COMPONENT_SEQUENCE_ID , BIC1.COMPONENT_SEQUENCE_ID) 
    AND BIC1.EFFECTIVITY_DATE = (SELECT MAX(BIC3.EFFECTIVITY_DATE) 
                              FROM BOM_REFERENCE_DESIGNATORS BRD2 , BOM_INVENTORY_COMPONENTS BIC3 
                              WHERE BIC3.COMPONENT_SEQUENCE_ID = BRD2.COMPONENT_SEQUENCE_ID 
                              AND DECODE(BIC3.IMPLEMENTATION_DATE, NULL, BIC3.OLD_COMPONENT_SEQUENCE_ID , BIC3.COMPONENT_SEQUENCE_ID) 
                                  = DECODE(BIC1.IMPLEMENTATION_DATE , NULL , BIC1.OLD_COMPONENT_SEQUENCE_ID , BIC1.COMPONENT_SEQUENCE_ID) 
                              AND BIC3.BILL_SEQUENCE_ID = BIC2.BILL_SEQUENCE_ID 
                              AND BRD2.COMPONENT_REFERENCE_DESIGNATOR = BRD1.COMPONENT_REFERENCE_DESIGNATOR 
                              AND BIC3.EFFECTIVITY_DATE <= BIC2.EFFECTIVITY_DATE)
/


/*----------------------------------------------------------------------*/
--      Create View WM_ENG_BOM_BILL_OF_MTLS_QRY_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ENG_BOM_BILL_OF_MTLS_QRY_VW 
AS
SELECT 
TO_NUMBER(NULL) WEB_TRANSACTION_ID,
'ENGBOM' DOCUMENT_TYPE,
'QUERY' DOCUMENT_STATUS,
BOM.BILL_SEQUENCE_ID BILL_SEQUENCE_ID,
MSI.CONCATENATED_SEGMENTS ITEM_NUMBER,
HOU.NAME ORGANIZATION_NAME,
MSI1.CONCATENATED_SEGMENTS COMMON_ITEM_NUMBER,
HOU1.NAME COMMON_ORG_NAME,
BOM.ALTERNATE_BOM_DESIGNATOR ALTERNATE_BOM_DESIGNATOR,
BOM.SPECIFIC_ASSEMBLY_COMMENT SPECIFIC_ASSEMBLY_COMMENT,
BOM.PENDING_FROM_ECN PENDING_FROM_ECN,
BOM.ASSEMBLY_TYPE ASSEMBLY_TYPE,
NULL DEMAND_SOURCE_LINE,
NULL SET_ID,
NULL DEMAND_SOURCE_TYPE,
NULL DEMAND_SOURCE_HEADER_ID,
BOM.NEXT_EXPLODE_DATE NEXT_EXPLODE_DATE,
NULL TRANSACTION_TYPE,
MUM.UNIT_OF_MEASURE,
NULL REVISION 
FROM 
FND_COMMON_LOOKUPS FCL , 
BOM_BILL_OF_MATERIALS BOM ,
HR_ALL_ORGANIZATION_UNITS HOU,
MTL_SYSTEM_ITEMS_B_KFV MSI,
HR_ALL_ORGANIZATION_UNITS HOU1,
MTL_UNITS_OF_MEASURE_TL MUM,
MTL_SYSTEM_ITEMS_B_KFV MSI1
WHERE 
BOM.ASSEMBLY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
AND BOM.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
AND BOM.ORGANIZATION_ID = HOU.ORGANIZATION_ID
AND BOM.COMMON_ASSEMBLY_ITEM_ID = MSI1.INVENTORY_ITEM_ID(+)
AND BOM.COMMON_ORGANIZATION_ID = MSI1.ORGANIZATION_ID(+)
AND BOM.COMMON_ORGANIZATION_ID= HOU1.ORGANIZATION_ID(+)
AND BOM.ORGANIZATION_ID = HOU.ORGANIZATION_ID
AND MUM.UOM_CODE = MSI.PRIMARY_UOM_CODE
AND MUM.LANGUAGE = USERENV('LANG') 
AND MSI.ITEM_TYPE = FCL.LOOKUP_CODE(+) 
AND FCL.LOOKUP_TYPE(+) = 'ITEM_TYPE' 
AND FCL.APPLICATION_ID(+) = 401
AND BOM.ASSEMBLY_TYPE = 2
/

 
SHOW ERRORS

