CREATE TABLE ORDER_HEADER_BUFFER (
   ORDER_ID NVARCHAR (20) NULL ,
   TRANSACTION_ID NVARCHAR (30) NULL ,
   ORDER_DATE NVARCHAR (40) NULL ,
   TOTAL_COST NVARCHAR (20) NULL ,
   IS_VALID NVARCHAR (10) NULL ,
   SENDER_ID NVARCHAR (20) NULL ,
   RECEIVER_ID NVARCHAR (20) NULL
)
;

