CREATE TABLE ORDER_HEADER (
   ORDER_ID NVARCHAR (20) NOT NULL ,
   TRANSACTION_ID NVARCHAR (30) NOT NULL ,
   ORDER_DATE NVARCHAR (40) NOT NULL ,
   TOTAL_COST NVARCHAR (20) NOT NULL ,
   IS_VALID NVARCHAR (10) NOT NULL ,
   SENDER_ID NVARCHAR (20) NOT NULL ,
   RECEIVER_ID NVARCHAR (20) NOT NULL
)
/
CREATE TABLE SRC_ORDER_PRODUCTS (
	PRODUCT_NO NVARCHAR (20) NOT NULL ,
	PRODUCT_NAME NVARCHAR (50) NULL ,
	PRODUCT_DESCRIPTION NVARCHAR (255) ,
	UNIT_PRICE NUMBER (9) NULL ,
	PRIMARY KEY (PRODUCT_NO)
) 
/
CREATE TABLE SRC_CUSTOMERS (
	CUSTOMER_NO NVARCHAR (20) NULL ,
	CUSTOMER_NAME NVARCHAR (40) NULL 
)
/
CREATE TABLE ORDER_HEADER_BUFFER (
   ORDER_ID NVARCHAR (20) NULL ,
   TRANSACTION_ID NVARCHAR (30) NULL ,
   ORDER_DATE NVARCHAR (40) NULL ,
   TOTAL_COST NVARCHAR (20) NULL ,
   IS_VALID NVARCHAR (10) NULL ,
   SENDER_ID NVARCHAR (20) NULL ,
   RECEIVER_ID NVARCHAR (20) NULL
)
/
CREATE TABLE ORDER_DETAILS (
   ORDER_ID NVARCHAR (20) NOT NULL ,
   TRANSACTION_ID NVARCHAR (30) NOT NULL ,
   SKU NVARCHAR (40) NOT NULL ,
   QUANTITY NVARCHAR (20) NOT NULL
)
/
CREATE TRIGGER ORDER_HEADER_TRIG ON ORDER_HEADER after insert as  begin INSERT INTO ORDER_HEADER_BUFFER (ORDER_ID, TRANSACTION_ID, ORDER_DATE, TOTAL_COST, IS_VALID, SENDER_ID, RECEIVER_ID)  SELECT inserted.ORDER_ID, inserted.TRANSACTION_ID, inserted.ORDER_DATE, inserted.TOTAL_COST, inserted.IS_VALID, inserted.SENDER_ID, inserted.RECEIVER_ID FROM inserted  end
;

