/*  ***************************************************************************
    *    $Date:   14 Aug 2001 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:    webMethods
    * Process Name:   Create Custom Views for Advance Shipping Notice outbound in Application Schema  
    * Program Name:   wm_from_shipnotice_vw.sql
    * Version #:      1.0
    * Title:          View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:        SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *   Create Views in APPS schema for Advance Shipping Notice Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     24-OCT-02	Panchali Samanta         Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_shipnotice_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."

/*----------------------------------------------------------------------*/
--      Create View WM_ASN_DETAIL_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_ASN_DETAIL_VW 
AS
SELECT 
  DISTINCT
  WMTC.WEB_TRANSACTION_ID,  
  WMTC.TRANSACTION_TYPE DOCUMENT_TYPE,  
  DECODE((WMTC.TRANSACTION_STATUS),0,'UPDATE',1
               ,'INSERT',2, 'DELETE')   DOCUMENT_STATUS,  
  WDD.SOURCE_LINE_ID ORDER_LINE_ID,
  OEH.ORDER_NUMBER ORDER_NUMBER,
  WDD.SOURCE_LINE_NUMBER  ORDER_LINE_NUMBER,
  OEH.CUST_PO_NUMBER PURCHASE_ORDER_NUMBER,
  OEH.ORDERED_DATE ORDER_DATE,
  OEH.FLOW_STATUS_CODE  ORDER_STATUS,
  OEH.FREIGHT_TERMS_CODE FREIGHT_TERMS_CODE_INT,
  OEH.FOB_POINT_CODE FOB_CODE_INT,
  OEH.SHIPPING_METHOD_CODE SHIP_METHOD_INT,
  OEH.CONVERSION_RATE  CONVERSION_RATE,
  OEH.TRANSACTIONAL_CURR_CODE  CURRENCY_CODE, 
  ORG.NAME  ORGANIZATION_NAME,
  CUST_ACCT.CUSTOMER_NUMBER CUSTOMER_NUMBER, 
  CUST_ACCT.CUSTOMER_NAME  CUSTOMER_NAME,
  RAD2.ORIG_SYSTEM_REFERENCE INVOICE_CODE_INT,
  RAD2.ECE_TP_LOCATION_CODE INVOICE_CODE_EXT,
  HCSU2.LOCATION INVOICE_NAME,
  RAD2.ADDRESS1 INVOICE_ADDRESS1,
  RAD2.ADDRESS2 INVOICE_ADDRESS2,
  RAD2.ADDRESS3 INVOICE_ADDRESS3,
  RAD2.ADDRESS4 INVOICE_ADDRESS4,
  RAD2.ADDRESSEE	INVOICE_ADDRESSEE,
  RAD2.IDENTIFYING_ADDRESS_FLAG	INVOICE_IDENTIFY_ADDR_FLAG,	
  RAD2.CITY INVOICE_CITY,
  RAD2.POSTAL_CODE INVOICE_POSTAL_CODE,
  RAD2.COUNTRY INVOICE_COUNTRY_INT,
  RAD2.STATE INVOICE_STATE_INT,
  RAD2.PROVINCE INVOICE_PROVINCE_INT,
  RAD2.COUNTY INVOICE_COUNTY,
  RCO2.LAST_NAME INVOICE_CONTACT_LAST_NAME,
  RCO2.FIRST_NAME INVOICE_CONTACT_FIRST_NAME,
  RCO2.JOB_TITLE INVOICE_CONTACT_JOB_TITLE,
  RAD1.ORIG_SYSTEM_REFERENCE ORDER_BY_CODE_INT,
  RAD1.ECE_TP_LOCATION_CODE ORDER_BY_CODE_EXT,
  RAD1.ADDRESS1 ORDER_BY_ADDRESS1,
  RAD1.ADDRESS2 ORDER_BY_ADDRESS2 ,
  RAD1.ADDRESS3 ORDER_BY_ADDRESS3,
  RAD1.ADDRESS4 ORDER_BY_ADDRESS4,
  RAD1.ADDRESSEE	ORDER_BY_ADDRESSEE,
  RAD1.IDENTIFYING_ADDRESS_FLAG	ORDER_BY_IDENTIFY_ADDR_FLAG,	
  RAD1.CITY ORDER_BY_CITY,
  RAD1.POSTAL_CODE ORDER_BY_POSTAL_CODE,
  RAD1.COUNTRY ORDER_BY_COUNTRY_INT,
  RAD1.STATE ORDER_BY_STATE_INT,
  RAD1.PROVINCE ORDER_BY_PROVINCE_INT,
  RAD1.COUNTY ORDER_BY_COUNTY,
  RCO1.LAST_NAME ORDER_BY_CONTACT_LAST_NAME,
  RCO1.FIRST_NAME ORDER_BY_CONTACT_FIRST_NAME,
  RCO1.JOB_TITLE ORDER_BY_CONTACT_JOB_TITLE,
  RAD3.ORIG_SYSTEM_REFERENCE ORDER_SHIP_CODE_INT,
  RAD3.ECE_TP_LOCATION_CODE ORDER_SHIP_CODE_EXT,
  HCSU3.LOCATION ORDER_SHIP_NAME,
  RAD3.ADDRESS1 ORDER_SHIP_ADDRESS1,
  RAD3.ADDRESS2 ORDER_SHIP_ADDRESS2,
  RAD3.ADDRESS3 ORDER_SHIP_ADDRESS3,
  RAD3.ADDRESS4 ORDER_SHIP_ADDRESS4,
  RAD3.ADDRESSEE	ORDER_SHIP_ADDRESSEE,
  RAD3.IDENTIFYING_ADDRESS_FLAG	ORDER_SHIP_IDENTIFY_ADDR_FLAG,
  RAD3.CITY ORDER_SHIP_CITY,
  RAD3.POSTAL_CODE ORDER_SHIP_POSTAL_CODE,
  RAD3.COUNTRY ORDER_SHIP_COUNTRY_INT,
  RAD3.STATE ORDER_SHIP_STATE_INT,
  RAD3.PROVINCE ORDER_SHIP_PROVINCE_INT,
  RAD3.COUNTY ORDER_SHIP_COUNTY,
  RCO3.LAST_NAME ORDER_SHIP_CONTACT_LAST_NAME,
  RCO3.FIRST_NAME ORDER_SHIP_CONTACT_FIRST_NAME,
  RCO3.JOB_TITLE ORDER_SHIP_CONTACT_JOB_TITLE,
  L.CREATION_DATE LINE_CREATION_DATE,
  L.LAST_UPDATE_DATE LINE_MODIFIED_DATE,
  L.ACTUAL_SHIPMENT_DATE LINE_ACTUAL_SHIP_DATE,
  L.REQUEST_DATE LINE_REQUEST_DATE,
  L.PROMISE_DATE LINE_PROMISE_DATE,
  L.SCHEDULE_SHIP_DATE LINE_SCHEDULED_SHIP_DATE,
  L.SHIPPING_METHOD_CODE  LINE_SHIPMENT_METHOD,
  WDD.HOLD_CODE  HOLD_CODE,
  RAD.ORIG_SYSTEM_REFERENCE LINE_SHIP_CODE_INT,
  RAD.ECE_TP_LOCATION_CODE LINE_SHIP_CODE_EXT,
  HCSU.LOCATION LINE_SHIP_NAME,
  RAD.ADDRESS1 LINE_SHIP_ADDRESS1,
  RAD.ADDRESS2 LINE_SHIP_ADDRESS2,
  RAD.ADDRESS3 LINE_SHIP_ADDRESS3,
  RAD.ADDRESS4 LINE_SHIP_ADDRESS4,
  RAD.ADDRESSEE	LINE_SHIP_ADDRESSEE,
  RAD.IDENTIFYING_ADDRESS_FLAG	LINE_SHIP_IDENTIFY_ADDR_FLAG,
  RAD.CITY LINE_SHIP_CITY,
  RAD.POSTAL_CODE LINE_SHIP_POSTAL_CODE,
  RAD.COUNTRY LINE_SHIP_COUNTRY_INT,
  RAD.STATE LINE_SHIP_STATE_INT,
  RAD.PROVINCE LINE_SHIP_PROVINCE_INT,
  RAD.COUNTY LINE_SHIP_COUNTY,
  RCO.LAST_NAME LINE_SHIP_CONTACT_LAST_NAME,
  RCO.FIRST_NAME LINE_SHIP_CONTACT_FIRST_NAME,
  RCO.JOB_TITLE LINE_SHIP_CONTACT_JOB_TITLE,
  WDD.NET_WEIGHT NET_WEIGHT,
  WDD.GROSS_WEIGHT GROSS_WEIGHT,
  (WDD.GROSS_WEIGHT-WDD.NET_WEIGHT) TARE_WEIGHT,
  WDD.WEIGHT_UOM_CODE WEIGHT_UOM,
  WDD.VOLUME VOLUME,
  WDD.VOLUME_UOM_CODE  VOLUME_UOM,
  WDD.SHIPPED_QUANTITY SHIP_QUANTITY1,
  L.ORDERED_QUANTITY ORDERED_QUANTITY1,
  L.ORDER_QUANTITY_UOM  QUANTITY1_UOM,
  WDD.SHIPPED_QUANTITY2 SHIP_QUANTITY2,
  L.ORDERED_QUANTITY2 ORDERED_QUANTITY2,
  L.ORDERED_QUANTITY_UOM2 QUANTITY2_UOM,
  WDD.ITEM_DESCRIPTION ITEM_DESCRIPTION,
  ITEM.CONCATENATED_SEGMENTS ITEM,
  CUST_ITEM.CUSTOMER_ITEM_NUMBER CUSTOMER_ITEM,
  MTP.ORGANIZATION_CODE FROM_WAREHOUSE,
  HOU.NAME FROM_WAREHOUSE_NAME,
  HRL.ADDRESS_LINE_1 WAREHOUSE_ADDRESS1,
  HRL.ADDRESS_LINE_2 WAREHOUSE_ADDRESS2,
  HRL.ADDRESS_LINE_3 WAREHOUSE_ADDRESS3,
  HRL.TOWN_OR_CITY WAREHOUSE_CITY,
  HRL.POSTAL_CODE WAREHOUSE_POSTAL_CODE,
  HRL.COUNTRY WAREHOUSE_COUNTRY_INT,
  HRL.REGION_1 WAREHOUSE_REGION1_INT,
  HRL.REGION_2 WAREHOUSE_REGION2_INT,
  HRL.REGION_3 WAREHOUSE_REGION3_INT,
  HRL.TELEPHONE_NUMBER_1 WAREHOUSE_TELEPHONE_1,
  HRL.TELEPHONE_NUMBER_2 WAREHOUSE_TELEPHONE_2,
  HRL.TELEPHONE_NUMBER_3 WAREHOUSE_TELEPHONE_3,
  L.UNIT_LIST_PRICE  LIST_PRICE,
  L.TAX_VALUE  NET_TAX,
  L.UNIT_SELLING_PRICE UNIT_PRICE,
  (L.UNIT_SELLING_PRICE * L.PRICING_QUANTITY) EXTENDED_PRICE,
  WDD.LOT_NUMBER  LOT_NUMBER,
  WDD.SUBLOT_NUMBER SUBLOT_NUMBER,
  OSET.SET_NAME  SHIP_SET_NAME,
  WDD.FILLED_VOLUME	FILLED_VOLUME
FROM
  WM_TRACK_CHANGES_VW WMTC,
  WSH_NEW_DELIVERIES WND,
  WSH_DELIVERY_ASSIGNMENTS WDA,
  WSH_DELIVERY_DETAILS WDD,
  OE_ORDER_LINES_ALL  L,
  OE_ORDER_HEADERS_ALL OEH,
  RA_CONTACTS RCO,
  RA_ADDRESSES_ALL RAD,
  HZ_CUST_SITE_USES_ALL HCSU,
  MTL_SYSTEM_ITEMS_B_KFV ITEM,
  MTL_CUSTOMER_ITEMS CUST_ITEM,
  HR_LOCATIONS_ALL HRL,
  MTL_PARAMETERS MTP,
  HR_ORGANIZATION_UNITS HOU,
  OE_SETS  OSET,
  HR_ALL_ORGANIZATION_UNITS ORG,
  RA_CUSTOMERS CUST_ACCT,
  RA_CONTACTS RCO1,
  RA_ADDRESSES_ALL RAD1,
  RA_CONTACTS RCO2,
  RA_ADDRESSES_ALL RAD2,
  HZ_CUST_SITE_USES_ALL HCSU2,
  RA_CONTACTS RCO3,
  RA_ADDRESSES_ALL RAD3,
  HZ_CUST_SITE_USES_ALL HCSU3
WHERE
  OEH.SHIP_TO_ORG_ID = HCSU3.SITE_USE_ID (+) AND
  HCSU3.CONTACT_ID = RCO3.CONTACT_ID (+) AND
  HCSU3.CUST_ACCT_SITE_ID = RAD3.ADDRESS_ID (+) AND
  OEH.INVOICE_TO_ORG_ID = HCSU2.SITE_USE_ID (+) AND
  HCSU2.CONTACT_ID = RCO2.CONTACT_ID (+) AND
  HCSU2.CUST_ACCT_SITE_ID = RAD2.ADDRESS_ID (+) AND
  L.SHIP_TO_ORG_ID = HCSU.SITE_USE_ID (+) AND
  HCSU.CONTACT_ID = RCO.CONTACT_ID (+) AND
  HCSU.CUST_ACCT_SITE_ID = RAD.ADDRESS_ID (+) AND
  HOU.ORGANIZATION_ID(+) = MTP.ORGANIZATION_ID AND
  MTP.ORGANIZATION_ID(+) = HRL.INVENTORY_ORGANIZATION_ID AND
  HRL.LOCATION_ID = WND.INITIAL_PICKUP_LOCATION_ID AND
  WDD.INVENTORY_ITEM_ID = ITEM.INVENTORY_ITEM_ID(+) AND
  WDD.ORGANIZATION_ID = ITEM.ORGANIZATION_ID(+) AND
  CUST_ITEM.CUSTOMER_ITEM_ID (+) = L.ORDERED_ITEM_ID AND
  L.SHIP_SET_ID = OSET.SET_ID (+) AND
  OEH.SOLD_TO_CONTACT_ID = RCO1.CONTACT_ID (+) AND
  RCO1.ADDRESS_ID = RAD1.ADDRESS_ID (+) AND
  ORG.ORGANIZATION_ID(+) = OEH.ORG_ID AND
  OEH.SOLD_TO_ORG_ID = CUST_ACCT.CUSTOMER_ID(+) AND
  L.HEADER_ID = OEH.HEADER_ID AND
  L.HEADER_ID = WDD.SOURCE_HEADER_ID AND
  L.LINE_ID = WDD.SOURCE_LINE_ID AND
  WND.DELIVERY_ID = WDA.DELIVERY_ID AND
  WDA.DELIVERY_DETAIL_ID = WDD.DELIVERY_DETAIL_ID AND
  WDD.SOURCE_CODE = 'OE' AND
  WDD.CONTAINER_FLAG = 'N' AND
  NVL(WDD.SHIPPED_QUANTITY, 0) > 0 AND
  WDD.SOURCE_LINE_ID = WMTC.TRANSACTION_ID AND  
  TRANSACTION_STATUS <= 2 AND  
  WMTC.TRANSACTION_TYPE = 'ASN'  
ORDER BY WMTC.WEB_TRANSACTION_ID
/
  
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_ASN_ORDER_QRY_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_ASN_ORDER_QRY_VW
AS
SELECT 
  DISTINCT
  WDD.SOURCE_LINE_ID ORDER_LINE_ID,
  OEH.ORDER_NUMBER ORDER_NUMBER, 
  WDD.SOURCE_LINE_NUMBER  ORDER_LINE_NUMBER,
  OEH.CUST_PO_NUMBER PURCHASE_ORDER_NUMBER,
  OEH.ORDERED_DATE ORDER_DATE,
  OEH.FLOW_STATUS_CODE  ORDER_STATUS,
  OEH.FREIGHT_TERMS_CODE FREIGHT_TERMS_CODE_INT,
  OEH.FOB_POINT_CODE FOB_CODE_INT,
  OEH.SHIPPING_METHOD_CODE SHIP_METHOD_INT,
  OEH.CONVERSION_RATE  CONVERSION_RATE,
  OEH.TRANSACTIONAL_CURR_CODE  CURRENCY_CODE, 
  ORG.NAME  ORGANIZATION_NAME,
  CUST_ACCT.CUSTOMER_NUMBER CUSTOMER_NUMBER, 
  CUST_ACCT.CUSTOMER_NAME  CUSTOMER_NAME,
  RAD1.ORIG_SYSTEM_REFERENCE ORDER_BY_CODE_INT,
  RAD1.ECE_TP_LOCATION_CODE ORDER_BY_CODE_EXT,
  RAD1.ADDRESS1 ORDER_BY_ADDRESS1,
  RAD1.ADDRESS2 ORDER_BY_ADDRESS2 ,
  RAD1.ADDRESS3 ORDER_BY_ADDRESS3,
  RAD1.ADDRESS4 ORDER_BY_ADDRESS4,
  RAD1.ADDRESSEE	ORDER_BY_ADDRESSEE,
  RAD1.IDENTIFYING_ADDRESS_FLAG	ORDER_BY_IDENTIFY_ADDR_FLAG,
  RAD1.CITY ORDER_BY_CITY,
  RAD1.POSTAL_CODE ORDER_BY_POSTAL_CODE,
  RAD1.COUNTRY ORDER_BY_COUNTRY_INT,
  RAD1.STATE ORDER_BY_STATE_INT,
  RAD1.PROVINCE ORDER_BY_PROVINCE_INT,
  RAD1.COUNTY ORDER_BY_COUNTY,
  RCO1.LAST_NAME ORDER_BY_CONTACT_LAST_NAME,
  RCO1.FIRST_NAME ORDER_BY_CONTACT_FIRST_NAME,
  RCO1.JOB_TITLE ORDER_BY_CONTACT_JOB_TITLE,
  RAD2.ORIG_SYSTEM_REFERENCE INVOICE_CODE_INT,
  RAD2.ECE_TP_LOCATION_CODE INVOICE_CODE_EXT,
  HCSU2.LOCATION INVOICE_NAME,
  RAD2.ADDRESS1 INVOICE_ADDRESS1,
  RAD2.ADDRESS2 INVOICE_ADDRESS2,
  RAD2.ADDRESS3 INVOICE_ADDRESS3,
  RAD2.ADDRESS4 INVOICE_ADDRESS4,
  RAD2.ADDRESSEE	INVOICE_ADDRESSEE,
  RAD2.IDENTIFYING_ADDRESS_FLAG	INVOICE_IDENTIFY_ADDR_FLAG,
  RAD2.CITY INVOICE_CITY,
  RAD2.POSTAL_CODE INVOICE_POSTAL_CODE,
  RAD2.COUNTRY INVOICE_COUNTRY_INT,
  RAD2.STATE INVOICE_STATE_INT,
  RAD2.PROVINCE INVOICE_PROVINCE_INT,
  RAD2.COUNTY INVOICE_COUNTY,
  RCO2.LAST_NAME INVOICE_CONTACT_LAST_NAME,
  RCO2.FIRST_NAME INVOICE_CONTACT_FIRST_NAME,
  RCO2.JOB_TITLE INVOICE_CONTACT_JOB_TITLE,
  RAD3.ORIG_SYSTEM_REFERENCE ORDER_SHIP_CODE_INT,
  RAD3.ECE_TP_LOCATION_CODE ORDER_SHIP_CODE_EXT,
  HCSU3.LOCATION ORDER_SHIP_NAME,
  RAD3.ADDRESS1 ORDER_SHIP_ADDRESS1,
  RAD3.ADDRESS2 ORDER_SHIP_ADDRESS2,
  RAD3.ADDRESS3 ORDER_SHIP_ADDRESS3,
  RAD3.ADDRESS4 ORDER_SHIP_ADDRESS4,
  RAD3.ADDRESSEE	ORDER_SHIP_ADDRESSEE,
  RAD3.IDENTIFYING_ADDRESS_FLAG	ORDER_SHIP_IDENTIFY_ADDR_FLAG,
  RAD3.CITY ORDER_SHIP_CITY,
  RAD3.POSTAL_CODE ORDER_SHIP_POSTAL_CODE,
  RAD3.COUNTRY ORDER_SHIP_COUNTRY_INT,
  RAD3.STATE ORDER_SHIP_STATE_INT,
  RAD3.PROVINCE ORDER_SHIP_PROVINCE_INT,
  RAD3.COUNTY ORDER_SHIP_COUNTY,
  RCO3.LAST_NAME ORDER_SHIP_CONTACT_LAST_NAME,
  RCO3.FIRST_NAME ORDER_SHIP_CONTACT_FIRST_NAME,
  RCO3.JOB_TITLE ORDER_SHIP_CONTACT_JOB_TITLE,
  L.CREATION_DATE LINE_CREATION_DATE,
  L.LAST_UPDATE_DATE LINE_MODIFIED_DATE,
  L.ACTUAL_SHIPMENT_DATE LINE_ACTUAL_SHIP_DATE,
  L.REQUEST_DATE LINE_REQUEST_DATE,
  L.PROMISE_DATE LINE_PROMISE_DATE,
  L.SCHEDULE_SHIP_DATE LINE_SCHEDULED_SHIP_DATE,
  L.SHIPPING_METHOD_CODE  LINE_SHIPMENT_METHOD,
  WDD.HOLD_CODE  HOLD_CODE,
  RAD.ORIG_SYSTEM_REFERENCE LINE_SHIP_CODE_INT,
  RAD.ECE_TP_LOCATION_CODE LINE_SHIP_CODE_EXT,
  HCSU.LOCATION LINE_SHIP_NAME,
  RAD.ADDRESS1 LINE_SHIP_ADDRESS1,
  RAD.ADDRESS2 LINE_SHIP_ADDRESS2,
  RAD.ADDRESS3 LINE_SHIP_ADDRESS3,
  RAD.ADDRESS4 LINE_SHIP_ADDRESS4,
  RAD.ADDRESSEE	LINE_SHIP_ADDRESSEE,
  RAD.IDENTIFYING_ADDRESS_FLAG	LINE_SHIP_IDENTIFY_ADDR_FLAG,
  RAD.CITY LINE_SHIP_CITY,
  RAD.POSTAL_CODE LINE_SHIP_POSTAL_CODE,
  RAD.COUNTRY LINE_SHIP_COUNTRY_INT,
  RAD.STATE LINE_SHIP_STATE_INT,
  RAD.PROVINCE LINE_SHIP_PROVINCE_INT,
  RAD.COUNTY LINE_SHIP_COUNTY,
  RCO.LAST_NAME LINE_SHIP_CONTACT_LAST_NAME,
  RCO.FIRST_NAME LINE_SHIP_CONTACT_FIRST_NAME,
  RCO.JOB_TITLE LINE_SHIP_CONTACT_JOB_TITLE,
  WDD.NET_WEIGHT NET_WEIGHT,
  WDD.GROSS_WEIGHT GROSS_WEIGHT,
  (WDD.GROSS_WEIGHT-WDD.NET_WEIGHT) TARE_WEIGHT,
  WDD.WEIGHT_UOM_CODE WEIGHT_UOM,
  WDD.VOLUME VOLUME,
  WDD.VOLUME_UOM_CODE  VOLUME_UOM,
  WDD.SHIPPED_QUANTITY SHIP_QUANTITY1,
  L.ORDERED_QUANTITY ORDERED_QUANTITY1,
  L.ORDER_QUANTITY_UOM  QUANTITY1_UOM,
  WDD.SHIPPED_QUANTITY2 SHIP_QUANTITY2,
  L.ORDERED_QUANTITY2 ORDERED_QUANTITY2,
  L.ORDERED_QUANTITY_UOM2 QUANTITY2_UOM,
  WDD.ITEM_DESCRIPTION ITEM_DESCRIPTION,
  ITEM.CONCATENATED_SEGMENTS ITEM,
  CUST_ITEM.CUSTOMER_ITEM_NUMBER CUSTOMER_ITEM,
  MTP.ORGANIZATION_CODE FROM_WAREHOUSE,
  HOU.NAME FROM_WAREHOUSE_NAME,
  HRL.ADDRESS_LINE_1 WAREHOUSE_ADDRESS1,
  HRL.ADDRESS_LINE_2 WAREHOUSE_ADDRESS2,
  HRL.ADDRESS_LINE_3 WAREHOUSE_ADDRESS3,
  HRL.TOWN_OR_CITY WAREHOUSE_CITY,
  HRL.POSTAL_CODE WAREHOUSE_POSTAL_CODE,
  HRL.COUNTRY WAREHOUSE_COUNTRY_INT,
  HRL.REGION_1 WAREHOUSE_REGION1_INT,
  HRL.REGION_2 WAREHOUSE_REGION2_INT,
  HRL.REGION_3 WAREHOUSE_REGION3_INT,
  HRL.TELEPHONE_NUMBER_1 WAREHOUSE_TELEPHONE_1,
  HRL.TELEPHONE_NUMBER_2 WAREHOUSE_TELEPHONE_2,
  HRL.TELEPHONE_NUMBER_3 WAREHOUSE_TELEPHONE_3,
  L.UNIT_LIST_PRICE  LIST_PRICE,
  L.TAX_VALUE  NET_TAX,
  L.UNIT_SELLING_PRICE UNIT_PRICE,
  (L.UNIT_SELLING_PRICE * L.PRICING_QUANTITY) EXTENDED_PRICE,
  WDD.LOT_NUMBER  LOT_NUMBER,
  WDD.SUBLOT_NUMBER SUBLOT_NUMBER,
  OSET.SET_NAME  SHIP_SET_NAME,
  WDD.FILLED_VOLUME	FILLED_VOLUME
FROM
  WSH_NEW_DELIVERIES WND,
  WSH_DELIVERY_ASSIGNMENTS WDA,
  WSH_DELIVERY_DETAILS WDD,
  OE_ORDER_LINES_ALL  L,
  OE_ORDER_HEADERS_ALL OEH,
  RA_CONTACTS RCO,
  RA_ADDRESSES_ALL RAD,
  HZ_CUST_SITE_USES_ALL HCSU,
  MTL_SYSTEM_ITEMS_B_KFV ITEM,
  MTL_CUSTOMER_ITEMS CUST_ITEM,
  HR_LOCATIONS_ALL HRL,
  MTL_PARAMETERS MTP,
  HR_ORGANIZATION_UNITS HOU,
  OE_SETS  OSET,
  HR_ALL_ORGANIZATION_UNITS ORG,
  RA_CUSTOMERS CUST_ACCT,
  RA_CONTACTS RCO1,
  RA_ADDRESSES_ALL RAD1,
  RA_CONTACTS RCO2,
  RA_ADDRESSES_ALL RAD2,
  HZ_CUST_SITE_USES_ALL HCSU2,
  RA_CONTACTS RCO3,
  RA_ADDRESSES_ALL RAD3,
  HZ_CUST_SITE_USES_ALL HCSU3
WHERE
  OEH.SHIP_TO_ORG_ID = HCSU3.SITE_USE_ID (+) AND
  HCSU3.CONTACT_ID = RCO3.CONTACT_ID (+) AND
  HCSU3.CUST_ACCT_SITE_ID = RAD3.ADDRESS_ID (+) AND
  OEH.INVOICE_TO_ORG_ID = HCSU2.SITE_USE_ID (+) AND
  HCSU2.CONTACT_ID = RCO2.CONTACT_ID (+) AND
  HCSU2.CUST_ACCT_SITE_ID = RAD2.ADDRESS_ID (+) AND
  L.SHIP_TO_ORG_ID = HCSU.SITE_USE_ID (+) AND
  HCSU.CONTACT_ID = RCO.CONTACT_ID (+) AND
  HCSU.CUST_ACCT_SITE_ID = RAD.ADDRESS_ID (+) AND
  HOU.ORGANIZATION_ID(+) = MTP.ORGANIZATION_ID AND
  MTP.ORGANIZATION_ID(+) = HRL.INVENTORY_ORGANIZATION_ID AND
  HRL.LOCATION_ID = WND.INITIAL_PICKUP_LOCATION_ID AND
  WDD.INVENTORY_ITEM_ID = ITEM.INVENTORY_ITEM_ID(+) AND
  WDD.ORGANIZATION_ID = ITEM.ORGANIZATION_ID(+) AND
  CUST_ITEM.CUSTOMER_ITEM_ID (+) = L.ORDERED_ITEM_ID AND
  L.SHIP_SET_ID = OSET.SET_ID (+) AND
  OEH.SOLD_TO_CONTACT_ID = RCO1.CONTACT_ID (+) AND
  RCO1.ADDRESS_ID = RAD1.ADDRESS_ID (+) AND
  ORG.ORGANIZATION_ID(+) = OEH.ORG_ID AND
  OEH.SOLD_TO_ORG_ID = CUST_ACCT.CUSTOMER_ID(+) AND
  L.HEADER_ID = OEH.HEADER_ID AND
  L.HEADER_ID = WDD.SOURCE_HEADER_ID AND
  L.LINE_ID = WDD.SOURCE_LINE_ID AND
  WND.DELIVERY_ID = WDA.DELIVERY_ID AND
  WDA.DELIVERY_DETAIL_ID = WDD.DELIVERY_DETAIL_ID AND
  WDD.SOURCE_CODE = 'OE' AND
  WDD.CONTAINER_FLAG = 'N' AND
  NVL(WDD.SHIPPED_QUANTITY, 0) > 0
/
  
SHOW ERRORS
