/*  ***************************************************************************
    *    $Date:   14 Aug 2001 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for Sales Order outbound in Application Schema  
    * Program Name:         wm_from_salesorder_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for Sales Order Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     01-OCT-02	Panchali Samanta         Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_salesorder_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."

/*----------------------------------------------------------------------*/
--      Create View WM_ORDER_HEADERS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ORDER_HEADERS_VW ( 
WEB_TRANSACTION_ID,  
DOCUMENT_TYPE,  
DOCUMENT_STATUS,  
HEADER_ID,
FLOW_STATUS_CODE,
ORDER_TYPE,
ORGANIZATION_NAME,
ORDER_NUMBER,
VERSION_NUMBER,
ORDERED_DATE, 
ORDER_CATEGORY,
ORDER_SOURCE,
PRICE_LIST,
ORIG_SYS_DOCUMENT_REF, 
CONVERSION_RATE, 
CONVERSION_RATE_DATE, 
CONVERSION_TYPE_CODE, 
CONVERSION_TYPE,
TRANSACTIONAL_CURR_CODE, 
SALESREP,
SALES_CHANNEL_CODE,
SALES_CHANNEL,
RETURN_REASON_CODE,
RETURN_REASON,
TAX_POINT_CODE, 
TAX_POINT,
TAX_EXEMPT_FLAG, 
TAX_EXEMPT_NUMBER, 
TAX_EXEMPT_REASON_CODE, 
TAX_EXEMPT_REASON,
AGREEMENT,
INVOICING_RULE,
ACCOUNTING_RULE, 
PAYMENT_TERM,
DEMAND_CLASS_CODE,  
DEMAND_CLASS,
SHIPMENT_PRIORITY_CODE,
SHIPMENT_PRIORITY,
SHIPMENT_PRIORITY_CODE_INT,
SHIPPING_METHOD_CODE, 
SHIPPING_METHOD,
FREIGHT_CARRIER_CODE,
FREIGHT_CARRIER, 
FREIGHT_TERMS_CODE,
FREIGHT_TERMS,
FOB_POINT_CODE,  
FOB_POINT,
PARTIAL_SHIPMENTS_ALLOWED, 
SHIP_TOLERANCE_ABOVE, 
SHIP_TOLERANCE_BELOW,
SHIPPING_INSTRUCTIONS, 
PACKING_INSTRUCTIONS,
ORDER_DATE_TYPE_CODE,
EARLIEST_SCHEDULE_LIMIT, 
LATEST_SCHEDULE_LIMIT,
CUST_PO_NUMBER,
PAYMENT_TYPE_CODE, 
PAYMENT_AMOUNT,
CHECK_NUMBER, 
CREDIT_CARD_CODE, 
CREDIT_CARD_HOLDER_NAME, 
CREDIT_CARD_NUMBER, 
CREDIT_CARD_EXPIRATION_DATE, 
CREDIT_CARD_APPROVAL_CODE,
SOLD_FROM_ORG, 
SOLD_TO_ORG,
SHIP_FROM_ORG,
SHIP_TO_ORG,
SHIP_TO_ADDRESS1,
SHIP_TO_ADDRESS2,
SHIP_TO_ADDRESS3,
SHIP_TO_ADDRESS4,
SHIP_TO_CITY,
SHIP_TO_COUNTY,
SHIP_TO_STATE,
SHIP_TO_POSTAL_CODE,
SHIP_TO_PROVINCE,
SHIP_TO_COUNTRY,
SHIP_TO_CUSTOMER_NUMBER,
SHIP_TO_CUSTOMER,
INVOICE_TO_ORG, 
INVOICE_ADDRESS1, 
INVOICE_ADDRESS2, 
INVOICE_ADDRESS3,
INVOICE_ADDRESS4,
INVOICE_CITY,
INVOICE_COUNTY,
INVOICE_STATE,
INVOICE_POSTAL_CODE,
INVOICE_PROVINCE_INT,
INVOICE_COUNTRY,
INVOICE_CUSTOMER_NUMBER,
INVOICE_CUSTOMER,
DELIVER_TO_ORG, 
DELIVER_TO_CONTACT,
DELIVER_TO_CUSTOMER_NUMBER,
DELIVER_TO_CUSTOMER,
SOLD_TO_CONTACT,
SHIP_TO_CONTACT_FIRST_NAME,
SHIP_TO_CONTACT_LAST_NAME,
SHIP_TO_CONTACT,
INVOICE_TO_CONTACT_FIRST_NAME,
INVOICE_TO_CONTACT_LAST_NAME,
INVOICE_TO_CONTACT,
CREDIT_CARD_APPROVAL_DATE,
BOOKED_FLAG, 
CANCELLED_FLAG,
CHANGE_SEQUENCE,
CUSTOMER_NUMBER, 
CUSTOMER_NAME,
CHANGE_REQUEST_CODE,
ORDERED_BY_CONTACT_FIRST_NAME,
ORDERED_BY_CONTACT_LAST_NAME,
HEADER_PO_CONTEXT,
PO_REVISION_DATE,
CHANGE_REASON,
CHANGE_COMMENT,
OPERATION_CODE,
CLOSED_FLAG,
REJECTED_FLAG,
READY_FLAG,
STATUS_FLAG,
FORCE_APPLY_FLAG,
INVOICE_ADDRESSEE,
INVOICE_IDENTIFY_ADDRESS_FLAG,
SHIP_TO_ADDRESSEE,
SHIP_TO_IDENTIFY_ADDRESS_FLAG
)
AS
SELECT
WMTC.WEB_TRANSACTION_ID,  
WMTC.TRANSACTION_TYPE DOCUMENT_TYPE,  
DECODE((WMTC.TRANSACTION_STATUS),0,'UPDATE',1,'INSERT',2, 'DELETE') DOCUMENT_STATUS,  
OEH.HEADER_ID,
OEH.FLOW_STATUS_CODE,
OT.NAME ORDER_TYPE,
ORG.NAME,
OEH.ORDER_NUMBER,
OEH.VERSION_NUMBER,
OEH.ORDERED_DATE, 
OECAT.MEANING ORDER_CATEGORY,
SRC.NAME  ORDER_SOURCE,
PL.NAME PRICE_LIST,
OEH.ORIG_SYS_DOCUMENT_REF, 
OEH.CONVERSION_RATE, 
OEH.CONVERSION_RATE_DATE, 
OEH.CONVERSION_TYPE_CODE, 
GLCTYP.USER_CONVERSION_TYPE  CONVERSION_TYPE,
OEH.TRANSACTIONAL_CURR_CODE, 
RAS.NAME SALESREP,
OEH.SALES_CHANNEL_CODE,
OESAL.MEANING SALES_CHANNEL,
OEH.RETURN_REASON_CODE,
LUP.MEANING RETURN_REASON,
OEH.TAX_POINT_CODE, 
OELKUPTAX.MEANING TAX_POINT,
OEH.TAX_EXEMPT_FLAG, 
OEH.TAX_EXEMPT_NUMBER, 
OEH.TAX_EXEMPT_REASON_CODE, 
ARL.MEANING  TAX_EXEMPT_REASON,
OAB.NAME AGREEMENT,
INVRULE.NAME INVOICING_RULE,
ACCRULE.NAME ACCOUNTING_RULE, 
TERMTL.NAME PAYMENT_TERM,
OEH.DEMAND_CLASS_CODE,  
FNDLKUP.MEANING DEMAND_CLASS,
OEH.SHIPMENT_PRIORITY_CODE,
OELKUP.MEANING SHIPMENT_PRIORITY,
OEH.SHIPMENT_PRIORITY_CODE SHIPMENT_PRIORITY_CODE_INT,
OEH.SHIPPING_METHOD_CODE, 
OESLKUP.MEANING  SHIPPING_METHOD,
OEH.FREIGHT_CARRIER_CODE,
FRT.DESCRIPTION FREIGHT_CARRIER, 
OEH.FREIGHT_TERMS_CODE,
OELKUP2.MEANING  FREIGHT_TERMS,
OEH.FOB_POINT_CODE,  
FOB.MEANING FOB_POINT,
OEH.PARTIAL_SHIPMENTS_ALLOWED, 
OEH.SHIP_TOLERANCE_ABOVE, 
OEH.SHIP_TOLERANCE_BELOW,
OEH.SHIPPING_INSTRUCTIONS, 
OEH.PACKING_INSTRUCTIONS,
OEH.ORDER_DATE_TYPE_CODE,
OEH.EARLIEST_SCHEDULE_LIMIT, 
OEH.LATEST_SCHEDULE_LIMIT,
OEH.CUST_PO_NUMBER,
OEH.PAYMENT_TYPE_CODE, 
OEH.PAYMENT_AMOUNT,
OEH.CHECK_NUMBER, 
OEH.CREDIT_CARD_CODE, 
OEH.CREDIT_CARD_HOLDER_NAME, 
OEH.CREDIT_CARD_NUMBER, 
OEH.CREDIT_CARD_EXPIRATION_DATE, 
OEH.CREDIT_CARD_APPROVAL_CODE,
SOLD_FROM_ORG.NAME SOLD_FROM_ORG, 
SUBSTRB(PARTY.PARTY_NAME,1,50) SOLD_TO_ORG,
SHIP_FROM_ORG.NAME SHIP_FROM_ORG,
SHIP_TO_ORG.LOCATION SHIP_TO_ORG,
SHIP_TO_ADDR.ADDRESS1 SHIP_TO_ADDRESS1,
SHIP_TO_ADDR.ADDRESS2 SHIP_TO_ADDRESS2,
SHIP_TO_ADDR.ADDRESS3 SHIP_TO_ADDRESS3,
SHIP_TO_ADDR.ADDRESS4 SHIP_TO_ADDRESS4,
SHIP_TO_ADDR.CITY  SHIP_TO_CITY,
SHIP_TO_ADDR.COUNTY SHIP_TO_COUNTY,
SHIP_TO_ADDR.STATE SHIP_TO_STATE,
SHIP_TO_ADDR.POSTAL_CODE SHIP_TO_POSTAL_CODE,
SHIP_TO_ADDR.PROVINCE SHIP_TO_PROVINCE,
SHIP_TO_ADDR.COUNTRY SHIP_TO_COUNTRY,
SHIP_TO_CUST.CUSTOMER_NUMBER SHIP_TO_CUSTOMER_NUMBER,
SHIP_TO_CUST.CUSTOMER_NAME SHIP_TO_CUSTOMER,
BILLORG.LOCATION INVOICE_TO_ORG, 
BILL_TO_ADDR.ADDRESS1 INVOICE_ADDRESS1, 
BILL_TO_ADDR.ADDRESS2 INVOICE_ADDRESS2, 
BILL_TO_ADDR.ADDRESS3 INVOICE_ADDRESS3,
BILL_TO_ADDR.ADDRESS4 INVOICE_ADDRESS4,
BILL_TO_ADDR.CITY  INVOICE_CITY,
BILL_TO_ADDR.COUNTY INVOICE_COUNTY,
BILL_TO_ADDR.STATE INVOICE_STATE,
BILL_TO_ADDR.POSTAL_CODE INVOICE_POSTAL_CODE,
BILL_TO_ADDR.PROVINCE INVOICE_PROVINCE_INT,
BILL_TO_ADDR.COUNTRY INVOICE_COUNTRY,
BILL_TO_CUST.CUSTOMER_NUMBER INVOICE_CUSTOMER_NUMBER,
BILL_TO_CUST.CUSTOMER_NAME INVOICE_CUSTOMER,
DELIVERORG.LOCATION DELIVER_TO_ORG, 
DELIVERCONT.NAME  DELIVER_TO_CONTACT,
DELIVER_TO_CUST.CUSTOMER_NUMBER DELIVER_TO_CUSTOMER_NUMBER,
DELIVER_TO_CUST.CUSTOMER_NAME DELIVER_TO_CUSTOMER,
DECODE(SOLDCONT.LAST_NAME,NULL,NULL,SOLDCONT.LAST_NAME||', ')|| 
DECODE(SOLDCONT.FIRST_NAME,NULL,NULL,SOLDCONT.FIRST_NAME||' ')||
SOLDCONT.TITLE SOLD_TO_CONTACT,
SHIPCONT.FIRST_NAME SHIP_TO_CONTACT_FIRST_NAME,
SHIPCONT.LAST_NAME SHIP_TO_CONTACT_LAST_NAME,
DECODE(SHIPCONT.LAST_NAME,NULL,NULL,SHIPCONT.LAST_NAME||', ')
||DECODE(SHIPCONT.FIRST_NAME,NULL,NULL,SHIPCONT.FIRST_NAME||' ')
||SHIPCONT.TITLE SHIP_TO_CONTACT,
BILLCONT.FIRST_NAME INVOICE_TO_CONTACT_FIRST_NAME,
BILLCONT.LAST_NAME INVOICE_TO_CONTACT_LAST_NAME,
DECODE(BILLCONT.LAST_NAME,NULL,NULL,BILLCONT.LAST_NAME||', ')||
DECODE(BILLCONT.FIRST_NAME,NULL,NULL,BILLCONT.FIRST_NAME||' ')||
BILLCONT.TITLE INVOICE_TO_CONTACT,
OEH.CREDIT_CARD_APPROVAL_DATE,
OEH.BOOKED_FLAG, 
OEH.CANCELLED_FLAG,
OEH.CHANGE_SEQUENCE,
CUST_ACCT.CUSTOMER_NUMBER CUSTOMER_NUMBER, 
CUST_ACCT.CUSTOMER_NAME  CUSTOMER_NAME,
NULL CHANGE_REQUEST_CODE,
NULL ORDERED_BY_CONTACT_FIRST_NAME,
NULL ORDERED_BY_CONTACT_LAST_NAME,
NULL HEADER_PO_CONTEXT,
NULL PO_REVISION_DATE,
NULL CHANGE_REASON,
NULL CHANGE_COMMENT,
NULL OPERATION_CODE,
NULL CLOSED_FLAG,
NULL REJECTED_FLAG,
NULL READY_FLAG,
NULL STATUS_FLAG,
NULL FORCE_APPLY_FLAG,
BILL_TO_ADDR.ADDRESSEE		INVOICE_ADDRESSEE,
BILL_TO_ADDR.IDENTIFYING_ADDRESS_FLAG INVOICE_IDENTIFY_ADDRESS_FLAG,
SHIP_TO_ADDR.ADDRESSEE	SHIP_TO_ADDRESSEE,
SHIP_TO_ADDR.IDENTIFYING_ADDRESS_FLAG	SHIP_TO_IDENTIFY_ADDRESS_FLAG
FROM 
WM_TRACK_CHANGES_VW WMTC,
OE_ORDER_HEADERS_ALL OEH,
OE_TRANSACTION_TYPES_TL OT,
HR_ALL_ORGANIZATION_UNITS ORG,
OE_ORDER_SOURCES SRC,
QP_LIST_HEADERS_TL PL, 
FND_CURRENCIES FNDCUR,
RA_SALESREPS_ALL RAS,
FND_LOOKUP_VALUES LUP,
AR_LOOKUPS  ARL,
OE_AGREEMENTS_TL  OAB,
RA_RULES INVRULE, 
RA_RULES ACCRULE, 
RA_TERMS_B TERMB,
RA_TERMS_TL TERMTL,
OE_FND_COMMON_LOOKUPS_V  FNDLKUP,
OE_LOOKUPS   OELKUP,
OE_SHIP_METHODS_V OESLKUP,
GL_DAILY_CONVERSION_TYPES  GLCTYP,
ORG_FREIGHT FRT,
OE_LOOKUPS  OELKUP2,
AR_LOOKUPS  FOB,
HR_ALL_ORGANIZATION_UNITS SOLD_FROM_ORG,
RA_CUSTOMERS CUST_ACCT,
HZ_PARTIES PARTY,
HR_ALL_ORGANIZATION_UNITS SHIP_FROM_ORG,
RA_SITE_USES_ALL SHIP_TO_ORG,
RA_ADDRESSES_ALL SHIP_TO_ADDR, 
RA_SITE_USES_ALL BILLORG, 
RA_ADDRESSES_ALL BILL_TO_ADDR,
RA_SITE_USES_ALL DELIVERORG, 
OE_CONTACTS_V DELIVERCONT,
RA_ADDRESSES_ALL DELIVER_TO_ADDR,
RA_CUSTOMERS DELIVER_TO_CUST,
RA_CONTACTS SOLDCONT, 
RA_CONTACTS SHIPCONT, 
RA_CONTACTS BILLCONT,  
RA_CUSTOMERS SHIP_TO_CUST,
RA_CUSTOMERS BILL_TO_CUST,
OE_LOOKUPS  OECAT,
OE_LOOKUPS  OESAL,
OE_LOOKUPS OELKUPTAX
WHERE 
OEH.ORDER_TYPE_ID = OT.TRANSACTION_TYPE_ID AND 
OT.LANGUAGE(+) = USERENV('LANG') AND
ORG.ORGANIZATION_ID(+) = OEH.ORG_ID AND
FRT.ORGANIZATION_ID(+) = OEH.ORG_ID AND
FRT.FREIGHT_CODE(+) = OEH.FREIGHT_CARRIER_CODE AND
OEH.ORDER_SOURCE_ID = SRC.ORDER_SOURCE_ID(+) AND
OEH.PRICE_LIST_ID = PL.LIST_HEADER_ID(+) AND 
PL.LANGUAGE(+) = USERENV('LANG') AND
OEH.TRANSACTIONAL_CURR_CODE = FNDCUR.CURRENCY_CODE(+) AND
RAS.SALESREP_ID(+) = OEH.SALESREP_ID AND
RAS.ORG_ID(+) = OEH.ORG_ID AND
LUP.LOOKUP_TYPE(+) = 'CREDIT_MEMO_REASON' AND
LUP.LOOKUP_CODE(+) = OEH.RETURN_REASON_CODE AND
ARL.LOOKUP_TYPE(+) ='TAX_CONTROL_FLAG' AND
ARL.LOOKUP_CODE(+) = OEH.TAX_EXEMPT_REASON_CODE AND
OAB.AGREEMENT_ID(+) = OEH.AGREEMENT_ID AND
OAB.LANGUAGE(+) = USERENV('LANG') AND
OEH.INVOICING_RULE_ID = INVRULE.RULE_ID(+) AND
OEH.ACCOUNTING_RULE_ID = ACCRULE.RULE_ID(+) AND 
OEH.PAYMENT_TERM_ID = TERMB.TERM_ID(+) AND 
TERMB.TERM_ID = TERMTL.TERM_ID(+) AND
TERMTL.LANGUAGE(+) = USERENV('LANG') AND
FNDLKUP.LOOKUP_TYPE(+) = 'DEMAND_CLASS' AND
FNDLKUP.LOOKUP_CODE(+) = OEH.DEMAND_CLASS_CODE AND
OELKUP.LOOKUP_TYPE(+) = 'SHIPMENT_PRIORITY' AND
OELKUP.LOOKUP_CODE(+) = OEH.SHIPMENT_PRIORITY_CODE AND
OESLKUP.LOOKUP_TYPE(+) = 'SHIP_METHOD' AND
OESLKUP.LOOKUP_CODE(+) = OEH.SHIPPING_METHOD_CODE AND
GLCTYP.CONVERSION_TYPE(+) = OEH.CONVERSION_TYPE_CODE AND
OELKUP2.LOOKUP_TYPE(+) = 'FREIGHT_TERMS' AND
OELKUP2.LOOKUP_CODE(+) = OEH.FREIGHT_TERMS_CODE AND
FOB.LOOKUP_CODE(+) = OEH.FOB_POINT_CODE AND
FOB.LOOKUP_TYPE(+) = 'FOB' AND
SOLD_FROM_ORG.ORGANIZATION_ID(+) = OEH.SOLD_FROM_ORG_ID AND
OEH.SOLD_TO_ORG_ID = CUST_ACCT.CUSTOMER_ID(+) AND
CUST_ACCT.PARTY_ID = PARTY.PARTY_ID(+) AND
OEH.SHIP_FROM_ORG_ID = SHIP_FROM_ORG.ORGANIZATION_ID(+) AND 
OEH.SHIP_TO_ORG_ID = SHIP_TO_ORG.SITE_USE_ID(+) AND 
SHIP_TO_ORG.ADDRESS_ID = SHIP_TO_ADDR.ADDRESS_ID(+) AND 
OEH.INVOICE_TO_ORG_ID = BILLORG.SITE_USE_ID(+) AND
BILLORG.ADDRESS_ID = BILL_TO_ADDR.ADDRESS_ID(+) AND
OEH.DELIVER_TO_ORG_ID = DELIVERORG.SITE_USE_ID(+) AND
DELIVERORG.ADDRESS_ID = DELIVER_TO_ADDR.ADDRESS_ID(+) AND
DELIVER_TO_ADDR.CUSTOMER_ID = DELIVER_TO_CUST.CUSTOMER_ID(+) AND
OEH.DELIVER_TO_CONTACT_ID = DELIVERCONT.CONTACT_ID(+) AND
OEH.SOLD_TO_CONTACT_ID = SOLDCONT.CONTACT_ID(+) AND 
OEH.SHIP_TO_CONTACT_ID = SHIPCONT.CONTACT_ID(+) AND 
OEH.INVOICE_TO_CONTACT_ID = BILLCONT.CONTACT_ID(+) AND
SHIP_TO_ADDR.CUSTOMER_ID = SHIP_TO_CUST.CUSTOMER_ID(+) AND
BILL_TO_ADDR.CUSTOMER_ID = BILL_TO_CUST.CUSTOMER_ID(+) AND
OECAT.LOOKUP_CODE(+) = OEH.ORDER_CATEGORY_CODE AND
OECAT.LOOKUP_TYPE(+) = 'ORDER_CATEGORY' AND
OESAL.LOOKUP_CODE(+) = OEH.SALES_CHANNEL_CODE AND
OESAL.LOOKUP_TYPE(+) = 'SALES_CHANNEL' AND
OELKUPTAX.LOOKUP_CODE(+) = OEH.TAX_POINT_CODE AND
OELKUPTAX.LOOKUP_TYPE(+) = 'TAX_POINT' AND
OEH.BOOKED_FLAG = 'Y' AND
OEH.HEADER_ID = WMTC.TRANSACTION_ID AND  
TRANSACTION_STATUS <= 2 AND  
WMTC.TRANSACTION_TYPE = 'SALESORDER'  
ORDER BY WMTC.WEB_TRANSACTION_ID
/
  
SHOW ERRORS


/*----------------------------------------------------------------------*/
--      Create View WM_ORDER_LINES_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_ORDER_LINES_VW (
LINE_ID,
HEADER_ID, 
LINE_NUMBER,
FLOW_STATUS_CODE,
CHANGE_SEQUENCE,
CHANGE_REQUEST_CODE, 
ORDER_SOURCE,
ORIG_SYS_LINE_REF,
ORIG_SYS_SHIPMENT_REF,
SHIPMENT_NUMBER,
SPLIT_LINE_LINE_REF,
LINE_TYPE, 
ITEM_TYPE_CODE,
ITEM_TYPE,
SOURCE_TYPE_CODE,
SOURCE_TYPE,
SCHEDULE_STATUS_CODE,
SCHEDULE_STATUS,
INVENTORY_ITEM,
TOP_MODEL_LINE_REF,
LINK_TO_LINE_REF,
ATO_LINE_REF,
EXPLOSION_DATE, 
COMPONENT_CODE,
SORT_ORDER,
MODEL_GROUP_NUMBER,
OPTION_NUMBER, 
OPTION_FLAG,
SHIP_MODEL_COMPLETE_FLAG,
SCHEDULE_SHIP_DATE,
SCHEDULE_ARRIVAL_DATE, 
ACTUAL_ARRIVAL_DATE,
REQUEST_DATE,
PROMISE_DATE,
DELIVERY_LEAD_TIME,
ORDERED_QUANTITY, 
ORDER_QUANTITY_UOM,
SHIPPING_QUANTITY, 
SHIPPING_QUANTITY_UOM,
SHIPPED_QUANTITY,
CANCELLED_QUANTITY,  
FULFILLED_QUANTITY,
PRICING_QUANTITY, 
PRICING_QUANTITY_UOM,
SOLD_FROM_ORG, 
SOLD_TO_ORG,
SHIP_FROM_ORG,
DELIVERY_NAME,
SHIP_TO_ORG,
SHIP_TO_ADDRESS1,
SHIP_TO_ADDRESS2,
SHIP_TO_ADDRESS3,
SHIP_TO_ADDRESS4,
SHIP_TO_CITY,
SHIP_TO_COUNTY,
SHIP_TO_STATE,
SHIP_TO_POSTAL_CODE,
SHIP_TO_COUNTRY,
DELIVER_TO_ORG, 
INVOICE_TO_ORG,
BILL_TO_ADDRESS1, 
BILL_TO_ADDRESS2, 
BILL_TO_ADDRESS3, 
BILL_TO_ADDRESS4,
BILL_TO_CITY,
BILL_TO_COUNTY,
BILL_TO_STATE,
BILL_TO_POSTAL_CODE,
BILL_TO_COUNTRY,
SHIP_TO_CONTACT_FIRST_NAME,
SHIP_TO_CONTACT_LAST_NAME,
SHIP_TO_CONTACT_JOB_TITLE,
SHIP_TO_CONTACT,
DELIVER_TO_CONTACT,
INVOICE_TO_CONTACT,
DROP_SHIP_FLAG,
VEH_CUS_ITEM_CUM_KEY,
CUST_PRODUCTION_SEQ_NUM,
LOAD_SEQ_NUMBER,
OVER_SHIP_REASON_CODE, 
OVER_SHIP_RESOLVED_FLAG,
AUTHORIZED_TO_SHIP_FLAG,
SHIP_TOLERANCE_ABOVE, 
SHIP_TOLERANCE_BELOW, 
SHIP_SET_NAME,
ARRIVAL_SET_NAME, 
PRICE_LIST,
PRICING_DATE,
UNIT_LIST_PRICE,
UNIT_LIST_PRICE_PER_PQTY,
UNIT_SELLING_PRICE,  
UNIT_SELLING_PRICE_PER_PQTY ,
TAX_DATE, 
TAX_CODE,
TAX_VALUE,
CALCULATED_PRICE_FLAG,
TAX_EXEMPT_FLAG, 
TAX_EXEMPT_NUMBER, 
TAX_EXEMPT_REASON_CODE,
TAX_EXEMPT_REASON,
TAX_POINT_CODE,
TAX_POINT,
AGREEMENT,
ACCOUNTING_RULE, 
INVOICING_RULE,
PAYMENT_TERM,
DEMAND_CLASS_CODE,  
DEMAND_CLASS,
SHIPMENT_PRIORITY_CODE,
SHIPMENT_PRIORITY,
SHIPPING_METHOD_CODE, 
SHIPPING_METHOD,
FREIGHT_CARRIER_CODE,
FREIGHT_CARRIER, 
FREIGHT_TERMS_CODE,
FREIGHT_TERMS,
FOB_POINT_CODE,  
FOB_POINT,
SALESREP,
SHIPPING_INSTRUCTIONS, 
PACKING_INSTRUCTIONS,
RETURN_REASON_CODE,
RETURN_REASON,
REFERENCE_TYPE, 
REFERENCE_HEADER,
REFERENCE_LINE,
CREDIT_INVOICE_NUMBER,
CUSTOMER_LINE_NUMBER ,
CUSTOMER_PO_NUMBER, 
CUSTOMER_SHIPMENT_NUMBER, 
CUSTOMER_ITEM_NAME,
CUSTOMER_ITEM_REVISION,
CUSTOMER_ITEM_NET_PRICE ,
DEMAND_BUCKET_TYPE_CODE,
CUSTOMER_DOCK_CODE, 
CUSTOMER_JOB, 
CUSTOMER_PRODUCTION_LINE, 
CUST_MODEL_SERIAL_NUMBER,
PROJECT,
TASK,
FULFILLMENT_SET_NAME,
END_ITEM_UNIT_NUMBER, 
ITEM_REVISION ,
SCHEDULE_DATE,
SHIP_TO_CONTACT_AREA_CODE1,
SHIP_TO_CONTACT_AREA_CODE2,
SHIP_TO_CONTACT_AREA_CODE3,
CUSTOMER_ITEM_ID_TYPE,
INVOICE_SET_NAME,
TAX,
SCHEDULE_ITEM_DETAIL,
DEMAND_STREAM,
SERVICE_DURATION ,  
SERVICE_START_DATE , 
SERVICE_END_DATE , 
SERVICE_COTERMINATE_FLAG , 
UNIT_SELLING_PERCENT , 
UNIT_LIST_PERCENT , 
UNIT_PERCENT_BASE_PRICE , 
SERVICE_NUMBER ,
CANCELLED_FLAG,
FULFILLED_FLAG,
SERVICE_TXN_REASON_CODE , 
SERVICE_TXN_COMMENTS ,
CLOSED_FLAG,
CONTRACT_PO_NUMBER,
LINE_PO_CONTEXT,
OPERATION_CODE,
CHANGE_REASON,
CHANGE_COMMENTS,
REJECTED_FLAG,
STATUS_FLAG,
BILL_TO_ADDRESSEE,
BILL_TO_IDENTIFY_ADDRESS_FLAG,
SHIP_TO_ADDRESSEE,
SHIP_TO_IDENTIFY_ADDRESS_FLAG
)
AS
SELECT
L.LINE_ID,
L.HEADER_ID, 
L.LINE_NUMBER,
L.FLOW_STATUS_CODE,
NULL CHANGE_SEQUENCE,
NULL CHANGE_REQUEST_CODE, 
SRC.NAME  ORDER_SOURCE,
L.ORIG_SYS_LINE_REF,
L.ORIG_SYS_SHIPMENT_REF,
L.SHIPMENT_NUMBER,
LI.ORIG_SYS_LINE_REF  SPLIT_LINE_LINE_REF,
LTT.NAME LINE_TYPE, 
L.ITEM_TYPE_CODE,
OEL.MEANING  ITEM_TYPE,
L.SOURCE_TYPE_CODE,
OS.MEANING SOURCE_TYPE,
L.SCHEDULE_STATUS_CODE,
OSH.MEANING SCHEDULE_STATUS,
ITEM.CONCATENATED_SEGMENTS  INVENTORY_ITEM,
LT.ORIG_SYS_LINE_REF  TOP_MODEL_LINE_REF,
LL.ORIG_SYS_LINE_REF LINK_TO_LINE_REF,
LA.ORIG_SYS_LINE_REF ATO_LINE_REF,
L.EXPLOSION_DATE, 
L.COMPONENT_CODE,
L.SORT_ORDER,
L.MODEL_GROUP_NUMBER,
L.OPTION_NUMBER, 
L.OPTION_FLAG,
L.SHIP_MODEL_COMPLETE_FLAG,
L.SCHEDULE_SHIP_DATE,
L.SCHEDULE_ARRIVAL_DATE, 
L.ACTUAL_ARRIVAL_DATE,
L.REQUEST_DATE,
L.PROMISE_DATE,
L.DELIVERY_LEAD_TIME,
L.ORDERED_QUANTITY, 
L.ORDER_QUANTITY_UOM,
L.SHIPPING_QUANTITY, 
L.SHIPPING_QUANTITY_UOM,
L.SHIPPED_QUANTITY,
L.CANCELLED_QUANTITY,  
L.FULFILLED_QUANTITY,
L.PRICING_QUANTITY, 
L.PRICING_QUANTITY_UOM,
SOLD_FROM_ORG.NAME SOLD_FROM_ORG, 
SUBSTRB(PARTY.PARTY_NAME,1,50) SOLD_TO_ORG,
SHIP_FROM_ORG.NAME SHIP_FROM_ORG,
NULL DELIVERY_NAME,
SHIP_TO_ORG.LOCATION SHIP_TO_ORG,
SHIP_TO_ADDR.ADDRESS1 SHIP_TO_ADDRESS1,
SHIP_TO_ADDR.ADDRESS2 SHIP_TO_ADDRESS2,
SHIP_TO_ADDR.ADDRESS3 SHIP_TO_ADDRESS3,
SHIP_TO_ADDR.ADDRESS4 SHIP_TO_ADDRESS4,
SHIP_TO_ADDR.CITY  SHIP_TO_CITY,
SHIP_TO_ADDR.COUNTY SHIP_TO_COUNTY,
SHIP_TO_ADDR.STATE SHIP_TO_STATE,
SHIP_TO_ADDR.POSTAL_CODE SHIP_TO_POSTAL_CODE,
SHIP_TO_ADDR.COUNTRY SHIP_TO_COUNTRY,
DELIVERORG.LOCATION DELIVER_TO_ORG, 
BILLORG.LOCATION INVOICE_TO_ORG,
BILL_TO_ADDR.ADDRESS1 BILL_TO_ADDRESS1, 
BILL_TO_ADDR.ADDRESS2 BILL_TO_ADDRESS2, 
BILL_TO_ADDR.ADDRESS3 BILL_TO_ADDRESS3, 
BILL_TO_ADDR.ADDRESS4 BILL_TO_ADDRESS4, 
BILL_TO_ADDR.CITY BILL_TO_CITY,
BILL_TO_ADDR.COUNTY BILL_TO_COUNTY,
BILL_TO_ADDR.STATE  BILL_TO_STATE,
BILL_TO_ADDR.POSTAL_CODE  BILL_TO_POSTAL_CODE,
BILL_TO_ADDR.COUNTRY  BILL_TO_COUNTRY,
SHIPCONT.FIRST_NAME SHIP_TO_CONTACT_FIRST_NAME,
SHIPCONT.LAST_NAME SHIP_TO_CONTACT_LAST_NAME,
SHIPCONT.JOB_TITLE SHIP_TO_CONTACT_JOB_TITLE,
DECODE(SHIPCONT.LAST_NAME,NULL,NULL,SHIPCONT.LAST_NAME||', ')||
DECODE(SHIPCONT.FIRST_NAME,NULL,NULL,SHIPCONT.FIRST_NAME||' ')||
SHIPCONT.TITLE SHIP_TO_CONTACT,
DELIVERCONT.NAME  DELIVER_TO_CONTACT,
BILLCONT.NAME INVOICE_TO_CONTACT,
NULL DROP_SHIP_FLAG,
L.VEH_CUS_ITEM_CUM_KEY_ID  VEH_CUS_ITEM_CUM_KEY,
L.CUST_PRODUCTION_SEQ_NUM,
NULL LOAD_SEQ_NUMBER,
L.OVER_SHIP_REASON_CODE, 
L.OVER_SHIP_RESOLVED_FLAG,
L.AUTHORIZED_TO_SHIP_FLAG,
L.SHIP_TOLERANCE_ABOVE, 
L.SHIP_TOLERANCE_BELOW, 
OSET.SET_NAME  SHIP_SET_NAME,
ASET.SET_NAME ARRIVAL_SET_NAME, 
PL.NAME PRICE_LIST,
L.PRICING_DATE,
L.UNIT_LIST_PRICE,
L.UNIT_LIST_PRICE_PER_PQTY,
L.UNIT_SELLING_PRICE,  
L.UNIT_SELLING_PRICE_PER_PQTY ,
L.TAX_DATE, 
L.TAX_CODE,
L.TAX_VALUE,
NULL CALCULATED_PRICE_FLAG,
L.TAX_EXEMPT_FLAG, 
L.TAX_EXEMPT_NUMBER, 
L.TAX_EXEMPT_REASON_CODE,
ARL.MEANING  TAX_EXEMPT_REASON,
L.TAX_POINT_CODE,
OELKUPTAX.MEANING TAX_POINT,
OAB.NAME AGREEMENT,
ACCRULE.NAME ACCOUNTING_RULE, 
INVRULE.NAME INVOICING_RULE,
TERM.NAME PAYMENT_TERM,
L.DEMAND_CLASS_CODE,  
FNDLKUP.MEANING DEMAND_CLASS,
L.SHIPMENT_PRIORITY_CODE,
OELKUP.MEANING SHIPMENT_PRIORITY,
L.SHIPPING_METHOD_CODE, 
OESLKUP.MEANING  SHIPPING_METHOD,
L.FREIGHT_CARRIER_CODE,
FRT.DESCRIPTION FREIGHT_CARRIER, 
L.FREIGHT_TERMS_CODE,
OELKUP2.MEANING  FREIGHT_TERMS,
L.FOB_POINT_CODE,  
FOB.MEANING FOB_POINT,
RAS.NAME SALESREP,
L.SHIPPING_INSTRUCTIONS, 
L.PACKING_INSTRUCTIONS,
L.RETURN_REASON_CODE,
LUP.MEANING RETURN_REASON,
L.REFERENCE_TYPE, 
H1.ORIG_SYS_DOCUMENT_REF  REFERENCE_HEADER,
L1.ORIG_SYS_LINE_REF REFERENCE_LINE,
RCT.TRX_NUMBER CREDIT_INVOICE_NUMBER,
L.CUSTOMER_LINE_NUMBER ,
L.CUST_PO_NUMBER  CUSTOMER_PO_NUMBER, 
L.CUSTOMER_SHIPMENT_NUMBER, 
CUST_ITEM.CUSTOMER_ITEM_NUMBER CUSTOMER_ITEM_NAME,
NULL CUSTOMER_ITEM_REVISION,
L.CUSTOMER_ITEM_NET_PRICE ,
L.DEMAND_BUCKET_TYPE_CODE,
L.CUSTOMER_DOCK_CODE, 
L.CUSTOMER_JOB, 
L.CUSTOMER_PRODUCTION_LINE, 
L.CUST_MODEL_SERIAL_NUMBER,
PROJECT.NAME  PROJECT,
TASK.TASK_NAME TASK,
FUL.SET_NAME FULFILLMENT_SET_NAME,
L.END_ITEM_UNIT_NUMBER, 
L.ITEM_REVISION ,
NULL SCHEDULE_DATE,
NULL SHIP_TO_CONTACT_AREA_CODE1,
NULL SHIP_TO_CONTACT_AREA_CODE2,
NULL SHIP_TO_CONTACT_AREA_CODE3,
NULL CUSTOMER_ITEM_ID_TYPE,
NULL INVOICE_SET_NAME,
NULL TAX,
NULL SCHEDULE_ITEM_DETAIL,
NULL DEMAND_STREAM,
L.SERVICE_DURATION ,  
L.SERVICE_START_DATE , 
L.SERVICE_END_DATE , 
L.SERVICE_COTERMINATE_FLAG , 
L.UNIT_SELLING_PERCENT , 
L.UNIT_LIST_PERCENT , 
L.UNIT_PERCENT_BASE_PRICE , 
L.SERVICE_NUMBER ,
L.CANCELLED_FLAG,
L.FULFILLED_FLAG,
L.SERVICE_TXN_REASON_CODE , 
L.SERVICE_TXN_COMMENTS ,
NULL CLOSED_FLAG,
NULL CONTRACT_PO_NUMBER,
NULL LINE_PO_CONTEXT,
NULL OPERATION_CODE,
NULL CHANGE_REASON,
NULL CHANGE_COMMENTS,
NULL REJECTED_FLAG,
NULL STATUS_FLAG,
BILL_TO_ADDR.ADDRESSEE		BILL_TO_ADDRESSEE,
BILL_TO_ADDR.IDENTIFYING_ADDRESS_FLAG	BILL_TO_IDENTIFY_ADDRESS_FLAG,
SHIP_TO_ADDR.ADDRESSEE		SHIP_TO_ADDRESSEE,
SHIP_TO_ADDR.IDENTIFYING_ADDRESS_FLAG	SHIP_TO_IDENTIFY_ADDRESS_FLAG
FROM 
OE_ORDER_SOURCES SRC,
OE_ORDER_HEADERS_ALL H, 
OE_ORDER_LINES_ALL L,
OE_ORDER_LINES_ALL LI,
OE_TRANSACTION_TYPES_TL LTT,
OE_LOOKUPS  OEL,
OE_LOOKUPS  OS,
OE_LOOKUPS  OSH,
MTL_SYSTEM_ITEMS_B_KFV ITEM,
OE_ORDER_LINES_ALL LT,
OE_ORDER_LINES_ALL LL,
OE_ORDER_LINES_ALL LA,
HR_ALL_ORGANIZATION_UNITS SOLD_FROM_ORG,
HZ_CUST_ACCOUNTS CUST_ACCT,
HZ_PARTIES PARTY, 
HR_ALL_ORGANIZATION_UNITS SHIP_FROM_ORG,
RA_SITE_USES_ALL SHIP_TO_ORG,
RA_ADDRESSES_ALL SHIP_TO_ADDR,
RA_SITE_USES_ALL DELIVERORG, 
RA_SITE_USES_ALL BILLORG, 
RA_ADDRESSES_ALL BILL_TO_ADDR,
RA_CONTACTS SHIPCONT,
OE_CONTACTS_V DELIVERCONT,
OE_CONTACTS_V BILLCONT,
OE_SETS OSET,
OE_SETS ASET,
QP_LIST_HEADERS_VL PL,
AR_LOOKUPS ARL,
OE_AGREEMENTS_TL  OAB,
RA_RULES ACCRULE, 
RA_RULES INVRULE, 
OE_LOOKUPS OELKUPTAX,
RA_TERMS_TL TERM, 
OE_FND_COMMON_LOOKUPS_V  FNDLKUP,
OE_LOOKUPS   OELKUP,
OE_SHIP_METHODS_V OESLKUP,
ORG_FREIGHT FRT,
OE_LOOKUPS  OELKUP2,
AR_LOOKUPS  FOB,
RA_SALESREPS_ALL RAS,
FND_LOOKUP_VALUES LUP,
OE_ORDER_HEADERS_ALL H1, 
OE_ORDER_LINES_ALL L1,
PA_PROJECTS_ALL PROJECT,
PA_TASKS  TASK,
RA_CUSTOMER_TRX_LINES_ALL RCTL,
RA_CUSTOMER_TRX_ALL RCT, 
OE_LINE_SETS FULFILL,
OE_SETS FUL,
MTL_CUSTOMER_ITEMS CUST_ITEM
WHERE 
H.ORDER_SOURCE_ID = SRC.ORDER_SOURCE_ID (+) AND
L.HEADER_ID = H.HEADER_ID AND
LI.LINE_ID (+) = L.SPLIT_FROM_LINE_ID AND
OEL.LOOKUP_CODE(+) = L.ITEM_TYPE_CODE AND
OEL.LOOKUP_TYPE (+) = 'ITEM_TYPE' AND
OS.LOOKUP_CODE(+) = L.SOURCE_TYPE_CODE AND
OS.LOOKUP_TYPE (+) = 'SOURCE_TYPE' AND
OSH.LOOKUP_CODE(+) = L.SCHEDULE_STATUS_CODE AND
OSH.LOOKUP_TYPE (+) = 'SCHEDULE_STATUS' AND
ITEM.INVENTORY_ITEM_ID (+) = L.INVENTORY_ITEM_ID AND
ITEM.ORGANIZATION_ID(+) = L.ORG_ID AND
LT.LINE_ID (+) = L.TOP_MODEL_LINE_ID AND
LL.LINE_ID (+) = L.LINK_TO_LINE_ID AND
LA.LINE_ID (+) = L.ATO_LINE_ID AND
SOLD_FROM_ORG.ORGANIZATION_ID(+) = L.SOLD_FROM_ORG_ID AND
L.SOLD_TO_ORG_ID = CUST_ACCT.CUST_ACCOUNT_ID(+) AND
CUST_ACCT.PARTY_ID = PARTY.PARTY_ID(+) AND
L.SHIP_FROM_ORG_ID = SHIP_FROM_ORG.ORGANIZATION_ID (+) AND
L.SHIP_TO_ORG_ID = SHIP_TO_ORG.SITE_USE_ID (+) AND
SHIP_TO_ORG.ADDRESS_ID = SHIP_TO_ADDR.ADDRESS_ID (+) AND 
L.DELIVER_TO_ORG_ID = DELIVERORG.SITE_USE_ID (+) AND
L.INVOICE_TO_ORG_ID = BILLORG.SITE_USE_ID (+) AND 
BILLORG.ADDRESS_ID = BILL_TO_ADDR.ADDRESS_ID (+) AND
L.SHIP_TO_CONTACT_ID = SHIPCONT.CONTACT_ID (+) AND
L.DELIVER_TO_CONTACT_ID = DELIVERCONT.CONTACT_ID (+) AND
L.INVOICE_TO_CONTACT_ID = BILLCONT.CONTACT_ID (+) AND
L.REFERENCE_HEADER_ID = H1.HEADER_ID(+) AND
L1.LINE_ID (+) = L.REFERENCE_LINE_ID AND
CUST_ITEM.CUSTOMER_ITEM_ID (+) = L.ORDERED_ITEM_ID AND
L.LINE_TYPE_ID = LTT.TRANSACTION_TYPE_ID (+) AND
LTT.LANGUAGE(+) = USERENV('LANG') AND
L.SHIP_SET_ID = OSET.SET_ID (+) AND
L.HEADER_ID = OSET.HEADER_ID(+) AND
L.ARRIVAL_SET_ID = ASET.SET_ID (+) AND
L.HEADER_ID = ASET.HEADER_ID(+) AND
L.PRICE_LIST_ID = PL.LIST_HEADER_ID (+) AND
ARL.LOOKUP_TYPE(+) ='TAX_CONTROL_FLAG' AND
ARL.LOOKUP_CODE (+) = L.TAX_EXEMPT_REASON_CODE AND
OAB.AGREEMENT_ID(+) = L.AGREEMENT_ID AND
OAB.LANGUAGE(+) = USERENV('LANG') AND
L.ACCOUNTING_RULE_ID = ACCRULE.RULE_ID (+) AND 
L.INVOICING_RULE_ID = INVRULE.RULE_ID (+) AND 
OELKUPTAX.LOOKUP_CODE(+) = L.TAX_POINT_CODE AND
OELKUPTAX.LOOKUP_TYPE (+) = 'TAX_POINT' AND
L.PAYMENT_TERM_ID = TERM.TERM_ID (+) AND 
TERM.LANGUAGE(+) = USERENV('LANG') AND
FNDLKUP.LOOKUP_TYPE(+) = 'DEMAND_CLASS' AND
FNDLKUP.LOOKUP_CODE(+) = L.DEMAND_CLASS_CODE AND
OELKUP.LOOKUP_TYPE(+) = 'SHIPMENT_PRIORITY' AND
OELKUP.LOOKUP_CODE(+) = L.SHIPMENT_PRIORITY_CODE AND
OESLKUP.LOOKUP_TYPE(+) = 'SHIP_METHOD' AND
OESLKUP.LOOKUP_CODE(+) = L.SHIPPING_METHOD_CODE AND
OELKUP2.LOOKUP_TYPE(+) = 'FREIGHT_TERMS' AND
OELKUP2.LOOKUP_CODE(+) = L.FREIGHT_TERMS_CODE AND
FOB.LOOKUP_CODE(+) = L.FOB_POINT_CODE AND
FOB.LOOKUP_TYPE(+) = 'FOB' AND
FRT.FREIGHT_CODE (+) = L.FREIGHT_CARRIER_CODE AND
FRT.ORGANIZATION_ID (+) = L.ORG_ID AND
RAS.SALESREP_ID(+)  = L.SALESREP_ID AND
RAS.ORG_ID (+) = L.ORG_ID AND
LUP.LOOKUP_TYPE(+) = 'CREDIT_MEMO_REASON' AND
LUP.LOOKUP_CODE(+) = L.RETURN_REASON_CODE AND
PROJECT.PROJECT_ID (+) = L.PROJECT_ID AND
PROJECT.ORG_ID (+) = L.ORG_ID AND
TASK.TASK_ID (+) = L.TASK_ID AND
RCTL.CUSTOMER_TRX_LINE_ID (+) = L.CREDIT_INVOICE_LINE_ID AND
RCTL.ORG_ID(+) = L.ORG_ID AND
RCT.CUSTOMER_TRX_ID (+) = RCTL.CUSTOMER_TRX_ID AND
RCT.ORG_ID(+) = RCTL.ORG_ID AND
FULFILL.LINE_ID (+) = L.LINE_ID AND
FULFILL.SET_ID = FUL.SET_ID(+) AND
FUL.SET_TYPE (+) = 'FULFILLMENT_SET'
/
  
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_SALES_CREDITS_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_SALES_CREDITS_VW (
HEADER_ID,
LINE_ID,
ORIG_SYS_CREDIT_REF,
ORDER_SOURCE,
QUOTA_FLAG,
PERCENT,
SALESREP,
SALES_CREDIT_TYPE,
CHANGE_REQUEST_CODE,
CHANGE_SEQUENCE,
OPERATION_CODE,
STATUS_FLAG,
GROUP_NAME,
SALES_GROUP_UPDATED_FLAG
)
AS
SELECT 
C.HEADER_ID,
C.LINE_ID,
C.ORIG_SYS_CREDIT_REF,
SRC.NAME ORDER_SOURCE,
C.QUOTA_FLAG,
C.PERCENT,
SALES.NAME  SALESREP,
CREDIT_TYPES.NAME SALES_CREDIT_TYPE,
NULL CHANGE_REQUEST_CODE,
NULL CHANGE_SEQUENCE,
NULL OPERATION_CODE,
NULL STATUS_FLAG,
(SELECT group_name FROM jtf_rs_defresgroups_vl where group_id =C.SALES_GROUP_ID),
C.SALES_GROUP_UPDATED_FLAG
FROM 
OE_SALES_CREDITS C,
OE_ORDER_HEADERS_ALL H,
OE_ORDER_LINES_ALL L,
OE_ORDER_SOURCES SRC,
RA_SALESREPS_ALL SALES,
OE_SALES_CREDIT_TYPES  CREDIT_TYPES
WHERE
C.HEADER_ID = H.HEADER_ID AND
L.HEADER_ID = H.HEADER_ID AND
C.LINE_ID = L.LINE_ID AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID  AND
SALES.SALESREP_ID = C.SALESREP_ID AND
SALES.ORG_ID (+) = H.ORG_ID AND
CREDIT_TYPES.SALES_CREDIT_TYPE_ID (+) = C.SALES_CREDIT_TYPE_ID
/
  
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_HEADER_SALES_CREDIT_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_HEADER_SALES_CREDIT_VW (
HEADER_ID,
ORIG_SYS_CREDIT_REF,
ORDER_SOURCE,
QUOTA_FLAG,
PERCENT,
SALESREP,
SALES_CREDIT_TYPE,
CHANGE_REQUEST_CODE,
CHANGE_SEQUENCE,
OPERATION_CODE,
STATUS_FLAG,
GROUP_NAME,
SALES_GROUP_UPDATED_FLAG
)
AS
SELECT 
C.HEADER_ID,
C.ORIG_SYS_CREDIT_REF,
SRC.NAME ORDER_SOURCE,
C.QUOTA_FLAG,
C.PERCENT,
SALES.NAME  SALESREP,
CREDIT_TYPES.NAME SALES_CREDIT_TYPE,
NULL CHANGE_REQUEST_CODE,
NULL CHANGE_SEQUENCE,
NULL OPERATION_CODE,
NULL STATUS_FLAG,
(SELECT group_name FROM jtf_rs_defresgroups_vl where group_id =C.SALES_GROUP_ID),
C.SALES_GROUP_UPDATED_FLAG
FROM 
OE_SALES_CREDITS C,
OE_ORDER_HEADERS_ALL H,
OE_ORDER_SOURCES SRC,
RA_SALESREPS_ALL SALES,
OE_SALES_CREDIT_TYPES  CREDIT_TYPES
WHERE
C.HEADER_ID = H.HEADER_ID AND
C.LINE_ID IS NULL AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID  AND
SALES.SALESREP_ID = C.SALESREP_ID AND
SALES.ORG_ID (+) = H.ORG_ID AND
CREDIT_TYPES.SALES_CREDIT_TYPE_ID (+) = C.SALES_CREDIT_TYPE_ID
/

SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_PRICE_ADJ_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_PRICE_ADJ_VW (
HEADER_ID, 
LINE_ID,
ADJUSTED_AMOUNT,
ADJUSTED_AMOUNT_PER_PQTY,
APPLIED_FLAG ,
ARITHMETIC_OPERATOR ,
AUTOMATIC_FLAG ,
CHANGE_REASON_CODE , 
CHANGE_REASON_TEXT ,
CHANGE_REQUEST_CODE,
CHANGE_SEQUENCE,
CHARGE_TYPE_CODE , 
CHARGE_SUBTYPE_CODE ,
COST_TYPE,
COST_UNIT_AMOUNT,
COST_QUANTITY,
COST_AMOUNT,
COST_CURRENCY_CODE,
FREIGHT_CODE,
CREDIT_OR_CHARGE_FLAG ,
DISCOUNT_NAME,
LINE_DISCOUNT_NAME,
ESTIMATED_FLAG , 
INVOICED_FLAG ,
INC_IN_SALES_PERFORMANCE ,
INCLUDE_ON_RETURNS_FLAG ,
LIST_NAME ,
LIST_LINE_TYPE_CODE ,
LIST_LINE_NUMBER, 
MODIFIED_FROM , 
MODIFIED_TO ,
MODIFIER_MECHANISM_TYPE_CODE ,  
OPERAND ,
OPERAND_PER_PQTY,
OPERATION_CODE,
ORDER_SOURCE,
ORIG_SYS_DISCOUNT_REF ,
PARENT_ADJUSTMENT_NAME,
PRICING_PHASE,
PERCENT ,
TAX_CODE ,
UPDATE_ALLOWED ,
UPDATED_FLAG ,
VERSION_NUMBER,
STATUS_FLAG
)
AS
SELECT 
ADJ.HEADER_ID, 
ADJ.LINE_ID,
ADJ.ADJUSTED_AMOUNT,
ADJ.ADJUSTED_AMOUNT_PER_PQTY,
ADJ.APPLIED_FLAG ,
ADJ.ARITHMETIC_OPERATOR ,
ADJ.AUTOMATIC_FLAG ,
ADJ.CHANGE_REASON_CODE , 
ADJ.CHANGE_REASON_TEXT ,
NULL CHANGE_REQUEST_CODE,
NULL CHANGE_SEQUENCE,
ADJ.CHARGE_TYPE_CODE , 
ADJ.CHARGE_SUBTYPE_CODE ,
COST_TYPE.FREIGHT_COST_TYPE_CODE  COST_TYPE,
COST.UNIT_AMOUNT COST_UNIT_AMOUNT,
COST.QUANTITY COST_QUANTITY,
COST.TOTAL_AMOUNT COST_AMOUNT,
COST.CURRENCY_CODE  COST_CURRENCY_CODE,
COST.FREIGHT_CODE,
ADJ.CREDIT_OR_CHARGE_FLAG ,
DISCOUNT.NAME  DISCOUNT_NAME,
DISCOUNT_LINE.NAME LINE_DISCOUNT_NAME,
ADJ.ESTIMATED_FLAG , 
ADJ.INVOICED_FLAG ,
ADJ.INC_IN_SALES_PERFORMANCE ,
ADJ.INCLUDE_ON_RETURNS_FLAG ,
QPLH.NAME LIST_NAME ,
ADJ.LIST_LINE_TYPE_CODE ,
ADJ.LIST_LINE_NO LIST_LINE_NUMBER, 
ADJ.MODIFIED_FROM , 
ADJ.MODIFIED_TO ,
ADJ.MODIFIER_MECHANISM_TYPE_CODE ,  
ADJ.OPERAND ,
ADJ.OPERAND_PER_PQTY,
NULL OPERATION_CODE,
SRC.NAME ORDER_SOURCE,
ADJ.ORIG_SYS_DISCOUNT_REF ,
PQPH.NAME PARENT_ADJUSTMENT_NAME,
PHASE.NAME PRICING_PHASE,
ADJ.PERCENT ,
ADJ.TAX_CODE ,
ADJ.UPDATE_ALLOWED ,
ADJ.UPDATED_FLAG ,
NULL VERSION_NUMBER,
NULL STATUS_FLAG
FROM 
OE_PRICE_ADJUSTMENTS ADJ , 
QP_PRICING_PHASES PHASE,
QP_LIST_HEADERS_TL QPLH ,
OE_ORDER_HEADERS_ALL H,
OE_ORDER_LINES_ALL L,
WSH_FREIGHT_COSTS  COST,
WSH_FREIGHT_COST_TYPES  COST_TYPE,
SO_DISCOUNTS  DISCOUNT,
SO_DISCOUNT_LINES_115  LINE_DISCOUNT,
SO_DISCOUNTS  DISCOUNT_LINE,
OE_ORDER_SOURCES SRC,
QP_LIST_HEADERS_TL PQPH ,
OE_PRICE_ADJUSTMENTS ADJP 
WHERE 
ADJ.LIST_HEADER_ID = QPLH.LIST_HEADER_ID(+) AND
QPLH.LANGUAGE(+) = USERENV('LANG') AND
ADJ.PRICING_PHASE_ID = PHASE.PRICING_PHASE_ID(+) AND
ADJ.HEADER_ID = H.HEADER_ID AND
L.HEADER_ID = H.HEADER_ID AND
ADJ.LINE_ID = L.LINE_ID AND
COST.FREIGHT_COST_ID (+) = ADJ.COST_ID AND
COST_TYPE.FREIGHT_COST_TYPE_ID (+) = COST.FREIGHT_COST_TYPE_ID AND
DISCOUNT.DISCOUNT_ID(+) = ADJ.DISCOUNT_ID AND
LINE_DISCOUNT.DISCOUNT_LINE_ID (+) = ADJ.DISCOUNT_LINE_ID AND
LINE_DISCOUNT.DISCOUNT_ID = DISCOUNT_LINE.DISCOUNT_ID (+) AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID AND
ADJP.LIST_HEADER_ID = PQPH.LIST_HEADER_ID(+) AND
PQPH.LANGUAGE(+) = USERENV('LANG') AND
ADJP.PRICE_ADJUSTMENT_ID (+) = ADJ.PARENT_ADJUSTMENT_ID
/
  
SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_HEADER_PRICE_ADJ_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_HEADER_PRICE_ADJ_VW (
HEADER_ID, 
ADJUSTED_AMOUNT,
ADJUSTED_AMOUNT_PER_PQTY,
APPLIED_FLAG ,
ARITHMETIC_OPERATOR ,
AUTOMATIC_FLAG ,
CHANGE_REASON_CODE , 
CHANGE_REASON_TEXT ,
CHANGE_REQUEST_CODE,
CHANGE_SEQUENCE,
CHARGE_TYPE_CODE , 
CHARGE_SUBTYPE_CODE ,
COST_TYPE,
COST_UNIT_AMOUNT,
COST_QUANTITY,
COST_AMOUNT,
COST_CURRENCY_CODE,
FREIGHT_CODE,
CREDIT_OR_CHARGE_FLAG ,
DISCOUNT_NAME,
LINE_DISCOUNT_NAME,
ESTIMATED_FLAG , 
INVOICED_FLAG ,
INC_IN_SALES_PERFORMANCE ,
INCLUDE_ON_RETURNS_FLAG ,
LIST_NAME ,
LIST_LINE_TYPE_CODE ,
LIST_LINE_NUMBER, 
MODIFIED_FROM , 
MODIFIED_TO ,
MODIFIER_MECHANISM_TYPE_CODE ,  
OPERAND ,
OPERAND_PER_PQTY,
OPERATION_CODE,
ORDER_SOURCE,
ORIG_SYS_DISCOUNT_REF ,
PARENT_ADJUSTMENT_NAME,
PRICING_PHASE,
PERCENT ,
TAX_CODE ,
UPDATE_ALLOWED ,
UPDATED_FLAG ,
VERSION_NUMBER,
STATUS_FLAG
)
AS
SELECT 
ADJ.HEADER_ID, 
ADJ.ADJUSTED_AMOUNT,
ADJ.ADJUSTED_AMOUNT_PER_PQTY,
ADJ.APPLIED_FLAG ,
ADJ.ARITHMETIC_OPERATOR ,
ADJ.AUTOMATIC_FLAG ,
ADJ.CHANGE_REASON_CODE , 
ADJ.CHANGE_REASON_TEXT ,
NULL CHANGE_REQUEST_CODE,
NULL CHANGE_SEQUENCE,
ADJ.CHARGE_TYPE_CODE , 
ADJ.CHARGE_SUBTYPE_CODE ,
COST_TYPE.FREIGHT_COST_TYPE_CODE  COST_TYPE,
COST.UNIT_AMOUNT COST_UNIT_AMOUNT,
COST.QUANTITY COST_QUANTITY,
COST.TOTAL_AMOUNT COST_AMOUNT,
COST.CURRENCY_CODE  COST_CURRENCY_CODE,
COST.FREIGHT_CODE,
ADJ.CREDIT_OR_CHARGE_FLAG ,
DISCOUNT.NAME  DISCOUNT_NAME,
DISCOUNT_LINE.NAME LINE_DISCOUNT_NAME,
ADJ.ESTIMATED_FLAG , 
ADJ.INVOICED_FLAG ,
ADJ.INC_IN_SALES_PERFORMANCE ,
ADJ.INCLUDE_ON_RETURNS_FLAG ,
QPLH.NAME LIST_NAME ,
ADJ.LIST_LINE_TYPE_CODE ,
ADJ.LIST_LINE_NO LIST_LINE_NUMBER, 
ADJ.MODIFIED_FROM , 
ADJ.MODIFIED_TO ,
ADJ.MODIFIER_MECHANISM_TYPE_CODE ,  
ADJ.OPERAND ,
ADJ.OPERAND_PER_PQTY,
NULL OPERATION_CODE,
SRC.NAME ORDER_SOURCE,
ADJ.ORIG_SYS_DISCOUNT_REF ,
PQPH.NAME PARENT_ADJUSTMENT_NAME,
PHASE.NAME PRICING_PHASE,
ADJ.PERCENT ,
ADJ.TAX_CODE ,
ADJ.UPDATE_ALLOWED ,
ADJ.UPDATED_FLAG ,
NULL VERSION_NUMBER,
NULL STATUS_FLAG
FROM 
OE_PRICE_ADJUSTMENTS ADJ , 
QP_PRICING_PHASES PHASE,
QP_LIST_HEADERS_TL QPLH ,
OE_ORDER_HEADERS_ALL H,
WSH_FREIGHT_COSTS  COST,
WSH_FREIGHT_COST_TYPES  COST_TYPE,
SO_DISCOUNTS  DISCOUNT,
SO_DISCOUNT_LINES_115  LINE_DISCOUNT,
SO_DISCOUNTS  DISCOUNT_LINE,
OE_ORDER_SOURCES SRC,
QP_LIST_HEADERS_TL PQPH ,
OE_PRICE_ADJUSTMENTS ADJP 
WHERE 
ADJ.LIST_HEADER_ID = QPLH.LIST_HEADER_ID(+) AND
QPLH.LANGUAGE(+) = USERENV('LANG') AND
ADJ.PRICING_PHASE_ID = PHASE.PRICING_PHASE_ID(+) AND
ADJ.HEADER_ID = H.HEADER_ID AND
ADJ.LINE_ID IS NULL AND
COST.FREIGHT_COST_ID (+) = ADJ.COST_ID AND
COST_TYPE.FREIGHT_COST_TYPE_ID (+) = COST.FREIGHT_COST_TYPE_ID AND
DISCOUNT.DISCOUNT_ID(+) = ADJ.DISCOUNT_ID AND
LINE_DISCOUNT.DISCOUNT_LINE_ID (+) = ADJ.DISCOUNT_LINE_ID AND
LINE_DISCOUNT.DISCOUNT_ID = DISCOUNT_LINE.DISCOUNT_ID (+) AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID AND
ADJP.LIST_HEADER_ID = PQPH.LIST_HEADER_ID(+) AND
PQPH.LANGUAGE(+) = USERENV('LANG') AND
ADJP.PRICE_ADJUSTMENT_ID (+) = ADJ.PARENT_ADJUSTMENT_ID
/

SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_PRICE_ATTRIBS_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_PRICE_ATTRIBS_VW 
(
HEADER_ID ,
LINE_ID , 
ORIG_SYS_ATTS_REF,
ORDER_SOURCE,
FLEX_TITLE,
PRICING_CONTEXT,
CHANGE_REQUEST_CODE,
CHANGE_SEQUENCE,
OPERATION_CODE,
STATUS_FLAG	
)
AS
SELECT 
P.HEADER_ID ,
P.LINE_ID , 
P.ORIG_SYS_ATTS_REF,
SRC.NAME ORDER_SOURCE,
P.FLEX_TITLE,
P.PRICING_CONTEXT,
NULL CHANGE_REQUEST_CODE,
NULL CHANGE_SEQUENCE,
NULL OPERATION_CODE,
NULL STATUS_FLAG
FROM 
OE_ORDER_PRICE_ATTRIBS P,
OE_ORDER_HEADERS_ALL H,
OE_ORDER_LINES_ALL L,
OE_ORDER_SOURCES SRC
WHERE
P.HEADER_ID = H.HEADER_ID AND
L.HEADER_ID = H.HEADER_ID AND
P.LINE_ID = L.LINE_ID AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID 
/

SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_HEADER_PRICE_ATTRB_VW
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_HEADER_PRICE_ATTRB_VW
(
HEADER_ID ,
ORIG_SYS_ATTS_REF,
ORDER_SOURCE,
FLEX_TITLE,
PRICING_CONTEXT,
CHANGE_REQUEST_CODE,
CHANGE_SEQUENCE,
OPERATION_CODE,
STATUS_FLAG
)
AS
SELECT 
P.HEADER_ID ,
P.ORIG_SYS_ATTS_REF,
SRC.NAME ORDER_SOURCE,
P.FLEX_TITLE,
P.PRICING_CONTEXT,
NULL CHANGE_REQUEST_CODE,
NULL CHANGE_SEQUENCE,
NULL OPERATION_CODE,
NULL STATUS_FLAG
FROM 
OE_ORDER_PRICE_ATTRIBS P,
OE_ORDER_HEADERS_ALL H,
OE_ORDER_SOURCES SRC
WHERE
P.HEADER_ID = H.HEADER_ID AND
P.LINE_ID IS NULL AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID 
/

SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_OE_RESERVTNS_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_OE_RESERVTNS_VW (
HEADER_ID,
LINE_ID,
ORDER_SOURCE,
REVISION,
ITEM_CODE,
SUBINVENTORY_CODE,
LOCATOR,
LOT_NUMBER,
QUANTITY,
ORIG_SYS_RESERVATION_REF,
CHANGE_SEQUENCE,
OPERATION_CODE
)
AS
SELECT 
L.HEADER_ID HEADER_ID,
R.DEMAND_SOURCE_LINE_ID LINE_ID,
SRC.NAME ORDER_SOURCE,
R.REVISION,
ITEM.CONCATENATED_SEGMENTS ITEM_CODE,
R.SUBINVENTORY_CODE,
LOC.CONCATENATED_SEGMENTS LOCATOR,
R.LOT_NUMBER,
R.RESERVATION_QUANTITY QUANTITY,
NULL ORIG_SYS_RESERVATION_REF,
NULL CHANGE_SEQUENCE,
NULL OPERATION_CODE
FROM 
MTL_RESERVATIONS R,
OE_ORDER_HEADERS_ALL H,
OE_ORDER_LINES_ALL L,
OE_ORDER_SOURCES SRC,
MTL_SYSTEM_ITEMS_B_KFV ITEM,
MTL_ITEM_LOCATIONS_KFV LOC
WHERE
L.HEADER_ID = H.HEADER_ID AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID  AND
R.DEMAND_SOURCE_TYPE_ID = 2 AND
R.DEMAND_SOURCE_LINE_ID = L.LINE_ID AND
ITEM.INVENTORY_ITEM_ID (+) = R.INVENTORY_ITEM_ID AND
ITEM.ORGANIZATION_ID (+) = R.ORGANIZATION_ID AND
LOC.INVENTORY_LOCATION_ID(+) = R.LOCATOR_ID AND
LOC.ORGANIZATION_ID (+) = R.ORGANIZATION_ID
/

SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_LOTSERIALS_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_LOTSERIALS_VW 
(
ORDER_SOURCE,
ORIG_SYS_LOTSERIAL_REF,
LOT_NUMBER ,
LINE_ID,
FROM_SERIAL_NUMBER,     
TO_SERIAL_NUMBER,       
QUANTITY,
CHANGE_REQUEST_CODE,
CHANGE_SEQUENCE,
OPERATION_CODE,
STATUS_FLAG
)
AS
SELECT 
SRC.NAME ORDER_SOURCE,
LOT.ORIG_SYS_LOTSERIAL_REF,
LOT.LOT_NUMBER ,
LOT.LINE_ID,
LOT.FROM_SERIAL_NUMBER,     
LOT.TO_SERIAL_NUMBER,       
LOT.QUANTITY,
NULL CHANGE_REQUEST_CODE,
NULL CHANGE_SEQUENCE,
NULL OPERATION_CODE,
NULL STATUS_FLAG
FROM 
OE_LOT_SERIAL_NUMBERS LOT,
OE_ORDER_HEADERS_ALL H,
OE_ORDER_LINES_ALL L,
OE_ORDER_SOURCES SRC
WHERE
L.HEADER_ID = H.HEADER_ID AND
LOT.LINE_ID = L.LINE_ID AND
SRC.ORDER_SOURCE_ID (+) = H.ORDER_SOURCE_ID
/

SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_OE_ACTIONS_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_OE_ACTIONS_VW (
HEADER_ID,
ORDER_SOURCE,
CHANGE_SEQUENCE,
HOLD_NAME,
HOLD_TYPE_CODE,
HOLD_UNTIL_DATE,
RELEASE_REASON_CODE,
COMMENTS,
CONTEXT,
OPERATION_CODE,
STATUS_FLAG
)
AS
SELECT 
H.HEADER_ID,
NULL ORDER_SOURCE,
NULL CHANGE_SEQUENCE,
NULL HOLD_NAME,
NULL HOLD_TYPE_CODE,
NULL HOLD_UNTIL_DATE,
NULL RELEASE_REASON_CODE,
NULL COMMENTS,
NULL CONTEXT,
NULL OPERATION_CODE,
NULL STATUS_FLAG
FROM 
OE_ORDER_HEADERS_ALL H
/

/*----------------------------------------------------------------------*/
--      Create View WM_OE_LINE_ACTIONS_VW 
/*----------------------------------------------------------------------*/
CREATE OR REPLACE VIEW WM_OE_LINE_ACTIONS_VW (
HEADER_ID,
LINE_ID,
ORDER_SOURCE,
CHANGE_SEQUENCE,
HOLD_NAME,
HOLD_TYPE_CODE,
HOLD_UNTIL_DATE,
RELEASE_REASON_CODE,
COMMENTS,
CONTEXT,
OPERATION_CODE,
STATUS_FLAG
)
AS
SELECT 
H.HEADER_ID,
L.LINE_ID,
NULL ORDER_SOURCE,
NULL CHANGE_SEQUENCE,
NULL HOLD_NAME,
NULL HOLD_TYPE_CODE,
NULL HOLD_UNTIL_DATE,
NULL RELEASE_REASON_CODE,
NULL COMMENTS,
NULL CONTEXT,
NULL OPERATION_CODE,
NULL STATUS_FLAG
FROM 
OE_ORDER_HEADERS_ALL H,
OE_ORDER_LINES_ALL L
WHERE
L.HEADER_ID = H.HEADER_ID
/

SHOW ERRORS

/*----------------------------------------------------------------------*/
--      Create View WM_ORDER_HEADER_QRY_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ORDER_HEADER_QRY_VW ( 
WEB_TRANSACTION_ID,  
DOCUMENT_TYPE,  
DOCUMENT_STATUS,
HEADER_ID,
FLOW_STATUS_CODE,
ORDER_TYPE,
ORGANIZATION_NAME,
ORDER_NUMBER,
VERSION_NUMBER,
ORDERED_DATE, 
ORDER_CATEGORY,
ORDER_SOURCE,
PRICE_LIST,
ORIG_SYS_DOCUMENT_REF, 
CONVERSION_RATE, 
CONVERSION_RATE_DATE, 
CONVERSION_TYPE_CODE, 
CONVERSION_TYPE,
TRANSACTIONAL_CURR_CODE, 
SALESREP,
SALES_CHANNEL_CODE,
SALES_CHANNEL,
RETURN_REASON_CODE,
RETURN_REASON,
TAX_POINT_CODE, 
TAX_POINT,
TAX_EXEMPT_FLAG, 
TAX_EXEMPT_NUMBER, 
TAX_EXEMPT_REASON_CODE, 
TAX_EXEMPT_REASON,
AGREEMENT,
INVOICING_RULE,
ACCOUNTING_RULE, 
PAYMENT_TERM,
DEMAND_CLASS_CODE,  
DEMAND_CLASS,
SHIPMENT_PRIORITY_CODE,
SHIPMENT_PRIORITY,
SHIPMENT_PRIORITY_CODE_INT,
SHIPPING_METHOD_CODE, 
SHIPPING_METHOD,
FREIGHT_CARRIER_CODE,
FREIGHT_CARRIER, 
FREIGHT_TERMS_CODE,
FREIGHT_TERMS,
FOB_POINT_CODE,  
FOB_POINT,
PARTIAL_SHIPMENTS_ALLOWED, 
SHIP_TOLERANCE_ABOVE, 
SHIP_TOLERANCE_BELOW,
SHIPPING_INSTRUCTIONS, 
PACKING_INSTRUCTIONS,
ORDER_DATE_TYPE_CODE,
EARLIEST_SCHEDULE_LIMIT, 
LATEST_SCHEDULE_LIMIT,
CUST_PO_NUMBER,
PAYMENT_TYPE_CODE, 
PAYMENT_AMOUNT,
CHECK_NUMBER, 
CREDIT_CARD_CODE, 
CREDIT_CARD_HOLDER_NAME, 
CREDIT_CARD_NUMBER, 
CREDIT_CARD_EXPIRATION_DATE, 
CREDIT_CARD_APPROVAL_CODE,
SOLD_FROM_ORG, 
SOLD_TO_ORG,
SHIP_FROM_ORG,
SHIP_TO_ORG,
SHIP_TO_ADDRESS1,
SHIP_TO_ADDRESS2,
SHIP_TO_ADDRESS3,
SHIP_TO_ADDRESS4,
SHIP_TO_CITY,
SHIP_TO_COUNTY,
SHIP_TO_STATE,
SHIP_TO_POSTAL_CODE,
SHIP_TO_PROVINCE,
SHIP_TO_COUNTRY,
SHIP_TO_CUSTOMER_NUMBER,
SHIP_TO_CUSTOMER,
INVOICE_TO_ORG, 
INVOICE_ADDRESS1, 
INVOICE_ADDRESS2, 
INVOICE_ADDRESS3,
INVOICE_ADDRESS4,
INVOICE_CITY,
INVOICE_COUNTY,
INVOICE_STATE,
INVOICE_POSTAL_CODE,
INVOICE_PROVINCE_INT,
INVOICE_COUNTRY,
INVOICE_CUSTOMER_NUMBER,
INVOICE_CUSTOMER,
DELIVER_TO_ORG, 
DELIVER_TO_CONTACT,
DELIVER_TO_CUSTOMER_NUMBER,
DELIVER_TO_CUSTOMER,
SOLD_TO_CONTACT,
SHIP_TO_CONTACT_FIRST_NAME,
SHIP_TO_CONTACT_LAST_NAME,
SHIP_TO_CONTACT,
INVOICE_TO_CONTACT_FIRST_NAME,
INVOICE_TO_CONTACT_LAST_NAME,
INVOICE_TO_CONTACT,
CREDIT_CARD_APPROVAL_DATE,
BOOKED_FLAG, 
CANCELLED_FLAG,
CHANGE_SEQUENCE,
CUSTOMER_NUMBER, 
CUSTOMER_NAME,
CHANGE_REQUEST_CODE,
ORDERED_BY_CONTACT_FIRST_NAME,
ORDERED_BY_CONTACT_LAST_NAME,
HEADER_PO_CONTEXT,
PO_REVISION_DATE,
CHANGE_REASON,
CHANGE_COMMENT,
OPERATION_CODE,
CLOSED_FLAG,
REJECTED_FLAG,
READY_FLAG,
STATUS_FLAG,
FORCE_APPLY_FLAG,
TRANSACTION_PHASE_CODE,
QUOTE_NUMBER,
QUOTE_DATE,
USER_STATUS_CODE,
DRAFT_SUBMITTED_FLAG,
INVOICE_ADDRESSEE,
INVOICE_IDENTIFY_ADDRESS_FLAG,
SHIP_TO_ADDRESSEE,
SHIP_TO_IDENTIFY_ADDRESS_FLAG
)
AS
SELECT
NULL,
'SALESORDER',
'QUERY',
OEH.HEADER_ID,
OEH.FLOW_STATUS_CODE,
OT.NAME  ORDER_TYPE,
ORG.NAME ORGANIZATION_NAME,
OEH.ORDER_NUMBER,
OEH.VERSION_NUMBER,
OEH.ORDERED_DATE, 
OECAT.MEANING ORDER_CATEGORY,
SRC.NAME  ORDER_SOURCE,
PL.NAME PRICE_LIST,
OEH.ORIG_SYS_DOCUMENT_REF, 
OEH.CONVERSION_RATE, 
OEH.CONVERSION_RATE_DATE, 
OEH.CONVERSION_TYPE_CODE, 
GLCTYP.USER_CONVERSION_TYPE  CONVERSION_TYPE,
OEH.TRANSACTIONAL_CURR_CODE, 
RAS.NAME SALESREP,
OEH.SALES_CHANNEL_CODE,
OESAL.MEANING SALES_CHANNEL,
OEH.RETURN_REASON_CODE,
LUP.MEANING RETURN_REASON,
OEH.TAX_POINT_CODE, 
OELKUPTAX.MEANING TAX_POINT,
OEH.TAX_EXEMPT_FLAG, 
OEH.TAX_EXEMPT_NUMBER, 
OEH.TAX_EXEMPT_REASON_CODE, 
ARL.MEANING  TAX_EXEMPT_REASON,
OAB.NAME AGREEMENT,
INVRULE.NAME INVOICING_RULE,
ACCRULE.NAME ACCOUNTING_RULE, 
TERMTL.NAME PAYMENT_TERM,
OEH.DEMAND_CLASS_CODE,  
FNDLKUP.MEANING DEMAND_CLASS,
OEH.SHIPMENT_PRIORITY_CODE,
OELKUP.MEANING SHIPMENT_PRIORITY,
OEH.SHIPMENT_PRIORITY_CODE SHIPMENT_PRIORITY_CODE_INT,
OEH.SHIPPING_METHOD_CODE, 
OESLKUP.MEANING  SHIPPING_METHOD,
OEH.FREIGHT_CARRIER_CODE,
FRT.DESCRIPTION FREIGHT_CARRIER, 
OEH.FREIGHT_TERMS_CODE,
OELKUP2.MEANING  FREIGHT_TERMS,
OEH.FOB_POINT_CODE,  
FOB.MEANING FOB_POINT,
OEH.PARTIAL_SHIPMENTS_ALLOWED, 
OEH.SHIP_TOLERANCE_ABOVE, 
OEH.SHIP_TOLERANCE_BELOW,
OEH.SHIPPING_INSTRUCTIONS, 
OEH.PACKING_INSTRUCTIONS,
OEH.ORDER_DATE_TYPE_CODE,
OEH.EARLIEST_SCHEDULE_LIMIT, 
OEH.LATEST_SCHEDULE_LIMIT,
OEH.CUST_PO_NUMBER,
OEH.PAYMENT_TYPE_CODE, 
OEH.PAYMENT_AMOUNT,
OEH.CHECK_NUMBER, 
OEH.CREDIT_CARD_CODE, 
OEH.CREDIT_CARD_HOLDER_NAME, 
OEH.CREDIT_CARD_NUMBER, 
OEH.CREDIT_CARD_EXPIRATION_DATE, 
OEH.CREDIT_CARD_APPROVAL_CODE,
SOLD_FROM_ORG.NAME SOLD_FROM_ORG, 
SUBSTRB(PARTY.PARTY_NAME,1,50) SOLD_TO_ORG,
SHIP_FROM_ORG.NAME SHIP_FROM_ORG,
SHIP_TO_ORG.LOCATION SHIP_TO_ORG,
SHIP_TO_ADDR.ADDRESS1 SHIP_TO_ADDRESS1,
SHIP_TO_ADDR.ADDRESS2 SHIP_TO_ADDRESS2,
SHIP_TO_ADDR.ADDRESS3 SHIP_TO_ADDRESS3,
SHIP_TO_ADDR.ADDRESS4 SHIP_TO_ADDRESS4,
SHIP_TO_ADDR.CITY  SHIP_TO_CITY,
SHIP_TO_ADDR.COUNTY SHIP_TO_COUNTY,
SHIP_TO_ADDR.STATE SHIP_TO_STATE,
SHIP_TO_ADDR.POSTAL_CODE SHIP_TO_POSTAL_CODE,
SHIP_TO_ADDR.PROVINCE SHIP_TO_PROVINCE,
SHIP_TO_ADDR.COUNTRY SHIP_TO_COUNTRY,
SHIP_TO_CUST.CUSTOMER_NUMBER SHIP_TO_CUSTOMER_NUMBER,
SHIP_TO_CUST.CUSTOMER_NAME SHIP_TO_CUSTOMER,
BILLORG.LOCATION INVOICE_TO_ORG, 
BILL_TO_ADDR.ADDRESS1 INVOICE_ADDRESS1, 
BILL_TO_ADDR.ADDRESS2 INVOICE_ADDRESS2, 
BILL_TO_ADDR.ADDRESS3 INVOICE_ADDRESS3,
BILL_TO_ADDR.ADDRESS4 INVOICE_ADDRESS4,
BILL_TO_ADDR.CITY  INVOICE_CITY,
BILL_TO_ADDR.COUNTY INVOICE_COUNTY,
BILL_TO_ADDR.STATE INVOICE_STATE,
BILL_TO_ADDR.POSTAL_CODE INVOICE_POSTAL_CODE,
BILL_TO_ADDR.PROVINCE INVOICE_PROVINCE_INT,
BILL_TO_ADDR.COUNTRY INVOICE_COUNTRY,
BILL_TO_CUST.CUSTOMER_NUMBER INVOICE_CUSTOMER_NUMBER,
BILL_TO_CUST.CUSTOMER_NAME INVOICE_CUSTOMER,
DELIVERORG.LOCATION DELIVER_TO_ORG, 
DELIVERCONT.NAME  DELIVER_TO_CONTACT,
DELIVER_TO_CUST.CUSTOMER_NUMBER DELIVER_TO_CUSTOMER_NUMBER,
DELIVER_TO_CUST.CUSTOMER_NAME DELIVER_TO_CUSTOMER,
DECODE(SOLDCONT.LAST_NAME,NULL,NULL,SOLDCONT.LAST_NAME||', ')|| 
DECODE(SOLDCONT.FIRST_NAME,NULL,NULL,SOLDCONT.FIRST_NAME||' ')||
SOLDCONT.TITLE SOLD_TO_CONTACT,
SHIPCONT.FIRST_NAME SHIP_TO_CONTACT_FIRST_NAME,
SHIPCONT.LAST_NAME SHIP_TO_CONTACT_LAST_NAME,
DECODE(SHIPCONT.LAST_NAME,NULL,NULL,SHIPCONT.LAST_NAME||', ')
||DECODE(SHIPCONT.FIRST_NAME,NULL,NULL,SHIPCONT.FIRST_NAME||' ')
||SHIPCONT.TITLE SHIP_TO_CONTACT,
BILLCONT.FIRST_NAME INVOICE_TO_CONTACT_FIRST_NAME,
BILLCONT.LAST_NAME INVOICE_TO_CONTACT_LAST_NAME,
DECODE(BILLCONT.LAST_NAME,NULL,NULL,BILLCONT.LAST_NAME||', ')||
DECODE(BILLCONT.FIRST_NAME,NULL,NULL,BILLCONT.FIRST_NAME||' ')||
BILLCONT.TITLE INVOICE_TO_CONTACT,
OEH.CREDIT_CARD_APPROVAL_DATE,
OEH.BOOKED_FLAG, 
OEH.CANCELLED_FLAG,
OEH.CHANGE_SEQUENCE,
CUST_ACCT.CUSTOMER_NUMBER CUSTOMER_NUMBER, 
CUST_ACCT.CUSTOMER_NAME  CUSTOMER_NAME,
NULL CHANGE_REQUEST_CODE,
NULL ORDERED_BY_CONTACT_FIRST_NAME,
NULL ORDERED_BY_CONTACT_LAST_NAME,
NULL HEADER_PO_CONTEXT,
NULL PO_REVISION_DATE,
NULL CHANGE_REASON,
NULL CHANGE_COMMENT,
NULL OPERATION_CODE,
NULL CLOSED_FLAG,
NULL REJECTED_FLAG,
NULL READY_FLAG,
NULL STATUS_FLAG,
NULL FORCE_APPLY_FLAG,
OEH.TRANSACTION_PHASE_CODE,
OEH.QUOTE_NUMBER,
OEH.QUOTE_DATE,
OEH.USER_STATUS_CODE,
OEH.DRAFT_SUBMITTED_FLAG,
BILL_TO_ADDR.ADDRESSEE		INVOICE_ADDRESSEE,
BILL_TO_ADDR.IDENTIFYING_ADDRESS_FLAG	INVOICE_IDENTIFY_ADDRESS_FLAG,
SHIP_TO_ADDR.ADDRESSEE		SHIP_TO_ADDRESSEE,
SHIP_TO_ADDR.IDENTIFYING_ADDRESS_FLAG	SHIP_TO_IDENTIFY_ADDRESS_FLAG
FROM 
OE_ORDER_HEADERS_ALL OEH,
OE_TRANSACTION_TYPES_TL OT,
HR_ALL_ORGANIZATION_UNITS ORG,
OE_ORDER_SOURCES SRC,
QP_LIST_HEADERS_TL PL, 
FND_CURRENCIES FNDCUR,
RA_SALESREPS_ALL RAS,
FND_LOOKUP_VALUES LUP,
AR_LOOKUPS  ARL,
OE_AGREEMENTS_TL  OAB,
RA_RULES INVRULE, 
RA_RULES ACCRULE, 
RA_TERMS_B TERMB,
RA_TERMS_TL TERMTL,
OE_FND_COMMON_LOOKUPS_V  FNDLKUP,
OE_LOOKUPS   OELKUP,
OE_SHIP_METHODS_V OESLKUP,
GL_DAILY_CONVERSION_TYPES  GLCTYP,
ORG_FREIGHT FRT,
OE_LOOKUPS  OELKUP2,
AR_LOOKUPS  FOB,
HR_ALL_ORGANIZATION_UNITS SOLD_FROM_ORG,
RA_CUSTOMERS CUST_ACCT,
HZ_PARTIES PARTY,
HR_ALL_ORGANIZATION_UNITS SHIP_FROM_ORG,
RA_SITE_USES_ALL SHIP_TO_ORG,
RA_ADDRESSES_ALL SHIP_TO_ADDR, 
RA_SITE_USES_ALL BILLORG, 
RA_ADDRESSES_ALL BILL_TO_ADDR,
RA_SITE_USES_ALL DELIVERORG, 
OE_CONTACTS_V DELIVERCONT,
RA_ADDRESSES_ALL DELIVER_TO_ADDR,
RA_CUSTOMERS DELIVER_TO_CUST,
RA_CONTACTS SOLDCONT, 
RA_CONTACTS SHIPCONT, 
RA_CONTACTS BILLCONT,  
RA_CUSTOMERS SHIP_TO_CUST,
RA_CUSTOMERS BILL_TO_CUST,
OE_LOOKUPS  OECAT,
OE_LOOKUPS  OESAL,
OE_LOOKUPS OELKUPTAX
WHERE 
OEH.ORDER_TYPE_ID = OT.TRANSACTION_TYPE_ID AND 
OT.LANGUAGE(+) = USERENV('LANG') AND
ORG.ORGANIZATION_ID(+) = OEH.ORG_ID AND
FRT.ORGANIZATION_ID(+) = OEH.ORG_ID AND
FRT.FREIGHT_CODE(+) = OEH.FREIGHT_CARRIER_CODE AND
OEH.ORDER_SOURCE_ID = SRC.ORDER_SOURCE_ID(+) AND
OEH.PRICE_LIST_ID = PL.LIST_HEADER_ID(+) AND 
PL.LANGUAGE(+) = USERENV('LANG') AND
OEH.TRANSACTIONAL_CURR_CODE = FNDCUR.CURRENCY_CODE(+) AND
RAS.SALESREP_ID(+) = OEH.SALESREP_ID AND
RAS.ORG_ID(+) = OEH.ORG_ID AND
LUP.LOOKUP_TYPE(+) = 'CREDIT_MEMO_REASON' AND
LUP.LOOKUP_CODE(+) = OEH.RETURN_REASON_CODE AND
ARL.LOOKUP_TYPE(+) ='TAX_CONTROL_FLAG' AND
ARL.LOOKUP_CODE(+) = OEH.TAX_EXEMPT_REASON_CODE AND
OAB.AGREEMENT_ID(+) = OEH.AGREEMENT_ID AND
OAB.LANGUAGE(+) = USERENV('LANG') AND
OEH.INVOICING_RULE_ID = INVRULE.RULE_ID(+) AND
OEH.ACCOUNTING_RULE_ID = ACCRULE.RULE_ID(+) AND 
OEH.PAYMENT_TERM_ID = TERMB.TERM_ID(+) AND 
TERMB.TERM_ID = TERMTL.TERM_ID(+) AND
TERMTL.LANGUAGE(+) = USERENV('LANG') AND
FNDLKUP.LOOKUP_TYPE(+) = 'DEMAND_CLASS' AND
FNDLKUP.LOOKUP_CODE(+) = OEH.DEMAND_CLASS_CODE AND
OELKUP.LOOKUP_TYPE(+) = 'SHIPMENT_PRIORITY' AND
OELKUP.LOOKUP_CODE(+) = OEH.SHIPMENT_PRIORITY_CODE AND
OESLKUP.LOOKUP_TYPE(+) = 'SHIP_METHOD' AND
OESLKUP.LOOKUP_CODE(+) = OEH.SHIPPING_METHOD_CODE AND
GLCTYP.CONVERSION_TYPE(+) = OEH.CONVERSION_TYPE_CODE AND
OELKUP2.LOOKUP_TYPE(+) = 'FREIGHT_TERMS' AND
OELKUP2.LOOKUP_CODE(+) = OEH.FREIGHT_TERMS_CODE AND
FOB.LOOKUP_CODE(+) = OEH.FOB_POINT_CODE AND
FOB.LOOKUP_TYPE(+) = 'FOB' AND
SOLD_FROM_ORG.ORGANIZATION_ID(+) = OEH.SOLD_FROM_ORG_ID AND
OEH.SOLD_TO_ORG_ID = CUST_ACCT.CUSTOMER_ID(+) AND
CUST_ACCT.PARTY_ID = PARTY.PARTY_ID(+) AND
OEH.SHIP_FROM_ORG_ID = SHIP_FROM_ORG.ORGANIZATION_ID(+) AND 
OEH.SHIP_TO_ORG_ID = SHIP_TO_ORG.SITE_USE_ID(+) AND 
SHIP_TO_ORG.ADDRESS_ID = SHIP_TO_ADDR.ADDRESS_ID(+) AND 
OEH.INVOICE_TO_ORG_ID = BILLORG.SITE_USE_ID(+) AND
BILLORG.ADDRESS_ID = BILL_TO_ADDR.ADDRESS_ID(+) AND
OEH.DELIVER_TO_ORG_ID = DELIVERORG.SITE_USE_ID(+) AND
DELIVERORG.ADDRESS_ID = DELIVER_TO_ADDR.ADDRESS_ID(+) AND
DELIVER_TO_ADDR.CUSTOMER_ID = DELIVER_TO_CUST.CUSTOMER_ID(+) AND
OEH.DELIVER_TO_CONTACT_ID = DELIVERCONT.CONTACT_ID(+) AND
OEH.SOLD_TO_CONTACT_ID = SOLDCONT.CONTACT_ID(+) AND 
OEH.SHIP_TO_CONTACT_ID = SHIPCONT.CONTACT_ID(+) AND 
OEH.INVOICE_TO_CONTACT_ID = BILLCONT.CONTACT_ID(+) AND
SHIP_TO_ADDR.CUSTOMER_ID = SHIP_TO_CUST.CUSTOMER_ID(+) AND
BILL_TO_ADDR.CUSTOMER_ID = BILL_TO_CUST.CUSTOMER_ID(+) AND
OECAT.LOOKUP_CODE(+) = OEH.ORDER_CATEGORY_CODE AND
OECAT.LOOKUP_TYPE(+) = 'ORDER_CATEGORY' AND
OESAL.LOOKUP_CODE(+) = OEH.SALES_CHANNEL_CODE AND
OESAL.LOOKUP_TYPE(+) = 'SALES_CHANNEL' AND
OELKUPTAX.LOOKUP_CODE(+) = OEH.TAX_POINT_CODE AND
OELKUPTAX.LOOKUP_TYPE(+) = 'TAX_POINT' 
/

SHOW ERRORS
