CREATE TRIGGER ORDER_HEADER_TRIG ON ORDER_HEADER after insert as  begin INSERT INTO ORDER_HEADER_BUFFER (ORDER_ID, TRANSACTION_ID, ORDER_DATE, TOTAL_COST, IS_VALID, SENDER_ID, RECEIVER_ID)  SELECT inserted.ORDER_ID, inserted.TRANSACTION_ID, inserted.ORDER_DATE, inserted.TOTAL_COST, inserted.IS_VALID, inserted.SENDER_ID, inserted.RECEIVER_ID FROM inserted  end
;

