/*  ***************************************************************************
    *    $Date:   27 Sep 2002 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   TCS  $
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for AR Transactions outbound in Application Schema  
    * Program Name:         wm_from_artrans_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for AR Transactions Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     27-SEP-02	 Gautam Naha  Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_artrans_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUSTOMER_TRX_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUSTOMER_TRX_VW ( WEB_TRANSACTION_ID, 
DOCUMENT_TYPE, DOCUMENT_STATUS, ROW_ID, CUSTOMER_TRX_ID, 
TRX_NUMBER, OLD_TRX_NUMBER, CT_RELATED_TRX_NUMBER, CT_MODEL_TRX_NUMBER, 
TRX_DATE, TERM_DUE_DATE, PREVIOUS_CUSTOMER_TRX_ID, INITIAL_CUSTOMER_TRX_ID, 
RELATED_BATCH_SOURCE_ID, RELATED_CUSTOMER_TRX_ID, CUST_TRX_TYPE_ID, BATCH_ID, 
BATCH_SOURCE_ID, REASON_CODE, REASON_CODE_MEANING, TERM_ID, 
PRIMARY_SALESREP_ID, AGREEMENT_ID, CREDIT_METHOD_FOR_RULES, CREDIT_METHOD_FOR_INSTALLMENTS, 
RECEIPT_METHOD_ID, INVOICING_RULE_ID, INVOICING_RULE_NAME, SHIP_VIA, 
FOB_POINT, FINANCE_CHARGES, COMPLETE_FLAG, CUSTOMER_BANK_ACCOUNT_ID, 
RECURRED_FROM_TRX_NUMBER, STATUS_TRX, DEFAULT_TAX_EXEMPT_FLAG, SOLD_TO_CUSTOMER_ID, 
SOLD_TO_SITE_USE_ID, SOLD_TO_CONTACT_ID, BILL_TO_CUSTOMER_ID, BILL_TO_SITE_USE_ID, 
RAA_BILL_TO_ADDRESS_ID, BILL_TO_CONTACT_ID, BILL_TO_TAXPAYER_ID, SHIP_TO_CUSTOMER_ID, 
SHIP_TO_SITE_USE_ID, RAA_SHIP_TO_ADDRESS_ID, SHIP_TO_CONTACT_ID, SHIP_TO_TAXPAYER_ID, 
REMIT_TO_ADDRESS_ID, INVOICE_CURRENCY_CODE, CREATED_FROM, SET_OF_BOOKS_ID, 
PRINTING_ORIGINAL_DATE, PRINTING_LAST_PRINTED, PRINTING_OPTION, PRINTING_COUNT, 
PRINTING_PENDING, LAST_PRINTED_SEQUENCE_NUM, PURCHASE_ORDER, PURCHASE_ORDER_REVISION, 
PURCHASE_ORDER_DATE, CUSTOMER_REFERENCE, CUSTOMER_REFERENCE_DATE, COMMENTS, 
INTERNAL_NOTES, EXCHANGE_RATE_TYPE, EXCHANGE_DATE, EXCHANGE_RATE, 
TERRITORY_ID, END_DATE_COMMITMENT, START_DATE_COMMITMENT, ORIG_SYSTEM_BATCH_NAME, 
SHIP_DATE_ACTUAL, WAYBILL_NUMBER, DOC_SEQUENCE_ID, DOC_SEQUENCE_VALUE, 
PAYING_CUSTOMER_ID, PAYING_SITE_USE_ID, ATTRIBUTE_CATEGORY, ATTRIBUTE1, 
ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, 
ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, 
ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, 
ATTRIBUTE14, ATTRIBUTE15, HEADER_ATTRIBUTE_CATEGORY, HEADER_ATTRIBUTE1, 
HEADER_ATTRIBUTE2, HEADER_ATTRIBUTE3, HEADER_ATTRIBUTE4, HEADER_ATTRIBUTE5, 
HEADER_ATTRIBUTE6, HEADER_ATTRIBUTE7, HEADER_ATTRIBUTE8, HEADER_ATTRIBUTE9, 
HEADER_ATTRIBUTE10, HEADER_ATTRIBUTE11, HEADER_ATTRIBUTE12, HEADER_ATTRIBUTE13, 
HEADER_ATTRIBUTE14, HEADER_ATTRIBUTE15, GLOBAL_ATTRIBUTE1, GLOBAL_ATTRIBUTE2, 
GLOBAL_ATTRIBUTE3, GLOBAL_ATTRIBUTE4, GLOBAL_ATTRIBUTE5, GLOBAL_ATTRIBUTE6, 
GLOBAL_ATTRIBUTE7, GLOBAL_ATTRIBUTE8, GLOBAL_ATTRIBUTE9, GLOBAL_ATTRIBUTE10, 
GLOBAL_ATTRIBUTE11, GLOBAL_ATTRIBUTE12, GLOBAL_ATTRIBUTE13, GLOBAL_ATTRIBUTE14, 
GLOBAL_ATTRIBUTE15, GLOBAL_ATTRIBUTE16, GLOBAL_ATTRIBUTE17, GLOBAL_ATTRIBUTE18, 
GLOBAL_ATTRIBUTE19, GLOBAL_ATTRIBUTE20, GLOBAL_ATTRIBUTE_CATEGORY, DEFAULT_USSGL_TRANSACTION_CODE, 
DEFAULT_USSGL_TRX_CODE_CONTEXT, LAST_UPDATE_DATE, LAST_UPDATED_BY, CREATION_DATE, 
CREATED_BY, LAST_UPDATE_LOGIN, REQUEST_ID, RAC_BILL_TO_CUSTOMER_NAME, 
RAC_BILL_TO_CUSTOMER_NUM, SU_BILL_TO_LOCATION, RAA_BILL_TO_ADDRESS1, RAA_BILL_TO_ADDRESS2, 
RAA_BILL_TO_ADDRESS3_DB, RAA_BILL_TO_ADDRESS3, RAA_BILL_TO_CITY, RAA_BILL_TO_COUNTY, 
RAA_BILL_TO_STATE, RAA_BILL_TO_PROVINCE, RAA_BILL_TO_POSTAL_CODE, FT_BILL_TO_COUNTRY, 
RAA_BILL_TO_CONCAT_ADDRESS, RACO_BILL_TO_CONTACT_NAME, RAC_SHIP_TO_CUSTOMER_NAME, RAC_SHIP_TO_CUSTOMER_NUM, 
SU_SHIP_TO_LOCATION, RAA_SHIP_TO_ADDRESS1, RAA_SHIP_TO_ADDRESS2, RAA_SHIP_TO_ADDRESS3_DB, 
RAA_SHIP_TO_ADDRESS3, RAA_SHIP_TO_CITY, RAA_SHIP_TO_COUNTY, RAA_SHIP_TO_STATE, 
RAA_SHIP_TO_PROVINCE, RAA_SHIP_TO_POSTAL_CODE, FT_SHIP_TO_COUNTRY, RAA_SHIP_TO_CONCAT_ADDRESS, 
RACO_SHIP_TO_CONTACT_NAME, RAC_SOLD_TO_CUSTOMER_NAME, RAC_SOLD_TO_CUSTOMER_NUM, RAC_PAYING_CUSTOMER_NAME, 
RAC_PAYING_CUSTOMER_NUM, SU_PAYING_CUSTOMER_LOCATION, RAA_REMIT_TO_ADDRESS1, RAA_REMIT_TO_ADDRESS2, 
RAA_REMIT_TO_ADDRESS3_DB, RAA_REMIT_TO_ADDRESS3, RAA_REMIT_TO_CITY, RAA_REMIT_TO_COUNTY, 
RAA_REMIT_TO_STATE, RAA_REMIT_TO_PROVINCE, RAA_REMIT_TO_POSTAL_CODE, FT_REMIT_TO_COUNTRY, 
RAA_CONCAT_REMIT_TO_ADDRESS, APBA_BANK_ACCOUNT_NAME, APBA_BANK_ACCOUNT_NUM, APBA_INACTIVE_DATE, 
APB_CUSTOMER_BANK_NAME, APB_CUSTOMER_BANK_BRANCH_NAME, ARM_RECEIPT_METHOD_NAME, ARM_PAYMENT_TYPE_CODE, 
ARC_CREATION_METHOD_CODE, BATCH_SOURCE_NAME, BS_AUTO_TRX_NUMBERING_FLAG, BS_COPY_DOC_NUMBER_FLAG, 
RAB_BATCH_NAME, CTT_TYPE_NAME, CTT_CLASS, RAS_PRIMARY_SALESREP_NAME, 
RAS_PRIMARY_SALESREP_NUM, RAT_TERM_NAME, RAT_TERM_IN_USE_FLAG, SOA_AGREEMENT_NAME, 
OF_SHIP_VIA_NAME, OF_ORGANIZATION_ID, AL_FOB_MEANING, AL_DEFAULT_TAX_EXEMPT_FLAG, 
CT_REFERENCE, GD_GL_DATE, GDCT_USER_EXCHANGE_RATE_TYPE, CT_INVOICE_FOR_CB, 
PS_DISPUTE_AMOUNT, PS_DISPUTE_DATE, DH_MAX_DISPUTE_DATE, REV_RECOG_RUN_FLAG, 
POSTED_FLAG, SELECTED_FOR_PAYMENT_FLAG, ACTIVITY_FLAG, CTT_POST_TO_GL_FLAG, 
CTT_OPEN_RECEIVABLES_FLAG, CTT_ALLOW_FREIGHT_FLAG, CTT_CREATION_SIGN, CTT_ALLOW_OVERAPPLICATION_FLAG, 
CTT_NATURAL_APP_ONLY_FLAG, CTT_TAX_CALCULATION_FLAG, CTT_DEFAULT_STATUS, CTT_DEFAULT_TERM, 
CTT_DEFAULT_PRINTING_OPTION, RULES_FLAG, PRINTED_FLAG, CM_AGAINST_TRX_FLAG, 
SITE_STATUS, CUSTOMER_STATUS, OVERRIDE_TERMS, COMMITMENTS_EXIST_FLAG, 
AGREEMENTS_EXIST_FLAG, ATCHMT_FLAG, GLOBAL_ATTRIBUTE21, GLOBAL_ATTRIBUTE22, 
GLOBAL_ATTRIBUTE23, GLOBAL_ATTRIBUTE24, GLOBAL_ATTRIBUTE25, GLOBAL_ATTRIBUTE26, 
GLOBAL_ATTRIBUTE27, GLOBAL_ATTRIBUTE28, GLOBAL_ATTRIBUTE29, GLOBAL_ATTRIBUTE30, 
BATCH_SOURCE_TYPE, PAYMENT_SERVER_ORDER_NUM, SETS_OF_BOOKS_NAME, TRX_TYPE_NAME, 
TERRITORY, TERM_NAME, RELATED_BATCH_SOURCE_NAME, CONS_BILLING_NUM, 
APPROVAL_CODE, ADDRESS_VERIFICATION_CODE, ORGANIZATION_NAME ) AS SELECT  
WMTC.WEB_TRANSACTION_ID,  
WMTC.TRANSACTION_TYPE DOCUMENT_TYPE,  
DECODE((WMTC.TRANSACTION_STATUS),  
0,  
'UPDATE',  
1,  
'INSERT',  
2,  
'DELETE') DOCUMENT_STATUS,  
CT.ROWID ,  
CT.CUSTOMER_TRX_ID ,  
CT.TRX_NUMBER ,  
CT.OLD_TRX_NUMBER ,  
CT_REL.TRX_NUMBER ,  
CT.RECURRED_FROM_TRX_NUMBER ,  
CT.TRX_DATE ,  
ARPT_SQL_FUNC_UTIL.GET_FIRST_REAL_DUE_DATE(CT.CUSTOMER_TRX_ID,  CT.TERM_ID,  CT.TRX_DATE) ,  
/* RESOLVE THESE FOREIGN KEY REFERENCES */ CT.PREVIOUS_CUSTOMER_TRX_ID ,  
CT.INITIAL_CUSTOMER_TRX_ID ,  
CT.RELATED_BATCH_SOURCE_ID ,  
CT.RELATED_CUSTOMER_TRX_ID ,  
CT.CUST_TRX_TYPE_ID ,  
CT.BATCH_ID ,  
CT.BATCH_SOURCE_ID ,  
CT.REASON_CODE ,  
CT.REASON_CODE ,  
CT.TERM_ID ,  
CT.PRIMARY_SALESREP_ID ,  
CT.AGREEMENT_ID ,  
CT.CREDIT_METHOD_FOR_RULES ,  
CT.CREDIT_METHOD_FOR_INSTALLMENTS ,  
CT.RECEIPT_METHOD_ID ,  
CT.INVOICING_RULE_ID ,  
NULL,  
CT.SHIP_VIA ,  
CT.FOB_POINT ,  
CT.FINANCE_CHARGES ,  
CT.COMPLETE_FLAG ,  
CT.CUSTOMER_BANK_ACCOUNT_ID ,  
CT.RECURRED_FROM_TRX_NUMBER ,  
CT.STATUS_TRX ,  
CT.DEFAULT_TAX_EXEMPT_FLAG ,  
CT.SOLD_TO_CUSTOMER_ID ,  
CT.SOLD_TO_SITE_USE_ID ,  
CT.SOLD_TO_CONTACT_ID ,  
CT.BILL_TO_CUSTOMER_ID ,  
CT.BILL_TO_SITE_USE_ID ,  
RAA_BILL.CUST_ACCT_SITE_ID ,  
CT.BILL_TO_CONTACT_ID ,  
RAC_BILL_PARTY.JGZZ_FISCAL_CODE ,  
CT.SHIP_TO_CUSTOMER_ID ,  
CT.SHIP_TO_SITE_USE_ID ,  
RAA_SHIP.CUST_ACCT_SITE_ID ,  
CT.SHIP_TO_CONTACT_ID ,  
RAC_SHIP_PARTY.JGZZ_FISCAL_CODE ,  
CT.REMIT_TO_ADDRESS_ID ,  
/* END FOREIGN KEY REFERENCES TO BE RESOLVED */ CT.INVOICE_CURRENCY_CODE ,  
CT.CREATED_FROM ,  
CT.SET_OF_BOOKS_ID ,  
CT.PRINTING_ORIGINAL_DATE ,  
CT.PRINTING_LAST_PRINTED ,  
CT.PRINTING_OPTION ,  
CT.PRINTING_COUNT ,  
CT.PRINTING_PENDING ,  
CT.LAST_PRINTED_SEQUENCE_NUM ,  
CT.PURCHASE_ORDER ,  
CT.PURCHASE_ORDER_REVISION ,  
CT.PURCHASE_ORDER_DATE ,  
CT.CUSTOMER_REFERENCE ,  
CT.CUSTOMER_REFERENCE_DATE ,  
CT.COMMENTS ,  
CT.INTERNAL_NOTES ,  
CT.EXCHANGE_RATE_TYPE ,  
CT.EXCHANGE_DATE ,  
CT.EXCHANGE_RATE ,  
CT.TERRITORY_ID ,  
CT.END_DATE_COMMITMENT ,  
CT.START_DATE_COMMITMENT ,  
CT.ORIG_SYSTEM_BATCH_NAME ,  
CT.SHIP_DATE_ACTUAL ,  
CT.WAYBILL_NUMBER ,  
CT.DOC_SEQUENCE_ID ,  
CT.DOC_SEQUENCE_VALUE ,  
CT.PAYING_CUSTOMER_ID ,  
CT.PAYING_SITE_USE_ID ,  
CT.ATTRIBUTE_CATEGORY ,  
CT.ATTRIBUTE1 ,  
CT.ATTRIBUTE2 ,  
CT.ATTRIBUTE3 ,  
CT.ATTRIBUTE4 ,  
CT.ATTRIBUTE5 ,  
CT.ATTRIBUTE6 ,  
CT.ATTRIBUTE7 ,  
CT.ATTRIBUTE8 ,  
CT.ATTRIBUTE9 ,  
CT.ATTRIBUTE10 ,  
CT.ATTRIBUTE11 ,  
CT.ATTRIBUTE12 ,  
CT.ATTRIBUTE13 ,  
CT.ATTRIBUTE14 ,  
CT.ATTRIBUTE15 ,  
CT.INTERFACE_HEADER_CONTEXT ,  
CT.INTERFACE_HEADER_ATTRIBUTE1 ,  
CT.INTERFACE_HEADER_ATTRIBUTE2 ,  
CT.INTERFACE_HEADER_ATTRIBUTE3 ,  
CT.INTERFACE_HEADER_ATTRIBUTE4 ,  
CT.INTERFACE_HEADER_ATTRIBUTE5 ,  
CT.INTERFACE_HEADER_ATTRIBUTE6 ,  
CT.INTERFACE_HEADER_ATTRIBUTE7 ,  
CT.INTERFACE_HEADER_ATTRIBUTE8 ,  
CT.INTERFACE_HEADER_ATTRIBUTE9 ,  
CT.INTERFACE_HEADER_ATTRIBUTE10 ,  
CT.INTERFACE_HEADER_ATTRIBUTE11 ,  
CT.INTERFACE_HEADER_ATTRIBUTE12 ,  
CT.INTERFACE_HEADER_ATTRIBUTE13 ,  
CT.INTERFACE_HEADER_ATTRIBUTE14 ,  
CT.INTERFACE_HEADER_ATTRIBUTE15 ,  
CT.GLOBAL_ATTRIBUTE1 ,  
CT.GLOBAL_ATTRIBUTE2 ,  
CT.GLOBAL_ATTRIBUTE3 ,  
CT.GLOBAL_ATTRIBUTE4 ,  
CT.GLOBAL_ATTRIBUTE5 ,  
CT.GLOBAL_ATTRIBUTE6 ,  
CT.GLOBAL_ATTRIBUTE7 ,  
CT.GLOBAL_ATTRIBUTE8 ,  
CT.GLOBAL_ATTRIBUTE9 ,  
CT.GLOBAL_ATTRIBUTE10 ,  
CT.GLOBAL_ATTRIBUTE11 ,  
CT.GLOBAL_ATTRIBUTE12 ,  
CT.GLOBAL_ATTRIBUTE13 ,  
CT.GLOBAL_ATTRIBUTE14 ,  
CT.GLOBAL_ATTRIBUTE15 ,  
CT.GLOBAL_ATTRIBUTE16 ,  
CT.GLOBAL_ATTRIBUTE17 ,  
CT.GLOBAL_ATTRIBUTE18 ,  
CT.GLOBAL_ATTRIBUTE19 ,  
CT.GLOBAL_ATTRIBUTE20 ,  
CT.GLOBAL_ATTRIBUTE_CATEGORY ,  
CT.DEFAULT_USSGL_TRANSACTION_CODE ,  
CT.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CT.LAST_UPDATE_DATE ,  
CT.LAST_UPDATED_BY ,  
CT.CREATION_DATE ,  
CT.CREATED_BY ,  
CT.LAST_UPDATE_LOGIN ,  
CT.REQUEST_ID ,  
SUBSTRB(RAC_BILL_PARTY.PARTY_NAME,  
1,  
50) ,  
RAC_BILL.ACCOUNT_NUMBER ,  
SU_BILL.LOCATION ,  
RAA_BILL_LOC.ADDRESS1 ,  
RAA_BILL_LOC.ADDRESS2 ,  
RAA_BILL_LOC.ADDRESS3 ,  
DECODE( RAA_BILL.CUST_ACCT_SITE_ID,  NULL,  NULL,  ARH_ADDR_PKG.FORMAT_LAST_ADDRESS_LINE(RAA_BILL_LOC.ADDRESS_STYLE,  
RAA_BILL_LOC.ADDRESS3,  
RAA_BILL_LOC.ADDRESS4,  
RAA_BILL_LOC.CITY,  
RAA_BILL_LOC.COUNTY,  
RAA_BILL_LOC.STATE,  
RAA_BILL_LOC.PROVINCE,  
FT_BILL.TERRITORY_SHORT_NAME,  
RAA_BILL_LOC.POSTAL_CODE) ) ,  
RAA_BILL_LOC.CITY ,  
RAA_BILL_LOC.COUNTY ,  
RAA_BILL_LOC.STATE ,  
RAA_BILL_LOC.PROVINCE ,  
RAA_BILL_LOC.POSTAL_CODE ,  
FT_BILL.TERRITORY_SHORT_NAME ,  
DECODE( RAA_BILL.CUST_ACCT_SITE_ID,  
NULL,  
NULL,  
ARH_ADDR_PKG.ARXTW_FORMAT_ADDRESS(RAA_BILL_LOC.ADDRESS_STYLE,  
RAA_BILL_LOC.ADDRESS1,  
RAA_BILL_LOC.ADDRESS2,  
RAA_BILL_LOC.ADDRESS3,  
RAA_BILL_LOC.ADDRESS4,  
RAA_BILL_LOC.CITY,  
RAA_BILL_LOC.COUNTY,  
RAA_BILL_LOC.STATE,  
RAA_BILL_LOC.PROVINCE,  
RAA_BILL_LOC.POSTAL_CODE,  
FT_BILL.TERRITORY_SHORT_NAME) ) ,  
DECODE(SUBSTRB(RACO_BILL_PARTY.PERSON_LAST_NAME,  
1,  
50),  
NULL,  
SUBSTRB(RACO_BILL_PARTY.PERSON_FIRST_NAME,  
1,  
40),  
SUBSTRB(RACO_BILL_PARTY.PERSON_LAST_NAME,  
1,  
50) ||',  
' || SUBSTRB(RACO_BILL_PARTY.PERSON_FIRST_NAME,  
1,  
40)) ,  
SUBSTRB(RAC_SHIP_PARTY.PARTY_NAME,  
1,  
50) ,  
RAC_SHIP.ACCOUNT_NUMBER ,  
SU_SHIP.LOCATION ,  
RAA_SHIP_LOC.ADDRESS1 ,  
RAA_SHIP_LOC.ADDRESS2 ,  
RAA_SHIP_LOC.ADDRESS3 ,  
DECODE( RAA_SHIP.CUST_ACCT_SITE_ID,  
NULL,  
NULL,  
ARH_ADDR_PKG.FORMAT_LAST_ADDRESS_LINE(RAA_SHIP_LOC.ADDRESS_STYLE,  
RAA_SHIP_LOC.ADDRESS3,  
RAA_SHIP_LOC.ADDRESS4,  
RAA_SHIP_LOC.CITY,  
RAA_SHIP_LOC.COUNTY,  
RAA_SHIP_LOC.STATE,  
RAA_SHIP_LOC.PROVINCE,  
FT_SHIP.TERRITORY_SHORT_NAME,  
RAA_SHIP_LOC.POSTAL_CODE) ) ,  
RAA_SHIP_LOC.CITY ,  
RAA_SHIP_LOC.COUNTY ,  
RAA_SHIP_LOC.STATE ,  
RAA_SHIP_LOC.PROVINCE ,  
RAA_SHIP_LOC.POSTAL_CODE ,  
FT_SHIP.TERRITORY_SHORT_NAME ,  
DECODE( RAA_SHIP.CUST_ACCT_SITE_ID,  
NULL,  
NULL,  
ARH_ADDR_PKG.ARXTW_FORMAT_ADDRESS(RAA_SHIP_LOC.ADDRESS_STYLE,  
RAA_SHIP_LOC.ADDRESS1,  
RAA_SHIP_LOC.ADDRESS2,  
RAA_SHIP_LOC.ADDRESS3,  
RAA_SHIP_LOC.ADDRESS4,  
RAA_SHIP_LOC.CITY,  
RAA_SHIP_LOC.COUNTY,  
RAA_SHIP_LOC.STATE,  
RAA_SHIP_LOC.PROVINCE,  
RAA_SHIP_LOC.POSTAL_CODE,  
FT_SHIP.TERRITORY_SHORT_NAME) ) ,  
DECODE(SUBSTRB(RACO_SHIP_PARTY.PERSON_LAST_NAME,  
1,  
50),  
NULL,  
SUBSTRB(RACO_SHIP_PARTY.PERSON_FIRST_NAME,  
1,  
40),  
SUBSTRB(RACO_SHIP_PARTY.PERSON_LAST_NAME,  
1,  
50) || ',' || SUBSTRB(RACO_SHIP_PARTY.PERSON_FIRST_NAME,  
1,  
40)) ,  
SUBSTRB(RAC_SOLD_PARTY.PARTY_NAME,  
1,  
50) ,  
RAC_SOLD.ACCOUNT_NUMBER ,  
SUBSTRB(RAC_PAYING_PARTY.PARTY_NAME,  
1,  
50) ,  
RAC_PAYING.ACCOUNT_NUMBER ,  
SU_PAYING.LOCATION ,  
RAA_REMIT_LOC.ADDRESS1 ,  
RAA_REMIT_LOC.ADDRESS2 ,  
RAA_REMIT_LOC.ADDRESS3 ,  
DECODE( RAA_REMIT.CUST_ACCT_SITE_ID,  
NULL,  
NULL,  
ARH_ADDR_PKG.FORMAT_LAST_ADDRESS_LINE(RAA_REMIT_LOC.ADDRESS_STYLE,  
RAA_REMIT_LOC.ADDRESS3,  
RAA_REMIT_LOC.ADDRESS4,  
RAA_REMIT_LOC.CITY,  
RAA_REMIT_LOC.COUNTY,  
RAA_REMIT_LOC.STATE,  
RAA_REMIT_LOC.PROVINCE,  
FT_REMIT.TERRITORY_SHORT_NAME,  
RAA_REMIT_LOC.POSTAL_CODE) ) ,  
RAA_REMIT_LOC.CITY ,  
RAA_REMIT_LOC.COUNTY ,  
RAA_REMIT_LOC.STATE ,  
RAA_REMIT_LOC.PROVINCE ,  
RAA_REMIT_LOC.POSTAL_CODE ,  
FT_REMIT.TERRITORY_SHORT_NAME ,  
DECODE( RAA_REMIT.CUST_ACCT_SITE_ID,  
NULL,  
NULL,  
ARH_ADDR_PKG.ARXTW_FORMAT_ADDRESS(RAA_REMIT_LOC.ADDRESS_STYLE,  
RAA_REMIT_LOC.ADDRESS1,  
RAA_REMIT_LOC.ADDRESS2,  
RAA_REMIT_LOC.ADDRESS3,  
RAA_REMIT_LOC.ADDRESS4,  
RAA_REMIT_LOC.CITY,  
RAA_REMIT_LOC.COUNTY,  
RAA_REMIT_LOC.STATE,  
RAA_REMIT_LOC.PROVINCE,  
RAA_REMIT_LOC.POSTAL_CODE,  
FT_REMIT.TERRITORY_SHORT_NAME) ) ,  
APBA.BANK_ACCOUNT_NAME ,  
DECODE (NVL(FND_PROFILE.VALUE('AR_MASK_BANK_ACCOUNT_NUMBERS'),  
'F'),  
'N',  
APBA.BANK_ACCOUNT_NUM,  
'F',  
RPAD(SUBSTR(APBA.BANK_ACCOUNT_NUM,  
1,  
4),  
LENGTH(APBA.BANK_ACCOUNT_NUM),  
'*'),  
'L',  
LPAD(SUBSTR(APBA.BANK_ACCOUNT_NUM,  
-4),  
LENGTH(APBA.BANK_ACCOUNT_NUM),  
'*')) ,  
APBA.INACTIVE_DATE ,  
APB.BANK_NAME ,  
APB.BANK_BRANCH_NAME ,  
ARM.NAME ,  
ARM.PAYMENT_TYPE_CODE ,  
ARC.CREATION_METHOD_CODE ,  
BS.NAME ,  
BS.AUTO_TRX_NUMBERING_FLAG ,  
BS.COPY_DOC_NUMBER_FLAG ,  
RAB.NAME ,  
CTT.NAME ,  
CTT.TYPE ,  
ARPT_SQL_FUNC_UTIL.get_salesrep_name_number(CT.PRIMARY_SALESREP_ID,  
'NAME') ,  
ARPT_SQL_FUNC_UTIL.get_salesrep_name_number(CT.PRIMARY_SALESREP_ID,  
'NUMBER') ,  
RAT.NAME ,  
RAT.IN_USE ,  
SOA.NAME ,  
ORF.DESCRIPTION ,  
ORF.ORGANIZATION_ID ,  
AL_FOB.MEANING ,  
AL_TAX.MEANING ,  
ARPT_SQL_FUNC_UTIL.GET_REFERENCE(CT.ROWID) ,  
GD.GL_DATE ,  
GDCT.USER_CONVERSION_TYPE ,  
ARPT_SQL_FUNC_UTIL.GET_CB_INVOICE( CT.CUSTOMER_TRX_ID,  
CTT.TYPE) ,  
ARPT_SQL_FUNC_UTIL.GET_DISPUTE_AMOUNT( CT.CUSTOMER_TRX_ID,  
CTT.TYPE,  
CTT.ACCOUNTING_AFFECT_FLAG ) ,  
ARPT_SQL_FUNC_UTIL.GET_DISPUTE_DATE( CT.CUSTOMER_TRX_ID,  
CTT.TYPE,  
CTT.ACCOUNTING_AFFECT_FLAG ) ,  
ARPT_SQL_FUNC_UTIL.GET_MAX_DISPUTE_DATE( CT.CUSTOMER_TRX_ID,  
CTT.TYPE,  
CTT.ACCOUNTING_AFFECT_FLAG ) ,  
ARPT_SQL_FUNC_UTIL.GET_REVENUE_RECOG_RUN_FLAG(CT.CUSTOMER_TRX_ID,  
CT.INVOICING_RULE_ID) ,  
ARPT_SQL_FUNC_UTIL.GET_POSTED_FLAG( CT.CUSTOMER_TRX_ID,  
CTT.POST_TO_GL,  
CT.COMPLETE_FLAG ) ,  
ARPT_SQL_FUNC_UTIL.GET_SELECTED_FOR_PAYMENT_FLAG( CT.CUSTOMER_TRX_ID,  
CTT.ACCOUNTING_AFFECT_FLAG,  
CT.COMPLETE_FLAG ) ,  
ARPT_SQL_FUNC_UTIL.GET_ACTIVITY_FLAG( CT.CUSTOMER_TRX_ID,  
CTT.ACCOUNTING_AFFECT_FLAG,  
CT.COMPLETE_FLAG,  
CTT.TYPE,  
CT.INITIAL_CUSTOMER_TRX_ID,  
CT.PREVIOUS_CUSTOMER_TRX_ID ) ,  
CTT.POST_TO_GL ,  
CTT.ACCOUNTING_AFFECT_FLAG ,  
CTT.ALLOW_FREIGHT_FLAG ,  
CTT.CREATION_SIGN ,  
CTT.ALLOW_OVERAPPLICATION_FLAG ,  
CTT.NATURAL_APPLICATION_ONLY_FLAG ,  
CTT.TAX_CALCULATION_FLAG ,  
CTT.DEFAULT_STATUS ,  
CTT.DEFAULT_TERM ,  
CTT.DEFAULT_PRINTING_OPTION ,  
DECODE(CT.INVOICING_RULE_ID,  
NULL,  
'N',  
'Y') ,  
DECODE(CT.PRINTING_LAST_PRINTED,  
NULL,  
'N',  
'Y') ,  
DECODE(CT.PREVIOUS_CUSTOMER_TRX_ID,  
NULL,  
'N',  
'Y') ,  
SU_BILL.STATUS ,  
RAC_BILL.STATUS ,  
ARPT_SQL_FUNC_UTIL.GET_OVERRIDE_TERMS(CT.BILL_TO_CUSTOMER_ID,  
CT.BILL_TO_SITE_USE_ID) ,  
DECODE(CT.INITIAL_CUSTOMER_TRX_ID,  
NULL,  
DECODE(CTT.TYPE,  
'DEP',  
'N',  
'GUAR',  
'N',  
'CB',  
'N',  
'Y' ),  
'Y') ,  
DECODE(CT.AGREEMENT_ID,  
NULL,  
DECODE(CTT.TYPE,  
'CM',  
'N',  
ARPT_SQL_FUNC_UTIL.GET_AGREEMENTS_EXIST_FLAG( CT.BILL_TO_CUSTOMER_ID,  
CT.TRX_DATE) ),  
'Y') ,  
FND_ATTACHMENT_UTIL_PKG.GET_ATCHMT_EXISTS('RA_CUSTOMER_TRX',  
CT.CUSTOMER_TRX_ID) ,  
CT.GLOBAL_ATTRIBUTE21 ,  
CT.GLOBAL_ATTRIBUTE22 ,  
CT.GLOBAL_ATTRIBUTE23 ,  
CT.GLOBAL_ATTRIBUTE24 ,  
CT.GLOBAL_ATTRIBUTE15 ,  
CT.GLOBAL_ATTRIBUTE26 ,  
CT.GLOBAL_ATTRIBUTE27 ,  
CT.GLOBAL_ATTRIBUTE28 ,  
CT.GLOBAL_ATTRIBUTE29 ,  
CT.GLOBAL_ATTRIBUTE30 ,  
BS.BATCH_SOURCE_TYPE,  
CT.PAYMENT_SERVER_ORDER_NUM,  
SOB.NAME,  
CTY.NAME,  
FT_BILL.TERRITORY_SHORT_NAME,  
RAT.NAME,  
RBS.NAME,  
NULL,  
CT.APPROVAL_CODE,  
CT.ADDRESS_VERIFICATION_CODE,  
ORG.ORGANIZATION_NAME  
FROM  
RA_CUST_TRX_LINE_GL_DIST_ALL GD,  
RA_CUSTOMER_TRX_ALL CT,  
HZ_CUST_ACCOUNTS RAC_BILL,  
HZ_PARTIES RAC_BILL_PARTY,  
HZ_CUST_ACCOUNTS RAC_SHIP,  
HZ_PARTIES RAC_SHIP_PARTY,  
HZ_CUST_ACCOUNTS RAC_SOLD,  
HZ_PARTIES RAC_SOLD_PARTY,  
HZ_CUST_ACCOUNTS RAC_PAYING,  
HZ_PARTIES RAC_PAYING_PARTY,  
HZ_CUST_SITE_USES_ALL SU_BILL,  
HZ_CUST_SITE_USES_ALL SU_SHIP,  
HZ_CUST_SITE_USES_ALL SU_PAYING,  
FND_TERRITORIES_VL FT_BILL,  
FND_TERRITORIES_VL FT_SHIP,  
FND_TERRITORIES_VL FT_REMIT,  
HZ_CUST_ACCT_SITES_ALL RAA_BILL,  
HZ_PARTY_SITES RAA_BILL_PS,  
HZ_LOCATIONS RAA_BILL_LOC,  
HZ_CUST_ACCT_SITES_ALL RAA_SHIP,  
HZ_PARTY_SITES RAA_SHIP_PS,  
HZ_LOCATIONS RAA_SHIP_LOC,  
HZ_CUST_ACCT_SITES_ALL RAA_REMIT,  
HZ_PARTY_SITES RAA_REMIT_PS,  
HZ_LOCATIONS RAA_REMIT_LOC,  
HZ_CUST_ACCOUNT_ROLES RACO_SHIP,  
HZ_PARTIES RACO_SHIP_PARTY,  
HZ_RELATIONSHIPS RACO_SHIP_REL,  
HZ_CUST_ACCOUNT_ROLES RACO_BILL,  
HZ_PARTIES RACO_BILL_PARTY,  
HZ_RELATIONSHIPS RACO_BILL_REL,  
AP_BANK_ACCOUNTS_ALL APBA,  
AP_BANK_BRANCHES APB,  
AR_RECEIPT_METHODS ARM,  
AR_RECEIPT_CLASSES ARC,  
RA_BATCH_SOURCES_ALL BS,  
RA_BATCHES_ALL RAB,  
RA_CUST_TRX_TYPES_ALL CTT,  
RA_TERMS RAT,  
SO_AGREEMENTS SOA,  
ORG_FREIGHT ORF,  
GL_DAILY_CONVERSION_TYPES GDCT,  
RA_CUSTOMER_TRX_ALL CT_REL,  
AR_LOOKUPS AL_FOB,  
AR_LOOKUPS AL_TAX,  
wm_track_changes_vw wmtc,  
org_organization_definitions org,  
ra_batch_sources_all rbs,  
gl_sets_of_books sob,  
ra_cust_trx_types_all cty  
WHERE  
CT.CUSTOMER_TRX_ID = GD.CUSTOMER_TRX_ID AND  
'REC' = GD.ACCOUNT_CLASS AND  
'Y' = GD.LATEST_REC_FLAG AND  
CT.RELATED_CUSTOMER_TRX_ID = CT_REL.CUSTOMER_TRX_ID(+) AND  
CT.BILL_TO_CUSTOMER_ID = RAC_BILL.CUST_ACCOUNT_ID AND  
RAC_BILL.PARTY_ID = RAC_BILL_PARTY.PARTY_ID AND  
CT.SHIP_TO_CUSTOMER_ID = RAC_SHIP.CUST_ACCOUNT_ID(+) AND  
RAC_SHIP.PARTY_ID = RAC_SHIP_PARTY.PARTY_ID(+) AND  
CT.SOLD_TO_CUSTOMER_ID = RAC_SOLD.CUST_ACCOUNT_ID(+) AND  
RAC_SOLD.PARTY_ID = RAC_SOLD_PARTY.PARTY_ID(+) AND  
CT.PAYING_CUSTOMER_ID = RAC_PAYING.CUST_ACCOUNT_ID(+) AND  
RAC_PAYING.PARTY_ID = RAC_PAYING_PARTY.PARTY_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SU_BILL.SITE_USE_ID AND  
CT.SHIP_TO_SITE_USE_ID = SU_SHIP.SITE_USE_ID(+) AND  
CT.PAYING_SITE_USE_ID = SU_PAYING.SITE_USE_ID(+) AND  
SU_BILL.CUST_ACCT_SITE_ID = RAA_BILL.CUST_ACCT_SITE_ID AND  
RAA_BILL.PARTY_SITE_ID = RAA_BILL_PS.PARTY_SITE_ID AND  
RAA_BILL_LOC.LOCATION_ID = RAA_BILL_PS.LOCATION_ID AND  
SU_SHIP.CUST_ACCT_SITE_ID = RAA_SHIP.CUST_ACCT_SITE_ID(+) AND  
RAA_SHIP.PARTY_SITE_ID = RAA_SHIP_PS.PARTY_SITE_ID(+) AND  
RAA_SHIP_LOC.LOCATION_ID(+) = RAA_SHIP_PS.LOCATION_ID AND  
CT.BILL_TO_CONTACT_ID = RACO_BILL.CUST_ACCOUNT_ROLE_ID(+) AND  
RACO_BILL.PARTY_ID = RACO_BILL_REL.PARTY_ID(+) and  
raco_bill_rel.subject_table_name(+) = 'HZ_PARTIES' and  
raco_bill_rel.object_table_name(+) = 'HZ_PARTIES' and  
raco_bill_rel.directional_flag(+) = 'F' AND  
RACO_BILL.ROLE_TYPE(+) = 'CONTACT' AND  
RACO_BILL_REL.SUBJECT_ID = RACO_BILL_PARTY.PARTY_ID(+) AND  
CT.SHIP_TO_CONTACT_ID = RACO_SHIP.CUST_ACCOUNT_ROLE_ID(+) AND  
RACO_SHIP.PARTY_ID = RACO_SHIP_REL.PARTY_ID(+) and  
raco_ship_rel.subject_table_name(+) = 'HZ_PARTIES' and  
raco_ship_rel.object_table_name(+) = 'HZ_PARTIES' and  
raco_ship_rel.directional_flag(+) = 'F' AND  
RACO_SHIP.ROLE_TYPE(+) = 'CONTACT' AND  
RACO_SHIP_REL.SUBJECT_ID = RACO_SHIP_PARTY.PARTY_ID(+) AND  
CT.REMIT_TO_ADDRESS_ID = RAA_REMIT.CUST_ACCT_SITE_ID(+) AND  
RAA_REMIT.PARTY_SITE_ID = RAA_REMIT_PS.PARTY_SITE_ID(+) AND  
RAA_REMIT_LOC.LOCATION_ID(+) = RAA_REMIT_PS.LOCATION_ID AND  
RAA_BILL_LOC.COUNTRY = FT_BILL.TERRITORY_CODE(+) AND  
RAA_SHIP_LOC.COUNTRY = FT_SHIP.TERRITORY_CODE(+) AND  
RAA_REMIT_LOC.COUNTRY = FT_REMIT.TERRITORY_CODE(+) AND  
CT.CUSTOMER_BANK_ACCOUNT_ID = APBA.BANK_ACCOUNT_ID(+) AND  
APBA.BANK_BRANCH_ID = APB.BANK_BRANCH_ID(+) AND  
CT.RECEIPT_METHOD_ID = ARM.RECEIPT_METHOD_ID(+) AND  
ARM.RECEIPT_CLASS_ID = ARC.RECEIPT_CLASS_ID(+) AND  
CT.BATCH_SOURCE_ID = BS.BATCH_SOURCE_ID AND  
CT.ORG_ID = BS.ORG_ID AND  
CT.RELATED_BATCH_SOURCE_ID = RBS.BATCH_SOURCE_ID (+) AND  
CT.ORG_ID = RBS.ORG_ID (+) AND  
CT.BATCH_ID = RAB.BATCH_ID(+) AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CT.ORG_ID = CTT.ORG_ID AND  
CTT.TYPE <> 'BR' /* 19-APR-2000 J Rautiainen BR Implementation */ AND  
CT.TERM_ID = RAT.TERM_ID(+) AND  
CT.AGREEMENT_ID = SOA.AGREEMENT_ID(+) AND  
CT.EXCHANGE_RATE_TYPE = GDCT.CONVERSION_TYPE(+) AND  
'FOB' = AL_FOB.LOOKUP_TYPE(+) AND  
CT.FOB_POINT = AL_FOB.LOOKUP_CODE(+) AND  
CT.SHIP_VIA = ORF.FREIGHT_CODE(+) AND  
CT.ORG_ID = ORF.ORGANIZATION_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CT.DEFAULT_TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
CT.ORG_ID = ORG.ORGANIZATION_ID (+) AND  
CT.SET_OF_BOOKS_ID = SOB.SET_OF_BOOKS_ID (+) AND  
CT.CUST_TRX_TYPE_ID = CTY.CUST_TRX_TYPE_ID (+) AND  
CT.ORG_ID = CTY.ORG_ID (+) AND  
CT.CUSTOMER_TRX_ID = WMTC.TRANSACTION_ID AND  
TRANSACTION_STATUS <= 2 AND  
WMTC.TRANSACTION_TYPE = 'ARTRANSACTION'  AND
CT.COMPLETE_FLAG = 'Y'
ORDER BY WMTC.WEB_TRANSACTION_ID
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_LINE_GL_DIST_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_LINE_GL_DIST_VW ( CUST_TRX_LINE_GL_DIST_ID, 
CUSTOMER_TRX_ID, CUSTOMER_TRX_LINE_ID, CUST_TRX_LINE_SALESREP_ID, ACCT_DISTRIBUTION_PERCENT, 
AMOUNT, ACCTD_AMOUNT, GL_DATE, ORIGINAL_GL_DATE, 
GL_POSTED_DATE, ACCOUNT_CLASS, ACCOUNT_SET_FLAG, LATEST_REC_FLAG, 
CODE_COMBINATION_ID, ACCOUNT_NUMBER, COLLECTED_TAX_CCID, INTERIM_TAX_ACCOUNT_NUMBER, 
COMMENTS, SET_OF_BOOKS_ID, LAST_UPDATE_DATE, LAST_UPDATED_BY, 
CREATION_DATE, CREATED_BY, LAST_UPDATE_LOGIN, REQUEST_ID, 
PROGRAM_APPLICATION_ID, PROGRAM_ID, PROGRAM_UPDATE_DATE, POST_REQUEST_ID, 
POSTING_CONTROL_ID, RA_POST_LOOP_NUMBER, USSGL_TRANSACTION_CODE, USSGL_TRANSACTION_CODE_CONTEXT, 
ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, 
ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, 
ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, 
ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, 
CTL_LINE_AMOUNT, RR_ACCOUNTING_RULE, CTL_LINE_NUMBER, CTL_OTHER_LINE_NUMBER, 
AL_CLASS_MEANING, AL_LINE_TYPE_MEANING, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, 
INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, 
INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, 
INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, 
INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15 ) AS SELECT  
LGD.CUST_TRX_LINE_GL_DIST_ID ,  
LGD.CUSTOMER_TRX_ID ,  
LGD.CUSTOMER_TRX_LINE_ID ,  
LGD.CUST_TRX_LINE_SALESREP_ID ,  
LGD.PERCENT ,  
LGD.AMOUNT ,  
LGD.ACCTD_AMOUNT ,  
LGD.GL_DATE ,  
LGD.ORIGINAL_GL_DATE ,  
LGD.GL_POSTED_DATE ,  
LGD.ACCOUNT_CLASS ,  
LGD.ACCOUNT_SET_FLAG ,  
LGD.LATEST_REC_FLAG ,  
LGD.CODE_COMBINATION_ID ,  
LGD.CONCATENATED_SEGMENTS ,  
LGD.COLLECTED_TAX_CCID ,  
LGD.COLLECTED_TAX_CONCAT_SEG ,  
LGD.COMMENTS ,  
LGD.SET_OF_BOOKS_ID ,  
LGD.LAST_UPDATE_DATE ,  
LGD.LAST_UPDATED_BY ,  
LGD.CREATION_DATE ,  
LGD.CREATED_BY ,  
LGD.LAST_UPDATE_LOGIN ,  
LGD.REQUEST_ID ,  
LGD.PROGRAM_APPLICATION_ID ,  
LGD.PROGRAM_ID ,  
LGD.PROGRAM_UPDATE_DATE ,  
LGD.POST_REQUEST_ID ,  
LGD.POSTING_CONTROL_ID ,  
LGD.RA_POST_LOOP_NUMBER ,  
LGD.USSGL_TRANSACTION_CODE ,  
LGD.USSGL_TRANSACTION_CODE_CONTEXT ,  
LGD.ATTRIBUTE_CATEGORY ,  
LGD.ATTRIBUTE1 ,  
LGD.ATTRIBUTE2 ,  
LGD.ATTRIBUTE3 ,  
LGD.ATTRIBUTE4 ,  
LGD.ATTRIBUTE5 ,  
LGD.ATTRIBUTE6 ,  
LGD.ATTRIBUTE7 ,  
LGD.ATTRIBUTE8 ,  
LGD.ATTRIBUTE9 ,  
LGD.ATTRIBUTE10 ,  
LGD.ATTRIBUTE11 ,  
LGD.ATTRIBUTE12 ,  
LGD.ATTRIBUTE13 ,  
LGD.ATTRIBUTE14 ,  
LGD.ATTRIBUTE15 ,  
CTL.EXTENDED_AMOUNT ,  
RR.NAME ,  
DECODE(CTL.LINK_TO_CUST_TRX_LINE_ID,  
NULL,  
CTL.LINE_NUMBER,  
CTL_LINE.LINE_NUMBER) ,  
DECODE(CTL.LINK_TO_CUST_TRX_LINE_ID,  
NULL,  
'',  
CTL.LINE_NUMBER) ,  
AL_CLASS.MEANING ,  
AL_TYPE.MEANING,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1 ,  
CTL.INTERFACE_LINE_ATTRIBUTE2 ,  
CTL.INTERFACE_LINE_ATTRIBUTE3 ,  
CTL.INTERFACE_LINE_ATTRIBUTE4 ,  
CTL.INTERFACE_LINE_ATTRIBUTE5 ,  
CTL.INTERFACE_LINE_ATTRIBUTE6 ,  
CTL.INTERFACE_LINE_ATTRIBUTE7 ,  
CTL.INTERFACE_LINE_ATTRIBUTE8 ,  
CTL.INTERFACE_LINE_ATTRIBUTE9 ,  
CTL.INTERFACE_LINE_ATTRIBUTE10 ,  
CTL.INTERFACE_LINE_ATTRIBUTE11 ,  
CTL.INTERFACE_LINE_ATTRIBUTE12 ,  
CTL.INTERFACE_LINE_ATTRIBUTE13 ,  
CTL.INTERFACE_LINE_ATTRIBUTE14 ,  
CTL.INTERFACE_LINE_ATTRIBUTE15  
FROM  
RA_CUST_TRX_LINE_GL_DIST_ALL LGD,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINE,  
AR_LOOKUPS AL_CLASS,  
AR_LOOKUPS AL_TYPE,  
RA_RULES RR  
WHERE  
LGD.CUSTOMER_TRX_LINE_ID = CTL.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.LINK_TO_CUST_TRX_LINE_ID = CTL_LINE.CUSTOMER_TRX_LINE_ID(+) AND  
AL_CLASS.LOOKUP_TYPE = 'AUTOGL_TYPE' AND  
AL_CLASS.LOOKUP_CODE = LGD.ACCOUNT_CLASS AND  
AL_TYPE.LOOKUP_TYPE(+) = 'STD_LINE_TYPE' AND  
AL_TYPE.LOOKUP_CODE(+) = CTL.LINE_TYPE AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+)
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_FREIGHT_VW
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_RA_CUST_TRX_FREIGHT_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, PREVIOUS_CUST_TRX_LINE_NUM, LINE_NUMBER, 
LINE_TYPE, DESCRIPTION, QUANTITY_ORDERED, QUANTITY_CREDITED, 
QUANTITY, UNIT_STANDARD_PRICE, UNIT_SELLING_PRICE, REVENUE_AMOUNT, 
AMOUNT, AMOUNT_INCLUDES_TAX_FLAG, UOM_CODE, REASON_CODE, 
REASON_CODE_MEANING, ACCOUNTING_RULE_ID, ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, 
RULE_START_DATE, LAST_PERIOD_TO_CREDIT, INVENTORY_ITEM_ID, INVENTORY_ITEM, 
MEMO_LINE_ID, MEMO_LINE_NAME, TAX_PRECEDENCE, TAX_RATE, 
TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, 
SALES_TAX_ID, SALES_TAX_CODE, LOCATION_SEGMENT_ID, VAT_TAX_ID, 
SALES_ORDER_SOURCE, SALES_ORDER, SALES_ORDER_REVISION, SALES_ORDER_LINE, 
SALES_ORDER_DATE, MOVEMENT_ID, DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, 
ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, 
ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, 
ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, 
ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, 
INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, 
INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, 
INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, 
INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, 
REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, 
REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, 
REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, 
REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, 
UOM_NAME, WAREHOUSE_ID, WAREHOUSE_NAME, ORGANIZATION_NAME, 
TRANSLATED_DESCRIPTION, TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, 
SALES_TAX_FROM_POSTAL_CODE, TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
CTL.MEMO_LINE_ID ,  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL_TL T,  
AR_MEMO_LINES_ALL_B B,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_B_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   (+)AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL.LINE_TYPE = 'FREIGHT' AND  
CTL.LINK_TO_CUST_TRX_LINE_ID is NULL
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_NOTES_VW 
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_AR_NOTES_VW ( NOTE_ID, 
CUSTOMER_TRX_ID, NOTE_DATE, SOURCE, AL_NOTE_TYPE_MEANING, 
MEMO, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, 
CREATION_DATE, CREATED_BY ) AS SELECT  
N.NOTE_ID ,  
N.CUSTOMER_TRX_ID ,  
N.CREATION_DATE ,  
N.NOTE_TYPE ,  
L.MEANING ,  
N.TEXT ,  
N.LAST_UPDATED_BY ,  
N.LAST_UPDATE_DATE ,  
N.LAST_UPDATE_LOGIN ,  
N.CREATION_DATE ,  
N.CREATED_BY  
FROM  
AR_NOTES N,  
AR_LOOKUPS L  
WHERE  
L.LOOKUP_TYPE = 'NOTE_TYPE' AND  
N.NOTE_TYPE = L.LOOKUP_CODE
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_CHARGES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_CHARGES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, PREVIOUS_CUST_TRX_LINE_NUM, LINE_NUMBER, 
LINE_TYPE, DESCRIPTION, QUANTITY_ORDERED, QUANTITY_CREDITED, 
QUANTITY, UNIT_STANDARD_PRICE, UNIT_SELLING_PRICE, REVENUE_AMOUNT, 
AMOUNT, AMOUNT_INCLUDES_TAX_FLAG, UOM_CODE, REASON_CODE, 
REASON_CODE_MEANING, ACCOUNTING_RULE_ID, ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, 
RULE_START_DATE, LAST_PERIOD_TO_CREDIT, INVENTORY_ITEM_ID, INVENTORY_ITEM, 
MEMO_LINE_ID, MEMO_LINE_NAME, TAX_PRECEDENCE, TAX_RATE, 
TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, 
SALES_TAX_ID, SALES_TAX_CODE, LOCATION_SEGMENT_ID, VAT_TAX_ID, 
SALES_ORDER_SOURCE, SALES_ORDER, SALES_ORDER_REVISION, SALES_ORDER_LINE, 
SALES_ORDER_DATE, MOVEMENT_ID, DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, 
ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, 
ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, 
ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, 
ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, 
INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, 
INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, 
INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, 
INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, 
REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, 
REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, 
REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, 
REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, 
UOM_NAME, WAREHOUSE_ID, WAREHOUSE_NAME, ORGANIZATION_NAME, 
TRANSLATED_DESCRIPTION, TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, 
SALES_TAX_FROM_POSTAL_CODE, TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
CTL.MEMO_LINE_ID ,  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL_TL T,  
AR_MEMO_LINES_ALL_B B,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_B_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   (+)AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL.LINE_TYPE = 'CHARGES' AND  
CTL.LINK_TO_CUST_TRX_LINE_ID is NULL
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUSTOMER_TRX_LINES_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUSTOMER_TRX_LINES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINK_TO_CUST_TRX_LINE, PREVIOUS_CUST_TRX_LINE_NUM, 
INITIAL_CUSTOMER_TRX_LINE_NUM, LINE_NUMBER, LINE_TYPE, DESCRIPTION, 
QUANTITY_ORDERED, QUANTITY_CREDITED, QUANTITY_INVOICED, UNIT_STANDARD_PRICE, 
UNIT_SELLING_PRICE, REVENUE_AMOUNT, EXTENDED_AMOUNT, AMOUNT_INCLUDES_TAX_FLAG, 
UOM_CODE, REASON_CODE, REASON_CODE_MEANING, ACCOUNTING_RULE_ID, 
ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, RULE_START_DATE, LAST_PERIOD_TO_CREDIT, 
INVENTORY_ITEM_ID, INVENTORY_ITEM, MEMO_LINE_ID, MEMO_LINE_NAME, 
TAX_PRECEDENCE, TAX_RATE, TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, 
TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, SALES_TAX_ID, SALES_TAX_CODE, 
LOCATION_SEGMENT_ID, VAT_TAX_ID, SALES_ORDER_SOURCE, SALES_ORDER, 
SALES_ORDER_REVISION, SALES_ORDER_LINE, SALES_ORDER_DATE, MOVEMENT_ID, 
DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, ATTRIBUTE_CATEGORY, ATTRIBUTE1, 
ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, 
ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, 
ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, 
ATTRIBUTE14, ATTRIBUTE15, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, 
INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, 
INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, 
INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, 
INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, 
REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, 
REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, 
REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, 
REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, UOM_NAME, WAREHOUSE_ID, 
WAREHOUSE_NAME, ORGANIZATION_NAME, VAT_TAX_CODE, TRANSLATED_DESCRIPTION, 
TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, SALES_TAX_FROM_POSTAL_CODE, 
TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE, LINK_TO_LINE_CONTEXT, LINK_TO_LINE_ATTRIBUTE1, 
LINK_TO_LINE_ATTRIBUTE2, LINK_TO_LINE_ATTRIBUTE3, LINK_TO_LINE_ATTRIBUTE4, LINK_TO_LINE_ATTRIBUTE5, 
LINK_TO_LINE_ATTRIBUTE6, LINK_TO_LINE_ATTRIBUTE7, LINK_TO_LINE_ATTRIBUTE8, LINK_TO_LINE_ATTRIBUTE9, 
LINK_TO_LINE_ATTRIBUTE10, LINK_TO_LINE_ATTRIBUTE11, LINK_TO_LINE_ATTRIBUTE12, LINK_TO_LINE_ATTRIBUTE13, 
LINK_TO_LINE_ATTRIBUTE14, LINK_TO_LINE_ATTRIBUTE15 ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_LINK.LINE_NUMBER LINK_TO_CUST_TRX_LINE,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
NULL,  
--CTL_INI.LINE_NUMBER INITIAL_CUSTOMER_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
/*SEGMENT 1 IN TABLE MTL_SYSTEM_ITEMS */    CTL.MEMO_LINE_ID ,  
/* + MEMO_LINE_NAME*/  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
/* MTL_MOVEMENT_STATISTICS*/    CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
VAT.TAX_CODE ,  
CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE,  
CTL_LINK.INTERFACE_LINE_CONTEXT ,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE1,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE2,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE3,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE4,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE5,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE6,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE7,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE8,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE9,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE10,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE11,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE12,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE13,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE14,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE15  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
--MTL_UNITS_OF_MEASURE UOM_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL_TL T,  
AR_MEMO_LINES_ALL_B B,  
AR_VAT_TAX_ALL_B VAT,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
--- CHANGE BEGINS  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINK,  
--RA_CUSTOMER_TRX_LINES_ALL CTL_INI,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_B_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG,  
MTL_UNITS_OF_MEASURE UOM_LINK  
--MTL_UNITS_OF_MEASURE UOM_INI  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') /* 19-APR-2000 J RAUTIAINEN BR IMPLEMENTATION */ AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
--CTL_PREV.UOM_CODE = UOM_PREV.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.VAT_TAX_ID = VAT.VAT_TAX_ID(+) AND  
CTL.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
--- CHANGE BEGINS  
CTL_LINK.CUSTOMER_TRX_LINE_ID (+) = CTL.LINK_TO_CUST_TRX_LINE_ID AND  
--CTL_INI.CUSTOMER_TRX_LINE_ID (+) = CTL.INITIAL_CUSTOMER_TRX_LINE_ID  AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CT.ORG_ID = VAT.ORG_ID  AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL_LINK.UOM_CODE = UOM_LINK.UOM_CODE(+) AND  
--CTL_INI.UOM_CODE = UOM_INI.UOM_CODE(+) AND  
CTL.LINE_TYPE = 'LINE'
/


/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_FREIGHTLINES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_FREIGHTLINES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINK_TO_CUST_TRX_LINE, PREVIOUS_CUST_TRX_LINE_NUM, 
LINE_NUMBER, LINE_TYPE, DESCRIPTION, QUANTITY_ORDERED, 
QUANTITY_CREDITED, QUANTITY_INVOICED, UNIT_STANDARD_PRICE, UNIT_SELLING_PRICE, 
REVENUE_AMOUNT, AMOUNT, AMOUNT_INCLUDES_TAX_FLAG, UOM_CODE, 
REASON_CODE, REASON_CODE_MEANING, ACCOUNTING_RULE_ID, ACCOUNTING_RULE_DURATION, 
ACCOUNTING_RULE_NAME, RULE_START_DATE, LAST_PERIOD_TO_CREDIT, INVENTORY_ITEM_ID, 
INVENTORY_ITEM, MEMO_LINE_ID, MEMO_LINE_NAME, TAX_PRECEDENCE, 
TAX_RATE, TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, TAX_EXEMPT_REASON_CODE, 
TAX_EXEMPT_REASON_CODE_MEANING, SALES_TAX_ID, SALES_TAX_CODE, LOCATION_SEGMENT_ID, 
VAT_TAX_ID, SALES_ORDER_SOURCE, SALES_ORDER, SALES_ORDER_REVISION, 
SALES_ORDER_LINE, SALES_ORDER_DATE, MOVEMENT_ID, DEFAULT_USSGL_TRANSACTION_CODE, 
DEFAULT_USSGL_TRX_CODE_CONTEXT, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, 
ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, 
ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, 
ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, 
ATTRIBUTE15, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, 
INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, 
INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, 
INTERFACE_LINE_ATTRIBUTE15, REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, REFERENCE_LINE_ATTRIBUTE2, 
REFERENCE_LINE_ATTRIBUTE3, REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, REFERENCE_LINE_ATTRIBUTE6, 
REFERENCE_LINE_ATTRIBUTE7, REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, REFERENCE_LINE_ATTRIBUTE10, 
REFERENCE_LINE_ATTRIBUTE11, REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, REFERENCE_LINE_ATTRIBUTE14, 
REFERENCE_LINE_ATTRIBUTE15, UOM_NAME, WAREHOUSE_ID, WAREHOUSE_NAME, 
ORGANIZATION_NAME, TRANSLATED_DESCRIPTION, TAX_ITEM_EXCEPTION, TAX_EXEMPTION, 
SALES_TAX_TO_POSTAL_CODE, SALES_TAX_FROM_POSTAL_CODE, TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE, 
LINK_TO_LINE_CONTEXT, LINK_TO_LINE_ATTRIBUTE1, LINK_TO_LINE_ATTRIBUTE2, LINK_TO_LINE_ATTRIBUTE3, 
LINK_TO_LINE_ATTRIBUTE4, LINK_TO_LINE_ATTRIBUTE5, LINK_TO_LINE_ATTRIBUTE6, LINK_TO_LINE_ATTRIBUTE7, 
LINK_TO_LINE_ATTRIBUTE8, LINK_TO_LINE_ATTRIBUTE9, LINK_TO_LINE_ATTRIBUTE10, LINK_TO_LINE_ATTRIBUTE11, 
LINK_TO_LINE_ATTRIBUTE12, LINK_TO_LINE_ATTRIBUTE13, LINK_TO_LINE_ATTRIBUTE14, LINK_TO_LINE_ATTRIBUTE15
 ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_LINK.LINE_NUMBER LINK_TO_CUST_TRX_LINE,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
CTL.MEMO_LINE_ID ,  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE,  
CTL_LINK.INTERFACE_LINE_CONTEXT ,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE1,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE2,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE3,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE4,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE5,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE6,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE7,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE8,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE9,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE10,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE11,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE12,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE13,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE14,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE15  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL_TL T,  
AR_MEMO_LINES_ALL_B B,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINK,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_B_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG,  
MTL_UNITS_OF_MEASURE UOM_LINK  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
CTL_LINK.CUSTOMER_TRX_LINE_ID (+) = CTL.LINK_TO_CUST_TRX_LINE_ID AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   (+)AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL_LINK.UOM_CODE = UOM_LINK.UOM_CODE(+) AND  
CTL.LINE_TYPE = 'FREIGHT'
/
 

/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUST_TRX_TAXLINES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUST_TRX_TAXLINES_VW ( CUSTOMER_TRX_LINE_ID, 
CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINK_TO_CUST_TRX_LINE, PREVIOUS_CUST_TRX_LINE_NUM, 
INITIAL_CUSTOMER_TRX_LINE_NUM, LINE_NUMBER, LINE_TYPE, DESCRIPTION, 
QUANTITY_ORDERED, QUANTITY_CREDITED, QUANTITY_INVOICED, UNIT_STANDARD_PRICE, 
UNIT_SELLING_PRICE, REVENUE_AMOUNT, AMOUNT, AMOUNT_INCLUDES_TAX_FLAG, 
UOM_CODE, REASON_CODE, REASON_CODE_MEANING, ACCOUNTING_RULE_ID, 
ACCOUNTING_RULE_DURATION, ACCOUNTING_RULE_NAME, RULE_START_DATE, LAST_PERIOD_TO_CREDIT, 
INVENTORY_ITEM_ID, INVENTORY_ITEM, MEMO_LINE_ID, MEMO_LINE_NAME, 
TAX_PRECEDENCE, TAX_RATE, TAX_EXEMPT_FLAG, TAX_EXEMPT_NUMBER, 
TAX_EXEMPT_REASON_CODE, TAX_EXEMPT_REASON_CODE_MEANING, SALES_TAX_ID, SALES_TAX_CODE, 
LOCATION_SEGMENT_ID, VAT_TAX_ID, SALES_ORDER_SOURCE, SALES_ORDER, 
SALES_ORDER_REVISION, SALES_ORDER_LINE, SALES_ORDER_DATE, MOVEMENT_ID, 
DEFAULT_USSGL_TRANSACTION_CODE, DEFAULT_USSGL_TRX_CODE_CONTEXT, ATTRIBUTE_CATEGORY, ATTRIBUTE1, 
ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, 
ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, 
ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, 
ATTRIBUTE14, ATTRIBUTE15, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, 
INTERFACE_LINE_ATTRIBUTE2, INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, 
INTERFACE_LINE_ATTRIBUTE6, INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, 
INTERFACE_LINE_ATTRIBUTE10, INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, 
INTERFACE_LINE_ATTRIBUTE14, INTERFACE_LINE_ATTRIBUTE15, REFERENCE_LINE_CONTEXT, REFERENCE_LINE_ATTRIBUTE1, 
REFERENCE_LINE_ATTRIBUTE2, REFERENCE_LINE_ATTRIBUTE3, REFERENCE_LINE_ATTRIBUTE4, REFERENCE_LINE_ATTRIBUTE5, 
REFERENCE_LINE_ATTRIBUTE6, REFERENCE_LINE_ATTRIBUTE7, REFERENCE_LINE_ATTRIBUTE8, REFERENCE_LINE_ATTRIBUTE9, 
REFERENCE_LINE_ATTRIBUTE10, REFERENCE_LINE_ATTRIBUTE11, REFERENCE_LINE_ATTRIBUTE12, REFERENCE_LINE_ATTRIBUTE13, 
REFERENCE_LINE_ATTRIBUTE14, REFERENCE_LINE_ATTRIBUTE15, UOM_NAME, WAREHOUSE_ID, 
WAREHOUSE_NAME, ORGANIZATION_NAME, VAT_TAX_CODE, TRANSLATED_DESCRIPTION, 
TAX_ITEM_EXCEPTION, TAX_EXEMPTION, SALES_TAX_TO_POSTAL_CODE, SALES_TAX_FROM_POSTAL_CODE, 
TAX_ACCOUNT_NUMBER, LOCATION_SEGMENT_VALUE, LINK_TO_LINE_CONTEXT, LINK_TO_LINE_ATTRIBUTE1, 
LINK_TO_LINE_ATTRIBUTE2, LINK_TO_LINE_ATTRIBUTE3, LINK_TO_LINE_ATTRIBUTE4, LINK_TO_LINE_ATTRIBUTE5, 
LINK_TO_LINE_ATTRIBUTE6, LINK_TO_LINE_ATTRIBUTE7, LINK_TO_LINE_ATTRIBUTE8, LINK_TO_LINE_ATTRIBUTE9, 
LINK_TO_LINE_ATTRIBUTE10, LINK_TO_LINE_ATTRIBUTE11, LINK_TO_LINE_ATTRIBUTE12, LINK_TO_LINE_ATTRIBUTE13, 
LINK_TO_LINE_ATTRIBUTE14, LINK_TO_LINE_ATTRIBUTE15 ) AS SELECT  
CTL.CUSTOMER_TRX_LINE_ID ,  
CTL.CUSTOMER_TRX_ID ,  
CTL.LINK_TO_CUST_TRX_LINE_ID ,  
CTL_LINK.LINE_NUMBER LINK_TO_CUST_TRX_LINE,  
CTL_PREV.LINE_NUMBER PREVIOUS_CUST_TRX_LINE_NUM,  
NULL,  
--CTL_INI.LINE_NUMBER INITIAL_CUSTOMER_TRX_LINE_NUM,  
CTL.LINE_NUMBER ,  
CTL.LINE_TYPE ,  
CTL.DESCRIPTION ,  
CTL.QUANTITY_ORDERED ,  
CTL.QUANTITY_CREDITED,  
CTL.QUANTITY_INVOICED,  
CTL.UNIT_STANDARD_PRICE ,  
CTL.UNIT_SELLING_PRICE ,  
CTL.REVENUE_AMOUNT ,  
CTL.EXTENDED_AMOUNT ,  
NVL(CTL.AMOUNT_INCLUDES_TAX_FLAG,'DEFAULT') ,  
CTL.UOM_CODE ,  
CTL.REASON_CODE ,  
AL.MEANING REASON_CODE_MEANING,  
CTL.ACCOUNTING_RULE_ID ,  
CTL.ACCOUNTING_RULE_DURATION ,  
RR.NAME ACCOUNTING_RULE_NAME,  
CTL.RULE_START_DATE ,  
CTL.LAST_PERIOD_TO_CREDIT ,  
CTL.INVENTORY_ITEM_ID ,  
MSI.CONCATENATED_SEGMENTS  INVENTORY_ITEM,  
/*SEGMENT 1 IN TABLE MTL_SYSTEM_ITEMS */    CTL.MEMO_LINE_ID ,  
/* + MEMO_LINE_NAME*/  
T.NAME MEMO_LINE_NAME,  
CTL.TAX_PRECEDENCE ,  
CTL.TAX_RATE ,  
CTL.TAX_EXEMPT_FLAG ,  
CTL.TAX_EXEMPT_NUMBER ,  
CTL.TAX_EXEMPT_REASON_CODE ,  
AL_TAX_REASON.MEANING TAX_EXEMPT_REASON_CODE_MEANING,  
CTL.SALES_TAX_ID ,  
NULL SALES_TAX_CODE,  
CTL.LOCATION_SEGMENT_ID ,  
CTL.VAT_TAX_ID ,  
CTL.SALES_ORDER_SOURCE ,  
CTL.SALES_ORDER ,  
CTL.SALES_ORDER_REVISION ,  
CTL.SALES_ORDER_LINE ,  
CTL.SALES_ORDER_DATE ,  
CTL.MOVEMENT_ID ,  
/* MTL_MOVEMENT_STATISTICS*/    CTL.DEFAULT_USSGL_TRANSACTION_CODE ,  
CTL.DEFAULT_USSGL_TRX_CODE_CONTEXT ,  
CTL.ATTRIBUTE_CATEGORY,  
CTL.ATTRIBUTE1,  
CTL.ATTRIBUTE2,  
CTL.ATTRIBUTE3,  
CTL.ATTRIBUTE4,  
CTL.ATTRIBUTE5,  
CTL.ATTRIBUTE6,  
CTL.ATTRIBUTE7,  
CTL.ATTRIBUTE8,  
CTL.ATTRIBUTE9,  
CTL.ATTRIBUTE10,  
CTL.ATTRIBUTE11,  
CTL.ATTRIBUTE12,  
CTL.ATTRIBUTE13,  
CTL.ATTRIBUTE14,  
CTL.ATTRIBUTE15,  
CTL.INTERFACE_LINE_CONTEXT ,  
CTL.INTERFACE_LINE_ATTRIBUTE1,  
CTL.INTERFACE_LINE_ATTRIBUTE2,  
CTL.INTERFACE_LINE_ATTRIBUTE3,  
CTL.INTERFACE_LINE_ATTRIBUTE4,  
CTL.INTERFACE_LINE_ATTRIBUTE5,  
CTL.INTERFACE_LINE_ATTRIBUTE6,  
CTL.INTERFACE_LINE_ATTRIBUTE7,  
CTL.INTERFACE_LINE_ATTRIBUTE8,  
CTL.INTERFACE_LINE_ATTRIBUTE9,  
CTL.INTERFACE_LINE_ATTRIBUTE10,  
CTL.INTERFACE_LINE_ATTRIBUTE11,  
CTL.INTERFACE_LINE_ATTRIBUTE12,  
CTL.INTERFACE_LINE_ATTRIBUTE13,  
CTL.INTERFACE_LINE_ATTRIBUTE14,  
CTL.INTERFACE_LINE_ATTRIBUTE15,  
CTL_PREV.INTERFACE_LINE_CONTEXT ,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE1,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE2,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE3,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE4,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE5,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE6,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE7,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE8,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE9,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE10,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE11,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE12,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE13,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE14,  
CTL_PREV.INTERFACE_LINE_ATTRIBUTE15,  
UOM.UNIT_OF_MEASURE UOM_NAME,  
CTL.WAREHOUSE_ID ,  
HRORG.NAME WAREHOUSE_NAME ,  /* HR_ALL_ORGANIZATION_UNITS / AR_CUSTOMERS_V*/  
ORG.ORGANIZATION_NAME ,  
VAT.TAX_CODE ,  
CTL.TRANSLATED_DESCRIPTION,  
NULL TAX_ITEM_EXCEPTION,  
NULL TAX_EXEMPTION,  
NULL SALES_TAX_TO_POSTAL_CODE,  
NULL SALES_TAX_FROM_POSTAL_CODE,  
NULL TAX_ACCOUNT_NUMBER,  
NULL LOCATION_SEGMENT_VALUE,  
CTL_LINK.INTERFACE_LINE_CONTEXT ,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE1,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE2,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE3,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE4,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE5,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE6,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE7,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE8,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE9,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE10,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE11,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE12,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE13,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE14,  
CTL_LINK.INTERFACE_LINE_ATTRIBUTE15  
FROM  
AR_LOOKUPS AL_TAX,  
AR_LOOKUPS AL_CM_REASON,  
AR_LOOKUPS AL_INV_REASON,  
AR_LOOKUPS AL_TAX_REASON,  
RA_RULES RR,  
MTL_UNITS_OF_MEASURE UOM,  
--MTL_UNITS_OF_MEASURE UOM_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL_PREV,  
RA_CUSTOMER_TRX_LINES_ALL CTL,  
RA_CUSTOMER_TRX_ALL CT,  
RA_CUST_TRX_TYPES_ALL CTT,  
AR_MEMO_LINES_ALL_TL T,  
AR_MEMO_LINES_ALL_B B,  
AR_VAT_TAX_ALL_B VAT,  
ORG_ORGANIZATION_DEFINITIONS ORG,  
RA_ADDRESSES_ALL RADD,  
RA_SITE_USES_ALL SITE ,  
--- CHANGE BEGINS  
RA_CUSTOMER_TRX_LINES_ALL CTL_LINK,  
--RA_CUSTOMER_TRX_LINES_ALL CTL_INI,  
AR_LOOKUPS AL,  
MTL_SYSTEM_ITEMS_B_KFV MSI,  
HR_ALL_ORGANIZATION_UNITS HRORG,  
MTL_UNITS_OF_MEASURE UOM_LINK  
--MTL_UNITS_OF_MEASURE UOM_INI  
WHERE  
CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND  
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND  
CTT.TYPE NOT IN ('DEP', 'GUAR','BR') /* 19-APR-2000 J RAUTIAINEN BR IMPLEMENTATION */ AND  
CTL.PREVIOUS_CUSTOMER_TRX_LINE_ID = CTL_PREV.CUSTOMER_TRX_LINE_ID(+) AND  
CTL.UOM_CODE = UOM.UOM_CODE(+) AND  
--CTL_PREV.UOM_CODE = UOM_PREV.UOM_CODE(+) AND  
CTL.ACCOUNTING_RULE_ID = RR.RULE_ID(+) AND  
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND  
'INVOICING_REASON' = AL_INV_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_INV_REASON.LOOKUP_CODE(+) AND  
'CREDIT_MEMO_REASON' = AL_CM_REASON.LOOKUP_TYPE(+) AND  
CTL.REASON_CODE = AL_CM_REASON.LOOKUP_CODE(+) AND  
'TAX_REASON' = AL_TAX_REASON.LOOKUP_TYPE(+) AND  
CTL.TAX_EXEMPT_REASON_CODE = AL_TAX_REASON.LOOKUP_CODE(+) AND  
CTL.MEMO_LINE_ID = B.MEMO_LINE_ID(+) AND  
CTL.VAT_TAX_ID = VAT.VAT_TAX_ID(+) AND  
CTL.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND  
CT.BILL_TO_SITE_USE_ID = SITE.SITE_USE_ID AND  
SITE.ADDRESS_ID = RADD.ADDRESS_ID AND  
--- CHANGE BEGINS  
CTL_LINK.CUSTOMER_TRX_LINE_ID (+) = CTL.LINK_TO_CUST_TRX_LINE_ID AND  
--CTL_INI.CUSTOMER_TRX_LINE_ID (+) = CTL.INITIAL_CUSTOMER_TRX_LINE_ID  AND  
AL.LOOKUP_CODE (+) = CTL.REASON_CODE AND  
MSI.INVENTORY_ITEM_ID (+) = CTL.INVENTORY_ITEM_ID AND  
MSI.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
HRORG.ORGANIZATION_ID (+) = CTL.ORG_ID AND  
B.MEMO_LINE_ID = T.MEMO_LINE_ID (+) AND  
B.ORG_ID   =  T.ORG_ID  (+) AND  
CT.ORG_ID  = CTL.ORG_ID   AND  
CT.ORG_ID = RADD.ORG_ID (+)  AND  
CT.ORG_ID = SITE.ORG_ID (+) AND  
CT.ORG_ID = VAT.ORG_ID  AND  
CTL.ORG_ID = B.ORG_ID (+) AND  
CTL.ORG_ID = CTT.ORG_ID (+) AND  
CTL_LINK.UOM_CODE = UOM_LINK.UOM_CODE(+) AND  
--CTL_INI.UOM_CODE = UOM_INI.UOM_CODE(+) AND  
CTL.LINE_TYPE = 'TAX'
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_SALESREPS_LINES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_SALESREPS_LINES_VW ( CUSTOMER_TRX_ID, 
CUST_TRX_LINE_SALESREP_ID, SALESREP_NUMBER, CUSTOMER_TRX_LINE_ID, REVENUE_PERCENT_SPLIT, 
REVENUE_AMOUNT_SPLIT, NON_REVENUE_PERCENT_SPLIT, NON_REVENUE_AMOUNT_SPLIT, SALESREP_NAME, 
SALES_CREDIT_TYPE_NAME, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, 
INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, 
INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, 
INTERFACE_LINE_ATTRIBUTE15, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, 
ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, 
ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, 
ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, 
ATTRIBUTE15 ) AS SELECT  
TRX_LINE.CUSTOMER_TRX_ID,  
SCREDITS.CUST_TRX_LINE_SALESREP_ID,  
SALESREP.SALESREP_NUMBER ,  
SCREDITS.CUSTOMER_TRX_LINE_ID ,  
SCREDITS.REVENUE_PERCENT_SPLIT ,  
SCREDITS.REVENUE_AMOUNT_SPLIT ,  
SCREDITS.NON_REVENUE_PERCENT_SPLIT ,  
SCREDITS.NON_REVENUE_AMOUNT_SPLIT ,  
SALESREP.NAME,  
SCT.NAME SALES_CREDIT_TYPE_NAME,  
NULL INTERFACE_LINE_CONTEXT,  
NULL INTERFACE_LINE_ATTRIBUTE1,  
NULL INTERFACE_LINE_ATTRIBUTE2,  
NULL INTERFACE_LINE_ATTRIBUTE3,  
NULL INTERFACE_LINE_ATTRIBUTE4,  
NULL INTERFACE_LINE_ATTRIBUTE5,  
NULL INTERFACE_LINE_ATTRIBUTE6,  
NULL INTERFACE_LINE_ATTRIBUTE7,  
NULL INTERFACE_LINE_ATTRIBUTE8,  
NULL INTERFACE_LINE_ATTRIBUTE9,  
NULL INTERFACE_LINE_ATTRIBUTE10,  
NULL INTERFACE_LINE_ATTRIBUTE11,  
NULL INTERFACE_LINE_ATTRIBUTE12,  
NULL INTERFACE_LINE_ATTRIBUTE13,  
NULL INTERFACE_LINE_ATTRIBUTE14,  
NULL INTERFACE_LINE_ATTRIBUTE15,  
SCREDITS.ATTRIBUTE_CATEGORY ,  
SCREDITS.ATTRIBUTE1 ,  
SCREDITS.ATTRIBUTE2 ,  
SCREDITS.ATTRIBUTE3 ,  
SCREDITS.ATTRIBUTE4 ,  
SCREDITS.ATTRIBUTE5 ,  
SCREDITS.ATTRIBUTE6 ,  
SCREDITS.ATTRIBUTE7 ,  
SCREDITS.ATTRIBUTE8 ,  
SCREDITS.ATTRIBUTE9 ,  
SCREDITS.ATTRIBUTE10 ,  
SCREDITS.ATTRIBUTE11 ,  
SCREDITS.ATTRIBUTE12 ,  
SCREDITS.ATTRIBUTE13 ,  
SCREDITS.ATTRIBUTE14 ,  
SCREDITS.ATTRIBUTE15  
FROM  
JTF_RS_SALESREPS SALESREP ,  
JTF_RS_RESOURCE_EXTNS_VL RES,  
JTF_RS_SALESREPS PREV_SREP ,  
RA_CUST_TRX_LINE_SALESREPS_ALL  PREV_SCREDIT,  
RA_CUSTOMER_TRX_LINES_ALL TRX_LINE,  
RA_CUST_TRX_LINE_SALESREPS_ALL SCREDITS  ,  
SO_SALES_CREDIT_TYPES SCT  
WHERE  
SCREDITS.SALESREP_ID  = SALESREP.SALESREP_ID  AND  
SCREDITS.CUSTOMER_TRX_LINE_ID = TRX_LINE.CUSTOMER_TRX_LINE_ID (+) AND  
SCREDITS.PREV_CUST_TRX_LINE_SALESREP_ID = PREV_SCREDIT.CUST_TRX_LINE_SALESREP_ID(+) AND  
PREV_SCREDIT.SALESREP_ID = PREV_SREP.SALESREP_ID(+) AND  
TRX_LINE.ORG_ID (+) = SCREDITS.ORG_ID AND  
SALESREP.RESOURCE_ID = RES.RESOURCE_ID AND  
RES.CATEGORY IN ('EMPLOYEE','OTHER','PARTY','PARTNER','SUPPLIER_CONTACT') AND  
SALESREP.ORG_ID (+) = SCREDITS.ORG_ID AND  
SALESREP.SALES_CREDIT_TYPE_ID = SCT.SALES_CREDIT_TYPE_ID
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_SALESREPS_DEFAULT_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_SALESREPS_DEFAULT_VW ( CUSTOMER_TRX_ID, 
CUST_TRX_LINE_SALESREP_ID, SALESREP_NUMBER, CUSTOMER_TRX_LINE_ID, REVENUE_PERCENT_SPLIT, 
REVENUE_AMOUNT_SPLIT, NON_REVENUE_PERCENT_SPLIT, NON_REVENUE_AMOUNT_SPLIT, SALESREP_NAME, 
SALES_CREDIT_TYPE_NAME, INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE1, INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3, INTERFACE_LINE_ATTRIBUTE4, INTERFACE_LINE_ATTRIBUTE5, INTERFACE_LINE_ATTRIBUTE6, 
INTERFACE_LINE_ATTRIBUTE7, INTERFACE_LINE_ATTRIBUTE8, INTERFACE_LINE_ATTRIBUTE9, INTERFACE_LINE_ATTRIBUTE10, 
INTERFACE_LINE_ATTRIBUTE11, INTERFACE_LINE_ATTRIBUTE12, INTERFACE_LINE_ATTRIBUTE13, INTERFACE_LINE_ATTRIBUTE14, 
INTERFACE_LINE_ATTRIBUTE15, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, 
ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, 
ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, 
ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, 
ATTRIBUTE15 ) AS SELECT  
SCREDITS.CUSTOMER_TRX_ID,  
SCREDITS.CUST_TRX_LINE_SALESREP_ID,  
SALESREP.SALESREP_NUMBER ,  
SCREDITS.CUSTOMER_TRX_LINE_ID ,  
SCREDITS.REVENUE_PERCENT_SPLIT ,  
SCREDITS.REVENUE_AMOUNT_SPLIT ,  
SCREDITS.NON_REVENUE_PERCENT_SPLIT ,  
SCREDITS.NON_REVENUE_AMOUNT_SPLIT ,  
SALESREP.NAME,  
SCT.NAME SALES_CREDIT_TYPE_NAME,  
NULL INTERFACE_LINE_CONTEXT,  
NULL INTERFACE_LINE_ATTRIBUTE1,  
NULL INTERFACE_LINE_ATTRIBUTE2,  
NULL INTERFACE_LINE_ATTRIBUTE3,  
NULL INTERFACE_LINE_ATTRIBUTE4,  
NULL INTERFACE_LINE_ATTRIBUTE5,  
NULL INTERFACE_LINE_ATTRIBUTE6,  
NULL INTERFACE_LINE_ATTRIBUTE7,  
NULL INTERFACE_LINE_ATTRIBUTE8,  
NULL INTERFACE_LINE_ATTRIBUTE9,  
NULL INTERFACE_LINE_ATTRIBUTE10,  
NULL INTERFACE_LINE_ATTRIBUTE11,  
NULL INTERFACE_LINE_ATTRIBUTE12,  
NULL INTERFACE_LINE_ATTRIBUTE13,  
NULL INTERFACE_LINE_ATTRIBUTE14,  
NULL INTERFACE_LINE_ATTRIBUTE15,  
SCREDITS.ATTRIBUTE_CATEGORY ,  
SCREDITS.ATTRIBUTE1 ,  
SCREDITS.ATTRIBUTE2 ,  
SCREDITS.ATTRIBUTE3 ,  
SCREDITS.ATTRIBUTE4 ,  
SCREDITS.ATTRIBUTE5 ,  
SCREDITS.ATTRIBUTE6 ,  
SCREDITS.ATTRIBUTE7 ,  
SCREDITS.ATTRIBUTE8 ,  
SCREDITS.ATTRIBUTE9 ,  
SCREDITS.ATTRIBUTE10 ,  
SCREDITS.ATTRIBUTE11 ,  
SCREDITS.ATTRIBUTE12 ,  
SCREDITS.ATTRIBUTE13 ,  
SCREDITS.ATTRIBUTE14 ,  
SCREDITS.ATTRIBUTE15  
FROM  
JTF_RS_SALESREPS SALESREP ,  
JTF_RS_RESOURCE_EXTNS_VL RES,  
JTF_RS_SALESREPS PREV_SREP ,  
RA_CUST_TRX_LINE_SALESREPS_ALL  PREV_SCREDIT,  
RA_CUST_TRX_LINE_SALESREPS_ALL SCREDITS  ,  
SO_SALES_CREDIT_TYPES SCT  
WHERE  
SCREDITS.SALESREP_ID  = SALESREP.SALESREP_ID  AND  
SCREDITS.PREV_CUST_TRX_LINE_SALESREP_ID = PREV_SCREDIT.CUST_TRX_LINE_SALESREP_ID(+) AND  
PREV_SCREDIT.SALESREP_ID = PREV_SREP.SALESREP_ID(+) AND  
SALESREP.RESOURCE_ID = RES.RESOURCE_ID AND  
RES.CATEGORY IN ('EMPLOYEE','OTHER','PARTY','PARTNER','SUPPLIER_CONTACT') AND  
SALESREP.ORG_ID (+) = SCREDITS.ORG_ID AND  
SALESREP.SALES_CREDIT_TYPE_ID = SCT.SALES_CREDIT_TYPE_ID AND  
SCREDITS.CUSTOMER_TRX_LINE_ID IS NULL
/

/*----------------------------------------------------------------------*/
--      Create View WM_RA_CUSTOMER_TRX_QRY_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_RA_CUSTOMER_TRX_QRY_VW ( ROW_ID, CUSTOMER_TRX_ID, 
TRX_NUMBER, OLD_TRX_NUMBER, CT_RELATED_TRX_NUMBER, CT_MODEL_TRX_NUMBER, 
TRX_DATE, TERM_DUE_DATE, PREVIOUS_CUSTOMER_TRX_ID, INITIAL_CUSTOMER_TRX_ID, 
RELATED_BATCH_SOURCE_ID, RELATED_CUSTOMER_TRX_ID, CUST_TRX_TYPE_ID, BATCH_ID, 
BATCH_SOURCE_ID, REASON_CODE, REASON_CODE_MEANING, TERM_ID, 
PRIMARY_SALESREP_ID, AGREEMENT_ID, CREDIT_METHOD_FOR_RULES, CREDIT_METHOD_FOR_INSTALLMENTS, 
RECEIPT_METHOD_ID, INVOICING_RULE_ID, INVOICING_RULE_NAME, SHIP_VIA, 
FOB_POINT, FINANCE_CHARGES, COMPLETE_FLAG, CUSTOMER_BANK_ACCOUNT_ID, 
RECURRED_FROM_TRX_NUMBER, STATUS_TRX, DEFAULT_TAX_EXEMPT_FLAG, SOLD_TO_CUSTOMER_ID, 
SOLD_TO_SITE_USE_ID, SOLD_TO_CONTACT_ID, BILL_TO_CUSTOMER_ID, BILL_TO_SITE_USE_ID, 
RAA_BILL_TO_ADDRESS_ID, BILL_TO_CONTACT_ID, BILL_TO_TAXPAYER_ID, SHIP_TO_CUSTOMER_ID, 
SHIP_TO_SITE_USE_ID, RAA_SHIP_TO_ADDRESS_ID, SHIP_TO_CONTACT_ID, SHIP_TO_TAXPAYER_ID, 
REMIT_TO_ADDRESS_ID, INVOICE_CURRENCY_CODE, CREATED_FROM, SET_OF_BOOKS_ID, 
PRINTING_ORIGINAL_DATE, PRINTING_LAST_PRINTED, PRINTING_OPTION, PRINTING_COUNT, 
PRINTING_PENDING, LAST_PRINTED_SEQUENCE_NUM, PURCHASE_ORDER, PURCHASE_ORDER_REVISION, 
PURCHASE_ORDER_DATE, CUSTOMER_REFERENCE, CUSTOMER_REFERENCE_DATE, COMMENTS, 
INTERNAL_NOTES, EXCHANGE_RATE_TYPE, EXCHANGE_DATE, EXCHANGE_RATE, 
TERRITORY_ID, END_DATE_COMMITMENT, START_DATE_COMMITMENT, ORIG_SYSTEM_BATCH_NAME, 
SHIP_DATE_ACTUAL, WAYBILL_NUMBER, DOC_SEQUENCE_ID, DOC_SEQUENCE_VALUE, 
PAYING_CUSTOMER_ID, PAYING_SITE_USE_ID, ATTRIBUTE_CATEGORY, ATTRIBUTE1, 
ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, 
ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, 
ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, 
ATTRIBUTE14, ATTRIBUTE15, HEADER_ATTRIBUTE_CATEGORY, HEADER_ATTRIBUTE1, 
HEADER_ATTRIBUTE2, HEADER_ATTRIBUTE3, HEADER_ATTRIBUTE4, HEADER_ATTRIBUTE5, 
HEADER_ATTRIBUTE6, HEADER_ATTRIBUTE7, HEADER_ATTRIBUTE8, HEADER_ATTRIBUTE9, 
HEADER_ATTRIBUTE10, HEADER_ATTRIBUTE11, HEADER_ATTRIBUTE12, HEADER_ATTRIBUTE13, 
HEADER_ATTRIBUTE14, HEADER_ATTRIBUTE15, GLOBAL_ATTRIBUTE1, GLOBAL_ATTRIBUTE2, 
GLOBAL_ATTRIBUTE3, GLOBAL_ATTRIBUTE4, GLOBAL_ATTRIBUTE5, GLOBAL_ATTRIBUTE6, 
GLOBAL_ATTRIBUTE7, GLOBAL_ATTRIBUTE8, GLOBAL_ATTRIBUTE9, GLOBAL_ATTRIBUTE10, 
GLOBAL_ATTRIBUTE11, GLOBAL_ATTRIBUTE12, GLOBAL_ATTRIBUTE13, GLOBAL_ATTRIBUTE14, 
GLOBAL_ATTRIBUTE15, GLOBAL_ATTRIBUTE16, GLOBAL_ATTRIBUTE17, GLOBAL_ATTRIBUTE18, 
GLOBAL_ATTRIBUTE19, GLOBAL_ATTRIBUTE20, GLOBAL_ATTRIBUTE_CATEGORY, DEFAULT_USSGL_TRANSACTION_CODE, 
DEFAULT_USSGL_TRX_CODE_CONTEXT, LAST_UPDATE_DATE, LAST_UPDATED_BY, CREATION_DATE, 
CREATED_BY, LAST_UPDATE_LOGIN, REQUEST_ID, RAC_BILL_TO_CUSTOMER_NAME, 
RAC_BILL_TO_CUSTOMER_NUM, SU_BILL_TO_LOCATION, RAA_BILL_TO_ADDRESS1, RAA_BILL_TO_ADDRESS2, 
RAA_BILL_TO_ADDRESS3_DB, RAA_BILL_TO_ADDRESS3, RAA_BILL_TO_CITY, RAA_BILL_TO_COUNTY, 
RAA_BILL_TO_STATE, RAA_BILL_TO_PROVINCE, RAA_BILL_TO_POSTAL_CODE, FT_BILL_TO_COUNTRY, 
RAA_BILL_TO_CONCAT_ADDRESS, RACO_BILL_TO_CONTACT_NAME, RAC_SHIP_TO_CUSTOMER_NAME, RAC_SHIP_TO_CUSTOMER_NUM, 
SU_SHIP_TO_LOCATION, RAA_SHIP_TO_ADDRESS1, RAA_SHIP_TO_ADDRESS2, RAA_SHIP_TO_ADDRESS3_DB, 
RAA_SHIP_TO_ADDRESS3, RAA_SHIP_TO_CITY, RAA_SHIP_TO_COUNTY, RAA_SHIP_TO_STATE, 
RAA_SHIP_TO_PROVINCE, RAA_SHIP_TO_POSTAL_CODE, FT_SHIP_TO_COUNTRY, RAA_SHIP_TO_CONCAT_ADDRESS, 
RACO_SHIP_TO_CONTACT_NAME, RAC_SOLD_TO_CUSTOMER_NAME, RAC_SOLD_TO_CUSTOMER_NUM, RAC_PAYING_CUSTOMER_NAME, 
RAC_PAYING_CUSTOMER_NUM, SU_PAYING_CUSTOMER_LOCATION, RAA_REMIT_TO_ADDRESS1, RAA_REMIT_TO_ADDRESS2, 
RAA_REMIT_TO_ADDRESS3_DB, RAA_REMIT_TO_ADDRESS3, RAA_REMIT_TO_CITY, RAA_REMIT_TO_COUNTY, 
RAA_REMIT_TO_STATE, RAA_REMIT_TO_PROVINCE, RAA_REMIT_TO_POSTAL_CODE, FT_REMIT_TO_COUNTRY, 
RAA_CONCAT_REMIT_TO_ADDRESS, APBA_BANK_ACCOUNT_NAME, APBA_BANK_ACCOUNT_NUM, APBA_INACTIVE_DATE, 
APB_CUSTOMER_BANK_NAME, APB_CUSTOMER_BANK_BRANCH_NAME, ARM_RECEIPT_METHOD_NAME, ARM_PAYMENT_TYPE_CODE, 
ARC_CREATION_METHOD_CODE, BATCH_SOURCE_NAME, BS_AUTO_TRX_NUMBERING_FLAG, BS_COPY_DOC_NUMBER_FLAG, 
RAB_BATCH_NAME, CTT_TYPE_NAME, CTT_CLASS, RAS_PRIMARY_SALESREP_NAME, 
RAS_PRIMARY_SALESREP_NUM, RAT_TERM_NAME, RAT_TERM_IN_USE_FLAG, SOA_AGREEMENT_NAME, 
OF_SHIP_VIA_NAME, OF_ORGANIZATION_ID, AL_FOB_MEANING, AL_DEFAULT_TAX_EXEMPT_FLAG, 
CT_REFERENCE, GD_GL_DATE, GDCT_USER_EXCHANGE_RATE_TYPE, CT_INVOICE_FOR_CB, 
PS_DISPUTE_AMOUNT, PS_DISPUTE_DATE, DH_MAX_DISPUTE_DATE, REV_RECOG_RUN_FLAG, 
POSTED_FLAG, SELECTED_FOR_PAYMENT_FLAG, ACTIVITY_FLAG, CTT_POST_TO_GL_FLAG, 
CTT_OPEN_RECEIVABLES_FLAG, CTT_ALLOW_FREIGHT_FLAG, CTT_CREATION_SIGN, CTT_ALLOW_OVERAPPLICATION_FLAG, 
CTT_NATURAL_APP_ONLY_FLAG, CTT_TAX_CALCULATION_FLAG, CTT_DEFAULT_STATUS, CTT_DEFAULT_TERM, 
CTT_DEFAULT_PRINTING_OPTION, RULES_FLAG, PRINTED_FLAG, CM_AGAINST_TRX_FLAG, 
SITE_STATUS, CUSTOMER_STATUS, OVERRIDE_TERMS, COMMITMENTS_EXIST_FLAG, 
AGREEMENTS_EXIST_FLAG, ATCHMT_FLAG, GLOBAL_ATTRIBUTE21, GLOBAL_ATTRIBUTE22, 
GLOBAL_ATTRIBUTE23, GLOBAL_ATTRIBUTE24, GLOBAL_ATTRIBUTE25, GLOBAL_ATTRIBUTE26, 
GLOBAL_ATTRIBUTE27, GLOBAL_ATTRIBUTE28, GLOBAL_ATTRIBUTE29, GLOBAL_ATTRIBUTE30, 
BATCH_SOURCE_TYPE, PAYMENT_SERVER_ORDER_NUM, SETS_OF_BOOKS_NAME, TRX_TYPE_NAME, 
TERRITORY, TERM_NAME, RELATED_BATCH_SOURCE_NAME, CONS_BILLING_NUM, 
APPROVAL_CODE, ADDRESS_VERIFICATION_CODE, ORGANIZATION_NAME ) AS SELECT
CT.ROWID ,
CT.CUSTOMER_TRX_ID ,
CT.TRX_NUMBER ,
CT.OLD_TRX_NUMBER ,
CT_REL.TRX_NUMBER ,
CT.RECURRED_FROM_TRX_NUMBER ,
CT.TRX_DATE ,
ARPT_SQL_FUNC_UTIL.GET_FIRST_REAL_DUE_DATE(CT.CUSTOMER_TRX_ID,  CT.TERM_ID,  CT.TRX_DATE) ,
/* RESOLVE THESE FOREIGN KEY REFERENCES */ CT.PREVIOUS_CUSTOMER_TRX_ID ,
CT.INITIAL_CUSTOMER_TRX_ID ,
CT.RELATED_BATCH_SOURCE_ID ,
CT.RELATED_CUSTOMER_TRX_ID ,
CT.CUST_TRX_TYPE_ID ,
CT.BATCH_ID ,
CT.BATCH_SOURCE_ID ,
CT.REASON_CODE ,
CT.REASON_CODE ,
CT.TERM_ID ,
CT.PRIMARY_SALESREP_ID ,
CT.AGREEMENT_ID ,
CT.CREDIT_METHOD_FOR_RULES ,
CT.CREDIT_METHOD_FOR_INSTALLMENTS ,
CT.RECEIPT_METHOD_ID ,
CT.INVOICING_RULE_ID ,
NULL,
CT.SHIP_VIA ,
CT.FOB_POINT ,
CT.FINANCE_CHARGES ,
CT.COMPLETE_FLAG ,
CT.CUSTOMER_BANK_ACCOUNT_ID ,
CT.RECURRED_FROM_TRX_NUMBER ,
CT.STATUS_TRX ,
CT.DEFAULT_TAX_EXEMPT_FLAG ,
CT.SOLD_TO_CUSTOMER_ID ,
CT.SOLD_TO_SITE_USE_ID ,
CT.SOLD_TO_CONTACT_ID ,
CT.BILL_TO_CUSTOMER_ID ,
CT.BILL_TO_SITE_USE_ID ,
RAA_BILL.CUST_ACCT_SITE_ID ,
CT.BILL_TO_CONTACT_ID ,
RAC_BILL_PARTY.JGZZ_FISCAL_CODE ,
CT.SHIP_TO_CUSTOMER_ID ,
CT.SHIP_TO_SITE_USE_ID ,
RAA_SHIP.CUST_ACCT_SITE_ID ,
CT.SHIP_TO_CONTACT_ID ,
RAC_SHIP_PARTY.JGZZ_FISCAL_CODE ,
CT.REMIT_TO_ADDRESS_ID ,
/* END FOREIGN KEY REFERENCES TO BE RESOLVED */ CT.INVOICE_CURRENCY_CODE ,
CT.CREATED_FROM ,
CT.SET_OF_BOOKS_ID ,
CT.PRINTING_ORIGINAL_DATE ,
CT.PRINTING_LAST_PRINTED ,
CT.PRINTING_OPTION ,
CT.PRINTING_COUNT ,
CT.PRINTING_PENDING ,
CT.LAST_PRINTED_SEQUENCE_NUM ,
CT.PURCHASE_ORDER ,
CT.PURCHASE_ORDER_REVISION ,
CT.PURCHASE_ORDER_DATE ,
CT.CUSTOMER_REFERENCE ,
CT.CUSTOMER_REFERENCE_DATE ,
CT.COMMENTS ,
CT.INTERNAL_NOTES ,
CT.EXCHANGE_RATE_TYPE ,
CT.EXCHANGE_DATE ,
CT.EXCHANGE_RATE ,
CT.TERRITORY_ID ,
CT.END_DATE_COMMITMENT ,
CT.START_DATE_COMMITMENT ,
CT.ORIG_SYSTEM_BATCH_NAME ,
CT.SHIP_DATE_ACTUAL ,
CT.WAYBILL_NUMBER ,
CT.DOC_SEQUENCE_ID ,
CT.DOC_SEQUENCE_VALUE ,
CT.PAYING_CUSTOMER_ID ,
CT.PAYING_SITE_USE_ID ,
CT.ATTRIBUTE_CATEGORY ,
CT.ATTRIBUTE1 ,
CT.ATTRIBUTE2 ,
CT.ATTRIBUTE3 ,
CT.ATTRIBUTE4 ,
CT.ATTRIBUTE5 ,
CT.ATTRIBUTE6 ,
CT.ATTRIBUTE7 ,
CT.ATTRIBUTE8 ,
CT.ATTRIBUTE9 ,
CT.ATTRIBUTE10 ,
CT.ATTRIBUTE11 ,
CT.ATTRIBUTE12 ,
CT.ATTRIBUTE13 ,
CT.ATTRIBUTE14 ,
CT.ATTRIBUTE15 ,
CT.INTERFACE_HEADER_CONTEXT ,
CT.INTERFACE_HEADER_ATTRIBUTE1 ,
CT.INTERFACE_HEADER_ATTRIBUTE2 ,
CT.INTERFACE_HEADER_ATTRIBUTE3 ,
CT.INTERFACE_HEADER_ATTRIBUTE4 ,
CT.INTERFACE_HEADER_ATTRIBUTE5 ,
CT.INTERFACE_HEADER_ATTRIBUTE6 ,
CT.INTERFACE_HEADER_ATTRIBUTE7 ,
CT.INTERFACE_HEADER_ATTRIBUTE8 ,
CT.INTERFACE_HEADER_ATTRIBUTE9 ,
CT.INTERFACE_HEADER_ATTRIBUTE10 ,
CT.INTERFACE_HEADER_ATTRIBUTE11 ,
CT.INTERFACE_HEADER_ATTRIBUTE12 ,
CT.INTERFACE_HEADER_ATTRIBUTE13 ,
CT.INTERFACE_HEADER_ATTRIBUTE14 ,
CT.INTERFACE_HEADER_ATTRIBUTE15 ,
CT.GLOBAL_ATTRIBUTE1 ,
CT.GLOBAL_ATTRIBUTE2 ,
CT.GLOBAL_ATTRIBUTE3 ,
CT.GLOBAL_ATTRIBUTE4 ,
CT.GLOBAL_ATTRIBUTE5 ,
CT.GLOBAL_ATTRIBUTE6 ,
CT.GLOBAL_ATTRIBUTE7 ,
CT.GLOBAL_ATTRIBUTE8 ,
CT.GLOBAL_ATTRIBUTE9 ,
CT.GLOBAL_ATTRIBUTE10 ,
CT.GLOBAL_ATTRIBUTE11 ,
CT.GLOBAL_ATTRIBUTE12 ,
CT.GLOBAL_ATTRIBUTE13 ,
CT.GLOBAL_ATTRIBUTE14 ,
CT.GLOBAL_ATTRIBUTE15 ,
CT.GLOBAL_ATTRIBUTE16 ,
CT.GLOBAL_ATTRIBUTE17 ,
CT.GLOBAL_ATTRIBUTE18 ,
CT.GLOBAL_ATTRIBUTE19 ,
CT.GLOBAL_ATTRIBUTE20 ,
CT.GLOBAL_ATTRIBUTE_CATEGORY ,
CT.DEFAULT_USSGL_TRANSACTION_CODE ,
CT.DEFAULT_USSGL_TRX_CODE_CONTEXT ,
CT.LAST_UPDATE_DATE ,
CT.LAST_UPDATED_BY ,
CT.CREATION_DATE ,
CT.CREATED_BY ,
CT.LAST_UPDATE_LOGIN ,
CT.REQUEST_ID ,
SUBSTRB(RAC_BILL_PARTY.PARTY_NAME,
1,
50) ,
RAC_BILL.ACCOUNT_NUMBER ,
SU_BILL.LOCATION ,
RAA_BILL_LOC.ADDRESS1 ,
RAA_BILL_LOC.ADDRESS2 ,
RAA_BILL_LOC.ADDRESS3 ,
DECODE( RAA_BILL.CUST_ACCT_SITE_ID,  NULL,  NULL,  ARH_ADDR_PKG.FORMAT_LAST_ADDRESS_LINE(RAA_BILL_LOC.ADDRESS_STYLE,
RAA_BILL_LOC.ADDRESS3,
RAA_BILL_LOC.ADDRESS4,
RAA_BILL_LOC.CITY,
RAA_BILL_LOC.COUNTY,
RAA_BILL_LOC.STATE,
RAA_BILL_LOC.PROVINCE,
FT_BILL.TERRITORY_SHORT_NAME,
RAA_BILL_LOC.POSTAL_CODE) ) ,
RAA_BILL_LOC.CITY ,
RAA_BILL_LOC.COUNTY ,
RAA_BILL_LOC.STATE ,
RAA_BILL_LOC.PROVINCE ,
RAA_BILL_LOC.POSTAL_CODE ,
FT_BILL.TERRITORY_SHORT_NAME ,
DECODE( RAA_BILL.CUST_ACCT_SITE_ID,
NULL,
NULL,
ARH_ADDR_PKG.ARXTW_FORMAT_ADDRESS(RAA_BILL_LOC.ADDRESS_STYLE,
RAA_BILL_LOC.ADDRESS1,
RAA_BILL_LOC.ADDRESS2,
RAA_BILL_LOC.ADDRESS3,
RAA_BILL_LOC.ADDRESS4,
RAA_BILL_LOC.CITY,
RAA_BILL_LOC.COUNTY,
RAA_BILL_LOC.STATE,
RAA_BILL_LOC.PROVINCE,
RAA_BILL_LOC.POSTAL_CODE,
FT_BILL.TERRITORY_SHORT_NAME) ) ,
DECODE(SUBSTRB(RACO_BILL_PARTY.PERSON_LAST_NAME,
1,
50),
NULL,
SUBSTRB(RACO_BILL_PARTY.PERSON_FIRST_NAME,
1,
40),
SUBSTRB(RACO_BILL_PARTY.PERSON_LAST_NAME,
1,
50) ||',
' || SUBSTRB(RACO_BILL_PARTY.PERSON_FIRST_NAME,
1,
40)) ,
SUBSTRB(RAC_SHIP_PARTY.PARTY_NAME,
1,
50) ,
RAC_SHIP.ACCOUNT_NUMBER ,
SU_SHIP.LOCATION ,
RAA_SHIP_LOC.ADDRESS1 ,
RAA_SHIP_LOC.ADDRESS2 ,
RAA_SHIP_LOC.ADDRESS3 ,
DECODE( RAA_SHIP.CUST_ACCT_SITE_ID,
NULL,
NULL,
ARH_ADDR_PKG.FORMAT_LAST_ADDRESS_LINE(RAA_SHIP_LOC.ADDRESS_STYLE,
RAA_SHIP_LOC.ADDRESS3,
RAA_SHIP_LOC.ADDRESS4,
RAA_SHIP_LOC.CITY,
RAA_SHIP_LOC.COUNTY,
RAA_SHIP_LOC.STATE,
RAA_SHIP_LOC.PROVINCE,
FT_SHIP.TERRITORY_SHORT_NAME,
RAA_SHIP_LOC.POSTAL_CODE) ) ,
RAA_SHIP_LOC.CITY ,
RAA_SHIP_LOC.COUNTY ,
RAA_SHIP_LOC.STATE ,
RAA_SHIP_LOC.PROVINCE ,
RAA_SHIP_LOC.POSTAL_CODE ,
FT_SHIP.TERRITORY_SHORT_NAME ,
DECODE( RAA_SHIP.CUST_ACCT_SITE_ID,
NULL,
NULL,
ARH_ADDR_PKG.ARXTW_FORMAT_ADDRESS(RAA_SHIP_LOC.ADDRESS_STYLE,
RAA_SHIP_LOC.ADDRESS1,
RAA_SHIP_LOC.ADDRESS2,
RAA_SHIP_LOC.ADDRESS3,
RAA_SHIP_LOC.ADDRESS4,
RAA_SHIP_LOC.CITY,
RAA_SHIP_LOC.COUNTY,
RAA_SHIP_LOC.STATE,
RAA_SHIP_LOC.PROVINCE,
RAA_SHIP_LOC.POSTAL_CODE,
FT_SHIP.TERRITORY_SHORT_NAME) ) ,
DECODE(SUBSTRB(RACO_SHIP_PARTY.PERSON_LAST_NAME,
1,
50),
NULL,
SUBSTRB(RACO_SHIP_PARTY.PERSON_FIRST_NAME,
1,
40),
SUBSTRB(RACO_SHIP_PARTY.PERSON_LAST_NAME,
1,
50) || ',' || SUBSTRB(RACO_SHIP_PARTY.PERSON_FIRST_NAME,
1,
40)) ,
SUBSTRB(RAC_SOLD_PARTY.PARTY_NAME,
1,
50) ,
RAC_SOLD.ACCOUNT_NUMBER ,
SUBSTRB(RAC_PAYING_PARTY.PARTY_NAME,
1,
50) ,
RAC_PAYING.ACCOUNT_NUMBER ,
SU_PAYING.LOCATION ,
RAA_REMIT_LOC.ADDRESS1 ,
RAA_REMIT_LOC.ADDRESS2 ,
RAA_REMIT_LOC.ADDRESS3 ,
DECODE( RAA_REMIT.CUST_ACCT_SITE_ID,
NULL,
NULL,
ARH_ADDR_PKG.FORMAT_LAST_ADDRESS_LINE(RAA_REMIT_LOC.ADDRESS_STYLE,
RAA_REMIT_LOC.ADDRESS3,
RAA_REMIT_LOC.ADDRESS4,
RAA_REMIT_LOC.CITY,
RAA_REMIT_LOC.COUNTY,
RAA_REMIT_LOC.STATE,
RAA_REMIT_LOC.PROVINCE,
FT_REMIT.TERRITORY_SHORT_NAME,
RAA_REMIT_LOC.POSTAL_CODE) ) ,
RAA_REMIT_LOC.CITY ,
RAA_REMIT_LOC.COUNTY ,
RAA_REMIT_LOC.STATE ,
RAA_REMIT_LOC.PROVINCE ,
RAA_REMIT_LOC.POSTAL_CODE ,
FT_REMIT.TERRITORY_SHORT_NAME ,
DECODE( RAA_REMIT.CUST_ACCT_SITE_ID,
NULL,
NULL,
ARH_ADDR_PKG.ARXTW_FORMAT_ADDRESS(RAA_REMIT_LOC.ADDRESS_STYLE,
RAA_REMIT_LOC.ADDRESS1,
RAA_REMIT_LOC.ADDRESS2,
RAA_REMIT_LOC.ADDRESS3,
RAA_REMIT_LOC.ADDRESS4,
RAA_REMIT_LOC.CITY,
RAA_REMIT_LOC.COUNTY,
RAA_REMIT_LOC.STATE,
RAA_REMIT_LOC.PROVINCE,
RAA_REMIT_LOC.POSTAL_CODE,
FT_REMIT.TERRITORY_SHORT_NAME) ) ,
APBA.BANK_ACCOUNT_NAME ,
DECODE (NVL(FND_PROFILE.VALUE('AR_MASK_BANK_ACCOUNT_NUMBERS'),
'F'),
'N',
APBA.BANK_ACCOUNT_NUM,
'F',
RPAD(SUBSTR(APBA.BANK_ACCOUNT_NUM,
1,
4),
LENGTH(APBA.BANK_ACCOUNT_NUM),
'*'),
'L',
LPAD(SUBSTR(APBA.BANK_ACCOUNT_NUM,
-4),
LENGTH(APBA.BANK_ACCOUNT_NUM),
'*')) ,
APBA.INACTIVE_DATE ,
APB.BANK_NAME ,
APB.BANK_BRANCH_NAME ,
ARM.NAME ,
ARM.PAYMENT_TYPE_CODE ,
ARC.CREATION_METHOD_CODE ,
BS.NAME ,
BS.AUTO_TRX_NUMBERING_FLAG ,
BS.COPY_DOC_NUMBER_FLAG ,
RAB.NAME ,
CTT.NAME ,
CTT.TYPE ,
ARPT_SQL_FUNC_UTIL.get_salesrep_name_number(CT.PRIMARY_SALESREP_ID,
'NAME') ,
ARPT_SQL_FUNC_UTIL.get_salesrep_name_number(CT.PRIMARY_SALESREP_ID,
'NUMBER') ,
RAT.NAME ,
RAT.IN_USE ,
SOA.NAME ,
ORF.DESCRIPTION ,
ORF.ORGANIZATION_ID ,
AL_FOB.MEANING ,
AL_TAX.MEANING ,
ARPT_SQL_FUNC_UTIL.GET_REFERENCE(CT.ROWID) ,
GD.GL_DATE ,
GDCT.USER_CONVERSION_TYPE ,
ARPT_SQL_FUNC_UTIL.GET_CB_INVOICE( CT.CUSTOMER_TRX_ID,
CTT.TYPE) ,
ARPT_SQL_FUNC_UTIL.GET_DISPUTE_AMOUNT( CT.CUSTOMER_TRX_ID,
CTT.TYPE,
CTT.ACCOUNTING_AFFECT_FLAG ) ,
ARPT_SQL_FUNC_UTIL.GET_DISPUTE_DATE( CT.CUSTOMER_TRX_ID,
CTT.TYPE,
CTT.ACCOUNTING_AFFECT_FLAG ) ,
ARPT_SQL_FUNC_UTIL.GET_MAX_DISPUTE_DATE( CT.CUSTOMER_TRX_ID,
CTT.TYPE,
CTT.ACCOUNTING_AFFECT_FLAG ) ,
ARPT_SQL_FUNC_UTIL.GET_REVENUE_RECOG_RUN_FLAG(CT.CUSTOMER_TRX_ID,
CT.INVOICING_RULE_ID) ,
ARPT_SQL_FUNC_UTIL.GET_POSTED_FLAG( CT.CUSTOMER_TRX_ID,
CTT.POST_TO_GL,
CT.COMPLETE_FLAG ) ,
ARPT_SQL_FUNC_UTIL.GET_SELECTED_FOR_PAYMENT_FLAG( CT.CUSTOMER_TRX_ID,
CTT.ACCOUNTING_AFFECT_FLAG,
CT.COMPLETE_FLAG ) ,
ARPT_SQL_FUNC_UTIL.GET_ACTIVITY_FLAG( CT.CUSTOMER_TRX_ID,
CTT.ACCOUNTING_AFFECT_FLAG,
CT.COMPLETE_FLAG,
CTT.TYPE,
CT.INITIAL_CUSTOMER_TRX_ID,
CT.PREVIOUS_CUSTOMER_TRX_ID ) ,
CTT.POST_TO_GL ,
CTT.ACCOUNTING_AFFECT_FLAG ,
CTT.ALLOW_FREIGHT_FLAG ,
CTT.CREATION_SIGN ,
CTT.ALLOW_OVERAPPLICATION_FLAG ,
CTT.NATURAL_APPLICATION_ONLY_FLAG ,
CTT.TAX_CALCULATION_FLAG ,
CTT.DEFAULT_STATUS ,
CTT.DEFAULT_TERM ,
CTT.DEFAULT_PRINTING_OPTION ,
DECODE(CT.INVOICING_RULE_ID,
NULL,
'N',
'Y') ,
DECODE(CT.PRINTING_LAST_PRINTED,
NULL,
'N',
'Y') ,
DECODE(CT.PREVIOUS_CUSTOMER_TRX_ID,
NULL,
'N',
'Y') ,
SU_BILL.STATUS ,
RAC_BILL.STATUS ,
ARPT_SQL_FUNC_UTIL.GET_OVERRIDE_TERMS(CT.BILL_TO_CUSTOMER_ID,
CT.BILL_TO_SITE_USE_ID) ,
DECODE(CT.INITIAL_CUSTOMER_TRX_ID,
NULL,
DECODE(CTT.TYPE,
'DEP',
'N',
'GUAR',
'N',
'CB',
'N',
'Y' ),
'Y') ,
DECODE(CT.AGREEMENT_ID,
NULL,
DECODE(CTT.TYPE,
'CM',
'N',
ARPT_SQL_FUNC_UTIL.GET_AGREEMENTS_EXIST_FLAG( CT.BILL_TO_CUSTOMER_ID,
CT.TRX_DATE) ),
'Y') ,
FND_ATTACHMENT_UTIL_PKG.GET_ATCHMT_EXISTS('RA_CUSTOMER_TRX',
CT.CUSTOMER_TRX_ID) ,
CT.GLOBAL_ATTRIBUTE21 ,
CT.GLOBAL_ATTRIBUTE22 ,
CT.GLOBAL_ATTRIBUTE23 ,
CT.GLOBAL_ATTRIBUTE24 ,
CT.GLOBAL_ATTRIBUTE15 ,
CT.GLOBAL_ATTRIBUTE26 ,
CT.GLOBAL_ATTRIBUTE27 ,
CT.GLOBAL_ATTRIBUTE28 ,
CT.GLOBAL_ATTRIBUTE29 ,
CT.GLOBAL_ATTRIBUTE30 ,
BS.BATCH_SOURCE_TYPE,
CT.PAYMENT_SERVER_ORDER_NUM,
SOB.NAME,
CTY.NAME,
FT_BILL.TERRITORY_SHORT_NAME,
RAT.NAME,
RBS.NAME,
NULL,
CT.APPROVAL_CODE,
CT.ADDRESS_VERIFICATION_CODE,
ORG.ORGANIZATION_NAME
FROM
RA_CUST_TRX_LINE_GL_DIST_ALL GD,
RA_CUSTOMER_TRX_ALL CT,
HZ_CUST_ACCOUNTS RAC_BILL,
HZ_PARTIES RAC_BILL_PARTY,
HZ_CUST_ACCOUNTS RAC_SHIP,
HZ_PARTIES RAC_SHIP_PARTY,
HZ_CUST_ACCOUNTS RAC_SOLD,
HZ_PARTIES RAC_SOLD_PARTY,
HZ_CUST_ACCOUNTS RAC_PAYING,
HZ_PARTIES RAC_PAYING_PARTY,
HZ_CUST_SITE_USES_ALL SU_BILL,
HZ_CUST_SITE_USES_ALL SU_SHIP,
HZ_CUST_SITE_USES_ALL SU_PAYING,
FND_TERRITORIES_VL FT_BILL,
FND_TERRITORIES_VL FT_SHIP,
FND_TERRITORIES_VL FT_REMIT,
HZ_CUST_ACCT_SITES_ALL RAA_BILL,
HZ_PARTY_SITES RAA_BILL_PS,
HZ_LOCATIONS RAA_BILL_LOC,
HZ_CUST_ACCT_SITES_ALL RAA_SHIP,
HZ_PARTY_SITES RAA_SHIP_PS,
HZ_LOCATIONS RAA_SHIP_LOC,
HZ_CUST_ACCT_SITES_ALL RAA_REMIT,
HZ_PARTY_SITES RAA_REMIT_PS,
HZ_LOCATIONS RAA_REMIT_LOC,
HZ_CUST_ACCOUNT_ROLES RACO_SHIP,
HZ_PARTIES RACO_SHIP_PARTY,
HZ_RELATIONSHIPS RACO_SHIP_REL,
HZ_CUST_ACCOUNT_ROLES RACO_BILL,
HZ_PARTIES RACO_BILL_PARTY,
HZ_RELATIONSHIPS RACO_BILL_REL,
AP_BANK_ACCOUNTS_ALL APBA,
AP_BANK_BRANCHES APB,
AR_RECEIPT_METHODS ARM,
AR_RECEIPT_CLASSES ARC,
RA_BATCH_SOURCES_ALL BS,
RA_BATCHES_ALL RAB,
RA_CUST_TRX_TYPES_ALL CTT,
RA_TERMS RAT,
SO_AGREEMENTS SOA,
ORG_FREIGHT ORF,
GL_DAILY_CONVERSION_TYPES GDCT,
RA_CUSTOMER_TRX_ALL CT_REL,
AR_LOOKUPS AL_FOB,
AR_LOOKUPS AL_TAX,
org_organization_definitions org,
ra_batch_sources_all rbs,
gl_sets_of_books sob,
ra_cust_trx_types_all cty
WHERE
CT.CUSTOMER_TRX_ID = GD.CUSTOMER_TRX_ID AND
'REC' = GD.ACCOUNT_CLASS AND
'Y' = GD.LATEST_REC_FLAG AND
CT.RELATED_CUSTOMER_TRX_ID = CT_REL.CUSTOMER_TRX_ID(+) AND
CT.BILL_TO_CUSTOMER_ID = RAC_BILL.CUST_ACCOUNT_ID AND
RAC_BILL.PARTY_ID = RAC_BILL_PARTY.PARTY_ID AND
CT.SHIP_TO_CUSTOMER_ID = RAC_SHIP.CUST_ACCOUNT_ID(+) AND
RAC_SHIP.PARTY_ID = RAC_SHIP_PARTY.PARTY_ID(+) AND
CT.SOLD_TO_CUSTOMER_ID = RAC_SOLD.CUST_ACCOUNT_ID(+) AND
RAC_SOLD.PARTY_ID = RAC_SOLD_PARTY.PARTY_ID(+) AND
CT.PAYING_CUSTOMER_ID = RAC_PAYING.CUST_ACCOUNT_ID(+) AND
RAC_PAYING.PARTY_ID = RAC_PAYING_PARTY.PARTY_ID(+) AND
CT.BILL_TO_SITE_USE_ID = SU_BILL.SITE_USE_ID AND
CT.SHIP_TO_SITE_USE_ID = SU_SHIP.SITE_USE_ID(+) AND
CT.PAYING_SITE_USE_ID = SU_PAYING.SITE_USE_ID(+) AND
SU_BILL.CUST_ACCT_SITE_ID = RAA_BILL.CUST_ACCT_SITE_ID AND
RAA_BILL.PARTY_SITE_ID = RAA_BILL_PS.PARTY_SITE_ID AND
RAA_BILL_LOC.LOCATION_ID = RAA_BILL_PS.LOCATION_ID AND
SU_SHIP.CUST_ACCT_SITE_ID = RAA_SHIP.CUST_ACCT_SITE_ID(+) AND
RAA_SHIP.PARTY_SITE_ID = RAA_SHIP_PS.PARTY_SITE_ID(+) AND
RAA_SHIP_LOC.LOCATION_ID(+) = RAA_SHIP_PS.LOCATION_ID AND
CT.BILL_TO_CONTACT_ID = RACO_BILL.CUST_ACCOUNT_ROLE_ID(+) AND
RACO_BILL.PARTY_ID = RACO_BILL_REL.PARTY_ID(+) and
raco_bill_rel.subject_table_name(+) = 'HZ_PARTIES' and
raco_bill_rel.object_table_name(+) = 'HZ_PARTIES' and
raco_bill_rel.directional_flag(+) = 'F' AND
RACO_BILL.ROLE_TYPE(+) = 'CONTACT' AND
RACO_BILL_REL.SUBJECT_ID = RACO_BILL_PARTY.PARTY_ID(+) AND
CT.SHIP_TO_CONTACT_ID = RACO_SHIP.CUST_ACCOUNT_ROLE_ID(+) AND
RACO_SHIP.PARTY_ID = RACO_SHIP_REL.PARTY_ID(+) and
raco_ship_rel.subject_table_name(+) = 'HZ_PARTIES' and
raco_ship_rel.object_table_name(+) = 'HZ_PARTIES' and
raco_ship_rel.directional_flag(+) = 'F' AND
RACO_SHIP.ROLE_TYPE(+) = 'CONTACT' AND
RACO_SHIP_REL.SUBJECT_ID = RACO_SHIP_PARTY.PARTY_ID(+) AND
CT.REMIT_TO_ADDRESS_ID = RAA_REMIT.CUST_ACCT_SITE_ID(+) AND
RAA_REMIT.PARTY_SITE_ID = RAA_REMIT_PS.PARTY_SITE_ID(+) AND
RAA_REMIT_LOC.LOCATION_ID(+) = RAA_REMIT_PS.LOCATION_ID AND
RAA_BILL_LOC.COUNTRY = FT_BILL.TERRITORY_CODE(+) AND
RAA_SHIP_LOC.COUNTRY = FT_SHIP.TERRITORY_CODE(+) AND
RAA_REMIT_LOC.COUNTRY = FT_REMIT.TERRITORY_CODE(+) AND
CT.CUSTOMER_BANK_ACCOUNT_ID = APBA.BANK_ACCOUNT_ID(+) AND
APBA.BANK_BRANCH_ID = APB.BANK_BRANCH_ID(+) AND
CT.RECEIPT_METHOD_ID = ARM.RECEIPT_METHOD_ID(+) AND
ARM.RECEIPT_CLASS_ID = ARC.RECEIPT_CLASS_ID(+) AND
CT.BATCH_SOURCE_ID = BS.BATCH_SOURCE_ID AND
CT.ORG_ID = BS.ORG_ID AND
CT.RELATED_BATCH_SOURCE_ID = RBS.BATCH_SOURCE_ID (+) AND
CT.ORG_ID = RBS.ORG_ID (+) AND
CT.BATCH_ID = RAB.BATCH_ID(+) AND
CT.CUST_TRX_TYPE_ID = CTT.CUST_TRX_TYPE_ID AND
CT.ORG_ID = CTT.ORG_ID AND
CTT.TYPE <> 'BR' /* 19-APR-2000 J Rautiainen BR Implementation */ AND
CT.TERM_ID = RAT.TERM_ID(+) AND
CT.AGREEMENT_ID = SOA.AGREEMENT_ID(+) AND
CT.EXCHANGE_RATE_TYPE = GDCT.CONVERSION_TYPE(+) AND
'FOB' = AL_FOB.LOOKUP_TYPE(+) AND
CT.FOB_POINT = AL_FOB.LOOKUP_CODE(+) AND
CT.SHIP_VIA = ORF.FREIGHT_CODE(+) AND
CT.ORG_ID = ORF.ORGANIZATION_ID(+) AND
'TAX_CONTROL_FLAG' = AL_TAX.LOOKUP_TYPE(+) AND
CT.DEFAULT_TAX_EXEMPT_FLAG = AL_TAX.LOOKUP_CODE(+) AND
CT.ORG_ID = ORG.ORGANIZATION_ID (+) AND
CT.SET_OF_BOOKS_ID = SOB.SET_OF_BOOKS_ID (+) AND
CT.CUST_TRX_TYPE_ID = CTY.CUST_TRX_TYPE_ID (+) AND
CT.ORG_ID = CTY.ORG_ID (+)
/

SHOW ERRORS

