/*  ***************************************************************************
    *    $Date:   24 Sep 2001 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   TCS  $
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for Order Status outbound in Application Schema  
    * Program Name:         wm_from_orderstatus_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for Order Status Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     24-SEP-02	   Rajib Naha		   Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_orderstatus_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."

/*----------------------------------------------------------------------*/
--      CREATE VIEW WM_OS_QRY_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_OS_QRY_VW ( ROW_ID, 
CREATION_DATE, COMMENTS, ACCEPTANCE_REQUIRED_FLAG, ACCEPTANCE_DUE_DATE, 
USER_HOLD_FLAG, CANCEL_FLAG, FIRM_STATUS_LOOKUP_CODE, FROZEN_FLAG, 
ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE5, 
ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE10, ATTRIBUTE11, 
ATTRIBUTE13, ATTRIBUTE14, AMOUNT_LIMIT, MIN_RELEASE_AMOUNT, 
QUOTATION_CLASS_CODE, ATTRIBUTE12, ATTRIBUTE15, APPROVAL_REQUIRED_FLAG, 
CLOSED_CODE, SHIP_VIA_LOOKUP_CODE, FREIGHT_TERMS_LOOKUP_CODE, RATE_TYPE, 
RATE, FROM_TYPE_LOOKUP_CODE, END_DATE, AUTHORIZATION_STATUS, 
REVISED_DATE, NOTE_TO_AUTHORIZER, NOTE_TO_VENDOR, PRINT_COUNT, 
VENDOR_ORDER_NUM, REPLY_DATE, LAST_UPDATE_DATE, PO_DOCUMENT_NUM, 
SEGMENT2, SEGMENT4, END_DATE_ACTIVE, CREATED_BY, 
VENDOR_ID, VENDOR_SITE_ID, ATTRIBUTE6, ATTRIBUTE9, 
VENDOR_CONTACT_ID, SHIP_TO_LOCATION_ID, BILL_TO_LOCATION_ID, TERMS_ID, 
FOB_LOOKUP_CODE, PO_STATUS, CURRENCY_CODE, RATE_DATE, 
FROM_HEADER_ID, START_DATE, BLANKET_TOTAL_AMOUNT, REVISION_NUM, 
APPROVED_FLAG, APPROVED_DATE, NOTE_TO_RECEIVER, PRINTED_DATE, 
CONFIRMING_ORDER_FLAG, REPLY_METHOD_LOOKUP_CODE, PO_HEADER_ID, AGENT_ID, 
TYPE_LOOKUP_CODE, LAST_UPDATED_BY, SUMMARY_FLAG, ENABLED_FLAG, 
SEGMENT3, SEGMENT5, START_DATE_ACTIVE, LAST_UPDATE_LOGIN, 
GOVERNMENT_CONTEXT, PROGRAM_APPLICATION_ID, PROGRAM_ID, PROGRAM_UPDATE_DATE, 
REQUEST_ID, USSGL_TRANSACTION_CODE, CLOSED_DATE, FIRM_DATE, 
ATTRIBUTE_CATEGORY, ATTRIBUTE4, RFQ_CLOSE_DATE, QUOTE_TYPE_LOOKUP_CODE, 
QUOTE_WARNING_DELAY_UNIT, QUOTE_WARNING_DELAY, QUOTE_VENDOR_QUOTE_NUMBER, AGENT_NAME, 
DOC_TYPE_NAME, CAN_PREPARER_APPROVE_FLAG, SECURITY_LEVEL_CODE, VENDOR_NAME, 
TYPE_1099, VAT_CODE, VENDOR_SITE_CODE, SUPPLIER_ADDRESS_LINE1, 
SUPPLIER_ADDRESS_LINE2, SUPPLIER_ADDRESS_LINE3, SUPPLIER_CITY, SUPPLIER_STATE, 
SUPPLIER_ZIP, SUPPLIER_COUNTRY, SUPPLIER_PHONE, SUPPLIER_FAX, 
VENDOR_CONTACT, PAYMENT_TERMS, SHIP_TO_LOCATION, BILL_TO_LOCATION, 
DISP_RATE_TYPE, CREATION_DATE_DISP, STATUS, FOB_DSP, 
FREIGHT_TERMS_DSP, SUPPLY_AGREEMENT_FLAG, GLOBAL_ATTRIBUTE_CATEGORY, GLOBAL_ATTRIBUTE1, 
GLOBAL_ATTRIBUTE2, GLOBAL_ATTRIBUTE3, GLOBAL_ATTRIBUTE4, GLOBAL_ATTRIBUTE5, 
GLOBAL_ATTRIBUTE6, GLOBAL_ATTRIBUTE7, GLOBAL_ATTRIBUTE8, GLOBAL_ATTRIBUTE9, 
GLOBAL_ATTRIBUTE10, GLOBAL_ATTRIBUTE11, GLOBAL_ATTRIBUTE12, GLOBAL_ATTRIBUTE13, 
GLOBAL_ATTRIBUTE14, GLOBAL_ATTRIBUTE15, GLOBAL_ATTRIBUTE16, GLOBAL_ATTRIBUTE17, 
GLOBAL_ATTRIBUTE18, GLOBAL_ATTRIBUTE19, GLOBAL_ATTRIBUTE20, WF_ITEM_TYPE, 
WF_ITEM_KEY, PCARD_ID, PRICE_UPDATE_TOLERANCE, PAY_ON_CODE, 
PAY_ON_DSP, SHIP_TO_ADDRESS_LINE_1, SHIP_TO_ADDRESS_LINE_2, SHIP_TO_ADDRESS_LINE_3, 
SHIP_TO_TOWN_OR_CITY, SHIP_TO_REGION_1, SHIP_TO_REGION_2, SHIP_TO_REGION_3, 
SHIP_TO_COUNTRY, SHIP_TO_POSTAL_CODE, BILL_TO_ADDRESS_LINE_1, BILL_TO_ADDRESS_LINE_2, 
BILL_TO_ADDRESS_LINE_3, BILL_TO_TOWN_OR_CITY, BILL_TO_REGION_1, BILL_TO_REGION_2, 
BILL_TO_REGION_3, BILL_TO_COUNTRY, BILL_TO_POSTAL_CODE, ORGANIZATION_NAME ) AS SELECT  
POH.ROWID ,  
POH.CREATION_DATE ,  
POH.COMMENTS ,  
POH.ACCEPTANCE_REQUIRED_FLAG ,  
POH.ACCEPTANCE_DUE_DATE ,  
POH.USER_HOLD_FLAG ,  
POH.CANCEL_FLAG ,  
POH.FIRM_STATUS_LOOKUP_CODE ,  
POH.FROZEN_FLAG ,  
POH.ATTRIBUTE1 ,  
POH.ATTRIBUTE2 ,  
POH.ATTRIBUTE3 ,  
POH.ATTRIBUTE5 ,  
POH.ATTRIBUTE7 ,  
POH.ATTRIBUTE8 ,  
POH.ATTRIBUTE10 ,  
POH.ATTRIBUTE11 ,  
POH.ATTRIBUTE13 ,  
POH.ATTRIBUTE14 ,  
POH.AMOUNT_LIMIT ,  
POH.MIN_RELEASE_AMOUNT ,  
POH.QUOTATION_CLASS_CODE ,  
POH.ATTRIBUTE12 ,  
POH.ATTRIBUTE15 ,  
POH.APPROVAL_REQUIRED_FLAG ,  
POH.CLOSED_CODE ,  
POH.SHIP_VIA_LOOKUP_CODE ,  
POH.FREIGHT_TERMS_LOOKUP_CODE ,  
POH.RATE_TYPE ,  
POH.RATE ,  
POH.FROM_TYPE_LOOKUP_CODE ,  
POH.END_DATE ,  
POH.AUTHORIZATION_STATUS ,  
POH.REVISED_DATE ,  
POH.NOTE_TO_AUTHORIZER ,  
POH.NOTE_TO_VENDOR ,  
POH.PRINT_COUNT ,  
POH.VENDOR_ORDER_NUM ,  
POH.REPLY_DATE ,  
POH.LAST_UPDATE_DATE ,  
POH.SEGMENT1 ,  
POH.SEGMENT2 ,  
POH.SEGMENT4 ,  
POH.END_DATE_ACTIVE ,  
POH.CREATED_BY ,  
POH.VENDOR_ID ,  
POH.VENDOR_SITE_ID ,  
POH.ATTRIBUTE6 ,  
POH.ATTRIBUTE9 ,  
POH.VENDOR_CONTACT_ID ,  
POH.SHIP_TO_LOCATION_ID ,  
POH.BILL_TO_LOCATION_ID ,  
POH.TERMS_ID ,  
POH.FOB_LOOKUP_CODE ,  
WM_ORDER_STATUS_PKG.GET_PO_STATUS(POH.PO_HEADER_ID) ,  
POH.CURRENCY_CODE ,  
POH.RATE_DATE ,  
POH.FROM_HEADER_ID ,  
POH.START_DATE ,  
POH.BLANKET_TOTAL_AMOUNT ,  
POH.REVISION_NUM ,  
POH.APPROVED_FLAG ,  
POH.APPROVED_DATE ,  
POH.NOTE_TO_RECEIVER ,  
POH.PRINTED_DATE ,  
POH.CONFIRMING_ORDER_FLAG ,  
POH.REPLY_METHOD_LOOKUP_CODE ,  
POH.PO_HEADER_ID ,  
POH.AGENT_ID ,  
POH.TYPE_LOOKUP_CODE ,  
POH.LAST_UPDATED_BY ,  
POH.SUMMARY_FLAG ,  
POH.ENABLED_FLAG ,  
POH.SEGMENT3 ,  
POH.SEGMENT5 ,  
POH.START_DATE_ACTIVE ,  
POH.LAST_UPDATE_LOGIN ,  
POH.GOVERNMENT_CONTEXT ,  
POH.PROGRAM_APPLICATION_ID ,  
POH.PROGRAM_ID ,  
POH.PROGRAM_UPDATE_DATE ,  
POH.REQUEST_ID ,  
POH.USSGL_TRANSACTION_CODE ,  
POH.CLOSED_DATE ,  
POH.FIRM_DATE ,  
POH.ATTRIBUTE_CATEGORY ,  
POH.ATTRIBUTE4 ,  
POH.RFQ_CLOSE_DATE ,  
POH.QUOTE_TYPE_LOOKUP_CODE ,  
POH.QUOTE_WARNING_DELAY_UNIT ,  
POH.QUOTE_WARNING_DELAY ,  
POH.QUOTE_VENDOR_QUOTE_NUMBER ,  
P.FULL_NAME ,  
PDT.TYPE_NAME ,  
PDT.CAN_PREPARER_APPROVE_FLAG ,  
PDT.SECURITY_LEVEL_CODE ,  
V.VENDOR_NAME ,  
V.TYPE_1099 ,  
V.VAT_CODE ,  
VS.VENDOR_SITE_CODE ,  
VS.ADDRESS_LINE1 ,  
VS.ADDRESS_LINE2 ,  
VS.ADDRESS_LINE3 ,  
VS.CITY ,  
VS.STATE ,  
VS.ZIP ,  
VS.COUNTRY ,  
'('||VS.AREA_CODE||') '||VS.PHONE ,  
'('||VS.FAX_AREA_CODE||') '||VS.FAX ,  
DECODE(POH.VENDOR_CONTACT_ID,  
NULL,  
NULL,  
VC.LAST_NAME||',  
'|| VC.FIRST_NAME) ,  
AT.NAME ,  
HRL1.LOCATION_CODE ,  
HRL2.LOCATION_CODE ,  
GLDC.USER_CONVERSION_TYPE ,  
POH.CREATION_DATE ,  
WM_ORDER_STATUS_PKG.GET_PO_STATUS(POH.PO_HEADER_ID) ,  
POLC2.DISPLAYED_FIELD ,  
POLC3.DISPLAYED_FIELD ,  
POH.SUPPLY_AGREEMENT_FLAG ,  
POH.GLOBAL_ATTRIBUTE_CATEGORY ,  
POH.GLOBAL_ATTRIBUTE1 ,  
POH.GLOBAL_ATTRIBUTE2 ,  
POH.GLOBAL_ATTRIBUTE3 ,  
POH.GLOBAL_ATTRIBUTE4 ,  
POH.GLOBAL_ATTRIBUTE5 ,  
POH.GLOBAL_ATTRIBUTE6 ,  
POH.GLOBAL_ATTRIBUTE7 ,  
POH.GLOBAL_ATTRIBUTE8 ,  
POH.GLOBAL_ATTRIBUTE9 ,  
POH.GLOBAL_ATTRIBUTE10 ,  
POH.GLOBAL_ATTRIBUTE11 ,  
POH.GLOBAL_ATTRIBUTE12 ,  
POH.GLOBAL_ATTRIBUTE13 ,  
POH.GLOBAL_ATTRIBUTE14 ,  
POH.GLOBAL_ATTRIBUTE15 ,  
POH.GLOBAL_ATTRIBUTE16 ,  
POH.GLOBAL_ATTRIBUTE17 ,  
POH.GLOBAL_ATTRIBUTE18 ,  
POH.GLOBAL_ATTRIBUTE19 ,  
POH.GLOBAL_ATTRIBUTE20 ,  
POH.WF_ITEM_TYPE ,  
POH.WF_ITEM_KEY ,  
POH.PCARD_ID ,  
POH.PRICE_UPDATE_TOLERANCE ,  
POH.PAY_ON_CODE ,  
POLC4.DISPLAYED_FIELD,  
LOC1.ADDRESS_LINE_1,  
LOC1.ADDRESS_LINE_2,  
LOC1.ADDRESS_LINE_3,  
LOC1.TOWN_OR_CITY,  
LOC1.REGION_1,  
LOC1.REGION_2,  
LOC1.REGION_3,  
LOC1.COUNTRY,  
LOC1.POSTAL_CODE,  
LOC2.ADDRESS_LINE_1,  
LOC2.ADDRESS_LINE_2,  
LOC2.ADDRESS_LINE_3,  
LOC2.TOWN_OR_CITY,  
LOC2.REGION_1,  
LOC2.REGION_2,  
LOC2.REGION_3,  
LOC2.COUNTRY,  
LOC2.POSTAL_CODE,
HOU.NAME   
FROM  
PO_DOCUMENT_TYPES_ALL_B PDT,  
PO_DOCUMENT_TYPES_ALL_TL T,  
PO_LOOKUP_CODES POLC,  
PO_LOOKUP_CODES POLC2,  
PO_LOOKUP_CODES POLC3,  
PO_LOOKUP_CODES POLC4,  
GL_DAILY_CONVERSION_TYPES GLDC,  
AP_TERMS AT,  
PER_PEOPLE_F P,  
PO_VENDORS V,  
PO_VENDOR_SITES_ALL VS,  
PO_VENDOR_CONTACTS VC,  
HR_LOCATIONS_ALL_TL HRL1,  
HR_LOCATIONS_ALL LOC1,  
HR_LOCATIONS_ALL_TL HRL2,  
HR_LOCATIONS_ALL LOC2,  
PO_HEADERS_ALL POH,
HR_ALL_ORGANIZATION_UNITS HOU
WHERE  
POH.AGENT_ID = P.PERSON_ID AND  
TRUNC(SYSDATE) BETWEEN P.EFFECTIVE_START_DATE AND  
P.EFFECTIVE_END_DATE AND  
P.EMPLOYEE_NUMBER IS NOT NULL AND  
( ( PDT.DOCUMENT_TYPE_CODE in ( 'PO','PA') AND  
PDT.DOCUMENT_SUBTYPE = POH.TYPE_LOOKUP_CODE ) ) AND  
V.VENDOR_ID (+) = POH.VENDOR_ID AND  
VS.VENDOR_SITE_ID (+)= POH.VENDOR_SITE_ID AND  
VC.VENDOR_CONTACT_ID (+) = POH.VENDOR_CONTACT_ID AND  
AT.TERM_ID (+) = POH.TERMS_ID AND  
HRL1.LOCATION_ID (+) = POH.SHIP_TO_LOCATION_ID AND  
HRL1.LANGUAGE(+) = USERENV('LANG') AND  
HRL1.LOCATION_ID = LOC1.LOCATION_ID (+) AND  
HRL2.LOCATION_ID (+) = POH.BILL_TO_LOCATION_ID AND  
HRL2.LANGUAGE(+) = USERENV('LANG') AND  
HRL2.LOCATION_ID = LOC2.LOCATION_ID (+) AND  
GLDC.CONVERSION_TYPE (+) = POH.RATE_TYPE AND  
NVL(POH.AUTHORIZATION_STATUS,'INCOMPLETE') = POLC.LOOKUP_CODE(+) AND  
POLC.LOOKUP_TYPE(+) = 'AUTHORIZATION STATUS' AND  
POLC2.LOOKUP_CODE (+) = POH.FOB_LOOKUP_CODE AND  
POLC2.LOOKUP_TYPE (+) = 'FOB' AND  
POLC3.LOOKUP_CODE (+) = POH.FREIGHT_TERMS_LOOKUP_CODE AND  
POLC3.LOOKUP_TYPE (+) = 'FREIGHT TERMS' AND  
POLC4.LOOKUP_CODE (+) = POH.PAY_ON_CODE AND  
POLC4.LOOKUP_TYPE (+) = 'PAY ON CODE' AND  
POH.ORG_ID = PDT.ORG_ID (+) AND  
PDT.DOCUMENT_TYPE_CODE = T.DOCUMENT_TYPE_CODE and  
PDT.DOCUMENT_SUBTYPE = T.DOCUMENT_SUBTYPE and  
NVL(PDT.ORG_ID, -99) = NVL(T.ORG_ID, -99) and  
T.LANGUAGE = userenv('LANG') and
POH.ORG_ID = HOU.ORGANIZATION_ID 
/

SHOW ERRORS
