/*  ***************************************************************************
    *    $Date:   14 Aug 2001 10:56:36  $
    *    $Revision:   1.0  $
    *    $Author:   TCS  $
    *    Copyright (c) 2002, webMethods Inc. All Rights Reserved
    *
    *************************************************************************** 
    ***************************************************************************
    * Application:          webMethods
    * Process Name:         Create Custom Views for Customer outbound in Application Schema  
    * Program Name:         wm_from_customer_vw.sql
    * Version #:            1.0
    * Title:                View Installation Script for webMethods Oracle Apps Adapter 3.0
    * Utility:              SQL*Plus
    * Created by:           
    * Creation   Date:      
    *
    * Description:              
    *
    *           Create Views in APPS schema for Vendor Outbound
    *
    * Tables usage:     
    *           
    *
    * Procedures and Functions:
    *		
    *
    * Restart Information:      
    *
    *
    *
    * Flexfields Used:          
    *
    *
    *
    * Value Sets Used:          
    *
    *
    * Input Parameters:     
    *         
    *           Param1: &SpoolFile     
    *           Param2: &Apps User Password
    *          
    *   
    *
    * Menu Responsibilities and path: 
    *
    *
    * Technical Implementation Notes: 
    *
    *
    * Change History:
    *
    *==========================================================================
    * Date       | Name                  | Remarks
    *==========================================================================
     12-AUG-02	 Sudip Kumar Chaudhuri   Created
    ***************************************************************************
*/

  set feedback  on
  set verify            off
  set newpage   0
  set pause             off
  set termout   on

 prompt Program : wm_from_customer_vw.sql

  
connect &&apps_user/&&appspwd@&&DBString 

REM "Creating Views....."


/*----------------------------------------------------------------------*/
--      Create View WM_AR_CUSTOMERS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_CUSTOMERS_VW ( WEB_TRANSACTION_ID, 
DOCUMENT_TYPE, DOCUMENT_STATUS, CUSTOMER_ID, CUSTOMER_NAME, 
CUSTOMER_NUMBER, PARTY_ID, PARTY_NUMBER, PARTY_TYPE, 
CUSTOMER_KEY, CUSTOMER_STATUS, ORIG_SYSTEM_REFERENCE, CUSTOMER_PROSPECT_CODE, 
CUSTOMER_CATEGORY_CODE, CUSTOMER_CATEGORY_MEANING, CUSTOMER_CLASS_CODE, CUSTOMER_CLASS_MEANING, 
CUSTOMER_TYPE, CUSTOMER_TYPE_MEANING, PRIMARY_SALESREP_ID, PRIMARY_SALESREP_NAME, 
SIC_CODE, TAX_REFERENCE, TAX_CODE, FOB_POINT, 
FOB_POINT_MEANING, SHIP_VIA, GSA_INDICATOR, SHIP_PARTIAL, 
TAXPAYER_ID, PRICE_LIST_ID, PRICE_LIST_NAME, FREIGHT_TERM, 
FREIGHT_TERM_MEANING, ORDER_TYPE_ID, ORDER_TYPE_NAME, SALES_CHANNEL_CODE, 
SALES_CHANNEL_MEANING, WAREHOUSE_ID, WAREHOUSE_NAME, MISSION_STATEMENT, 
NUM_OF_EMPLOYEES, POTENTIAL_REVENUE_CURR_FY, POTENTIAL_REVENUE_NEXT_FY, FISCAL_YEAREND_MONTH, 
YEAR_ESTABLISHED, ANALYSIS_FY, COMPETITOR_FLAG, REFERENCE_USE_FLAG, 
THIRD_PARTY_FLAG, CUSTOMER_PROFILE_CLASS_ID, PROFILE_CLASS_NAME, CUSTOMER_NAME_PHONETIC, 
TAX_HEADER_LEVEL_FLAG, TAX_ROUNDING_RULE, ORIG_SYSTEM, COTERMINATE_DAY_MONTH, 
WAREHOUSE_UPDATE_DATE, LANGUAGE, TRANSLATED_CUSTOMER_NAME, PERSON_PRE_NAME_ADJUNCT, 
PERSON_FIRST_NAME, PERSON_MIDDLE_NAME, PERSON_LAST_NAME, PERSON_SUFFIX, 
PERSON_FIRST_NAME_PHONETIC, PERSON_LAST_NAME_PHONETIC, SHIP_SETS_INCLUDE_LINES_FLAG, ARRIVALSETS_INCLUDE_LINES_FLAG, 
SCHED_DATE_PUSH_FLAG, OVER_SHIPMENT_TOLERANCE, UNDER_SHIPMENT_TOLERANCE, OVER_RETURN_TOLERANCE, 
UNDER_RETURN_TOLERANCE, ITEM_CROSS_REF_PREF, DATE_TYPE_PREFERENCE, DATES_NEGATIVE_TOLERANCE, 
DATES_POSITIVE_TOLERANCE, INVOICE_QUANTITY_RULE, DUNS_NUMBER, ORGANIZATION_PROFILE_ID, 
PERSON_PROFILE_ID, SIC_CODE_TYPE ) AS SELECT  
WMTC.WEB_TRANSACTION_ID,  
WMTC.TRANSACTION_TYPE DOCUMENT_TYPE,  
DECODE((WMTC.TRANSACTION_STATUS),0,'UPDATE',1,'INSERT',2, 'DELETE') DOCUMENT_STATUS,  
CUST.CUSTOMER_ID CUSTOMER_ID ,  
CUST.CUSTOMER_NAME CUSTOMER_NAME ,  
CUST.CUSTOMER_NUMBER CUSTOMER_NUMBER ,  
CUST.PARTY_ID ,  
CUST.PARTY_NUMBER ,  
CUST.PARTY_TYPE ,  
CUST.CUSTOMER_KEY CUSTOMER_KEY ,  
CUST.STATUS STATUS ,  
CUST.ORIG_SYSTEM_REFERENCE ORIG_SYSTEM_REFERENCE ,  
CUST.CUSTOMER_PROSPECT_CODE CUSTOMER_PROSPECT_CODE ,  
CUST.CUSTOMER_CATEGORY_CODE CUSTOMER_CATEGORY_CODE ,  
L_CAT.MEANING CUSTOMER_CATEGORY_MEANING ,  
CUST.CUSTOMER_CLASS_CODE CUSTOMER_CLASS_CODE ,  
L_CLASS.MEANING CUSTOMER_CLASS_MEANING ,  
CUST.CUSTOMER_TYPE CUSTOMER_TYPE ,  
L_TYPE.MEANING CUSTOMER_TYPE_MEANING ,  
CUST.PRIMARY_SALESREP_ID PRIMARY_SALESREP_ID ,  
REP.NAME PRIMARY_SALESREP_NAME ,  
CUST.SIC_CODE SIC_CODE ,  
CUST.TAX_REFERENCE TAX_REFERENCE ,  
CUST.TAX_CODE TAX_CODE ,  
CUST.FOB_POINT FOB_POINT ,  
L_FOB.MEANING FOB_POINT_MEANING ,  
CUST.SHIP_VIA SHIP_VIA ,  
CUST.GSA_INDICATOR GSA_INDICATOR ,  
CUST.SHIP_PARTIAL SHIP_PARTIAL ,  
CUST.JGZZ_FISCAL_CODE TAXPAYER_ID ,  
CUST.PRICE_LIST_ID PRICE_LIST_ID ,  
PL.NAME PRICE_LIST_NAME ,  
CUST.FREIGHT_TERM FREIGHT_TERM ,  
L_FT.MEANING FREIGHT_TERM_MEANING ,  
CUST.ORDER_TYPE_ID ORDER_TYPE_ID ,  
OT.NAME ORDER_TYPE_NAME ,  
CUST.SALES_CHANNEL_CODE SALES_CHANNEL_CODE ,  
L_SC.MEANING SALES_CHANNEL_MEANING ,  
CUST.WAREHOUSE_ID WAREHOUSE_ID ,  
ORG.NAME WAREHOUSE_NAME ,  
CUST.MISSION_STATEMENT MISSION_STATEMENT ,  
CUST.NUM_OF_EMPLOYEES NUM_OF_EMPLOYEES ,  
CUST.POTENTIAL_REVENUE_CURR_FY POTENTIAL_REVENUE_CURR_FY ,  
CUST.POTENTIAL_REVENUE_NEXT_FY POTENTIAL_REVENUE_NEXT_FY ,  
CUST.FISCAL_YEAREND_MONTH FISCAL_YEAREND_MONTH ,  
CUST.YEAR_ESTABLISHED YEAR_ESTABLISHED ,  
CUST.ANALYSIS_FY ANALYSIS_FY ,  
CUST.COMPETITOR_FLAG COMPETITOR_FLAG ,  
CUST.REFERENCE_USE_FLAG REFERENCE_USE_FLAG ,  
CUST.THIRD_PARTY_FLAG THIRD_PARTY_FLAG ,  
CPC.CUSTOMER_PROFILE_CLASS_ID CUSTOMER_PROFILE_CLASS_ID ,  
CPC.NAME PROFILE_CLASS_NAME ,  
CUST.CUSTOMER_NAME_PHONETIC CUSTOMER_NAME_PHONETIC ,  
CUST.TAX_HEADER_LEVEL_FLAG TAX_HEADER_LEVEL_FLAG ,  
CUST.TAX_ROUNDING_RULE TAX_ROUNDING_RULE ,  
CUST.ORIG_SYSTEM ,  
CUST.COTERMINATE_DAY_MONTH ,  
CUST.WH_UPDATE_DATE ,  
CUST.LANGUAGE ,  
CUST.TRANSLATED_CUSTOMER_NAME ,  
CUST.PERSON_PRE_NAME_ADJUNCT ,  
CUST.PERSON_FIRST_NAME ,  
CUST.PERSON_MIDDLE_NAME ,  
CUST.PERSON_LAST_NAME ,  
CUST.PERSON_SUFFIX ,  
CUST.PERSON_FIRST_NAME_PHONETIC ,  
CUST.PERSON_LAST_NAME_PHONETIC ,  
CUST.SHIP_SETS_INCLUDE_LINES_FLAG ,  
CUST.ARRIVALSETS_INCLUDE_LINES_FLAG ,  
CUST.SCHED_DATE_PUSH_FLAG ,  
CUST.OVER_SHIPMENT_TOLERANCE ,  
CUST.UNDER_SHIPMENT_TOLERANCE ,  
CUST.OVER_RETURN_TOLERANCE ,  
CUST.UNDER_RETURN_TOLERANCE ,  
CUST.ITEM_CROSS_REF_PREF ,  
CUST.DATE_TYPE_PREFERENCE ,  
CUST.DATES_NEGATIVE_TOLERANCE ,  
CUST.DATES_POSITIVE_TOLERANCE ,  
CUST.INVOICE_QUANTITY_RULE ,  
CUST.DUNS_NUMBER ,  
ORG_PROF.ORGANIZATION_PROFILE_ID ,  
PER_PROF.PERSON_PROFILE_ID ,  
CUST.SIC_CODE_TYPE  
FROM  
AR_LOOKUPS L_CAT,  
AR_LOOKUPS L_CLASS,  
AR_LOOKUPS L_TYPE,  
RA_SALESREPS REP,  
AR_LOOKUPS L_FOB,  
SO_PRICE_LISTS PL,  
SO_LOOKUPS L_FT,  
SO_ORDER_TYPES OT,  
SO_LOOKUPS L_SC,  
HR_ALL_ORGANIZATION_UNITS ORG,  
AR_CUSTOMER_PROFILE_CLASSES CPC,  
AR_CUSTOMER_PROFILES CP,  
RA_CUSTOMERS CUST,  
HZ_CONTACT_RESTRICTIONS CONT_RES,  
HZ_CONTACT_POINTS CONT_POINT,  
HZ_ORGANIZATION_PROFILES ORG_PROF,  
HZ_PERSON_PROFILES PER_PROF,  
HZ_PARTIES PARTY,  
HZ_CUST_ACCOUNTS CUST_ACCT,  
WM_TRACK_CHANGES_VW WMTC  
WHERE  
CUST.CUSTOMER_CATEGORY_CODE = L_CAT.LOOKUP_CODE(+) AND  
L_CAT.LOOKUP_TYPE(+) = 'CUSTOMER_CATEGORY' AND  
CUST.CUSTOMER_CLASS_CODE = L_CLASS.LOOKUP_CODE(+) AND  
L_CLASS.LOOKUP_TYPE(+) = 'CUSTOMER CLASS' AND  
CUST.CUSTOMER_TYPE = L_TYPE.LOOKUP_CODE(+) AND  
L_TYPE.LOOKUP_TYPE(+) = 'CUSTOMER_TYPE' AND  
CUST.PRIMARY_SALESREP_ID = REP.SALESREP_ID(+) AND  
CUST.FOB_POINT = L_FOB.LOOKUP_CODE(+) AND  
L_FOB.LOOKUP_TYPE(+) = 'FOB' AND  
CUST.PRICE_LIST_ID = PL.PRICE_LIST_ID(+) AND  
CUST.FREIGHT_TERM = L_FT.LOOKUP_CODE(+) AND  
L_FT.LOOKUP_TYPE(+) = 'FREIGHT_TERMS' AND  
CUST.ORDER_TYPE_ID = OT.ORDER_TYPE_ID(+) AND  
CUST.SALES_CHANNEL_CODE = L_SC.LOOKUP_CODE(+) AND  
L_SC.LOOKUP_TYPE(+) = 'SALES_CHANNEL' AND  
CUST.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND  
CP.CUSTOMER_ID = CUST.CUSTOMER_ID AND  
CP.SITE_USE_ID IS NULL AND  
CP.CUSTOMER_PROFILE_CLASS_ID = CPC.CUSTOMER_PROFILE_CLASS_ID(+) AND  
CUST_ACCT.CUST_ACCOUNT_ID = CUST.CUSTOMER_ID AND  
CUST_ACCT.PARTY_ID = PARTY.PARTY_ID AND  
PARTY.PARTY_ID = ORG_PROF.PARTY_ID(+) AND  
PARTY.PARTY_ID = PER_PROF.PARTY_ID(+) AND  
PARTY.PARTY_ID = CONT_POINT.OWNER_TABLE_ID(+) AND  
CONT_POINT.OWNER_TABLE_NAME(+) = 'HZ_PARTIES' AND  
CONT_POINT.CONTACT_POINT_TYPE(+) = 'WEB' AND  
CONT_POINT.PRIMARY_FLAG(+) = 'Y' AND  
PARTY.PARTY_ID = CONT_RES.SUBJECT_ID(+) AND  
CONT_RES.SUBJECT_TABLE(+) = 'HZ_PARTIES' AND  
ORG_PROF.CONTENT_SOURCE_TYPE(+) = 'USER_ENTERED' AND  
PER_PROF.CONTENT_SOURCE_TYPE(+) = 'USER_ENTERED' AND  
ORG_PROF.EFFECTIVE_END_DATE IS NULL AND  
PER_PROF.EFFECTIVE_END_DATE IS NULL AND  
CUST_ACCT.CUST_ACCOUNT_ID = WMTC.TRANSACTION_ID AND  
TRANSACTION_STATUS <= 2 AND  
WMTC.TRANSACTION_TYPE = 'CUSTOMER'  
ORDER BY WMTC.WEB_TRANSACTION_ID
/


/*----------------------------------------------------------------------*/
--      Create View WM_CUST_PHONES_VW
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_CUST_PHONES_VW ( PHONE_ID, 
CUSTOMER_ID, ADDRESS_ID, CONTACT_ID, PHONE_NUMBER, 
STATUS, PHONE_TYPE, AREA_CODE, EXTENSION, 
PRIMARY_FLAG, ORIG_SYSTEM_REFERENCE, CONTACT_POINT_TYPE, TELEPHONE_TYPE, 
TIME_ZONE, PHONE_TOUCH_TONE_TYPE_FLAG, TELEX_NUMBER, WEB_TYPE, 
CUST_CONTACT_POINT_ID ) AS SELECT
CONT_POINT.CONTACT_POINT_ID /* PHONE_ID */ ,
CA.CUST_ACCOUNT_ID /* PARTY_ID */ ,
TO_NUMBER(NULL) /* ADDRESS_ID */ ,
TO_NUMBER(NULL) /* CONTACT_ID */ ,
DECODE(CONT_POINT.CONTACT_POINT_TYPE,  'TLX',  CONT_POINT.TELEX_NUMBER,  CONT_POINT.PHONE_NUMBER) ,
CONT_POINT.STATUS ,
NVL(CONT_POINT.PHONE_LINE_TYPE,  CONT_POINT.CONTACT_POINT_TYPE) ,
CONT_POINT.PHONE_AREA_CODE ,
CONT_POINT.PHONE_EXTENSION ,
CONT_POINT.PRIMARY_FLAG ,
CONT_POINT.ORIG_SYSTEM_REFERENCE ,
CONT_POINT.CONTACT_POINT_TYPE ,
CONT_POINT.TELEPHONE_TYPE ,
CONT_POINT.TIME_ZONE ,
CONT_POINT.PHONE_TOUCH_TONE_TYPE_FLAG ,
CONT_POINT.TELEX_NUMBER ,
CONT_POINT.WEB_TYPE ,
CONT_POINT.CONTACT_POINT_ID
FROM
HZ_CUST_ACCOUNTS CA ,
HZ_CONTACT_POINTS CONT_POINT
WHERE
CA.PARTY_ID = CONT_POINT.OWNER_TABLE_ID AND
CONT_POINT.OWNER_TABLE_NAME = 'HZ_PARTIES' AND
CONT_POINT.CONTACT_POINT_TYPE NOT IN ( 'EDI', 'EMAIL', 'WEB')
/

/*----------------------------------------------------------------------*/
--      Create View WM_CONT_PHONES_VW 
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_CONT_PHONES_VW ( PHONE_ID, 
CUSTOMER_ID, ADDRESS_ID, CONTACT_ID, PHONE_NUMBER, 
STATUS, PHONE_TYPE, AREA_CODE, EXTENSION, 
PRIMARY_FLAG, ORIG_SYSTEM_REFERENCE, CONTACT_POINT_TYPE, TELEPHONE_TYPE, 
TIME_ZONE, PHONE_TOUCH_TONE_TYPE_FLAG, TELEX_NUMBER, WEB_TYPE, 
CUST_CONTACT_POINT_ID ) AS SELECT    
CONT_POINT.CONTACT_POINT_ID /* PHONE_ID */ , 
CAR.CUST_ACCOUNT_ID /* CUSTOMER_ID */ ,    
CAR.CUST_ACCT_SITE_ID /* ADDRESS_ID */ ,    
CAR.CUST_ACCOUNT_ROLE_ID /* CONTACT_ID */ ,     
DECODE(CONT_POINT.CONTACT_POINT_TYPE,'TLX',CONT_POINT.TELEX_NUMBER,CONT_POINT.PHONE_NUMBER) ,    
CONT_POINT.STATUS ,    
NVL(CONT_POINT.PHONE_LINE_TYPE,CONT_POINT.CONTACT_POINT_TYPE) ,    
CONT_POINT.PHONE_AREA_CODE ,    
CONT_POINT.PHONE_EXTENSION ,    
CONT_POINT.PRIMARY_FLAG ,    
CONT_POINT.ORIG_SYSTEM_REFERENCE ,    
CONT_POINT.CONTACT_POINT_TYPE ,    
CONT_POINT.TELEPHONE_TYPE ,    
CONT_POINT.TIME_ZONE ,    
CONT_POINT.PHONE_TOUCH_TONE_TYPE_FLAG ,    
CONT_POINT.TELEX_NUMBER ,    
CONT_POINT.WEB_TYPE ,    
CONT_POINT.CONTACT_POINT_ID    
FROM    
HZ_CONTACT_POINTS CONT_POINT ,    
HZ_CUST_ACCOUNT_ROLES CAR    
WHERE    
CAR.PARTY_ID = CONT_POINT.OWNER_TABLE_ID AND    
CONT_POINT.OWNER_TABLE_NAME = 'HZ_PARTIES' AND    
CONT_POINT.CONTACT_POINT_TYPE NOT IN ( 'EDI', 'EMAIL', 'WEB')
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_SITE_USES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_SITE_USES_VW ( SITE_USE_ID, 
ADDRESS_ID, SITE_USE_CODE, SITE_USE_MEANING, PRIMARY_FLAG, 
STATUS, LOCATION, CONTACT_ID, CONTACT_NAME, 
BILL_TO_SITE_USE_ID, BILL_TO_LOCATION, ORIG_SYSTEM_REFERENCE, SIC_CODE, 
PAYMENT_TERM_ID, PAYMENT_TERM_NAME, GSA_INDICATOR, SHIP_PARTIAL, 
SHIP_VIA, FOB_POINT, FOB_POINT_MEANING, ORDER_TYPE_ID, 
ORDER_TYPE_NAME, PRICE_LIST_ID, PRICE_LIST_NAME, FREIGHT_TERM, 
FREIGHT_TERM_MEANING, WAREHOUSE_ID, WAREHOUSE_NAME, TERRITORY_ID, 
TAX_REFERENCE, TAX_CODE, DEMAND_CLASS_CODE, DEMAND_CLASS_MEANING, 
INVENTORY_LOCATION_ID, INVENTORY_LOCATION_CODE, INVENTORY_ORGANIZATION_ID, INVENTORY_ORGANIZATION_NAME, 
TAX_CLASSIFICATION, TAX_HEADER_LEVEL_FLAG, TAX_ROUNDING_RULE, PRIMARY_SALESREP_ID, 
PRIMARY_SALESREP_NAME, FINCHRG_RECEIVABLES_TRX_ID, FINCHRG_RECEIVABLES_TRX_NAME, GL_ID_REV, 
REV_ACCOUNT, GL_ID_FREIGHT, FREIGHT_ACCOUNT, GL_ID_REC, 
REC_ACCOUNT, GL_ID_CLEARING, CLEARING_ACCOUNT, GL_ID_TAX, 
TAX_ACCOUNT, GL_ID_UNBILLED, UNBILLED_ACCOUNT, GL_ID_UNEARNED, 
UNEARNED_ACCOUNT, GL_ID_UNPAID_REC, UNPAID_REC_ACCOUNT, GL_ID_REMITTANCE, 
REMITTANCE_ACCOUNT, GL_ID_FACTOR, FACTOR_ACCOUNT, DATES_NEGATIVE_TOLERANCE, 
DATES_POSITIVE_TOLERANCE, DATE_TYPE_PREFERENCE, OVER_SHIPMENT_TOLERANCE, UNDER_SHIPMENT_TOLERANCE, 
ITEM_CROSS_REF_PREF, OVER_RETURN_TOLERANCE, UNDER_RETURN_TOLERANCE, SHIP_SETS_INCLUDE_LINES_FLAG, 
ARRIVALSETS_INCLUDE_LINES_FLAG, SCHED_DATE_PUSH_FLAG, INVOICE_QUANTITY_RULE, PRICING_EVENT
 ) AS SELECT  
  SU.SITE_USE_ID , 
  SU.ADDRESS_ID , 
  SU.SITE_USE_CODE , 
  L_SU.MEANING , 
  SU.PRIMARY_FLAG , 
  SU.STATUS , 
  SU.LOCATION , 
  SU.CONTACT_ID , 
  DECODE(CONT.CONTACT_ID, NULL, NULL,  CONT.LAST_NAME || ', ' || CONT.FIRST_NAME) , 
  SU.BILL_TO_SITE_USE_ID , 
  SU_BILL.LOCATION , 
  SU.ORIG_SYSTEM_REFERENCE , 
  SU.SIC_CODE , 
  SU.PAYMENT_TERM_ID , 
  TERM.NAME , 
  SU.GSA_INDICATOR , 
  SU.SHIP_PARTIAL , 
  SU.SHIP_VIA , 
  SU.FOB_POINT , 
  L_FOB.MEANING , 
  SU.ORDER_TYPE_ID , 
  ORDT.NAME , 
  SU.PRICE_LIST_ID , 
  LIST.NAME , 
  SU.FREIGHT_TERM , 
  L_FT.MEANING , 
  SU.WAREHOUSE_ID , 
  ORG.NAME , 
  SU.TERRITORY_ID , 
  SU.TAX_REFERENCE , 
  SU.TAX_CODE , 
  SU.DEMAND_CLASS_CODE , 
  COMM.MEANING , 
  HRL.LOCATION_ID , 
  HRL.LOCATION_CODE , 
  INV_ORG.ORGANIZATION_ID , 
  INV_ORG.NAME , 
  SU.TAX_CLASSIFICATION , 
  SU.TAX_HEADER_LEVEL_FLAG , 
  SU.TAX_ROUNDING_RULE , 
  SU.PRIMARY_SALESREP_ID , 
  SR.NAME , 
  SU.FINCHRG_RECEIVABLES_TRX_ID , 
  RT.NAME , 
  SU.GL_ID_REV , 
  REV.CONCATENATED_SEGMENTS, 
  SU.GL_ID_FREIGHT , 
  FREIGHT.CONCATENATED_SEGMENTS, 
  SU.GL_ID_REC , 
  REC.CONCATENATED_SEGMENTS, 
  SU.GL_ID_CLEARING , 
  CLEARING.CONCATENATED_SEGMENTS, 
  SU.GL_ID_TAX , 
  TAX.CONCATENATED_SEGMENTS, 
  SU.GL_ID_UNBILLED , 
  UNBILLED.CONCATENATED_SEGMENTS, 
  SU.GL_ID_UNEARNED , 
  UNEARNED.CONCATENATED_SEGMENTS, 
  SU.GL_ID_UNPAID_REC , 
  UNPAID_REC.CONCATENATED_SEGMENTS, 
  SU.GL_ID_REMITTANCE , 
  REMITTANCE.CONCATENATED_SEGMENTS, 
  SU.GL_ID_FACTOR , 
  FACTOR.CONCATENATED_SEGMENTS, 
  SU.DATES_NEGATIVE_TOLERANCE , 
  SU.DATES_POSITIVE_TOLERANCE , 
  SU.DATE_TYPE_PREFERENCE , 
  SU.OVER_SHIPMENT_TOLERANCE , 
  SU.UNDER_SHIPMENT_TOLERANCE , 
  SU.ITEM_CROSS_REF_PREF , 
  SU.OVER_RETURN_TOLERANCE , 
  SU.UNDER_RETURN_TOLERANCE , 
  SU.SHIP_SETS_INCLUDE_LINES_FLAG , 
  SU.ARRIVALSETS_INCLUDE_LINES_FLAG , 
  SU.SCHED_DATE_PUSH_FLAG , 
  SU.INVOICE_QUANTITY_RULE , 
  SU.PRICING_EVENT 
FROM  
  RA_SITE_USES_ALL SU, 
  RA_SITE_USES_ALL SU_BILL, 
  AR_LOOKUPS L_SU, 
  RA_TERMS TERM, 
  AR_LOOKUPS L_FOB, 
  RA_CONTACTS CONT, 
  FND_COMMON_LOOKUPS COMM, 
  SO_LOOKUPS L_FT, 
  HR_ALL_ORGANIZATION_UNITS ORG, 
  OE_TRANSACTION_TYPES_VL ORDT, 
  SO_PRICE_LISTS LIST, 
  PO_LOCATION_ASSOCIATIONS_ALL PLA, 
  HR_LOCATIONS HRL, 
  RA_SALESREPS SR, 
  HR_ORGANIZATION_UNITS INV_ORG, 
  AR_RECEIVABLES_TRX_ALL RT, 
  GL_CODE_COMBINATIONS_KFV REV, 
  GL_CODE_COMBINATIONS_KFV FREIGHT, 
  GL_CODE_COMBINATIONS_KFV REC, 
  GL_CODE_COMBINATIONS_KFV CLEARING, 
  GL_CODE_COMBINATIONS_KFV TAX, 
  GL_CODE_COMBINATIONS_KFV UNBILLED, 
  GL_CODE_COMBINATIONS_KFV UNEARNED, 
  GL_CODE_COMBINATIONS_KFV UNPAID_REC, 
  GL_CODE_COMBINATIONS_KFV REMITTANCE, 
  GL_CODE_COMBINATIONS_KFV FACTOR 
WHERE  
  SU.BILL_TO_SITE_USE_ID = SU_BILL.SITE_USE_ID(+) AND 
  SU.SITE_USE_CODE = L_SU.LOOKUP_CODE(+) AND 
  L_SU.LOOKUP_TYPE(+) = 'SITE_USE_CODE' AND 
  SU.PAYMENT_TERM_ID = TERM.TERM_ID(+) AND 
  SU.FOB_POINT = L_FOB.LOOKUP_CODE(+) AND 
  L_FOB.LOOKUP_TYPE(+) = 'FOB' AND 
  SU.CONTACT_ID = CONT.CONTACT_ID(+) AND 
  SU.DEMAND_CLASS_CODE = COMM.LOOKUP_CODE(+) AND 
  COMM.LOOKUP_TYPE(+) = 'DEMAND_CLASS' AND 
  SU.FREIGHT_TERM = L_FT.LOOKUP_CODE(+) AND 
  L_FT.LOOKUP_TYPE(+) = 'FREIGHT_TERMS' AND 
  SU.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND 
  SU.ORDER_TYPE_ID = ORDT.TRANSACTION_TYPE_ID(+) AND 
  SU.PRICE_LIST_ID = LIST.PRICE_LIST_ID(+) AND 
  SU.SITE_USE_ID = PLA.SITE_USE_ID(+) AND 
  PLA.LOCATION_ID = HRL.LOCATION_ID(+) AND 
  PLA.ORGANIZATION_ID = INV_ORG.ORGANIZATION_ID(+) AND 
  SU.PRIMARY_SALESREP_ID = SR.SALESREP_ID (+) AND 
  SU.FINCHRG_RECEIVABLES_TRX_ID = RT.RECEIVABLES_TRX_ID(+) AND 
  SU.GL_ID_REV = REV.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_FREIGHT = FREIGHT.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_REC = REC.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_CLEARING = CLEARING.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_TAX = TAX.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_UNBILLED = UNBILLED.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_UNEARNED = UNEARNED.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_UNPAID_REC = UNPAID_REC.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_REMITTANCE = REMITTANCE.CODE_COMBINATION_ID(+) AND 
  SU.GL_ID_FACTOR = FACTOR.CODE_COMBINATION_ID(+)
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_CUST_RELATIONSHIPS_VW 
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_AR_CUST_RELATIONSHIPS_VW ( RELATED_CUSTOMER_ID, 
CUSTOMER_ID, RELATIONSHIP_TYPE_CODE, RELATED_CUSTOMER_NAME, RELATED_CUSTOMER_NUMBER, 
STATUS, COMMENTS, CUSTOMER_RECIPROCAL_FLAG, RELATIONSHIP_TYPE, 
RELATIONSHIP_TYPE_MEANING, BILL_TO_FLAG, SHIP_TO_FLAG ) AS SELECT   
REL.RELATED_CUSTOMER_ID ,   
REL.CUSTOMER_ID ,   
REL.RELATIONSHIP_TYPE ,   
CUST.CUSTOMER_NAME ,   
CUST.CUSTOMER_NUMBER ,   
REL.STATUS ,   
REL.COMMENTS ,   
REL.CUSTOMER_RECIPROCAL_FLAG ,   
REL.RELATIONSHIP_TYPE ,   
L.MEANING ,   
REL.BILL_TO_FLAG ,   
REL.SHIP_TO_FLAG   
FROM   
RA_CUSTOMER_RELATIONSHIPS_ALL REL,   
RA_CUSTOMERS CUST,   
AR_LOOKUPS L   
WHERE   
REL.RELATED_CUSTOMER_ID = CUST.CUSTOMER_ID AND   
L.LOOKUP_CODE = REL.RELATIONSHIP_TYPE AND   
L.LOOKUP_TYPE = 'RELATIONSHIP_TYPE'
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_CUST_RECEIPT_METHODS_VW
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_AR_CUST_RECEIPT_METHODS_VW ( CUST_RECEIPT_METHOD_ID, 
CUSTOMER_ID, SITE_USE_ID, PRIMARY_FLAG, RECEIPT_METHOD_ID, 
RECEIPT_METHOD_NAME, START_DATE, END_DATE, CHECK_RELATION_ID ) AS SELECT   
CRM.CUST_RECEIPT_METHOD_ID ,   
CRM.CUSTOMER_ID ,  
CRM.SITE_USE_ID ,  
CRM.PRIMARY_FLAG ,   
CRM.RECEIPT_METHOD_ID ,   
RM.NAME ,   
CRM.START_DATE ,   
CRM.END_DATE,
DECODE(CRM.SITE_USE_ID,NULL,CRM.CUSTOMER_ID,NULL)  
FROM   
RA_CUST_RECEIPT_METHODS CRM,   
AR_RECEIPT_METHODS RM   
WHERE   
RM.RECEIPT_METHOD_ID = CRM.RECEIPT_METHOD_ID
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_CUST_BANK_ACCOUNTS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_CUST_BANK_ACCOUNTS_VW ( BANK_ACCOUNT_USES_ID, 
CUSTOMER_ID, BANK_ACCOUNT_ID, BANK_BRANCH_ID, CUSTOMER_SITE_USE_ID, 
EXTERNAL_BANK_ACCOUNT_ID, START_DATE, END_DATE, PRIMARY_FLAG, 
BANK_NUMBER, BANK_NAME, BANK_BRANCH_NAME, BANK_BRANCH_NUM, 
BANK_BRANCH_DESCRIPTION, BANK_ACCOUNT_NAME, BANK_ACCOUNT_NUM, BANK_ACCOUNT_DESCRIPTION, 
BANK_CURRENCY_CODE, BANK_ACCOUNT_INACTIVE_DATE, BANK_BRANCH_ADDRESS1, BANK_BRANCH_ADDRESS2, 
BANK_BRANCH_ADDRESS3, BANK_BRANCH_ADDRESS4, BANK_BRANCH_CITY, BANK_BRANCH_STATE, 
BANK_BRANCH_ZIP, BANK_BRANCH_PROVINCE, BANK_BRANCH_COUNTRY, BANK_BRANCH_AREA_CODE, 
BANK_BRANCH_PHONE, BANK_BRANCH_COUNTY, BANK_BRANCH_EFT_USER_NUMBER, BANK_ACCOUNT_CHECK_DIGITS,
CHECK_RELATION_ID
 ) AS SELECT  
BAUSES.BANK_ACCOUNT_USES_ID ,  
BAUSES.CUSTOMER_ID ,  
BACCT.BANK_ACCOUNT_ID ,  
BBNCH.BANK_BRANCH_ID ,  
BAUSES.CUSTOMER_SITE_USE_ID ,  
BAUSES.EXTERNAL_BANK_ACCOUNT_ID ,  
BAUSES.START_DATE ,  
BAUSES.END_DATE ,  
BAUSES.PRIMARY_FLAG ,  
BBNCH.BANK_NUMBER ,  
BBNCH.BANK_NAME ,  
BBNCH.BANK_BRANCH_NAME ,  
BBNCH.BANK_NUM ,  
BBNCH.DESCRIPTION ,  
BACCT.BANK_ACCOUNT_NAME ,  
BACCT.BANK_ACCOUNT_NUM,  
BACCT.DESCRIPTION ,  
BACCT.CURRENCY_CODE,  
BACCT.INACTIVE_DATE,  
BBNCH.ADDRESS_LINE1,  
BBNCH.ADDRESS_LINE2,  
BBNCH.ADDRESS_LINE3,  
BBNCH.ADDRESS_LINE4,  
BBNCH.CITY,  
BBNCH.STATE,  
BBNCH.ZIP,  
BBNCH.PROVINCE,  
BBNCH.COUNTRY,  
BBNCH.AREA_CODE,  
BBNCH.PHONE,  
BBNCH.COUNTY,  
BBNCH.EFT_USER_NUMBER,  
BACCT.CHECK_DIGITS,
DECODE(BAUSES.CUSTOMER_SITE_USE_ID,NULL,BAUSES.CUSTOMER_ID,NULL)
FROM  
AP_BANK_ACCOUNT_USES_ALL BAUSES,  
AP_BANK_BRANCHES BBNCH,  
AP_BANK_ACCOUNTS_ALL BACCT  
WHERE  
BAUSES.EXTERNAL_BANK_ACCOUNT_ID = BACCT.BANK_ACCOUNT_ID AND  
BACCT.BANK_BRANCH_ID = BBNCH.BANK_BRANCH_ID
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_CUSTOMER_PROF_AMTS_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_CUSTOMER_PROF_AMTS_VW ( CUSTOMER_PROFILE_AMOUNT_ID, 
CUSTOMER_PROFILE_ID, CUSTOMER_ID, CUSTOMER_SITE_USE_ID, CURRENCY_CODE, 
TRX_CREDIT_LIMIT, OVERALL_CREDIT_LIMIT, MIN_DUNNING_AMOUNT, MIN_DUNNING_INVOICE_AMOUNT, 
MAX_INTEREST_CHARGE, MIN_STATEMENT_AMOUNT, AUTO_REC_MIN_RECEIPT_AMOUNT, INTEREST_RATE, 
MIN_FC_BALANCE_AMOUNT, MIN_FC_INVOICE_AMOUNT, CHECK_RELATION_ID ) AS SELECT   
CUST_ACCT_PROFILE_AMT_ID ,   
CUST_ACCOUNT_PROFILE_ID ,  
CUST_ACCOUNT_ID /* CUSTOMER_ID */ ,   
SITE_USE_ID /* CUSTOMER_SITE_USE_ID */ ,  
CURRENCY_CODE ,   
TRX_CREDIT_LIMIT ,   
OVERALL_CREDIT_LIMIT ,   
MIN_DUNNING_AMOUNT ,   
MIN_DUNNING_INVOICE_AMOUNT ,   
MAX_INTEREST_CHARGE ,   
MIN_STATEMENT_AMOUNT ,   
AUTO_REC_MIN_RECEIPT_AMOUNT ,   
INTEREST_RATE ,   
MIN_FC_BALANCE_AMOUNT ,   
MIN_FC_INVOICE_AMOUNT,
DECODE(SITE_USE_ID,NULL,CUST_ACCOUNT_PROFILE_ID,NULL)   
FROM   
HZ_CUST_PROFILE_AMTS
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_CUSTOMER_PROFILES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_CUSTOMER_PROFILES_VW ( CUSTOMER_PROFILE_ID, 
CUSTOMER_ID, SITE_USE_ID, CUSTOMER_PROFILE_CLASS_ID, STATUS, 
PROFILE_CLASS_NAME, PROFILE_CLASS_DESCRIPTION, COLLECTOR_ID, COLLECTOR_NAME, 
CREDIT_CHECKING, TOLERANCE, DISCOUNT_TERMS, DUNNING_LETTERS, 
INTEREST_CHARGES, STATEMENTS, CREDIT_BALANCE_STATEMENTS, CREDIT_HOLD, 
CREDIT_RATING, CREDIT_RATING_MEANING, RISK_CODE, RISK_MEANING, 
STANDARD_TERMS, STANDARD_TERMS_NAME, OVERRIDE_TERMS, DUNNING_LETTER_SET_ID, 
DUNNING_LETTER_SET_NAME, INTEREST_PERIOD_DAYS, PAYMENT_GRACE_DAYS, DISCOUNT_GRACE_DAYS, 
STATEMENT_CYCLE_ID, STATEMENT_CYCLE_NAME, ACCOUNT_STATUS, ACCOUNT_STATUS_MEANING, 
AUTOCASH_HIERARCHY_ID, AUTOCASH_HIERARCHY_NAME, AUTO_REC_INCL_DISPUTED_FLAG, TAX_PRINTING_OPTION, 
TAX_PRINTING_OPTION_MEANING, CHARGE_ON_FINANCE_CHARGE_FLAG, GROUPING_RULE_ID, GROUPING_RULE_NAME, 
CONS_INV_FLAG, CONS_INV_TYPE, PERCENT_COLLECTABLE, CLEARING_DAYS, 
AUTOCASH_HIERARCHY_ID_FOR_ADR, AUTOCASH_HIERARCHY_NAME_ADR, LOCKBOX_MATCHING_OPTION, LOCKBOX_MATCHING_OPTION_NAME,
CHECK_RELATION_ID
 ) AS SELECT   
CP.CUSTOMER_PROFILE_ID CUSTOMER_PROFILE_ID ,   
CP.CUSTOMER_ID CUSTOMER_ID ,   
CP.SITE_USE_ID SITE_USE_ID ,   
CP.CUSTOMER_PROFILE_CLASS_ID CUSTOMER_PROFILE_CLASS_ID ,   
CP.STATUS STATUS ,   
CPC.NAME PROFILE_CLASS_NAME ,   
CPC.DESCRIPTION PROFILE_CLASS_DESCRIPTION ,   
CP.COLLECTOR_ID COLLECTOR_ID ,   
COL.NAME COLLECTOR_NAME ,   
CP.CREDIT_CHECKING CREDIT_CHECKING ,   
CP.TOLERANCE TOLERANCE ,   
CP.DISCOUNT_TERMS DISCOUNT_TERMS ,   
CP.DUNNING_LETTERS DUNNING_LETTERS ,   
CP.INTEREST_CHARGES INTEREST_CHARGES ,   
CP.STATEMENTS STATEMENTS ,   
CP.CREDIT_BALANCE_STATEMENTS CREDIT_BALANCE_STATEMENTS ,   
CP.CREDIT_HOLD CREDIT_HOLD ,   
CP.CREDIT_RATING CREDIT_RATING ,   
L_CR.MEANING CREDIT_RATING_MEANING ,   
CP.RISK_CODE RISK_CODE ,   
L_RISK.MEANING RISK_MEANING ,   
CP.STANDARD_TERMS STANDARD_TERMS ,   
TERM.NAME STANDARD_TERMS_NAME ,   
CP.OVERRIDE_TERMS OVERRIDE_TERMS ,   
CP.DUNNING_LETTER_SET_ID DUNNING_LETTER_SET_ID ,   
DUN_SET.NAME DUNNING_LETTER_SET_NAME ,   
CP.INTEREST_PERIOD_DAYS INTEREST_PERIOD_DAYS ,   
CP.PAYMENT_GRACE_DAYS PAYMENT_GRACE_DAYS ,   
CP.DISCOUNT_GRACE_DAYS DISCOUNT_GRACE_DAYS ,   
CP.STATEMENT_CYCLE_ID STATEMENT_CYCLE_ID ,   
CYC.NAME STATEMENT_CYCLE_NAME ,   
CP.ACCOUNT_STATUS ACCOUNT_STATUS ,   
L_AS.MEANING ACCOUNT_STATUS_MEANING ,   
CP.AUTOCASH_HIERARCHY_ID AUTOCASH_HIERARCHY_ID ,   
HIER.HIERARCHY_NAME AUTOCASH_HIERARCHY_NAME ,   
CP.AUTO_REC_INCL_DISPUTED_FLAG AUTO_REC_INCL_DISPUTED_FLAG ,   
CP.TAX_PRINTING_OPTION TAX_PRINTING_OPTION ,   
L_TAX.MEANING TAX_PRINTING_OPTION_MEANING ,   
CP.CHARGE_ON_FINANCE_CHARGE_FLAG CHARGE_ON_FINANCE_CHARGE_FLAG ,   
CP.GROUPING_RULE_ID GROUPING_RULE_ID ,   
GRP.NAME GROUPING_RULE_NAME ,NVL(CP.CONS_INV_FLAG,'N' ) CONS_INV_FLAG ,   
CP.CONS_INV_TYPE CONS_INV_TYPE ,   
CP.PERCENT_COLLECTABLE PERCENT_COLLECTABLE ,   
CP.CLEARING_DAYS CLEARING_DAYS ,   
CP.AUTOCASH_HIERARCHY_ID_FOR_ADR AUTOCASH_HIERARCHY_ID_FOR_ADR ,   
HIER_ADR.HIERARCHY_NAME AUTOCASH_HIERARCHY_NAME_ADR ,   
CP.LOCKBOX_MATCHING_OPTION LOCKBOX_MATCHING_OPTION ,   
L_LMO.MEANING LOCKBOX_MATCHING_OPTION_NAME,
DECODE(CP.SITE_USE_ID,NULL,CP.CUSTOMER_ID,NULL)
FROM   
AR_CUSTOMER_PROFILES CP,   
AR_CUSTOMER_PROFILE_CLASSES CPC,   
AR_COLLECTORS COL,   
AR_LOOKUPS L_CR,   
AR_LOOKUPS L_RISK,   
AR_LOOKUPS L_AS,   
AR_LOOKUPS L_LMO,   
AR_STATEMENT_CYCLES CYC,   
RA_TERMS TERM,   
AR_DUNNING_LETTER_SETS DUN_SET,   
AR_AUTOCASH_HIERARCHIES HIER,   
AR_AUTOCASH_HIERARCHIES HIER_ADR,   
AR_LOOKUPS L_TAX,   
RA_GROUPING_RULES GRP   
WHERE   
CP.CUSTOMER_PROFILE_CLASS_ID = CPC.CUSTOMER_PROFILE_CLASS_ID(+) AND   
CP.COLLECTOR_ID = COL.COLLECTOR_ID AND   
CP.CREDIT_RATING = L_CR.LOOKUP_CODE(+) AND   
L_CR.LOOKUP_TYPE(+) = 'CREDIT_RATING' AND   
CP.RISK_CODE = L_RISK.LOOKUP_CODE(+) AND   
L_RISK.LOOKUP_TYPE(+) = 'RISK_CODE' AND   
CP.STATEMENT_CYCLE_ID = CYC.STATEMENT_CYCLE_ID(+) AND   
CP.STANDARD_TERMS = TERM.TERM_ID(+) AND   
CP.DUNNING_LETTER_SET_ID = DUN_SET.DUNNING_LETTER_SET_ID(+) AND   
CP.ACCOUNT_STATUS = L_AS.LOOKUP_CODE(+) AND   
L_AS.LOOKUP_TYPE(+) = 'ACCOUNT_STATUS' AND   
CP.LOCKBOX_MATCHING_OPTION = L_LMO.LOOKUP_CODE(+) AND   
L_LMO.LOOKUP_TYPE(+) = 'ARLPLB_MATCHING_OPTION' AND   
CP.AUTOCASH_HIERARCHY_ID = HIER.AUTOCASH_HIERARCHY_ID(+) AND   
CP.AUTOCASH_HIERARCHY_ID_FOR_ADR = HIER_ADR.AUTOCASH_HIERARCHY_ID(+) AND   
CP.TAX_PRINTING_OPTION = L_TAX.LOOKUP_CODE(+) AND   
L_TAX.LOOKUP_TYPE(+) = 'TAX_PRINTING_OPTION' AND   
CP.GROUPING_RULE_ID = GRP.GROUPING_RULE_ID(+)
/

/*----------------------------------------------------------------------*/
--      Create View WM_AR_CONTACT_ROLES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_CONTACT_ROLES_VW ( CONTACT_ROLE_ID, 
CONTACT_ID, USAGE_CODE, ORIG_SYSTEM_REFERENCE, PRIMARY_FLAG
 ) AS SELECT   
CR.CONTACT_ROLE_ID , 
CR.CONTACT_ID ,   
CR.USAGE_CODE ,   
CR.ORIG_SYSTEM_REFERENCE ,   
CR.PRIMARY_FLAG    
FROM   
RA_CONTACT_ROLES CR,   
AR_LOOKUPS ARLKP1   
WHERE   
CR.USAGE_CODE = ARLKP1.LOOKUP_CODE(+) AND   
ARLKP1.LOOKUP_TYPE(+) = 'SITE_USE_CODE'
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_CONTACTS_VW 
/*----------------------------------------------------------------------*/


CREATE OR REPLACE VIEW WM_AR_CONTACTS_VW ( CONTACT_ID, 
CUSTOMER_ID, ADDRESS_ID, CONTACT_PARTY_ID, ORG_CONTACT_ID, 
CONTACT_POINT_ID, CONTACT_NUMBER, PARTY_RELATIONSHIP_ID, REL_PARTY_ID, 
TITLE, TITLE_MEANING, FIRST_NAME, LAST_NAME, 
FIRST_NAME_ALT, LAST_NAME_ALT, STATUS, JOB_TITLE, 
MAIL_STOP, ORIG_SYSTEM_REFERENCE, CONTACT_KEY, EMAIL_ADDRESS,
CHECK_RELATION_ID
 ) AS SELECT   
CONT.CONTACT_ID CONTACT_ID ,   
CONT.CUSTOMER_ID CUSTOMER_ID ,   
CONT.ADDRESS_ID ADDRESS_ID , 
CONT.CONTACT_PARTY_ID ,   
CONT.ORG_CONTACT_ID ,   
CONT_POINT.CONTACT_POINT_ID ,   
CONT.CONTACT_NUMBER , 
REL.PARTY_RELATIONSHIP_ID ,   
REL_PARTY.PARTY_ID,      
CONT.TITLE TITLE ,   
L.MEANING TITLE_MEANING ,   
CONT.FIRST_NAME FIRST_NAME ,   
CONT.LAST_NAME LAST_NAME ,   
CONT.FIRST_NAME_ALT FIRST_NAME_ALT ,   
CONT.LAST_NAME_ALT LAST_NAME_ALT ,   
CONT.STATUS STATUS ,   
CONT.JOB_TITLE JOB_TITLE ,   
CONT.MAIL_STOP MAIL_STOP ,   
CONT.ORIG_SYSTEM_REFERENCE ORIG_SYSTEM_REFERENCE ,   
CONT.CONTACT_KEY CONTACT_KEY ,   
CONT.EMAIL_ADDRESS,
DECODE(CONT.ADDRESS_ID,NULL,CONT.CUSTOMER_ID,NULL)  
FROM   
RA_CONTACTS CONT ,   
AR_LOOKUPS L,   
HZ_CONTACT_RESTRICTIONS CONT_RES,   
HZ_PERSON_LANGUAGE PER_LANG,   
HZ_CONTACT_POINTS CONT_POINT,   
HZ_CUST_ACCOUNT_ROLES ACCT_ROLE,   
HZ_PARTIES PARTY,   
HZ_PARTIES REL_PARTY,   
HZ_PARTY_RELATIONSHIPS REL,   
HZ_ORG_CONTACTS ORG_CONT   
WHERE   
CONT.TITLE = L.LOOKUP_CODE(+) AND   
L.LOOKUP_TYPE(+) = 'CONTACT_TITLE' AND   
CONT.CONTACT_ID = ACCT_ROLE.CUST_ACCOUNT_ROLE_ID AND   
ACCT_ROLE.PARTY_ID = REL.PARTY_ID AND   
ACCT_ROLE.ROLE_TYPE = 'CONTACT' AND   
ORG_CONT.PARTY_RELATIONSHIP_ID = REL.PARTY_RELATIONSHIP_ID AND   
REL.SUBJECT_ID = PARTY.PARTY_ID AND   
REL_PARTY.PARTY_ID = REL.PARTY_ID AND   
PARTY.PARTY_ID = PER_LANG.PARTY_ID(+) AND   
PER_LANG.NATIVE_LANGUAGE(+) = 'Y' AND   
CONT_POINT.OWNER_TABLE_ID(+) = REL_PARTY.PARTY_ID AND   
CONT_POINT.CONTACT_POINT_TYPE(+) = 'EMAIL' AND   
CONT_POINT.PRIMARY_FLAG(+) = 'Y' AND   
PARTY.PARTY_ID = CONT_RES.SUBJECT_ID(+) AND   
CONT_RES.SUBJECT_TABLE(+) = 'HZ_PARTIES'
/


/*----------------------------------------------------------------------*/
--      Create View WM_AR_ADDRESSES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_ADDRESSES_VW ( PARTY_SITE_ID, 
PARTY_ID, PARTY_LOCATION_ID, SITE_NUMBER, ADDRESS_ID, 
CUSTOMER_ID, STATUS, ORIG_SYSTEM_REFERENCE, COUNTRY, 
TERRITORY_SHORT_NAME, ADDRESS_STYLE, ADDRESS1, ADDRESS2, 
ADDRESS3, ADDRESS4, CITY, COUNTY, 
STATE, PROVINCE, POSTAL_CODE, TERRITORY_ID, 
ADDRESS_KEY, SU_BILL_TO_FLAG, SU_BILL_TO_SITE_USE_ID, SU_SHIP_TO_FLAG, 
SHIP_TO_SITE_USE_ID, SU_MARKET_FLAG, MARKET_SITE_USES_ID, SU_DUN_FLAG, 
DUN_SITE_USE_ID, SU_STMT_FLAG, STMT_SITE_USE_ID, SU_LEGAL_FLAG, 
LEGAL_SITE_USE_ID, KEY_ACCOUNT_FLAG, LANGUAGE, LANGUAGE_DESCRIPTION, 
ADDRESS_LINES_PHONETIC, CUSTOMER_CATEGORY, CUSTOMER_CATEGORY_MEANING, EDI_LOCATION, 
TERRITORY, TRANSLATED_CUSTOMER_NAME, SALES_TAX_GEOCODE, SALES_TAX_INSIDE_CITY_LIMITS, 
IDENTIFYING_ADDRESS_FLAG, ADDRESSEE, ORGANIZATION_NAME ) AS SELECT  
ADDR.PARTY_SITE_ID ,  
ADDR.PARTY_ID ,  
ADDR.PARTY_LOCATION_ID ,  
ADDR.SITE_NUMBER ,  
ADDR.ADDRESS_ID ADDRESS_ID ,  
ADDR.CUSTOMER_ID CUSTOMER_ID ,  
ADDR.STATUS STATUS ,  
ADDR.ORIG_SYSTEM_REFERENCE ORIG_SYSTEM_REFERENCE ,  
ADDR.COUNTRY COUNTRY ,  
TERR.TERRITORY_SHORT_NAME TERRITORY_SHORT_NAME ,  
TERR.ADDRESS_STYLE ADDRESS_STYLE ,  
ADDR.ADDRESS1 ADDRESS1 ,  
ADDR.ADDRESS2 ADDRESS2 ,  
ADDR.ADDRESS3 ADDRESS3 ,  
ADDR.ADDRESS4 ADDRESS4 ,  
ADDR.CITY CITY ,  
ADDR.COUNTY COUNTY ,  
ADDR.STATE STATE ,  
ADDR.PROVINCE PROVINCE ,  
ADDR.POSTAL_CODE POSTAL_CODE ,  
ADDR.TERRITORY_ID TERRITORY_ID ,  
ADDR.ADDRESS_KEY ,  
'N' ,  
0 ,  
'N' ,  
0 ,  
'N' ,  
0 ,  
'N' ,  
0 ,  
'N' ,  
0 ,  
'N' ,  
0 ,  
ADDR.KEY_ACCOUNT_FLAG KEY_ACCOUNT_FLAG ,  
ADDR.LANGUAGE LANGUAGE ,  
LANG.DESCRIPTION LANGUAGE_DESCRIPTION ,  
ADDR.ADDRESS_LINES_PHONETIC ADDRESS_LINES_PHONETIC ,  
ADDR.CUSTOMER_CATEGORY_CODE CUSTOMER_CATEGORY ,  
L_CAT.MEANING CUSTOMER_CATEGORY_MEANING ,  
ADDR.ECE_TP_LOCATION_CODE EDI_LOCATION ,  
ADDR.TERRITORY TERRITORY ,  
ADDR.TRANSLATED_CUSTOMER_NAME TRANSLATED_CUSTOMER_NAME ,  
ADDR.SALES_TAX_GEOCODE SALES_TAX_GEOCODE ,  
ADDR.SALES_TAX_INSIDE_CITY_LIMITS SALES_TAX_INSIDE_CITY_LIMITS,  
ADDR.IDENTIFYING_ADDRESS_FLAG ,  
ADDR.ADDRESSEE ,  
ORG.ORGANIZATION_NAME  
FROM  
AR_LOOKUPS L_CAT,  
FND_TERRITORIES_VL TERR,  
FND_LANGUAGES_VL LANG,  
RA_ADDRESSES_ALL ADDR ,  
ORG_ORGANIZATION_DEFINITIONS ORG  
WHERE  
ADDR.CUSTOMER_CATEGORY_CODE = L_CAT.LOOKUP_CODE(+) AND  
L_CAT.LOOKUP_TYPE(+) = 'ADDRESS_CATEGORY' AND  
ADDR.COUNTRY = TERR.TERRITORY_CODE(+) AND  
ADDR.LANGUAGE = LANG.LANGUAGE_CODE(+) AND  
ADDR.ORG_ID = ORG.ORGANIZATION_ID
/


/*----------------------------------------------------------------------*/
--      Create View WM_ADDR_PHONES_VW 
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_ADDR_PHONES_VW ( PHONE_ID, 
CUSTOMER_ID, ADDRESS_ID, CONTACT_ID, PHONE_NUMBER, 
STATUS, PHONE_TYPE, AREA_CODE, EXTENSION, 
PRIMARY_FLAG, ORIG_SYSTEM_REFERENCE, CONTACT_POINT_TYPE, TELEPHONE_TYPE, 
TIME_ZONE, PHONE_TOUCH_TONE_TYPE_FLAG, TELEX_NUMBER, WEB_TYPE, 
CUST_CONTACT_POINT_ID ) AS SELECT  
CONT_POINT.CONTACT_POINT_ID /* PHONE_ID */ ,  
CAS.CUST_ACCOUNT_ID /* CUSTOMER_ID */ ,  
CAS.CUST_ACCT_SITE_ID /* ADDRESS_ID */ ,  
TO_NUMBER(NULL) /* CONTACT_ID */ ,  
DECODE(CONT_POINT.CONTACT_POINT_TYPE,'TLX',CONT_POINT.TELEX_NUMBER,CONT_POINT.PHONE_NUMBER) ,  
CONT_POINT.STATUS ,  
NVL(CONT_POINT.PHONE_LINE_TYPE,CONT_POINT.CONTACT_POINT_TYPE) ,  
CONT_POINT.PHONE_AREA_CODE ,  
CONT_POINT.PHONE_EXTENSION ,  
CONT_POINT.PRIMARY_FLAG ,  
CONT_POINT.ORIG_SYSTEM_REFERENCE ,  
CONT_POINT.CONTACT_POINT_TYPE ,  
CONT_POINT.TELEPHONE_TYPE ,  
CONT_POINT.TIME_ZONE ,  
CONT_POINT.PHONE_TOUCH_TONE_TYPE_FLAG ,  
CONT_POINT.TELEX_NUMBER ,  
CONT_POINT.WEB_TYPE ,  
CONT_POINT.CONTACT_POINT_ID  
FROM  
HZ_CONTACT_POINTS CONT_POINT ,  
HZ_CUST_ACCT_SITES_ALL CAS  
WHERE  
CAS.PARTY_SITE_ID = CONT_POINT.OWNER_TABLE_ID AND  
CONT_POINT.OWNER_TABLE_NAME = 'HZ_PARTY_SITES' AND  
CONT_POINT.CONTACT_POINT_TYPE NOT IN ( 'EDI', 'EMAIL', 'WEB')
/

/*----------------------------------------------------------------------*/
--      Create View WM_AR_CUSTOMERS_QRY_VW View for Customer Query Transaction
/*----------------------------------------------------------------------*/

CREATE OR REPLACE VIEW WM_AR_CUSTOMERS_QRY_VW ( WEB_TRANSACTION_ID, 
DOCUMENT_TYPE, DOCUMENT_STATUS, CUSTOMER_ID, CUSTOMER_NAME, 
CUSTOMER_NUMBER, PARTY_ID, PARTY_NUMBER, PARTY_ADDRESS1, 
PARTY_ADDRESS2, PARTY_ADDRESS3, PARTY_ADDRESS4, PARTY_CITY, 
PARTY_STATE, PARTY_PROVINCE, PARTY_COUNTY, PARTY_POSTAL_CODE, 
PARTY_COUNTRY, PARTY_TYPE, CUSTOMER_KEY, CUSTOMER_STATUS, 
ORIG_SYSTEM_REFERENCE, CUSTOMER_PROSPECT_CODE, CUSTOMER_CATEGORY_CODE, CUSTOMER_CATEGORY_MEANING, 
CUSTOMER_CLASS_CODE, CUSTOMER_CLASS_MEANING, CUSTOMER_TYPE, CUSTOMER_TYPE_MEANING, 
PRIMARY_SALESREP_ID, PRIMARY_SALESREP_NAME, SIC_CODE, TAX_REFERENCE, 
TAX_CODE, FOB_POINT, FOB_POINT_MEANING, SHIP_VIA, 
GSA_INDICATOR, SHIP_PARTIAL, TAXPAYER_ID, PRICE_LIST_ID, 
PRICE_LIST_NAME, FREIGHT_TERM, FREIGHT_TERM_MEANING, ORDER_TYPE_ID, 
ORDER_TYPE_NAME, SALES_CHANNEL_CODE, SALES_CHANNEL_MEANING, WAREHOUSE_ID, 
WAREHOUSE_NAME, MISSION_STATEMENT, NUM_OF_EMPLOYEES, POTENTIAL_REVENUE_CURR_FY, 
POTENTIAL_REVENUE_NEXT_FY, FISCAL_YEAREND_MONTH, YEAR_ESTABLISHED, ANALYSIS_FY, 
COMPETITOR_FLAG, REFERENCE_USE_FLAG, THIRD_PARTY_FLAG, CUSTOMER_PROFILE_CLASS_ID, 
PROFILE_CLASS_NAME, CUSTOMER_NAME_PHONETIC, TAX_HEADER_LEVEL_FLAG, TAX_ROUNDING_RULE, 
ORIG_SYSTEM, COTERMINATE_DAY_MONTH, WAREHOUSE_UPDATE_DATE, LANGUAGE, 
TRANSLATED_CUSTOMER_NAME, PERSON_PRE_NAME_ADJUNCT, PERSON_FIRST_NAME, PERSON_MIDDLE_NAME, 
PERSON_LAST_NAME, PERSON_SUFFIX, PERSON_FIRST_NAME_PHONETIC, PERSON_LAST_NAME_PHONETIC, 
SHIP_SETS_INCLUDE_LINES_FLAG, ARRIVALSETS_INCLUDE_LINES_FLAG, SCHED_DATE_PUSH_FLAG, OVER_SHIPMENT_TOLERANCE, 
UNDER_SHIPMENT_TOLERANCE, OVER_RETURN_TOLERANCE, UNDER_RETURN_TOLERANCE, ITEM_CROSS_REF_PREF, 
DATE_TYPE_PREFERENCE, DATES_NEGATIVE_TOLERANCE, DATES_POSITIVE_TOLERANCE, INVOICE_QUANTITY_RULE, 
DUNS_NUMBER, ORGANIZATION_PROFILE_ID, PERSON_PROFILE_ID, SIC_CODE_TYPE
 ) AS SELECT
NULL WEB_TRANSACTION_ID,
'CUSTOMER' DOCUMENT_TYPE,
'QUERY' DOCUMENT_STATUS,
CUST.CUSTOMER_ID CUSTOMER_ID ,
CUST.CUSTOMER_NAME CUSTOMER_NAME ,
CUST.CUSTOMER_NUMBER CUSTOMER_NUMBER ,
CUST.PARTY_ID ,
CUST.PARTY_NUMBER ,
WADD.ADDRESS1,
WADD.ADDRESS2,
WADD.ADDRESS3,
WADD.ADDRESS4,
WADD.CITY,
WADD.STATE,
WADD.PROVINCE,
WADD.COUNTY,
WADD.POSTAL_CODE,
WADD.COUNTRY,
CUST.PARTY_TYPE ,
CUST.CUSTOMER_KEY CUSTOMER_KEY ,
CUST.STATUS STATUS ,
CUST.ORIG_SYSTEM_REFERENCE ORIG_SYSTEM_REFERENCE ,
CUST.CUSTOMER_PROSPECT_CODE CUSTOMER_PROSPECT_CODE ,
CUST.CUSTOMER_CATEGORY_CODE CUSTOMER_CATEGORY_CODE ,
L_CAT.MEANING CUSTOMER_CATEGORY_MEANING ,
CUST.CUSTOMER_CLASS_CODE CUSTOMER_CLASS_CODE ,
L_CLASS.MEANING CUSTOMER_CLASS_MEANING ,
CUST.CUSTOMER_TYPE CUSTOMER_TYPE ,
L_TYPE.MEANING CUSTOMER_TYPE_MEANING ,
CUST.PRIMARY_SALESREP_ID PRIMARY_SALESREP_ID ,
REP.NAME PRIMARY_SALESREP_NAME ,
CUST.SIC_CODE SIC_CODE ,
CUST.TAX_REFERENCE TAX_REFERENCE ,
CUST.TAX_CODE TAX_CODE ,
CUST.FOB_POINT FOB_POINT ,
L_FOB.MEANING FOB_POINT_MEANING ,
CUST.SHIP_VIA SHIP_VIA ,
CUST.GSA_INDICATOR GSA_INDICATOR ,
CUST.SHIP_PARTIAL SHIP_PARTIAL ,
CUST.JGZZ_FISCAL_CODE TAXPAYER_ID ,
CUST.PRICE_LIST_ID PRICE_LIST_ID ,
PL.NAME PRICE_LIST_NAME ,
CUST.FREIGHT_TERM FREIGHT_TERM ,
L_FT.MEANING FREIGHT_TERM_MEANING ,
CUST.ORDER_TYPE_ID ORDER_TYPE_ID ,
OT.NAME ORDER_TYPE_NAME ,
CUST.SALES_CHANNEL_CODE SALES_CHANNEL_CODE ,
L_SC.MEANING SALES_CHANNEL_MEANING ,
CUST.WAREHOUSE_ID WAREHOUSE_ID ,
ORG.NAME WAREHOUSE_NAME ,
CUST.MISSION_STATEMENT MISSION_STATEMENT ,
CUST.NUM_OF_EMPLOYEES NUM_OF_EMPLOYEES ,
CUST.POTENTIAL_REVENUE_CURR_FY POTENTIAL_REVENUE_CURR_FY ,
CUST.POTENTIAL_REVENUE_NEXT_FY POTENTIAL_REVENUE_NEXT_FY ,
CUST.FISCAL_YEAREND_MONTH FISCAL_YEAREND_MONTH ,
CUST.YEAR_ESTABLISHED YEAR_ESTABLISHED ,
CUST.ANALYSIS_FY ANALYSIS_FY ,
CUST.COMPETITOR_FLAG COMPETITOR_FLAG ,
CUST.REFERENCE_USE_FLAG REFERENCE_USE_FLAG ,
CUST.THIRD_PARTY_FLAG THIRD_PARTY_FLAG ,
CPC.CUSTOMER_PROFILE_CLASS_ID CUSTOMER_PROFILE_CLASS_ID ,
CPC.NAME PROFILE_CLASS_NAME ,
CUST.CUSTOMER_NAME_PHONETIC CUSTOMER_NAME_PHONETIC ,
CUST.TAX_HEADER_LEVEL_FLAG TAX_HEADER_LEVEL_FLAG ,
CUST.TAX_ROUNDING_RULE TAX_ROUNDING_RULE ,
CUST.ORIG_SYSTEM ,
CUST.COTERMINATE_DAY_MONTH ,
CUST.WH_UPDATE_DATE ,
CUST.LANGUAGE ,
CUST.TRANSLATED_CUSTOMER_NAME ,
CUST.PERSON_PRE_NAME_ADJUNCT ,
CUST.PERSON_FIRST_NAME ,
CUST.PERSON_MIDDLE_NAME ,
CUST.PERSON_LAST_NAME ,
CUST.PERSON_SUFFIX ,
CUST.PERSON_FIRST_NAME_PHONETIC ,
CUST.PERSON_LAST_NAME_PHONETIC ,
CUST.SHIP_SETS_INCLUDE_LINES_FLAG ,
CUST.ARRIVALSETS_INCLUDE_LINES_FLAG ,
CUST.SCHED_DATE_PUSH_FLAG ,
CUST.OVER_SHIPMENT_TOLERANCE ,
CUST.UNDER_SHIPMENT_TOLERANCE ,
CUST.OVER_RETURN_TOLERANCE ,
CUST.UNDER_RETURN_TOLERANCE ,
CUST.ITEM_CROSS_REF_PREF ,
CUST.DATE_TYPE_PREFERENCE ,
CUST.DATES_NEGATIVE_TOLERANCE ,
CUST.DATES_POSITIVE_TOLERANCE ,
CUST.INVOICE_QUANTITY_RULE ,
CUST.DUNS_NUMBER ,
ORG_PROF.ORGANIZATION_PROFILE_ID ,
PER_PROF.PERSON_PROFILE_ID ,
CUST.SIC_CODE_TYPE
FROM
AR_LOOKUPS L_CAT,
AR_LOOKUPS L_CLASS,
AR_LOOKUPS L_TYPE,
RA_SALESREPS REP,
AR_LOOKUPS L_FOB,
SO_PRICE_LISTS PL,
SO_LOOKUPS L_FT,
SO_ORDER_TYPES OT,
SO_LOOKUPS L_SC,
HR_ALL_ORGANIZATION_UNITS ORG,
AR_CUSTOMER_PROFILE_CLASSES CPC,
AR_CUSTOMER_PROFILES CP,
RA_CUSTOMERS CUST,
HZ_CONTACT_RESTRICTIONS CONT_RES,
HZ_CONTACT_POINTS CONT_POINT,
HZ_ORGANIZATION_PROFILES ORG_PROF,
HZ_PERSON_PROFILES PER_PROF,
HZ_PARTIES PARTY,
WM_AR_ADDRESSES_VW WADD,
HZ_CUST_ACCOUNTS CUST_ACCT
WHERE
CUST.CUSTOMER_CATEGORY_CODE = L_CAT.LOOKUP_CODE(+) AND
L_CAT.LOOKUP_TYPE(+) = 'CUSTOMER_CATEGORY' AND
CUST.CUSTOMER_CLASS_CODE = L_CLASS.LOOKUP_CODE(+) AND
L_CLASS.LOOKUP_TYPE(+) = 'CUSTOMER CLASS' AND
CUST.CUSTOMER_TYPE = L_TYPE.LOOKUP_CODE(+) AND
L_TYPE.LOOKUP_TYPE(+) = 'CUSTOMER_TYPE' AND
CUST.PRIMARY_SALESREP_ID = REP.SALESREP_ID(+) AND
CUST.FOB_POINT = L_FOB.LOOKUP_CODE(+) AND
L_FOB.LOOKUP_TYPE(+) = 'FOB' AND
CUST.PRICE_LIST_ID = PL.PRICE_LIST_ID(+) AND
CUST.FREIGHT_TERM = L_FT.LOOKUP_CODE(+) AND
L_FT.LOOKUP_TYPE(+) = 'FREIGHT_TERMS' AND
CUST.ORDER_TYPE_ID = OT.ORDER_TYPE_ID(+) AND
CUST.SALES_CHANNEL_CODE = L_SC.LOOKUP_CODE(+) AND
L_SC.LOOKUP_TYPE(+) = 'SALES_CHANNEL' AND
CUST.WAREHOUSE_ID = ORG.ORGANIZATION_ID(+) AND
CP.CUSTOMER_ID = CUST.CUSTOMER_ID AND
CP.SITE_USE_ID IS NULL AND
CP.CUSTOMER_PROFILE_CLASS_ID = CPC.CUSTOMER_PROFILE_CLASS_ID(+) AND
CUST_ACCT.CUST_ACCOUNT_ID = CUST.CUSTOMER_ID AND
CUST_ACCT.PARTY_ID = PARTY.PARTY_ID AND
PARTY.PARTY_ID = ORG_PROF.PARTY_ID(+) AND
PARTY.PARTY_ID = PER_PROF.PARTY_ID(+) AND
PARTY.PARTY_ID = CONT_POINT.OWNER_TABLE_ID(+) AND
CONT_POINT.OWNER_TABLE_NAME(+) = 'HZ_PARTIES' AND
CONT_POINT.CONTACT_POINT_TYPE(+) = 'WEB' AND
CONT_POINT.PRIMARY_FLAG(+) = 'Y' AND
PARTY.PARTY_ID = CONT_RES.SUBJECT_ID(+) AND
CONT_RES.SUBJECT_TABLE(+) = 'HZ_PARTIES' AND
ORG_PROF.CONTENT_SOURCE_TYPE(+) = 'USER_ENTERED' AND
PER_PROF.CONTENT_SOURCE_TYPE(+) = 'USER_ENTERED' AND
WADD.CUSTOMER_ID=CUST_ACCT.CUST_ACCOUNT_ID AND
ORG_PROF.EFFECTIVE_END_DATE IS NULL AND
PER_PROF.EFFECTIVE_END_DATE IS NULL
/



 
SHOW ERRORS

