var mimeTypes = {
"*" : "application/octet-stream",
"3gp" : "video/3gp",
"3gpp" : "video/3gpp",
"3g2" : "video/3gpp",
"aif" : "audio/x-aiff",
"aifc" : "audio/x-aiff",
"aiff" : "audio/x-aiff",
"asf" : "video/x-ms-asf",
"avi" : "video/x-msvideo",
"flv" : "video/x-flv",
"gif" : "image/gif",
"m4v" : "video/m4v",
"mid" : "audio/mid",
"mov" : "video/quicktime",
"mp2" : "video/mpeg",
"mp3" : "audio/mp3",
"mp4" : "video/mp4",
"webm" : "video/webm",
"mpa" : "video/mpeg",
"mpe" : "video/mpeg",
"mpeg" : "video/mpeg",
"mpg" : "video/mpeg",
"mpv2" : "video/mpeg",
"swf" : "application/x-shockwave-flash",
"wav" : "audio/x-wav",
"wmv" : "video/x-ms-wmv"
};